### ISSUE TITLE
Molecule.rotateBy and Molecule.rotate redundancy

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#10]
It seems to me that `Molecule.rotateBy` and `Molecule.rotate` are redundant.

I was seeing this with @giadefa and it seems like, for example, `mol.rotate([0, 1, 0], 1.57)` and `mol.rotateBy(rotationmatrix([0, 1, 0],1.57))` do the same. So, the key is the `rotationmatrix` function.

I will still need to see this better, before proposing a change, specially because of the center attribute. And do testing, of course. But, in principle, `Molecule.rotateBy` could be kept, and `Molecule.rotate` could be deprecated.

J

**Comment by stefdoerr** [comment]
Hm yes, I guess it's a convenience function. Don't know if that is enough reason to kill it. Maybe the two could be joined somehow?
Like `mol.rotate` could check the dimensions of the rotation "matrix" and if it's 2D it uses it as a rotation matrix and if it's 1D it checks for the second argument to see if it's a scalar and then use it as the rotation axis with radians.

**Comment by j3mdamas** [comment]
OK, we want to keep it general. I was thinking about the 3D case. I'll keep that in mind and think about it.

**Comment by giadefa** [comment]
agreed.
deprecate rotate and show this
mol.rotateBy(rotationMatrix([0, 1, 0],1.57))
rotatematrix deprecates to rotateMatrix

**Comment by stefdoerr** [comment]
Deprecated
