### ISSUE TITLE
job queued

### ISSUE THREAD

**Issue by zainbsa** [Acellera/htmd#1002]
Hello, I am new at using the HTMD for simulations, I submitted an adaptive sampling simulation using HTMD, however my job has been on queue for the past 3days now and not running, although it was running initially. Please kindly advice.

**Comment by stefdoerr** [comment]
This sounds like an issue with your cluster. What queueing system are you using?

**Comment by zainbsa** [comment]
Hello,

I am using gpu

**Comment by stefdoerr** [comment]
Can you share the python code which submitted the job?

**Comment by zainbsa** [comment]
qsub $run_script >> _restarted

**Comment by stefdoerr** [comment]
Sorry, I would need to see the code you are executing. In any case qsub I think is an SGE command. I assume you need to talk with the admin on why your jobs are staying queued.
