### ISSUE TITLE
Error in app callback. 

### ISSUE THREAD

**Issue by hussain-beig** [Acellera/htmd#1003]
Hi, I was running a simple MD simulation of a keratin molecule with no ligands, no membrane. The simulation finished but I didn't get any result instead an app callback error. 
File /data/static/apps/SimpleRun/output/FABD05F4/fabd05f4-ebcf-4709-abd9-a77e88e10acd/filtered_run1.pdb was not found.

**Comment by stefdoerr** [comment]
This is a very curious bug. Would you mind resubmitting the job please? I can see the error page but I cannot see any computation being made for that job. Maybe it died before executing.

**Comment by hussain-beig** [comment]
I'm afraid the right pane which shows the option to resubmit just keeps loading and never actually gives me the option. I've the resubmitted the same system the link for which is: https://www.playmolecule.org/SimpleRun/job/7E5C4AF9.
 
Also I don't know if this has something to do with this but when I submitted this job the prompt told me the system is too large to simulate on the public PlayMolecule server and contact accellera for private installations.

**Comment by stefdoerr** [comment]
Ah ok then it won't run. Still weird that it's flagged as finished. It should not allow submitting the job. I'll take a look at it, thanks for the report!

**Comment by hussain-beig** [comment]
Cool, thank you for clearing that up.
