### ISSUE TITLE
Membrane builder issue (no registered platform called CUDA)

### ISSUE THREAD

**Issue by shozebhaider** [Acellera/htmd#1004]
Hi 

I am trying to use your membrane builder tutorial. When I run it I keep getting the error message 

Exception: There is no registered Platform called "CUDA"

I am using GTX3070 GPU with Driver 465.31 Cuda version 11.3
HTMD version 1.24.8

Any clues would be helpful.
Best wishes

Shozeb

**Comment by stefdoerr** [comment]
Hi Shozeb. This is curious. Are you talking about HTMD or some singularity app? Can you send me the whole error log and the commands which ran?
Membrane builder should not really depend on GPUs.

**Comment by shozebhaider** [comment]
Hi @stefdoerr 
Please take a look at the notebook (link attached). Apologies for the delay in response.
https://www.dropbox.com/s/0oj2whhcl9vmu9l/Lipids_notebook.ipynb?dl=0

**Comment by stefdoerr** [comment]
I see, it's the automatic equilibration which is failing. Can you try just setting equilibrate to False? You can then equilibrate with other software like ACEMD3, it's not critical to membranbuilder, it's just an added convenience function

**Comment by shozebhaider** [comment]
Many thanks. I shall test and close the ticket shortly.
