### ISSUE TITLE
calculating interaction energy in ACEMD

### ISSUE THREAD

**Issue by zainbsa** [Acellera/htmd#1006]
I am new at working with ACEMD and still trying to figure things out, I will like to know if it is possible to calculate the interaction energies of ligands with protein and also plot/analyze the contacts of the ligand with a protein?

**Comment by stefdoerr** [comment]
Hi, with ACEMD you cannot get specific interaction energies out.
It is however possible with ffevaluate https://software.acellera.com/docs/latest/htmd/tutorials/FFEvaluate.html

To calculate and plot protein ligand contacts you can do it with moleculekit MetricDistance class:
https://software.acellera.com/docs/latest/moleculekit/moleculekit.projections.metricdistance.html
You pass it a Molecule object with your trajectory and two selections for which to calculate distances and it returns those distances

**Comment by zainbsa** [comment]
Ok! Thank you.I will try these out.

**Comment by zainbsa** [comment]
Hi,
I followed the sample at https://software.acellera.com/docs/latest/htmd/tutorials/FFEvaluate.html to evaluate the interaction energies and setup my job script, but I have the topology extension as .top, and while running this I got the error below;
RuntimeError: Extension of file /software/software/HTMD/1.23.5/lib/python3.6/site-packages/htmd/data/abeta_sergio/structure.top not recognized. Report issue on HTMD issue tracker.

Does it mean it only recognize the .prmtop extension as in the sample? Please note I had to convert my topology from charmm to amber using the below;
import parmed as pmd
pmd.load_file('structure.psf').save('structure.top')

I also tried to change the extension here to .prmtop but it keeps refusing with this error;
AttributeError: 'NoneType' object has no attribute 'idx'

**Comment by stefdoerr** [comment]
Hi, unfortunately you will have to find a way to convert to prmtop. Maybe
antechamber can do it, otherwise you might have to rebuild the system in
AMBER. Sorry I cannot help you further but I'm currently out on holidays.

**Comment by zainbsa** [comment]
Hi,
I suspect the conversion I made from .psf file to .top using; pmd.load_file('structure.psf').save('structure.top') as initially stated is to a gromacs topology file and that is why it doesn't recognize the extension file while trying out the sample here; https://software.acellera.com/docs/latest/htmd/tutorials/FFEvaluate.html 

However, I tried to covert the topology file in gromacs to amber using;
gmx_top = pmd.load_file('structure.top', xyz= 'filtered.gro')
gmx_top.save('name.top', format='amber')
gmx_top.save('name.crd', format='rst7')

and then got this error; MoleculeError: Cannot bond two virtual sites/extra points together.
couldnt figure the conversion with antechamber

**Comment by zainbsa** [comment]
Hello,

As I understand now using the FFEvaluate the loadParameters function is suppose to read both AMBER and CHARMM forcefields but while using the .psf file generated from CHARMM I keep getting an error that the extension is not recognized.
RuntimeError: Extension of file /software/software/HTMD/1.23.5/lib/python3.6/site-packages/htmd/data/abeta_sergio/structure.psf not recognized. Report issue on HTMD issue tracker.

**Comment by stefdoerr** [comment]
This is weird. Can you post the code which throws the error and the full traceback which it prints?
Thanks!

**Comment by zainbsa** [comment]
Here it is; 

from ffevaluation.ffevaluate import FFEvaluate, loadParameters, viewForces
from moleculekit.molecule import Molecule
from htmd.home import home
from os.path import join

datadir = home(dataDir='abeta_sergio')

# Load the parameters
prm = loadParameters(join(datadir, 'structure.psf'))
# Load the topology
mol = Molecule(join(datadir, 'structure.psf'))

RuntimeError                              Traceback (most recent call last)
<ipython-input-18-2d29d01da3ab> in <module>
      9 
     10 # Load the parameters
---> 11 prm = loadParameters(join(datadir, 'structure.psf'))
     12 # Load the topology
     13 mol = Molecule(join(datadir, 'structure.psf'))

/software/software/HTMD/1.23.5/lib/python3.6/site-packages/ffevaluation/ffevaluate.py in loadParameters(fname)
     70 
     71     if prm is None:
---> 72         raise RuntimeError('Extension of file {} not recognized. Report issue on HTMD issue tracker.'.format(fname))
     73 
     74     return prm

RuntimeError: Extension of file /software/software/HTMD/1.23.5/lib/python3.6/site-packages/htmd/data/abeta_sergio/structure.psf not recognized. Report issue on HTMD issue tracker.

**Comment by stefdoerr** [comment]
PSF files don't contain parameters, they only contain topology. You also need a prm which the loadParameters function expects.

**Comment by zainbsa** [comment]
I see.However, using a parameter file; I still got the same error

# Load the parameters
prm = loadParameters(join(datadir, 'par_all36m_prot.prm'))
# Load the topology
mol = Molecule(join(datadir, 'structure.psf'))


RuntimeError                              Traceback (most recent call last)
<ipython-input-21-5184fbc10d0d> in <module>
      8 
      9 # Load the parameters
---> 10 prm = loadParameters(join(datadir, 'par_all36m_prot.prm'))
     11 # Load the topology
     12 mol = Molecule(join(datadir, 'structure.psf'))

/software/software/HTMD/1.23.5/lib/python3.6/site-packages/ffevaluation/ffevaluate.py in loadParameters(fname)
     70 
     71     if prm is None:
---> 72         raise RuntimeError('Extension of file {} not recognized. Report issue on HTMD issue tracker.'.format(fname))
     73 
     74     return prm

RuntimeError: Extension of file /software/software/HTMD/1.23.5/lib/python3.6/site-packages/htmd/data/abeta_sergio/par_all36m_prot.prm not recognized. Report issue on HTMD issue tracker.

**Comment by stefdoerr** [comment]
Did it print anything else before that complaining that it could not read the file correctly?

**Comment by zainbsa** [comment]
yes...
Failed to read /software/software/HTMD/1.23.5/lib/python3.6/site-packages/htmd/data/abeta_sergio/tmp_gauss-min.prm as CHARMM parameters. Attempting with AMBER prmtop reader
Failed to read /software/software/HTMD/1.23.5/lib/python3.6/site-packages/htmd/data/abeta_sergio/tmp_gauss-min.prm due to errors [Errno 2] No such file or directory: '/software/software/HTMD/1.23.5/lib/python3.6/site-packages/htmd/data/abeta_sergio/tmp_gauss-min.prm' Could not open /software/software/HTMD/1.23.5/lib/python3.6/site-packages/htmd/data/abeta_sergio/tmp_gauss-min.prm for reading

**Comment by stefdoerr** [comment]
Then it's probably not a valid prm file. Try this and see what it gives

```python
import parmed
prm = parmed.charmm.CharmmParameterSet("myfile.prm")
```

**Comment by zainbsa** [comment]
Using the above command line it actually reads the file, I also had to load my topology this way;
mol = parmed.charmm.CharmmParameterSet ('0.top_all36_prot.rtf') (P.S it doesn't read the .psf file here)

However, for the ffevaluation (I got the below error, could you please help me rewrite this script?)
# Create a FFEvaluate object
ffev = FFEvaluate(mol, prm)

AttributeError                            Traceback (most recent call last)
<ipython-input-36-f61058ac0bbd> in <module>
     15 
     16 # Create a FFEvaluate object
---> 17 ffev = FFEvaluate(mol, prm)
     18 
     19 # Load some coordinates

/software/software/HTMD/1.23.5/lib/python3.6/site-packages/ffevaluation/ffevaluate.py in __init__(self, mol, prm, betweensets, cutoff, rfa, solventDielectric)
    138         >>> energies, forces, atmnrg = ffev.calculate(mol.coords)
    139         """
--> 140         mol = mol.copy()
    141         setA, setB = calculateSets(mol, betweensets)
    142 

AttributeError: 'CharmmParameterSet' object has no attribute 'copy'

**Comment by stefdoerr** [comment]
```python
mol = Molecule("structure.psf")
prm = parmed.charmm.CharmmParameterSet("myfile.prm")
ffev = FFEvaluate(mol, prm)
```

**Comment by zainbsa** [comment]
I am sorry but it doesn't get better

KeyError                                  Traceback (most recent call last)
<ipython-input-37-3f0e6ce59fd6> in <module>
     15 
     16 # Create a FFEvaluate object
---> 17 ffev = FFEvaluate(mol, prm)
     18 
     19 # Load some coordinates

/software/software/HTMD/1.23.5/lib/python3.6/site-packages/ffevaluation/ffevaluate.py in __init__(self, mol, prm, betweensets, cutoff, rfa, solventDielectric)
    141         setA, setB = calculateSets(mol, betweensets)
    142 
--> 143         args = list(init(mol, prm))
    144         args.append(setA)
    145         args.append(setB)

/software/software/HTMD/1.23.5/lib/python3.6/site-packages/ffevaluation/ffevaluate.py in init(mol, prm)
    285     epsilon14 = np.zeros(len(uqtypes), dtype=np.float32)
    286     for i, type in enumerate(uqtypes):
--> 287         sigma[i] = prm.atom_types[type].sigma
    288         epsilon[i] = prm.atom_types[type].epsilon
    289         sigma14[i] = prm.atom_types[type].sigma_14

KeyError: 'CLA'

**Comment by stefdoerr** [comment]
There are missing some parameters in your prm file. Specifically those for residue names CLA which is the chloride ion. Try running

```python
from ffevaluation.test_ffevaluate import fixParameters
fixParameters("myprmfile.prm", "myprmfile_fixed.prm")

mol = Molecule("structure.psf")
prm = parmed.charmm.CharmmParameterSet("myprmfile_fixed.prm")
ffev = FFEvaluate(mol, prm)
``` 

If this doesn't work then you might need to copy those parameters into the prm file

**Comment by zainbsa** [comment]
Hello,
I loaded all the parameter files and I do not have the above error anymore but came up with another error. Is the complain still about the parameters? I am so sorry I just really need to make this work.

prm = parmed.charmm.CharmmParameterSet('par_all36m_prot.prm', 'tmp_gauss-min_charmm.rtf', 'toppar_water_ions_test.str', 'tmp_gauss-min_charmm.par', 'toppar_water_ions.str', 'top_water_ions.rtf')

mol = Molecule('structure.psf')

# Create a FFEvaluate object
ffev = FFEvaluate(mol, prm)

# Load some coordinates
mol.read(join(datadir,'structure.pdb'))


RuntimeError                              Traceback (most recent call last)
<ipython-input-16-32a9d048c7d7> in <module>
     18 
     19 # Create a FFEvaluate object
---> 20 ffev = FFEvaluate(mol, prm)
     21 
     22 # Load some coordinates

/software/software/HTMD/1.23.5/lib/python3.6/site-packages/ffevaluation/ffevaluate.py in __init__(self, mol, prm, betweensets, cutoff, rfa, solventDielectric)
    141         setA, setB = calculateSets(mol, betweensets)
    142 
--> 143         args = list(init(mol, prm))
    144         args.append(setA)
    145         args.append(setB)

/software/software/HTMD/1.23.5/lib/python3.6/site-packages/ffevaluation/ffevaluate.py in init(mol, prm)
    340             dihparam = prm.dihedral_types[ty[::-1]]
    341         else:
--> 342             raise RuntimeError('Could not find type {} in dihedral_types'.format(ty))
    343         i, j = sorted([dihed[0], dihed[3]])
    344         s14_atom_list[i].append(j)

RuntimeError: Could not find type ('NH1', 'CT1', 'CT3', 'HA3') in dihedral_types

**Comment by stefdoerr** [comment]
Is the gauss min file a ligand?
If yes can you check their prm files if there are atom types defined called NH1 CT1 CT3 HA3?
It seems to be missing the energy terms for the above dihedral angle.

**Comment by zainbsa** [comment]
Kindly find the link for my files. The filtered.* is after striping the waters and ions, while the parameters used for preparing the complex are tmp_gauss.*, top_water*, par_all36m*. Please let me know if I am missing anything. 
Thanks
https://filesender.cesnet.cz/?s=download&token=86152803-7326-4ea2-9d22-6b2c19e8ffc2

**Comment by zainbsa** [comment]
Hello, when I used the following parameters;
from ffevaluation.ffevaluate import FFEvaluate, loadParameters, viewForces
from moleculekit.molecule import Molecule
from htmd.home import home
import parmed
from os.path import join

datadir = home(dataDir='abeta_sergio')

# Load the parameters
prm = parmed.charmm.CharmmParameterSet('par_all36m_prot_fixed.prm', 'tmp_gauss-min_charmm.rtf', 'tmp_gauss-min_charmm.par', 'toppar_water_ions.str', 'top_water_ions.rtf')

# Load the topology
mol = Molecule('filtered.prmtop')

# Create a FFEvaluate object
ffev = FFEvaluate(mol, prm)

# Load some coordinates
mol.read('filtered.pdb')

# Calculate energy and forces
energies, forces, atom_energies = ffev.calculate(mol.coords)
# Visualize the forces
viewForces(mol, forces * 0.1)
# Calculate interaction energy between the protein and the ligand
ffev = FFEvaluate(mol, prm, betweensets=('protein', 'resname MOL'))
energies = ffev.calculateEnergies(mol.coords)
I got a VMD prompt, but it doesnt make any sense at all...Am I still doing something wrong OR how am I suppose to read this?
![Screenshot_20210831_134550](https://user-images.githubusercontent.com/85734960/131497783-54a11ad0-6f4e-4dac-90a7-139957af9c69.png)

**Comment by zainbsa** [comment]
I was expecting to get a file that will show the interaction values. If that makes sense
