### ISSUE TITLE
Adaptive step failing

### ISSUE THREAD

**Issue by smar966** [Acellera/htmd#1007]
Dear support team,

I am running adaptive sampling. The first epoch is done, and at the stage of running the adaptive.py script to create the second epoch, the process fails. My system is very large (>100,000 atoms), I don't know if it's because of that. 
Can you help me solve the issue? I'm attaching the adaptive.log file, please let me know what else do you need.

Thanks in advance!
Sergio
[adaptive.log](https://github.com/Acellera/htmd/files/6981963/adaptive.log)

**Comment by stefdoerr** [comment]
Do you define a goal function? Can you share it with me? Because I think it's complaining about some function signature.

**Comment by smar966** [comment]
Not goal, but adaptive. Here is the content of the adaptive.py:

from htmd.ui import *
htmd.config.config(ncpus=2)
md = AdaptiveMD()
md.nmin=2
md.nmax=10
md.nepochs = 10
md.projection = MetricRmsd(trajrmsdstr='protein and noh', refmol=Molecule('generators/0/structure.pdb'))
md.ticadim = 1
md.app = LocalGPUQueue()
md.dryrun = True
md.run()

**Comment by stefdoerr** [comment]
Seems to me actually like an incompatibility of the python code with the C function lib. This is weird though but seeing as you are on an old HTMD version, could you create a new environment with the latest HTMD 1.24.8 version and try again?

**Comment by smar966** [comment]
I'm using a grid installation and I'm not the one with permissions to upgrade it. Are you sure a newer version will solve the problem?...

**Comment by stefdoerr** [comment]
It seems to me like the installation has been broken. There is nothing wrong with the code you wrote and the error it throws is in a C function call which must be the HTMD atomselection calls.
In any case there have been many bugfixes since then in HTMD so I would advise to create a new env with the latest version anyway to ensure the results are correct.  They don't need to delete the old env, just make a new one for the new HTMD version

**Comment by smar966** [comment]
I've tried to run it on 2 different environments (the grid environment and my own machine) and the results were the same, but the HTMD version is the same in both. 
So I'll try to create an updated version and I'll let you know. Thank you!

**Comment by smar966** [comment]
@stefdoerr, I found the problem! I was using the full hydrated structure.pdb as reference, but I have to use the "filtered.pdb" because that's the system that will be analyzed during the adaptive step. After correcting this, the script is running fine.
Thanks a lot for your feedback!

**Comment by stefdoerr** [comment]
Oh great! That's a very weird error for it to throw though. But great you figured it out.
