### ISSUE TITLE
Using CHARMM36 for AdaptiveSampling/AdaptiveBandit 

### ISSUE THREAD

**Issue by DanielWicz** [Acellera/htmd#1008]
How do I point in the input file of a generator to use CHARMM36 ? Because the example in the AdaptiveSampling/AdaptiveBandit uses one-file charmm22 force field. So it's impossible to use Charmm36 as a single file per Charmm36 definition.

**Comment by DanielWicz** [comment]
Answer: Basically, you (I) don't need to use build-in MD engine to generate new trajectories. The idea is to provide "run.sh" as a generator that outputs .xtc files and topology file (pdb, psf etc.). You can e.g. use OpenMM/Gromacs/NAMD to do this.

**Comment by stefdoerr** [comment]
Exactly :) I was on holidays and was not able to answer it as quickly, but indeed you can use any MD software as long as it produces the right output files.
