### ISSUE TITLE
Nucleic Acid FF

### ISSUE THREAD

**Issue by shozebhaider** [Acellera/htmd#102]
Can you please add the following updated OL15 force field in the Amber list for RNA/DNA simulations.

http://fch.upol.cz/ff_ol/downloads.php

Many thanks.

**Comment by j3mdamas** [comment]
Hi @shozebhaider,

I'll add them soon, but they'll only be available when the next release is made (in September).

Cheers,
João

**Comment by j3mdamas** [comment]
Done here: Acellera/htmd@ac7852ca0dbda7500390b4ae4b7a8e5865072705

**Comment by j3mdamas** [comment]
@shozebhaider tested a build with holiday junction, it worked. needs more testing. I'd really appreciate any feedback and many some test builds that could be interesting to put in the code tests

**Comment by shozebhaider** [comment]
I shall do more tests on unusual systems and get back to you with examples and example notebooks. 

Best Wishes

Shozeb

**Comment by j3mdamas** [comment]
thanks.
