### ISSUE TITLE
aggregate Time - Metric data attribute error

### ISSUE THREAD

**Issue by JanaHorackova** [Acellera/htmd#1021]
Hi,
I want to use the aggregate time attribute of a MetricData object like this: data.aggTime (from documentation). I keep getting this error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-4d4e197dd566> in <module>
      3 
      4 # Estimate the total simulation time
----> 5 data.aggTime

AttributeError: 'MetricData' object has no attribute 'aggTime'

**Comment by stefdoerr** [comment]
Hi Jana, this happens if there is no fstep set on MetricData. Try setting `data.fstep = X` where X is your simulation sampling frequency in nanoseconds. In our case it's usually 0.1
