### ISSUE TITLE
faster equilibration.write()

### ISSUE THREAD

**Issue by alejandrovr** [Acellera/htmd#1022]
For very large systems, writing the equilibration folder takes a really long time, probably due to some of the sanity checks that are performed (cis peptide bonds). Could we make these checks an option?

**Comment by stefdoerr** [comment]
We could, but how many systems are you preparing that this is an issue though.

**Comment by alejandrovr** [comment]
Actually quite often, any system involving membranes. In general, it also feels unnecessary to double check.

**Comment by stefdoerr** [comment]
https://github.com/Acellera/htmd/commit/d22e1844b5251855d743637f36fd2b5aac8861b7
Go wild
