### ISSUE TITLE
smart restart via slurm

### ISSUE THREAD

**Issue by alejandrovr** [Acellera/htmd#1024]
ACEMD cannot restart trajectories on a GPU different to the one where the simulation first started.
Can we figure a way to automatically detect on which GPU it started and send the "restart job" to a suitable GPU via slurm?

**Comment by stefdoerr** [comment]
The solution is for ACEMD3 to implement restarts which don't depend on the GPU they ran on.
I think there is a plan for that @raimis ?

**Comment by stefdoerr** [comment]
It's not related to HTMD. It's also not related with jobqueues library because that one cannot determine either on what SLURM node the job ran before. This must be fixed in acemd3
