### ISSUE TITLE
Convert voxel to the molecule

### ISSUE THREAD

**Issue by mkoohim** [Acellera/htmd#1026]
Hi,
I am wondering if there is any way to convert back the voxel to the original molecule?

suppose i built the mol_voxel:
`mol_vox, mol_centers, mol_N = getVoxelDescriptors(mol, boxsize=[10, 10, 10], voxelsize=1, center=ca_center)
`

is there any way to convert back `mol_vox`to `mol`?

**Comment by stefdoerr** [comment]
No sorry, we don't have such functionality. It's not trivial anyway since the contributions of atoms are summed in the voxels.
