### ISSUE TITLE
Problem with the AMBER builder

### ISSUE THREAD

**Issue by jnoske** [Acellera/htmd#1028]
Hello,
I have problem with the builder in htmd 2.0.3. I want to build a protein-ligand-system.
Previously in the tleap input file, the ligand was loaded as a .mol2 file and combined with the protein.
Now the protein and the ligand are in one .pdb file and tleap crashes because there are no parameters for the residue:

FATAL:  Atom .R<MOL 204>.A<H8 21> does not have a type.

The .frcmod parameters are loaded as well, so I dont unterstand why it cannot provide parameters for my ligand, previously when my ligand was loaded as mol2 file and combined in tleap everthing worked fine.

[input.txt](https://github.com/Acellera/htmd/files/8289326/input.txt)
[param0_ligand.txt](https://github.com/Acellera/htmd/files/8289329/param0_ligand.txt)
[tleap.txt](https://github.com/Acellera/htmd/files/8289331/tleap.txt)

**Comment by stefdoerr** [comment]
Hi, the building behaviour indeed changed in the last HTMD versions. You now need to pass also the `prepi` or `mol2` file in amber.build topos argument like this and the filenames need to match between the frcmod and prepi/mol2. 
I definitely need to add documentation on this though, I had totally forgotten.

```python
        params = amber.defaultParam() + [os.path.join(refdir, "BEN.frcmod")]
        topos = amber.defaultTopo() + [os.path.join(refdir, "BEN.mol2")]

        bmol = build(newmol, outdir=tmpdir, param=params, topo=topos, ionize=False)
```

**Comment by jnoske** [comment]
Thanks that works!

**Comment by stefdoerr** [comment]
I updated now the tutorial on github and will be available on the next release. Thanks for the report!
