### ISSUE TITLE
Request parameterize file

### ISSUE THREAD

**Issue by binfen** [Acellera/htmd#1029]
Hi! Could you tell me where is the parameterize tool with htmd2.0.3? 
Thanks！

**Comment by stefdoerr** [comment]
Hi, the parameterize library is not publicly available anymore. You can use the Parameterize app in PlayMolecule, although right now it's undergoing maintenance, I hope to have it fixed very soon https://www.playmolecule.com/parameterize/

**Comment by binfen** [comment]
Fine. I've tried your web site and hope the tool coming soon.

**Comment by stefdoerr** [comment]
@binfen it's fixed now
