### ISSUE TITLE
unable to install HTMD=1.13.10

### ISSUE THREAD

**Issue by Lizeerd** [Acellera/htmd#1031]
i want to use the tool 'deeplyrough' which need htmd=1.13.10, ref: https://github.com/BenevolentAI/DeeplyTough
env: linux-64, python=3.6

if i run the following code:
"conda install -c acellera -c conda-forge htmd=1.13.10"
it raised: 
"PackagesNotFoundError: The following packages are not available from current channels"

then i tried to install it directly from github --tag=1.13.0 with the following code
"curl -LO https://github.com/Acellera/htmd/archive/refs/tags/1.13.10.tar.gz && \
    tar -xvzf 1.13.10.tar.gz && rm 1.13.10.tar.gz && cd htmd-1.13.10 && \
    python setup.py install && \
    cd .. && \
    rm -rf htmd-1.13.10;"
and it returned: 
"Processing dependencies for htmd==0.0.0
Finished processing dependencies for htmd==0.0.0"
which actually didn't installed successfully

so how can i install htmd-1.13.10

**Comment by stefdoerr** [comment]
hi @Lizeerd ,  can you give my fork a try? https://github.com/stefdoerr/DeeplyTough
I updated their code to use moleculekit but I don't have time to test it. If it works fine for you I will make it a pull request for them to accept
