### ISSUE TITLE
unsatisfiable error when i installed htmd

### ISSUE THREAD

**Issue by omotcha** [Acellera/htmd#1032]
I tried to install htmd using conda on my ubuntu linux, but encountered UnsatisfiableError: 

...The following specifications were found to be incompatible with your system:
- feature:/linux-64::__glibc==2.27=0
- python=3.7 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
Your installed version is :2.27

Does it mean that my glibc should be upgraded(but it seems that my glibc version satisfies the requirement)? Note that my kernel version is 4.15.0-20-generic and the python verion is 3.7.12.
I also tried to install your early releases by like "conda install htmd==1.10.0" but returns a PackagesNotFoundError. So what should I do next? 

Thanks.

**Comment by stefdoerr** [comment]
Hi, the installation command you are using is wrong: https://software.acellera.com/install-htmd.html
