### ISSUE TITLE
Install with Amber20?

### ISSUE THREAD

**Issue by khoroshyy** [Acellera/htmd#1033]
Hi.
Can I install HTMD with Amber20?
Thanks.
Petro.

**Comment by stefdoerr** [comment]
Is there any specific reason for this? Currently it installs with Amber22

**Comment by khoroshyy** [comment]
> Is there any specific reason for this? Currently it installs with Amber22

HI, Ambertoolls 22 is fine, what I cannot figure out how to install Amber20 along with it. When I install Amber 20 separately, I would download Amber20 and Ambertoolls22 and run the installation script which will install comes system and needed software. My problem is that in this way, conda do not see ambertools installed and trying to install ambertools from condaforge. 
Thanks.
Best regards.
Petro.

**Comment by stefdoerr** [comment]
Ah, you mean AMBER20 as in the simulation software. I am not sure how to install it in the same env, I have never tried.
But I don't see an issue with installing ambertools22 again inside the conda env. It's not used directly for the simulations as far as I know.

**Comment by khoroshyy** [comment]
OK. Thanks. I actually have not tried it.
