### ISSUE TITLE
how to cap peptides?

### ISSUE THREAD

**Issue by wowfee** [Acellera/htmd#1034]
Hello,
I have a peptide pdb (pep.pdb), and i want to cap terminal with ACE and NME, i used the followed code but failed:
```py
from htmd.ui import *
pep = Molecule('pep.pdb')
cap = amber.build(pep,caps['P']=['ACE','NME'],outdir='./',ionze=False)
```
it not work..
how could i to do this? 
thank you!

**Comment by stefdoerr** [comment]
```
caps['P']=['ACE','NME']
```
this is a dictionary assignment statement. you cannot pass to a function an assignment

```
bmol = amber.build(pep,caps={'P': ['ACE','NME']},outdir='./',ionize=False)
```
this is the correct syntax. or this:
```
caps = {}
caps['P']=['ACE','NME']
bmol = amber.build(pep,caps=caps,outdir='./',ionize=False)
```
I guess the documentation is a bit confusing on that aspect.

**Comment by wowfee** [comment]
thank you, the P in caps['P'] is the chain name? it return that not segment P in molecular, my pep.pdb is only one chain M.

**Comment by stefdoerr** [comment]
it's the segment name.
`print(mol.segid)` to see what the segment ID is

**Comment by wowfee** [comment]
thank you so much ,it worked now!

**Comment by stefdoerr** [comment]
Great!
