### ISSUE TITLE
unable to install htmd, glibc incompatible

### ISSUE THREAD

**Issue by chenludi** [Acellera/htmd#1038]
Hi,

I am unable to install htmd by minoconda. Here is the error I got. I also tried not specifying the version of htmd and I got the same error.
```
conda install -c acellera htmd=2.1.6
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                       

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.35=0
  - feature:|@/linux-64::__glibc==2.35=0

Your installed version is: 2.35
```
I used the latest minoconda
```
conda --version
conda 4.12.0
```
I constructed conda environment with python=3.8
```
conda create --prefix ./condaenv/py38htmd python=3.8
```

I also had the same problem with another Linux server which has an old glibc version (2.17). In this server, I had reported errors about version incompatibility of the glibc when using anaconda/2022.05. 
I also tried to use previous anaconda versions,  anaconda/2020.11 and anaconda/2020.02. It keeps asking me to register when using these two versions of anaconda.

**Comment by stefdoerr** [comment]
Hi, I am currently trying to build moleculekit for older glibc versions to fix this issue. I'll update you here once it's done.

**Comment by stefdoerr** [comment]
Hi @chenludi can you try again now? It should be pulling version 1.4.5 of moleculekit which doesn't have glibc issues. 
Actually I see now that your installation command is not correct. Please install with:
```
conda install htmd=2.2.0 python=3.10 -c acellera -c conda-forge
```

**Comment by chenludi** [comment]
Thank you for the fast response! @stefdoerr 

I installed htmd according to your command. I didn't get glibc error anymore. However, I have registration problems.

I first tried ```htmd_register``` and filled in the information. It returns with ```Cannot read the registration file``` when importing the package.

Then I called ```htmd_register()``` in python shell and filled up the information as suggested. However, I was asked to register again.

In addition, it returns with ```  Registration completed!``` every time.

Thank you!

**Comment by stefdoerr** [comment]
@chenludi Right I can reproduce this. There is some issue with the license server. I'll try to fix this ASAP

**Comment by stefdoerr** [comment]
Hi @chenludi this should be fixed now. Give it another try

**Comment by chenludi** [comment]
Thank you! It works well now.
