### ISSUE TITLE
Distance restraints

### ISSUE THREAD

**Issue by danaeko** [Acellera/htmd#1039]
Dear Acellera group,

I want to run an equilibration using distance restraints between several atoms and therefore I would like to ask you how can I specify distance restraints between two atoms in my input file for ACEMD. The option "atomRestraint" is only for positional restraints, right?

Thank you in advance

**Comment by stefdoerr** [comment]
@raimis is there support for distance restraints in ACEMD3?

**Comment by danaeko** [comment]
ACEMD allows only positional restraints? There is no implementation like extra bond (NAMD)?

**Comment by raimis** [comment]
ACEMD supports PLUMED (https://software.acellera.com/acemd/manual.html#metadynamics). With PLUMED, you can set up a huge variety of restraints.

**Comment by danaeko** [comment]
Thank you, I will try it!
