### ISSUE TITLE
Charmm file error on membrane build

### ISSUE THREAD

**Issue by shozebhaider** [Acellera/htmd#1042]
Hello Support team,

I am trying to do a membrane build using the example 
```py
from htmd.membranebuilder.build_membrane import listLipids, buildMembrane

# List all available lipids
listLipids()
# Define the dimensions of the membrane in the x and y axis in units of Angstrom
dimensions = [170, 170]
# Define the upper and lower layer lipid composition and ratio
ratioupper = {'popc': 8,'chl1':2}
ratiolower = {'popc': 8,'chl1':2}
# Build the membrane
memb = buildMembrane(dimensions, ratioupper, ratiolower, waterbuff=20.0)
# Visualize the membrane
memb.view()
```
However, I get this charmm file error: 
```
CharmmFileError: [Errno 2] No such file or directory: '/home/shozeb/miniconda3/envs/htmd/lib/python3.10/site-packages/htmd/share/membranebuilder/charmm-toppar/par_all36m_prot.prm'
```
This is incorrect as I have all the relevant files in this directory. Do I need to explicitly provide a path to my files?

Many thanks for your help.

Best wishes

Shozeb

**Comment by stefdoerr** [comment]
Hi Shozeb, this is weird, what version of HTMD are you using? `conda list htmd`

**Comment by shozebhaider** [comment]
Hi @stefdoerr I am using HTMD 2.2.0

**Comment by stefdoerr** [comment]
Can you post the whole error that it generated?

**Comment by stefdoerr** [comment]
Indeed it's a mistake of mine. Can you unzip this file into: `/home/shozeb/miniconda3/envs/htmd/lib/python3.10/site-packages/htmd/share/membranebuilder/charmm-toppar/`
[par_all36m_prot.zip](https://github.com/Acellera/htmd/files/10194951/par_all36m_prot.zip)

**Comment by shozebhaider** [comment]
Dear Stefan,

I shall indeed. However, I thought my miniconda might be broken, so I am reinstalling everything afresh. I shall update here as soon it the installation comes out of the infinite dependency searching mode.

**Comment by stefdoerr** [comment]
No everything was fine, I just forgot to add that file in some previous release to the folder. I will make a new release the following days which will have it but in the meanwhile add it manually to the path which the error points to

**Comment by shozebhaider** [comment]
Thanks @stefdoerr. Everything is working fine now.
