### ISSUE TITLE
Problems installing HTMD

### ISSUE THREAD

**Issue by lblaabjerg** [Acellera/htmd#1043]
Hi, 

I am having some problems installing HTMD (specifically version 2.0.5). I am installing in a fresh Miniconda environment with Python 3.7. 

If I run `conda install htmd=2.0.5 -c acellera -c conda-forge` it gets stuck trying to solve the environment (have tried waiting for ~20 min):

> (thermonet) [lasbla@s96n41 ThermoNet]$ conda install htmd=2.0.5 -c acellera -c conda-forge
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: \

If I run `conda install htmd=2.0.5 -c acellera` I get the following error:

> (thermonet) [lasbla@s96n41 ThermoNet]$ conda install htmd=2.0.5 -c acellera
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: /
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed
> 
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:
> 
>   - feature:/linux-64::__glibc==2.17=0
>   - feature:|@/linux-64::__glibc==2.17=0
> 
> Your installed version is: 2.17

**Comment by stefdoerr** [comment]
Why do you want to install an old version of HTMD? (and python 3.7 which reaches end of life in 6 months from now?)

**Comment by lblaabjerg** [comment]
Hi Sebastian. Thank you for the quick reply. I am trying to reproduce the results in this paper: https://github.com/gersteinlab/ThermoNet.

**Comment by stefdoerr** [comment]
Try 2.0.8. It's the latest version we released for python 3.7 and it should not have significant changes to 2.0.5

**Comment by stefdoerr** [comment]
Oh actually I now read the full question. You indeed should have waited for 20+ minutes :laughing:  That's conda for you.
The much faster alternative is using mamba

```
conda create -n myenv
conda activate myenv
conda install python=3.7 mamba -c conda-forge
mamba install htmd=2.0.8 -c acellera -c conda-forge
```
Conda dependency resolver is total trash. Installing and using mamba instead will get the package installed in a minute

**Comment by stefdoerr** [comment]
This is very weird because I can see htmd-deps 2.0.8 for python 3.7 existing...
Is there any chance you could move to python 3.8?

**Comment by lblaabjerg** [comment]
Hmm. I don't think that is possible because of dependency issues with the Tensorflow version used in ThermoNet (https://github.com/gersteinlab/ThermoNet).

I also tried installing HTMD 1.22 but then get the error:

> Looking for: ['htmd=1.22']
> 
> conda-forge/linux-64                                        Using cache
> conda-forge/noarch                                          Using cache
> pkgs/main/noarch                                              No change
> pkgs/r/linux-64                                               No change
> pkgs/main/linux-64                                            No change
> pkgs/r/noarch                                                 No change
> acellera/noarch                                               No change
> acellera/linux-64                                             No change
> 
> Pinned packages:
>   - python 3.7.*
> 
> 
> Encountered problems while solving:
>   - nothing provides ambermini >=16.16.0 needed by htmd-deps-1.22.3-py37_0
