### ISSUE TITLE
Issues with equilibration phase  (Protein-RNA-complex)

### ISSUE THREAD

**Issue by vas2201** [Acellera/htmd#1048]
Hello, 
I am running MD simulation on Protein-DNA-RNA complex. However, The DNA and RNA are dissociated in first step of the Equilibration phase.   Could you please advise on this matter ?.

Attached jupyter notebook and pdb as google drive 
https://drive.google.com/file/d/18_0bsrF1YEvO1XITmELEsTMFIsn92icK/view?usp=sharing

Regards
Vas

**Comment by stefdoerr** [comment]
Hi, can you show me the ACEMD input file in the equilibration folder?

**Comment by vas2201** [comment]
Thanks for your reply. 

input file 
******************************************************************************
#
barostat             	on
barostatpressure     	1.01325
boxsize              	117.9540023803711 148.80099487304688 127.14400482177734
coordinates          	structure.pdb
cutoff               	9
minimize             	500
parameters           	parameters
pme                  	on
restart              	on
slowperiod           	1
structure            	structure.psf
switchdistance       	7.5
switching            	on
temperature          	298
thermostat           	on
thermostatdamping    	1
thermostattemperature	298
timestep             	4
trajectoryfile       	output.xtc
trajectoryperiod     	25000
atomRestraint        	"protein and name CA" axes xyz width "0" setpoints 1@0 0@20ns
atomRestraint        	"protein and noh and not name CA" axes xyz width "0" setpoints 0.1@0 0@20ns
atomRestraint        	"nucleic and backbone" axes xyz width "0" setpoints 1@0 0@20ns
atomRestraint        	"nucleic and not backbone and noh" axes xyz width "0" setpoints 0.1@0 0@20ns
run                  	125000

**Comment by stefdoerr** [comment]
This looks ok, it should be applying restraints on the RNA and protein so they cannot move in the first step. Are you sure it's not just a wrapping issue? Can you send a screenshot of the first simulation step where you saw them disassociated?

**Comment by vas2201** [comment]
HI, 
I attached screenshot,  I see frame as DNA & RNA is not complex with protein.  I can't be very sure it is wrapping issue. 
https://drive.google.com/file/d/1LmDsahUvFM2XYbgjNNdpxuDrhqbMWrfS/view?usp=share_link
Regards
Vas

**Comment by stefdoerr** [comment]
can you show the waters as well? Then we will know if it's a wrapping issue

**Comment by vas2201** [comment]
attached : 
https://drive.google.com/file/d/1eA2Kt2AD0sU1hS3L0FvH65_7fybaNJnT/view?usp=share_link

**Comment by stefdoerr** [comment]
Yes this looks like a visualization issue due to the wrapping.
Try loading the trajectory into [moleculekit](https://software.acellera.com/moleculekit/installation.html) and re-wrapping:

```py
from moleculekit.molecule import Molecule
mol = Molecule("./structure.prmtop")
mol.read("output.xtc")
mol.wrap("protein or nucleic")
mol.view()
```

**Comment by stefdoerr** [comment]
https://software.acellera.com/htmd/tutorials/WrappingTutorial.html
Here is a tutorial which explains periodic wrapping in case you find it useful

**Comment by vas2201** [comment]
Thank you.

**Comment by stefdoerr** [comment]
Without having the files to check I can only assume that the PSF is wrong. Either different atom order from your dcd or wrong bonds specified.
