### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by jmroldan1975** [Acellera/htmd#1052]
Hi, I have just received this error message when running KDEEP: RuntimeError: Could not find any of the following fields dict_keys([None]) in SDF file /data/in/tmpc79cbhz2.sdf and ligand C23H25N3O5. I am attaching the ligand and receptor used. Can you check what happens? Thank you very much.
[files.zip](https://github.com/Acellera/htmd/files/10955402/files.zip)

**Comment by stefdoerr** [comment]
Right, thanks for pointing it out. I'll fix it ASAP

**Comment by stefdoerr** [comment]
Ok it's fixed now. Thanks a lot for the notification
