### ISSUE TITLE
Problem with charmm.build

### ISSUE THREAD

**Issue by danaeko** [Acellera/htmd#1055]
Dear acellera group,

I am trying to generate psf/pdb files for my protein system and I am getting the following error message "BuildError: 'No structure pdb/psf file was generated. Check /media/debian-user/TOSHIBA EXT/Membr_sys/sys_full_open/build_charmm_ok/log.txt for errors in building.'"
However, the log.txt file is empty. Is there any problem with charmm.build?

Thank you in advance

**Comment by stefdoerr** [comment]
No other errors? Not even in the console? Also I see there is a space in your path. Are you sure you are escaping

**Comment by danaeko** [comment]
Sorry for the late response, I am sending you the exact error message
I don't think that the path is the problem because I run the script in different directories and I get the same error message. Also, with the scripts I use I have built many protein/membrane systems and they were running normally before 5/6 months.

BuildError                                Traceback (most recent call last)
Cell In [5], line 18
     13 al={"SAPI24":"SP24", "SAPI25":"SP25"}
     14 #protein_charmm=charmm.build(protein, outdir='build_protein_system',aliasresidues=al,param=params, topo=topos, stream=streams, caps=None, ionize=False)
     15 
     16 
     17 #protein_charmm=charmm.build(protein, aliasresidues=al, outdir='build_charmm2',param=params, topo=topos, stream=streams, caps={"AS1": ['first None', 'last None'], "AS2":['first None', 'last None']}, ionize=True, saltconc=0.1)
---> 18 protein_charmm=charmm.build(protein_solv, aliasresidues=al, outdir='build_charmm_ok',param=params, topo=topos, stream=streams, caps={"AS1": ['first None', 'last CTER'], "AS2":['first None', 'last CTER'], "AS7":['first None', 'last None']},ionize=True,saltconc=0.15)

File ~/anaconda3/envs/acemd_env/lib/python3.8/site-packages/htmd/builder/charmm.py:391, in build(mol, topo, param, stream, prefix, outdir, caps, ionize, saltconc, saltanion, saltcation, disulfide, regenerate, patches, noregen, aliasresidues, psfgen, execute, _clean)
    389     molbuilt.read(path.join(outdir, "structure.psf"))
    390 else:
--> 391     raise BuildError(
    392         "No structure pdb/psf file was generated. Check {} for errors in building.".format(
    393             logpath
    394         )
    395     )
    397 if ionize:
    398     os.makedirs(path.join(outdir, "pre-ionize"))

BuildError: 'No structure pdb/psf file was generated. Check /media/debian-user/TOSHIBA EXT/Membr_sys/sys_dabd_open_memb/build_charmm_ok/log.txt for errors in building.'

**Comment by stefdoerr** [comment]
What does it print before the error. I need to see as much information as possible, otherwise it's hard to understand the issue.
Also can you try to locate that directory `/media/debian-user/TOSHIBA EXT/Membr_sys/sys_dabd_open_memb/build_charmm_ok/` with your file browser and look what is inside of it?

**Comment by stefdoerr** [comment]
So, running the build.vmd file manually works and builds the pdb psf files? That's very weird. I still have a feeling it might have to do with the windows-like paths. Can you try building the system inside your home folder instead of the external hard drive?

**Comment by stefdoerr** [comment]
Can you run the following snippet in the latest HTMD?

```py
from htmd.ui import *
mol = Molecule("3ptb")
mol.filter("protein")
pmol = systemPrepare(mol)
smol = solvate(pmol, pad=10)
charmm.build(smol, ionize=False, outdir="/tmp/test")
```
for me this works fine. So if there is any issue it must have to do with the system you are building in which case if you can upload here the files and the code you used so that I can try to debug it.

**Comment by stefdoerr** [comment]
what OS (and version) are you on?

**Comment by stefdoerr** [comment]
yeah this was compiled on 22.04 LTS so that's probably causing the libc issue. I'll see if I can make the build in 20.04 which hopefully will be forwards compatible

**Comment by stefdoerr** [comment]
Hi, can you try installing psfgen version 2.0.0_3 and tell me if it fixes your issue?

**Comment by stefdoerr** [comment]
Great!
