### ISSUE TITLE
3D FES profile  

### ISSUE THREAD

**Issue by vas2201** [Acellera/htmd#1065]
I am currently employing the following script to generate a Free Energy Surface (FES) profile, utilizing TICA-1 and TICA-2 as dimensions. Could I potentially integrate a third dimension into this script, using free energy (kcal/mole) as this additional dimension? This would enable the creation of a 3-dimensional FES profile.

model.plotFES(0, 1, temperature=360, states=True)

Thank you.

**Comment by stefdoerr** [comment]
Not with the existing function. You would have to implement it yourself
