### ISSUE TITLE
Switch from NVT to NPT (Equilibration)

### ISSUE THREAD

**Issue by H-EKE** [Acellera/htmd#1066]
Hi,

Im new usign ACEMD. I have seen that it is possible to define the equilibration protocol as in the tutorial:

```
from htmd.protocols.equilibration_v3 import Equilibration
from htmd.mdengine.acemd.acemd import GroupRestraint

# Use a 10A flat bottom potential to prevent the ligand from diffusing from original position during equilibration
width = np.array([10, 10, 10])
flatbot = GroupRestraint('segname L and noh', width, [(5, '0ns')])

md = Equilibration()
md.runtime = 40
md.timeunits = 'ns'
md.temperature = 300
md.restraints = [flatbot] + md.defaultEquilRestraints('20ns')
md.useconstantratio = True
md.write(os.path.join(path,'build'), os.path.join(path,'equil'))
```

Is there a fast way to specify to do a certain amounts in NVT, and the shift to NPT? Im trying to adapt some NAMD scripts that I had where I combined cycles of NVT-NPT-NVT-NPT.

Thanks in advance!

**Comment by stefdoerr** [comment]
No sorry, you will need to run individual simulations in a row, ACEMD does not allow switching from NVT to NPT during runtime
