### ISSUE TITLE
Registration not working for HTMD3 2022_12_07

### ISSUE THREAD

**Issue by honzamican** [Acellera/htmd#1068]
Dear Accelera,

we have purchased the license for HTMD3 for Masaryk University. 
I tried to run HTMD as a singularity container as we do in our workplace:
singularity exec htmd_2022_12_07.sif jupyter notebook --no-browser --port=8891

In the jupyter notebook, I import htmd:
from htmd.ui import *

And I get the following message: 

Registration is not approved: <html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>openresty</center>
</body>
</html>

I have my HTMD registration file in my user home directory, as well as in the same folder in which I am running the HTMD3 singularity container from (folder .htmd with subfolder .registered-htmd, containing the file named registration). Apparently, it is not recognized.

HTMD then prompts me to register, I type in my name, email, institution, city, and country, I get the following error: 

Registration failed: <html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>openresty</center>
</body>
</html>

I would like to ask you for help on how to overcome this issue, especially since I need to run adaptively sampled simulations which are due to a certain date. You can also contact me via honzamicann at gmail dot com. Thank you very much in advance.

**Comment by giadefa** [comment]
please write to ***@***.***

**Comment by honzamican** [comment]
Dear Accelera, I cannot write to ***@***. Which email I should write to?

Dne po 7. 8. 2023 15:16 uživatel Gianni De Fabritiis <
***@***.***> napsal:

> please write to ***@***.***
>

**Comment by stefdoerr** [comment]
hi, that would be info@acellera.com
Not sure what went wrong with Gianni's email
