### ISSUE TITLE
ACEMD on multiple nodes and/or GPUs

### ISSUE THREAD

**Issue by danaeko** [Acellera/htmd#1070]
Dear acellera group,

I would like to ask if I can run ACEMD in parallel on multiple nodes and/or GPUs.

Thank you in advance!

Danai

**Comment by stefdoerr** [comment]
You can run on multiple GPUs on a single node but you will lose some speed. It's only useful if your system does not fit into the memory of a single GPU.
Across nodes you cannot, there is no support for networking, also it would slow it down even further.
