### ISSUE TITLE
Error : model.viewStates(nucleic=True), not recognize the 'nucleic' parameter

### ISSUE THREAD

**Issue by vas2201** [Acellera/htmd#1073]
I am currently engaged in conformational analysis for RNA using adaptive simulations. I've encountered an issue where the code does not recognize the 'nucleic' parameter in the snippet provided below. Could you please provide some guidance on how to resolve this?.

model.numsamples = 1
model.viewStates(nucleic=True)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[47], line 2
      1 model.numsamples=1
----> 2 model.viewStates(nucleic=True)
      3 #model.viewStates(protein=True)

TypeError: Model.viewStates() got an unexpected keyword argument 'nucleic'

**Comment by stefdoerr** [comment]
I know this is very stupid but just pass `protein=True` (it's very old code, I was not thinking of the larger picture back then). It's only used for alignment anyway so if you want just use `getStates` and write the returned `mols` to files and visualize them as you like.

**Comment by stefdoerr** [comment]
Sorry for the super late response but can you try also protein=False? This might disable all the aligning and just work fine

**Comment by vas2201** [comment]
I tried with given option, The kernel is interrupted after this error message.  No output.  

Getting state Molecules:   0%|                                                                                                  | 0/5 [00:00<?, ?it/s]/home/nmrbox/spenumutchu/anaconda3/envs/100htmd/lib/python3.9/site-packages/moleculekit/align.py:46: RuntimeWarning: Mean of empty slice.
  centroidP = P.mean(axis=0)
/home/nmrbox/spenumutchu/anaconda3/envs/100htmd/lib/python3.9/site-packages/numpy/core/_methods.py:184: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/home/nmrbox/spenumutchu/anaconda3/envs/100htmd/lib/python3.9/site-packages/moleculekit/align.py:47: RuntimeWarning: Mean of empty slice.
  centroidQ = Q.mean(axis=0)
/home/nmrbox/spenumutchu/anaconda3/envs/100htmd/lib/python3.9/site-packages/moleculekit/align.py:27: RuntimeWarning: invalid value encountered in scalar divide
  RMSD = np.sqrt(np.abs(RMSD / P.shape[0]))
Getting state Molecules:  20%|██████████████████                                                                        | 1/5 [00:00<00:01,  2.29it/s]/home/nmrbox/spenumutchu/anaconda3/envs/100htmd/lib/python3.9/site-packages/moleculekit/align.py:46: RuntimeWarning: Mean of empty slice.
  centroidP = P.mean(axis=0)
/home/nmrbox/spenumutchu/anaconda3/envs/100htmd/lib/python3.9/site-packages/numpy/core/_methods.py:184: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/home/nmrbox/spenumutchu/anaconda3/envs/100htmd/lib/python3.9/site-packages/moleculekit/align.py:47: RuntimeWarning: Mean of empty slice.
  centroidQ = Q.mean(axis=0)
/home/nmrbox/spenumutchu/anaconda3/envs/100htmd/lib/python3.9/site-packages/moleculekit/align.py:27: RuntimeWarning: invalid value encountered in scalar divide
  RMSD = np.sqrt(np.abs(RMSD / P.shape[0]))
Getting state Molecules:  40%|████████████████████████████████████                                                      | 2/5 [00:00<00:01,  2.39it/s]/home/nmrbox/spenumutchu/anaconda3/envs/100htmd/lib/python3.9/site-packages/moleculekit/align.py:46: RuntimeWarning: Mean of empty slice.
  centroidP = P.mean(axis=0)
/home/nmrbox/spenumutchu/anaconda3/envs/100htmd/lib/python3.9/site-packages/numpy/core/_methods.py:184: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/home/nmrbox/spenumutchu/anaconda3/envs/100htmd/lib/python3.9/site-packages/moleculekit/align.py:47: RuntimeWarning: Mean of empty slice.
  centroidQ = Q.mean(axis=0)
/home/nmrbox/spenumutchu/anaconda3/envs/100htmd/lib/python3.9/site-packages/moleculekit/align.py:27: RuntimeWarning: invalid value encountered in scalar divide
  RMSD = np.sqrt(np.abs(RMSD / P.shape[0]))
Getting state Molecules:  60%|██████████████████████████████████████████████████████                                    | 3/5 [00:01<00:00,  2.40it/s]/home/nmrbox/spenumutchu/anaconda3/envs/100htmd/lib/python3.9/site-packages/moleculekit/align.py:46: RuntimeWarning: Mean of empty slice.
  centroidP = P.mean(axis=0)
/home/nmrbox/spenumutchu/anaconda3/envs/100htmd/lib/python3.9/site-packages/numpy/core/_methods.py:184: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/home/nmrbox/spenumutchu/anaconda3/envs/100htmd/lib/python3.9/site-packages/moleculekit/align.py:47: RuntimeWarning: Mean of empty slice.
  centroidQ = Q.mean(axis=0)
/home/nmrbox/spenumutchu/anaconda3/envs/100htmd/lib/python3.9/site-packages/moleculekit/align.py:27: RuntimeWarning: invalid value encountered in scalar divide
  RMSD = np.sqrt(np.abs(RMSD / P.shape[0]))
Getting state Molecules:  80%|████████████████████████████████████████████████████████████████████████                  | 4/5 [00:01<00:00,  2.46it/s]/home/nmrbox/spenumutchu/anaconda3/envs/100htmd/lib/python3.9/site-packages/moleculekit/align.py:46: RuntimeWarning: Mean of empty slice.
  centroidP = P.mean(axis=0)
/home/nmrbox/spenumutchu/anaconda3/envs/100htmd/lib/python3.9/site-packages/numpy/core/_methods.py:184: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/home/nmrbox/spenumutchu/anaconda3/envs/100htmd/lib/python3.9/site-packages/moleculekit/align.py:47: RuntimeWarning: Mean of empty slice.
  centroidQ = Q.mean(axis=0)
/home/nmrbox/spenumutchu/anaconda3/envs/100htmd/lib/python3.9/site-packages/moleculekit/align.py:27: RuntimeWarning: invalid value encountered in scalar divide
  RMSD = np.sqrt(np.abs(RMSD / P.shape[0]))
Getting state Molecules: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.38it/s]

**Comment by stefdoerr** [comment]
I believe this should be fixed in the latest HTMD version. Sorry for the very late fix.
