### ISSUE TITLE
Reg : Amber / Charmm Force field parameters for ARG (mono-methyl, dimethyl (asym, sym)

### ISSUE THREAD

**Issue by vas2201** [Acellera/htmd#1084]
Hi, 
I'm in search of force-field parameters for methyl modification of ARG (attached screenshot for your reference).
Screenshot :
(https://github.com/Acellera/htmd/assets/29959559/9edca9ad-6a46-4b1c-bd1c-3cf4f96846be)

Thus far, I've identified parameters for symmetrical dimethylated ARG (sDMA) in CHARMM (as DA2). However, I haven't found parameters for monomethylated ARG (MMA) or asymmetrical dimethylated ARG (aDMA). If you or someone you know has generated or worked on parameters for other types (MMA, aDMA). 

I changed the specific ARG to DA2 ( symmetrical dimethylated ) and build the system using chramm force field. I am getting the following error. please advise on this matter. 

mol = Molecule('step1_pdbreader.pdb')
mol.filter("protein")
mol.set('segid', 'A', sel='protein')
mol_op = systemPrepare(mol)
mol_seg = autoSegment(mol_op)
mol_solv = solvate (mol_seg, pad=10)
mol_amber = charmm.build(mol_solv, saltconc = 0.15, outdir='build-charmm', ignore_ns_errors = 'True')

Regards
Vas

ERROR : 
2024-03-22 00:25:51,946 - moleculekit.readers - WARNING - Atoms with names "HE21" "HE22" were guessed as element H but could also be He (helium). If this is a case, you can correct them with mol.set('element', 'He', sel='name "HE21" "HE22"')
2024-03-22 00:25:51,947 - moleculekit.readers - WARNING - Atoms with names "HG11" "HG12" "HG13" "HG21" "HG22" "HG23" were guessed as element H but could also be Hg (mercury). If this is a case, you can correct them with mol.set('element', 'Hg', sel='name "HG11" "HG12" "HG13" "HG21" "HG22" "HG23"')
2024-03-22 00:25:52,010 - moleculekit.molecule - INFO - Removed 24 atoms. 4650 atoms remaining in the molecule.

---- Molecule chain report ----
Chain P:
    First residue: MET     1  
    Final residue: ARG   319  
---- End of chain report ----

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
File ~/anaconda3/envs/htmd2/lib/python3.10/site-packages/moleculekit/tools/preparation.py:118, in _generate_nonstandard_residues_ff(mol, definition, forcefield, _molkit_ff, outdir, ignore_ns_errors, residue_smiles)
    117 try:
--> 118     from aceprep.prepare import rdk_prepare
    119 except ImportError:

ModuleNotFoundError: No module named 'aceprep'

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
Cell In[11], line 4
      2 mol.filter("protein")
      3 mol.set('segid', 'A', sel='protein')
----> 4 mol_op = systemPrepare(mol)
      5 mol_seg = autoSegment(mol_op)
      6 mol_solv = solvate (mol_seg, pad=10)

File ~/anaconda3/envs/htmd2/lib/python3.10/site-packages/moleculekit/tools/preparation.py:734, in systemPrepare(mol_in, titration, pH, force_protonation, no_opt, no_prot, no_titr, hold_nonpeptidic_bonds, verbose, return_details, hydrophobic_thickness, plot_pka, ignore_ns_errors, _logger_level, _molkit_ff, outdir, residue_smiles)
    731 _fix_protonation_resnames(mol_in)
    733 definition, forcefield = _get_custom_ff(molkit_ff=_molkit_ff)
--> 734 definition, forcefield = _generate_nonstandard_residues_ff(
    735     mol_in,
    736     definition,
    737     forcefield,
    738     _molkit_ff,
    739     outdir,
    740     ignore_ns_errors=ignore_ns_errors,
    741     residue_smiles=residue_smiles,
    742 )
    744 nonpept = None
    745 if hold_nonpeptidic_bonds:

File ~/anaconda3/envs/htmd2/lib/python3.10/site-packages/moleculekit/tools/preparation.py:122, in _generate_nonstandard_residues_ff(mol, definition, forcefield, _molkit_ff, outdir, ignore_ns_errors, residue_smiles)
    120     if ignore_ns_errors:
    121         return definition, forcefield
--> 122     raise RuntimeError(
    123         "To protonate non-canonical aminoacids you need the aceprep library. Please contact Acellera info@acellera.com for more information or set ignore_ns_errors=True to ignore non-canonical residues in the protonation (this will leave the residues unprotonated)."
    124     )
    126 with tempfile.TemporaryDirectory() as tmpdir:
    127     for res in not_in_ff:

RuntimeError: To protonate non-canonical aminoacids you need the aceprep library. Please contact Acellera info@acellera.com for more information or set ignore_ns_errors=True to ignore non-canonical residues in the protonation (this will leave the residues unprotonated).

**Comment by vas2201** [comment]
Looks like I can use amber force field . 
I have come across a resource provided by Dimitris's Group via the following link, which includes libraries, definitions, frcmod files, and sample input files for the modified ARG amino acid:
http://pc164.materials.uoi.gr/dpapageo/amberparams.php
However, I am uncertain about the process of copying or updating these libraries and frcmod files to the original files. If possible, could you please offer guidance and suggestions on how to update these parameters effectively?
Thank you very much for your assistance.

**Comment by vas2201** [comment]
I discovered force field parameters for Dimethyl Arginine (aSym, sym) under the names DA2 and 2MR, which can be found in the directory ~/lib/python3.10/site-packages/htmd/share/builder/amberfiles/ff-ptm/. However, I couldn't locate force field files for monomethyl arginine (MMA). 

After generating the PDB file with DA2 modifications at three sites (194, 206, 225), I encountered errors while constructing the Amber input files. Could you please assist me in resolving this issue?.

-I: Adding /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/cmd to search path.
-I: Adding /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/prep to search path.
-I: Adding /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm to search path.
-I: Adding /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib to search path.
-f: Source ./tleap.in.

Welcome to LEaP!
(no leaprc in search path)
Sourcing: ./tleap.in
----- Source: ./ff0_leaprc.protein.ff14SB
----- Source of ./ff0_leaprc.protein.ff14SB done
Log file: ./leap.log
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/parm10.dat
Reading title:
PARM99 + frcmod.ff99SB + frcmod.parmbsc0 + OL3 for RNA
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/frcmod.ff14SB
Reading force field modification type file (frcmod)
Reading title:
ff14SB protein backbone and sidechain parameters
Loading library: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib/amino12.lib
Loading library: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib/aminoct12.lib
Loading library: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib/aminont12.lib
----- Source: ./ff1_leaprc.lipid21
----- Source of ./ff1_leaprc.lipid21 done
Log file: ./leap.log
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/lipid21.dat
Reading title:
AMBER Lipid21 v1.0 C. J. Dickson, R.C. Walker, I.R. Gould.
Loading library: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib/lipid21.lib
----- Source: ./ff2_leaprc.gaff2
----- Source of ./ff2_leaprc.gaff2 done
Log file: ./leap.log
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/gaff2.dat
Reading title:
AMBER General Force Field for organic molecules (Version 2.11, May 2016)
----- Source: ./ff3_leaprc.RNA.Shaw
----- Source of ./ff3_leaprc.RNA.Shaw done
Log file: ./leap.log

/home/nmrbox/spenumutchu/anaconda3/envs/htmd2/bin/teLeap: Note.
Skipping parm10.dat: already loaded
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/frcmod.shaw
Reading force field modification type file (frcmod)
Reading title:
# force field modification accoding to Tan et al. Proc. Natl. Acad. Sci. 2018 and N*->NR (purines), NC->ND (Ade(N3,N1)), CB->CE (Ade(C4,C5)), CA->CF (Ade(C6)); and according to Steinbrecher et al. J. Chem. Theory Comput. 2012 and OS->OR (O3' and O5') and O2->OQ (O1P and O2P) 
Loading library: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib/RNA_Shaw.lib
----- Source: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/cmd/leaprc.water.tip4pd
----- Source of /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/cmd/leaprc.water.tip4pd done
Loading library: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib/atomic_ions.lib
Loading library: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib/solvents.lib
Loading library: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib/tip4pd.off
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/frcmod.tip4pd
Reading force field modification type file (frcmod)
Reading title:
This is the additional/replacement parameter set for TIP4P-D, modified from TIP4PEW.
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/frcmod.ions_charmm22
Reading force field modification type file (frcmod)
Reading title:
Ion parameters from CHARMM22. Beglov D & Roux B (1994) J. Chem. Phys. 100, 9050-9063.
----- Source: ./ff4_leaprc.DNA.bsc1
----- Source of ./ff4_leaprc.DNA.bsc1 done
Log file: ./leap.log

/home/nmrbox/spenumutchu/anaconda3/envs/htmd2/bin/teLeap: Note.
Skipping parm10.dat: already loaded
Substituting map O5* -> O5'  for  O5* -> O5'
Substituting map C5* -> C5'  for  C5* -> C5'
Substituting map C4* -> C4'  for  C4* -> C4'
Substituting map O4* -> O4'  for  O4* -> O4'
Substituting map C3* -> C3'  for  C3* -> C3'
Substituting map O3* -> O3'  for  O3* -> O3'
Substituting map C2* -> C2'  for  C2* -> C2'
Substituting map O2* -> O2'  for  O2* -> O2'
Substituting map C1* -> C1'  for  C1* -> C1'
Substituting map C5M -> C7  for  C5M -> C7
Substituting map H1* -> H1'  for  H1* -> H1'
Substituting map H2*1 -> H2'  for  H2*1 -> H2'
Substituting map H2*2 -> H2''  for  H2*2 -> H2''
Substituting map H2'1 -> H2'  for  H2'1 -> H2'
Substituting map H2'2 -> H2''  for  H2'2 -> H2''
Substituting map H3* -> H3'  for  H3* -> H3'
Substituting map H4* -> H4'  for  H4* -> H4'
Substituting map H5*1 -> H5'  for  H5*1 -> H5'
Substituting map H5*2 -> H5''  for  H5*2 -> H5''
Substituting map H5'1 -> H5'  for  H5'1 -> H5'
Substituting map H5'2 -> H5''  for  H5'2 -> H5''
Substituting map HO'2 -> HO2'  for  HO'2 -> HO2'
Substituting map H5T -> HO5'  for  H5T -> HO5'
Substituting map H3T -> HO3'  for  H3T -> HO3'
Substituting map O1' -> O4'  for  O1' -> O4'
Substituting map OA -> OP1  for  OA -> OP1
Substituting map OB -> OP2  for  OB -> OP2
Substituting map O1P -> OP1  for  O1P -> OP1
Substituting map O2P -> OP2  for  O2P -> OP2
Loading library: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib/parmBSC1.lib
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/frcmod.parmbsc1
Reading force field modification type file (frcmod)
Reading title:
Parmbsc1 force-field for DNA
----- Source: ./ff5_leaprc.water.tip3p
----- Source of ./ff5_leaprc.water.tip3p done
Loading library: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib/atomic_ions.lib
Loading library: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib/solvents.lib
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/frcmod.tip3p
Reading force field modification type file (frcmod)
Reading title:
This is the additional/replacement parameter set for TIP3P water
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/frcmod.ions1lm_126_tip3p
Reading force field modification type file (frcmod)
Reading title:
Li/Merz ion parameters of monovalent ions for TIP3P water model (12-6 normal usage set)
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/frcmod.ionsjc_tip3p
Reading force field modification type file (frcmod)
Reading title:
Monovalent ion parameters for Ewald and TIP3P water from Joung & Cheatham JPCB (2008)
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/frcmod.ions234lm_126_tip3p
Reading force field modification type file (frcmod)
Reading title:
Li/Merz ion parameters of divalent to tetravalent ions for TIP3P water model (12-6 normal usage set)
Loading Prep file: ./topo0_DA2.prepi
Loading parameters: ./param0_DA2.frcmod
Reading force field modification type file (frcmod)
Reading title:
remark goes here
Loading PDB file: ./input.pdb
Created a new atom named: HA within residue: .R<DA2 195>
Created a new atom named: HA within residue: .R<DA2 207>
Created a new atom named: HA within residue: .R<DA2 226>
  total atoms in file: 189410
  Leap added 11 missing atoms according to residue templates:
       11 H / lone pairs
  The file contained 3 atoms not in residue templates
Box dimensions:  141.403600 120.508600 126.107600
Checking Unit.

/home/nmrbox/spenumutchu/anaconda3/envs/htmd2/bin/teLeap: Warning!
There is a bond of 3.241 angstroms between NE2 and CD2 atoms:
-------  .R<HID 34>.A<NE2 13> and .R<HID 34>.A<CD2 14>

/home/nmrbox/spenumutchu/anaconda3/envs/htmd2/bin/teLeap: Warning!
The unperturbed charge of the unit (7.000000) is not zero.
FATAL:  Atom .R<DA2 195>.A<HA 31> does not have a type.
FATAL:  Atom .R<DA2 207>.A<HA 31> does not have a type.
FATAL:  Atom .R<DA2 226>.A<HA 31> does not have a type.

/home/nmrbox/spenumutchu/anaconda3/envs/htmd2/bin/teLeap: Fatal Error!
Failed to generate parameters

Exiting LEaP: Errors = 1; Warnings = 2; Notes = 2.

**Comment by stefdoerr** [comment]
Hi and sorry for the delay. It seems like it doesn't like the hydrogens on the DA2 residue. Can you remove all hydrogens from the protein with `mol.remove("element H")`, don't run systemPrepare and build directly to see if it works?

**Comment by vas2201** [comment]
This is also resolved. You can close this ticket as well.
