### ISSUE TITLE
Installation Error: acemd >=2019.01.24 , which does not exist

### ISSUE THREAD

**Issue by Jingdan-Chen** [Acellera/htmd#1085]
$ conda create -n md-analysis
$ conda activate md-analysis
$ conda install htmd=1.19 -c acellera -c psi4 -c conda-forge

Error information:
```Error info: 
Channels:
 - acellera
 - psi4
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides acemd >=2019.01.24 needed by htmd-deps-1.19-py37_0

Could not solve for environment specs
The following package could not be installed
└─ htmd 1.19**  is not installable because it requires
   └─ htmd-deps 1.19 , which requires
      └─ acemd >=2019.01.24 , which does not exist (perhaps a missing channel).
```

installing acemd with ```conda install -c conda-forge -c acellera acemd``` is ok, but install htmd using above command still fails with the same error info.

**Comment by stefdoerr** [comment]
It's very difficult to install such old versions. Do you have a specific reason for wanting that version? Generally newer versions include many bugfixes

**Comment by Jingdan-Chen** [comment]
This actually happens when I want to replicate the work of https://github.com/torchmd/torchmd-protein-thermodynamics
But now I am good with htmd=2.3.19. 
Thanks!
