### ISSUE TITLE
acemd Computation: atomRestraint harmonic caused external energy calculation 

### ISSUE THREAD

**Issue by Jingdan-Chen** [Acellera/htmd#1086]
I did a MD simulation with atomRestraint, and the log file shows corresponding energy increse caused by the harmonic marked as "External" in kcal/mol.

Example single H2O in a box:
```
REMARK original generated coordinate pdb file
ATOM      1  OH2 TIP3W9243      33.244 -11.503  56.844  1.00  0.00      W1   O
ATOM      2  H1  TIP3W9243      33.956 -10.890  57.098  1.00  0.00      W1   H
ATOM      3  H2  TIP3W9243      33.693 -12.082  56.212  1.00  0.00      W1   H
END
```
Restrain setting:
```
atomRestraint           "name OH2" setpoints 5@0
```
I would like to investigate the force on constrained atom ($`F_{output} - F_{harmonic}`$) in the system along the trajectory. Thus I have to know the exact formula of calculation.

I guess it is $`E_{external}=\frac{1}{2}k||x-x_0||^2;    F_{external}=-k(x-x_0)`$. For force I can not validate easily, but for the relationship of energy it seems to be $`E_{external} \approx k||x-x_0||^2`$. ($`E_{external}`$ read from log file, $`x`$ and $`x_0`$ read from output.xtc and input coordinates correspondingly)

The factor seems to be 1 rather than 0.5. I wonder why is it? And how does the harmonic force being calculated in the computation?

**Comment by stefdoerr** [comment]
The external energy is indeed defined as `"k*((x-x0)^2+(y-y0)^2+(z-z0)^2)"`. Same as in the tutorial here, except we calculate periodic distances.
http://docs.openmm.org/7.1.0/api-python/generated/simtk.openmm.openmm.CustomExternalForce.html

I am not totally clear as to why but maybe it's to avoid computation since you can directly scale the k to be k/2?

**Comment by Jingdan-Chen** [comment]
Thank you for certifying it. And I have known the force is $`F = - 2k\Delta x`$
