### ISSUE TITLE
Extract Trajectory Without Water and Ions

### ISSUE THREAD

**Issue by vas2201** [Acellera/htmd#1087]
Hi,

I have completed the production run and need to extract the trajectory excluding water and ions. Could you please assist by providing the script for this task?

Thank you for your help.

Best regards,
Vas

**Comment by stefdoerr** [comment]
```
from moleculekit.molecule import Molecule

mol = Molecule("./structure.prmtop")
mol.read("./output.xtc")
mol.filter("not water and not ion")
mol.write("./output_filtered.xtc")
```
