### ISSUE TITLE
Request to Fix Error with 5-Methyl Cytosine amber Force Fields and Suggestion for Improvement

### ISSUE THREAD

**Issue by vas2201** [Acellera/htmd#1090]
Dear Support Team,

I have successfully located and downloaded the amber force fields for 5-methyl cytosine (5MC) for RNA from the following database: 
Amber Manchester Nucleic Acids :
http://amber.manchester.ac.uk/nuc/ 

The files I accessed include:

tRNA.leaprc
tRNA.lib
tRNA.readme
tRNA_inf.html
tRNA.frcmod

I then proceeded to rename and copy these files into the respective directories within my HTMD2 environment, structured as follows:

leaprc file: ~/anaconda3/envs/htmd2/dat/leap/cmd/leaprc.tRNA
lib file: ~/anaconda3/envs/htmd2/dat/leap/lib/tRNA.lib
frcmod file: ~/anaconda3/envs/htmd2/dat/leap/parm/tRNA.frcmod
After creating the 5-methyl cytosine structure for target RNA using PyMOL, I loaded it into Amber using default force fields, confirmed by the successful execution of amber.listFiles(). 

However, I am encountering an error as detailed in the log files within the builder-amber .

I would appreciate any guidance on how to resolve this issue. 

Thank you for your attention to this matter. I look forward to your prompt response and solution.

Log.txt file from build-amber folder
```
********************************************
-I: Adding /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/cmd to search path.
-I: Adding /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/prep to search path.
-I: Adding /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm to search path.
-I: Adding /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib to search path.
-f: Source ./tleap.in.

Welcome to LEaP!
(no leaprc in search path)
Sourcing: ./tleap.in
----- Source: ./ff0_leaprc.protein.ff14SB
----- Source of ./ff0_leaprc.protein.ff14SB done
Log file: ./leap.log
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/parm10.dat
Reading title:
PARM99 + frcmod.ff99SB + frcmod.parmbsc0 + OL3 for RNA
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/frcmod.ff14SB
Reading force field modification type file (frcmod)
Reading title:
ff14SB protein backbone and sidechain parameters
Loading library: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib/amino12.lib
Loading library: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib/aminoct12.lib
Loading library: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib/aminont12.lib
----- Source: ./ff1_leaprc.lipid21
----- Source of ./ff1_leaprc.lipid21 done
Log file: ./leap.log
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/lipid21.dat
Reading title:
AMBER Lipid21 v1.0 C. J. Dickson, R.C. Walker, I.R. Gould.
Loading library: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib/lipid21.lib
----- Source: ./ff2_leaprc.gaff2
----- Source of ./ff2_leaprc.gaff2 done
Log file: ./leap.log
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/gaff2.dat
Reading title:
AMBER General Force Field for organic molecules (Version 2.11, May 2016)
----- Source: ./ff3_leaprc.RNA.Shaw
----- Source of ./ff3_leaprc.RNA.Shaw done
Log file: ./leap.log

/home/nmrbox/spenumutchu/anaconda3/envs/htmd2/bin/teLeap: Note.
Skipping parm10.dat: already loaded
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/frcmod.shaw
Reading force field modification type file (frcmod)
Reading title:
# force field modification accoding to Tan et al. Proc. Natl. Acad. Sci. 2018 and N*->NR (purines), NC->ND (Ade(N3,N1)), CB->CE (Ade(C4,C5)), CA->CF (Ade(C6)); and according to Steinbrecher et al. J. Chem. Theory Comput. 2012 and OS->OR (O3' and O5') and O2->OQ (O1P and O2P) 
Loading library: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib/RNA_Shaw.lib
----- Source: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/cmd/leaprc.water.tip4pd
----- Source of /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/cmd/leaprc.water.tip4pd done
Loading library: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib/atomic_ions.lib
Loading library: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib/solvents.lib
Loading library: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib/tip4pd.off
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/frcmod.tip4pd
Reading force field modification type file (frcmod)
Reading title:
This is the additional/replacement parameter set for TIP4P-D, modified from TIP4PEW.
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/frcmod.ions_charmm22
Reading force field modification type file (frcmod)
Reading title:
Ion parameters from CHARMM22. Beglov D & Roux B (1994) J. Chem. Phys. 100, 9050-9063.
----- Source: ./ff4_leaprc.DNA.bsc1
----- Source of ./ff4_leaprc.DNA.bsc1 done
Log file: ./leap.log

/home/nmrbox/spenumutchu/anaconda3/envs/htmd2/bin/teLeap: Note.
Skipping parm10.dat: already loaded
Substituting map O5* -> O5'  for  O5* -> O5'
Substituting map C5* -> C5'  for  C5* -> C5'
Substituting map C4* -> C4'  for  C4* -> C4'
Substituting map O4* -> O4'  for  O4* -> O4'
Substituting map C3* -> C3'  for  C3* -> C3'
Substituting map O3* -> O3'  for  O3* -> O3'
Substituting map C2* -> C2'  for  C2* -> C2'
Substituting map O2* -> O2'  for  O2* -> O2'
Substituting map C1* -> C1'  for  C1* -> C1'
Substituting map C5M -> C7  for  C5M -> C7
Substituting map H1* -> H1'  for  H1* -> H1'
Substituting map H2*1 -> H2'  for  H2*1 -> H2'
Substituting map H2*2 -> H2''  for  H2*2 -> H2''
Substituting map H2'1 -> H2'  for  H2'1 -> H2'
Substituting map H2'2 -> H2''  for  H2'2 -> H2''
Substituting map H3* -> H3'  for  H3* -> H3'
Substituting map H4* -> H4'  for  H4* -> H4'
Substituting map H5*1 -> H5'  for  H5*1 -> H5'
Substituting map H5*2 -> H5''  for  H5*2 -> H5''
Substituting map H5'1 -> H5'  for  H5'1 -> H5'
Substituting map H5'2 -> H5''  for  H5'2 -> H5''
Substituting map HO'2 -> HO2'  for  HO'2 -> HO2'
Substituting map H5T -> HO5'  for  H5T -> HO5'
Substituting map H3T -> HO3'  for  H3T -> HO3'
Substituting map O1' -> O4'  for  O1' -> O4'
Substituting map OA -> OP1  for  OA -> OP1
Substituting map OB -> OP2  for  OB -> OP2
Substituting map O1P -> OP1  for  O1P -> OP1
Substituting map O2P -> OP2  for  O2P -> OP2
Loading library: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib/parmBSC1.lib
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/frcmod.parmbsc1
Reading force field modification type file (frcmod)
Reading title:
Parmbsc1 force-field for DNA
----- Source: ./ff5_leaprc.water.tip3p
----- Source of ./ff5_leaprc.water.tip3p done
Loading library: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib/atomic_ions.lib
Loading library: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib/solvents.lib
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/frcmod.tip3p
Reading force field modification type file (frcmod)
Reading title:
This is the additional/replacement parameter set for TIP3P water
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/frcmod.ions1lm_126_tip3p
Reading force field modification type file (frcmod)
Reading title:
Li/Merz ion parameters of monovalent ions for TIP3P water model (12-6 normal usage set)
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/frcmod.ionsjc_tip3p
Reading force field modification type file (frcmod)
Reading title:
Monovalent ion parameters for Ewald and TIP3P water from Joung & Cheatham JPCB (2008)
Loading parameters: /home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/frcmod.ions234lm_126_tip3p
Reading force field modification type file (frcmod)
Reading title:
Li/Merz ion parameters of divalent to tetravalent ions for TIP3P water model (12-6 normal usage set)
Loading PDB file: ./input.pdb

/home/nmrbox/spenumutchu/anaconda3/envs/htmd2/bin/teLeap: Warning!
Unknown residue: 5MC   number: 105   type: Nonterminal
Creating new UNIT for residue: 5MC sequence: 106

/home/nmrbox/spenumutchu/anaconda3/envs/htmd2/bin/teLeap: Warning!
One sided connection. Residue () missing connect0 atom.
Created a new atom named: P within residue: .R<5MC 106>
Created a new atom named: OP1 within residue: .R<5MC 106>
Created a new atom named: OP2 within residue: .R<5MC 106>
Created a new atom named: O5' within residue: .R<5MC 106>
Created a new atom named: C5' within residue: .R<5MC 106>
Created a new atom named: C4' within residue: .R<5MC 106>
Created a new atom named: O4' within residue: .R<5MC 106>
Created a new atom named: C3' within residue: .R<5MC 106>
Created a new atom named: O3' within residue: .R<5MC 106>
Created a new atom named: C2' within residue: .R<5MC 106>
Created a new atom named: O2' within residue: .R<5MC 106>
Created a new atom named: C1' within residue: .R<5MC 106>
Created a new atom named: N1 within residue: .R<5MC 106>
Created a new atom named: C2 within residue: .R<5MC 106>
Created a new atom named: O2 within residue: .R<5MC 106>
Created a new atom named: N3 within residue: .R<5MC 106>
Created a new atom named: C4 within residue: .R<5MC 106>
Created a new atom named: N4 within residue: .R<5MC 106>
Created a new atom named: C5 within residue: .R<5MC 106>
Created a new atom named: C6 within residue: .R<5MC 106>
Created a new atom named: H5' within residue: .R<5MC 106>
Created a new atom named: H5'' within residue: .R<5MC 106>
Created a new atom named: H4' within residue: .R<5MC 106>
Created a new atom named: H3' within residue: .R<5MC 106>
Created a new atom named: H2' within residue: .R<5MC 106>
Created a new atom named: HO2' within residue: .R<5MC 106>
Created a new atom named: H1' within residue: .R<5MC 106>
Created a new atom named: H41 within residue: .R<5MC 106>
Created a new atom named: H42 within residue: .R<5MC 106>
Created a new atom named: H5 within residue: .R<5MC 106>
Created a new atom named: H6 within residue: .R<5MC 106>

/home/nmrbox/spenumutchu/anaconda3/envs/htmd2/bin/teLeap: Warning!
One sided connection. Residue (default_name) missing connect1 atom.
  total atoms in file: 18081
  Leap added 8 missing atoms according to residue templates:
       8 H / lone pairs
  The file contained 31 atoms not in residue templates
 (using default radius 1.500000 for P)
 (using default radius 1.500000 for OP1)
 (using default radius 1.500000 for OP2)
 (using default radius 1.500000 for O5')
 (using default radius 1.500000 for C5')
 (using default radius 1.500000 for C4')
 (using default radius 1.500000 for O4')
 (using default radius 1.500000 for C3')
 (using default radius 1.500000 for O3')
 (using default radius 1.500000 for C2')
 (using default radius 1.500000 for O2')
 (using default radius 1.500000 for C1')
 (using default radius 1.500000 for N1)
 (using default radius 1.500000 for C2)
 (using default radius 1.500000 for O2)
 (using default radius 1.500000 for N3)
 (using default radius 1.500000 for C4)
 (using default radius 1.500000 for N4)
 (using default radius 1.500000 for C5)
 (using default radius 1.500000 for C6)
 (using default radius 1.500000 for HO2')
Box dimensions:  64.333600 55.925600 65.416600
Checking Unit.

/home/nmrbox/spenumutchu/anaconda3/envs/htmd2/bin/teLeap: Warning!
The unperturbed charge of the unit (-3.000000) is not zero.
FATAL:  Atom .R<5MC 106>.A<P 1> does not have a type.
FATAL:  Atom .R<5MC 106>.A<OP1 2> does not have a type.
FATAL:  Atom .R<5MC 106>.A<OP2 3> does not have a type.
FATAL:  Atom .R<5MC 106>.A<O5' 4> does not have a type.
FATAL:  Atom .R<5MC 106>.A<C5' 5> does not have a type.
FATAL:  Atom .R<5MC 106>.A<C4' 6> does not have a type.
FATAL:  Atom .R<5MC 106>.A<O4' 7> does not have a type.
FATAL:  Atom .R<5MC 106>.A<C3' 8> does not have a type.
FATAL:  Atom .R<5MC 106>.A<O3' 9> does not have a type.
FATAL:  Atom .R<5MC 106>.A<C2' 10> does not have a type.
FATAL:  Atom .R<5MC 106>.A<O2' 11> does not have a type.
FATAL:  Atom .R<5MC 106>.A<C1' 12> does not have a type.
FATAL:  Atom .R<5MC 106>.A<N1 13> does not have a type.
FATAL:  Atom .R<5MC 106>.A<C2 14> does not have a type.
FATAL:  Atom .R<5MC 106>.A<O2 15> does not have a type.
FATAL:  Atom .R<5MC 106>.A<N3 16> does not have a type.
FATAL:  Atom .R<5MC 106>.A<C4 17> does not have a type.
FATAL:  Atom .R<5MC 106>.A<N4 18> does not have a type.
FATAL:  Atom .R<5MC 106>.A<C5 19> does not have a type.
FATAL:  Atom .R<5MC 106>.A<C6 20> does not have a type.
FATAL:  Atom .R<5MC 106>.A<H5' 21> does not have a type.
FATAL:  Atom .R<5MC 106>.A<H5'' 22> does not have a type.
FATAL:  Atom .R<5MC 106>.A<H4' 23> does not have a type.
FATAL:  Atom .R<5MC 106>.A<H3' 24> does not have a type.
FATAL:  Atom .R<5MC 106>.A<H2' 25> does not have a type.
FATAL:  Atom .R<5MC 106>.A<HO2' 26> does not have a type.
FATAL:  Atom .R<5MC 106>.A<H1' 27> does not have a type.
FATAL:  Atom .R<5MC 106>.A<H41 28> does not have a type.
FATAL:  Atom .R<5MC 106>.A<H42 29> does not have a type.
FATAL:  Atom .R<5MC 106>.A<H5 30> does not have a type.
FATAL:  Atom .R<5MC 106>.A<H6 31> does not have a type.

/home/nmrbox/spenumutchu/anaconda3/envs/htmd2/bin/teLeap: Fatal Error!
Failed to generate parameters

Exiting LEaP: Errors = 1; Warnings = 4; Notes = 2.
```

**Comment by stefdoerr** [comment]
Hi can you show me how you called the amber.build command please?
I am a bit concerned about this "nonterminal" line here
```
Unknown residue: 5MC   number: 105   type: Nonterminal
```
If you can please also share your input structure which you passed to amber.build, call `mol.write("./test.pdb")` right before and send me the file so I can debug the issue

**Comment by vas2201** [comment]
Hi Stefdoerr,

Thank you for your response. I have prepared a folder that includes a tRNA subfolder containing the force fields for 5MC (5-methyl-cytosine) and a PDB file, as well as a build amber folder and the Jupyter notebook I am using. I am not entirely certain that these tRNA files meet all the requirements specified by HTMD.

Really appreciate your time and help on this. 

Here is google drive link to download the folder. 
https://drive.google.com/file/d/1fe7i3ZjfFEa1Ij0lv81xONmTMKLHir4x/view?usp=sharing

**Comment by stefdoerr** [comment]
I managed to get a bit further but I hit this ridiculous error:

```
Could not find angle parameter for atom types: OR - P - O2
        for atom O3' at position -5.911000, -5.164340, 6.998260,
            atom P at position -5.832000, -3.815340, 7.884260,
        and atom O1P at position -4.478000, -3.733340, 8.477260.
```

but there is obviously no angle between O3',  P and O1P. There should be one between O5', P and O1P
So I'm sort of out of ideas. I think the topology of the 5MC residue is just wrong or the PDB names are wrong.
![image](https://github.com/Acellera/htmd/assets/7935362/496363ba-9413-4385-a4b7-9f6369c5e61c)

**Comment by stefdoerr** [comment]
This is the code I used. Practically I disabled capping and added the folder with the parameters to the teleapimports.
Ah I also had to modify tRNA.leaprc to remove these two imports because the first one was already loaded and gave an error and the second trna.pcy does not exist

```
#parm99 = loadamberparams parm99.dat
#parm99 = loadamberparams  trna.pcy
```

```py
mol = Molecule("./2LEB.pdb")
mol.remove("element H")
pmol = systemPrepare(mol)
pmol.set("segid", "P", sel="protein")
pmol.set("name", "O1P", sel='resname "5MC" and name OP1')
pmol.set("name", "O2P", sel='resname "5MC" and name OP2')
amber.build(pmol, ff=amber.defaultFf()+["./tRNA/tRNA.leaprc"], param=["./tRNA/tRNA.frcmod"], topo=["./tRNA/tRNA.in"], teleapimports=['/home/sdoerr/miniforge3/envs/htmd/dat/leap/cmd', '/home/sdoerr/miniforge3/envs/htmd/dat/leap/prep', '/home/sdoerr/miniforge3/envs/htmd/dat/leap/parm', '/home/sdoerr/miniforge3/envs/htmd/dat/leap/lib', "/home/sdoerr/Downloads/debug_folder/tRNA/"], caps={"P": ("none", "none")})
```

**Comment by vas2201** [comment]
Thanks for your help on this.  I encountered similer error from tleap:
Attached pdb coordinates (&atoms) for 5MC for reference below. I corrected the PDB atom names best of my knowledge. Lookslike the error is occurring from force field parameters.
Leap.log
*********
~/anaconda3/envs/htmd2/bin/teLeap: Error!
Could not find angle parameter for atom types: OR - P - O2
        for atom O3' at position -5.910162, -5.164340, 6.998260,
            atom P at position -5.831162, -3.815340, 7.884260,
        and atom O1P at position -4.477162, -3.733340, 8.477260.
~/anaconda3/envs/htmd2/bin/teLeap: Error!
Could not find angle parameter for atom types: OR - P - O2
        for atom O3' at position -5.910162, -5.164340, 6.998260,
            atom P at position -5.831162, -3.815340, 7.884260,
        and atom O2P at position -7.011162, -3.788340, 8.777260.

~/anaconda3/envs/htmd2/bin/teLeap: Error!
Could not find angle parameter for atom types: OR - P - OS
        for atom O3' at position -5.910162, -5.164340, 6.998260,
            atom P at position -5.831162, -3.815340, 7.884260,
        and atom O5' at position -5.986162, -2.610340, 6.823260.

~/anaconda3/envs/htmd2/bin/teLeap: Error!
Could not find angle parameter for atom types: OS - P - OQ
        for atom O3' at position -8.268162, 0.708660, 6.406260,
            atom P at position -9.803162, 0.922660, 5.963260,
        and atom OP1 at position -10.673162, 0.604660, 7.118260.

~/anaconda3/envs/htmd2/bin/teLeap: Error!
Could not find angle parameter for atom types: OS - P - OQ
        for atom O3' at position -8.268162, 0.708660, 6.406260,
            atom P at position -9.803162, 0.922660, 5.963260,
        and atom OP2 at position -9.998162, 0.198660, 4.692260.

~/anaconda3/envs/htmd2/bin/teLeap: Error!
Could not find angle parameter for atom types: OS - P - OR
        for atom O3' at position -8.268162, 0.708660, 6.406260,
            atom P at position -9.803162, 0.922660, 5.963260,
        and atom O5' at position -9.943162, 2.491660, 5.630260.
Building proper torsion parameters.
Building improper torsion parameters.
** Warning: No sp2 improper torsion term for  CM-CA-CM-CT
        atoms are: C6 C4 C5 CM5
** Warning: No sp2 improper torsion term for  NR-CE-CE-ND
        atoms are: N9 C5 C4 N3
** Warning: No sp2 improper torsion term for  NB-CF-CE-CE
        atoms are: N7 C6 C5 C4
** Warning: No sp2 improper torsion term for  NR-CB-CB-NC
        atoms are: N9 C5 C4 N3
total 385 improper torsions applied
Building H-Bond parameters.
Incorporating Non-Bonded adjustments.

Log.txt
******
~/anaconda3/envs/htmd2/bin/teLeap: Warning!
Parameter file was not saved.
quit
              Quit

Exiting LEaP: Errors = 6; Warnings = 2; Notes = 3.


~/anaconda3/envs/htmd2/bin/teLeap: Error!
Could not find angle parameter for atom types: OR - P - O2
        for atom O3' at position -5.910162, -5.164340, 6.998260,
            atom P at position -5.831162, -3.815340, 7.884260,
        and atom O1P at position -4.477162, -3.733340, 8.477260.

~/anaconda3/envs/htmd2/bin/teLeap: Error!
Could not find angle parameter for atom types: OR - P - O2
        for atom O3' at position -5.910162, -5.164340, 6.998260,
            atom P at position -5.831162, -3.815340, 7.884260,
        and atom O2P at position -7.011162, -3.788340, 8.777260.

~/anaconda3/envs/htmd2/bin/teLeap: Error!
Could not find angle parameter for atom types: OR - P - OS
        for atom O3' at position -5.910162, -5.164340, 6.998260,
            atom P at position -5.831162, -3.815340, 7.884260,
        and atom O5' at position -5.986162, -2.610340, 6.823260.

~/anaconda3/envs/htmd2/bin/teLeap: Error!
Could not find angle parameter for atom types: OS - P - OQ
        for atom O3' at position -8.268162, 0.708660, 6.406260,
            atom P at position -9.803162, 0.922660, 5.963260,
        and atom OP1 at position -10.673162, 0.604660, 7.118260.

~/anaconda3/envs/htmd2/bin/teLeap: Error!
Could not find angle parameter for atom types: OS - P - OQ
        for atom O3' at position -8.268162, 0.708660, 6.406260,
            atom P at position -9.803162, 0.922660, 5.963260,
        and atom OP2 at position -9.998162, 0.198660, 4.692260.

~/anaconda3/envs/htmd2/bin/teLeap: Error!
Could not find angle parameter for atom types: OS - P - OR
        for atom O3' at position -8.268162, 0.708660, 6.406260,
            atom P at position -9.803162, 0.922660, 5.963260,
        and atom O5' at position -9.943162, 2.491660, 5.630260.
Building proper torsion parameters.
Building improper torsion parameters.
total 385 improper torsions applied
Building H-Bond parameters.
Incorporating Non-Bonded adjustments.

~/anaconda3/envs/htmd2/bin/teLeap: Warning!
Parameter file was not saved.
              Quit

Exiting LEaP: Errors = 6; Warnings = 2; Notes = 3.

PDB coordinates for 5MC
***********************
ATOM   1670  P   5MC B 104     -10.323   0.041  11.325  1.00  0.00           P
ATOM   1671  O1P 5MC B 104      -8.969   0.123  11.918  1.00  0.00           O
ATOM   1672  O2P 5MC B 104     -11.503   0.068  12.218  1.00  0.00           O
ATOM   1673  O5' 5MC B 104     -10.478   1.246  10.264  1.00  0.00           O
ATOM   1674  C5' 5MC B 104     -10.346   2.577  10.719  1.00  0.00           C
ATOM   1675  C4' 5MC B 104     -10.483   3.624   9.608  1.00  0.00           C
ATOM   1676  O4' 5MC B 104      -9.620   3.348   8.525  1.00  0.00           O
ATOM   1677  C3' 5MC B 104     -11.884   3.801   9.032  1.00  0.00           C
ATOM   1678  O3' 5MC B 104     -12.760   4.565   9.847  1.00  0.00           O
ATOM   1679  C2' 5MC B 104     -11.573   4.469   7.710  1.00  0.00           C
ATOM   1680  O2' 5MC B 104     -11.440   5.868   7.859  1.00  0.00           O
ATOM   1681  C1' 5MC B 104     -10.214   3.876   7.351  1.00  0.00           C
ATOM   1682  N1  5MC B 104     -10.458   2.793   6.376  1.00  0.00           N
ATOM   1683  C2  5MC B 104     -10.191   3.018   5.035  1.00  0.00           C
ATOM   1684  O2  5MC B 104      -9.702   4.084   4.661  1.00  0.00           O
ATOM   1685  N3  5MC B 104     -10.482   2.035   4.139  1.00  0.00           N
ATOM   1686  C4  5MC B 104     -10.986   0.868   4.550  1.00  0.00           C
ATOM   1687  N4  5MC B 104     -11.241  -0.072   3.640  1.00  0.00           N
ATOM   1688  C5  5MC B 104     -11.246   0.608   5.928  1.00  0.00           C
ATOM   1689  C6  5MC B 104     -10.967   1.600   6.801  1.00  0.00           C
ATOM   1690  CM5 5MC B 104     -11.815  -0.725   6.448  0.00  0.00           C

**Comment by stefdoerr** [comment]
Yeah I'm also quite convinced there is an error in the topology of the tRNA files.

**Comment by stefdoerr** [comment]
Ah no the topology of 5MC is fine. The issue is the bond to the previous 103 residue. It's missing the parameters to bond the 5MC residue to the RNA C3'. Let me take another look

**Comment by stefdoerr** [comment]
Yeah the only angles defined in tRNA.frcmod including O2 which is the atom type of O1P and O2P are 
```
# in the tRNA.frcmod
O2 - P - HO   0.0      0.00  

# These from all_modrna08.frcmod
O2-P -O2	45.1	109.01	same as o -p4-o
O2-P -OS	43.1	110.621	same as o -p4-os
OH-P -O2	42.9	107.128	same as o -p4-oh
```
You will have to start searching for those parameters unfortunately. I cannot help much more with this.

**Comment by vas2201** [comment]
Amber Users recommended me to use the following parameters files. 

amber library file:         /home/user/amber**/dat/leap/lib/all_modrna08.lib
amber parameter file:   /home/user/amber**/dat/leap/parm/all_modrna08.frcmod

Import those paths in the leap file to test your system building.

I gave try , but end up with issues. 

Can you provide me code snippet to source these files properly , if possible ? 

Thanks for your help on this.

**Comment by stefdoerr** [comment]
`amber.build(mol, ff=amber.defaultFf()+["./tRNA/tRNA.leaprc", "leaprc.modrna08"], param=["./tRNA/tRNA.frcmod"], topo=["./tRNA/tRNA.in"], teleapimports=['/home/sdoerr/miniforge3/envs/htmd/dat/leap/cmd', '/home/sdoerr/miniforge3/envs/htmd/dat/leap/prep', '/home/sdoerr/miniforge3/envs/htmd/dat/leap/parm', '/home/sdoerr/miniforge3/envs/htmd/dat/leap/lib', "/home/sdoerr/Downloads/debug_folder/tRNA/"], ionize=False)` 

You just add leaprc.modrna08 to the ff argument list
Doesn't help though at least in my case

**Comment by vas2201** [comment]
I modified the `leaprc.modrna08` file by uncommenting the source lines.  I am able to build the system without errors. 
However, I am encountering issues while solvating and ionizing the system.  Can you provide further assistance on how to solvate and ionize the system?.

 leaprc.modrna08 file
******************************************
#
# ----- leaprc for loading modified RNA nucleotides.  The parameters are
#        described here:

#   R. Aduri, B.T. Psciuk, P. Saro, H. Taniga,
#   Schlegel, H.B. and J. SantaLucia, Jr. AMBER force field parameters 
#   for the naturally occurring modified nucleosides in RNA. 
#   J. Chem. Theory Comput. 3, 1465-1475, 2007.
#
# To use these residues, load this file into leap, after the Amber-FF, e.g.:
#
source leaprc.protein.ff14SB
source leaprc.RNA.OL3
source leaprc.modrna08
#

modrna08 = loadAmberParams all_modrna08.frcmod
loadOff all_modrna08.lib



I succefully   build the system using following snippet. 
********************************************************************
mol = Molecule("2LEB_3c_methyl.pdb")
mol.remove("element H")
pmol = systemPrepare(mol)
pmol.set("segid", "P", sel="protein")
amber.build(pmol, ff=amber.defaultFf()+["/home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/cmd/leaprc.modrna08"], param=["/home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm/all_modrna08.frcmod"], teleapimports=['/home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/cmd/', '/home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/prep', '/home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/parm', '/home/nmrbox/spenumutchu/anaconda3/envs/htmd2/dat/leap/lib'], ionize=False, caps={"P": ("none", "none")})
*********************************************************************************************************************


2024-05-15 00:06:55,947 - moleculekit.molecule - INFO - Removed 852 atoms. 944 atoms remaining in the molecule.


---- Molecule chain report ----
Chain A:
    First residue: MET     1  
    Final residue: SER   101  
Chain B:
    First residue: U     102  
    Final residue: RU3   107  
---- End of chain report ----

2024-05-15 00:06:57,292 - moleculekit.tools.preparation - WARNING - The following residues have not been optimized: 5MC
2024-05-15 00:06:57,346 - moleculekit.tools.preparation - INFO - Modified residue HIS    63 A to HID
2024-05-15 00:06:57,347 - moleculekit.tools.preparation - INFO - Modified residue HIS    99 A to HID
2024-05-15 00:06:57,348 - moleculekit.tools.preparation - INFO - Modified residue HIS   100 A to HID
2024-05-15 00:06:57,349 - moleculekit.tools.preparation - INFO - Modified residue U     102 B to RU5
2024-05-15 00:06:57,350 - moleculekit.tools.preparation - INFO - Modified residue C     103 B to RC
2024-05-15 00:06:57,351 - moleculekit.tools.preparation - INFO - Modified residue A     105 B to RA
2024-05-15 00:06:57,352 - moleculekit.tools.preparation - INFO - Modified residue G     106 B to RG
2024-05-15 00:06:57,353 - moleculekit.tools.preparation - WARNING - Dubious protonation state: the pKa of 1 residues is within 1.0 units of pH 7.4.
2024-05-15 00:06:57,354 - moleculekit.tools.preparation - WARNING - Dubious protonation state:    HIS   100 A (pKa= 6.42)
2024-05-15 00:06:57,502 - htmd.builder.amber - INFO - Detecting disulfide bonds.
2024-05-15 00:06:57,686 - htmd.builder.amber - INFO - Starting the build.
2024-05-15 00:06:58,760 - htmd.builder.amber - INFO - Finished building.

<moleculekit.molecule.Molecule object at 0x7f2359bbd360>
Molecule with 1802 atoms and 1 frames
Atom field - altloc shape: (1802,)
Atom field - atomtype shape: (1802,)
Atom field - beta shape: (1802,)
Atom field - chain shape: (1802,)
Atom field - charge shape: (1802,)
Atom field - coords shape: (1802, 3, 1)
Atom field - element shape: (1802,)
Atom field - formalcharge shape: (1802,)
Atom field - insertion shape: (1802,)
Atom field - masses shape: (1802,)
Atom field - name shape: (1802,)
Atom field - occupancy shape: (1802,)
Atom field - record shape: (1802,)
Atom field - resid shape: (1802,)
Atom field - resname shape: (1802,)
Atom field - segid shape: (1802,)
Atom field - serial shape: (1802,)
angles shape: (3287, 3)
bonds shape: (1834, 2)
bondtype shape: (1834,)
box shape: (3, 1)
boxangles shape: (3, 1)
crystalinfo: None
dihedrals shape: (7218, 4)
fileloc shape: (1, 2)
impropers shape: (389, 4)
reps: 
ssbonds shape: (0,)
step shape: (1,)
time shape: (1,)
topoloc: /home/nmrbox/spenumutchu/projects/htmd/SRSF2/SRSF2_WT_UCmCAGU_21/build/structure.prmtop
viewname: structure.prmtop

**Comment by stefdoerr** [comment]
Congratulations! Now for solving and ionizing, before building just do 

```py
smol = solvate(pmol)
bmol = amber.build(smol, ...., ionize=True)
```

Depending on how you want to solvate (cube or cuboid) you can use either the `pad` argument to solvate which will just add padding around the solute or use the `minmax` argument where you specify the minimum and maximum coordinates of the box.

See the building tutorial here for more details:
https://software.acellera.com/htmd/tutorials/system-building-protein-ligand.html#solvate

**Comment by vas2201** [comment]
How can I use magnesium chloride as ions instead of sodium chloride as ions for the system ?. Thank you.

**Comment by stefdoerr** [comment]
saltcation="Mg2+"

**Comment by vas2201** [comment]
Thanks for your help ! you can close this ticket.

**Comment by stefdoerr** [comment]
Great :)
