### ISSUE TITLE
Constant ratio for membrane protein simulations 

### ISSUE THREAD

**Issue by Saleh-OM4R** [Acellera/htmd#1092]
Hi, 

I just have a simple question for the use of constant ratio (`md.useconstantratio = True`) in membrane protein simulations, do I need to keep it `True` even in the production run or just use it in the equilibration? Because I noticed in the htmd tutorials that this setting is only used in the equilibration and not in the production run. 

Regards,

**Comment by stefdoerr** [comment]
Hi, it's only necessary in equilibration because it's run in NPT mode. Production runs are done in NVT so the box dimensions don't change and it's not necessary
