### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4062: ordinal not in range(128)

### ISSUE THREAD

**Issue by tonigi** [Acellera/htmd#1096]
I get that error on charmm.build. The cause may be here

```
File ~/Apps/anaconda3/envs/htmd/lib/python3.10/encodings/ascii.py:26, in IncrementalDecoder.decode(self, input, final)
     25 def decode(self, input, final=False):
---> 26     return codecs.ascii_decode
```

because in `htmd/share/builder/charmmfiles/par/par_all36_cgenff.prm` there are some names with non-ascii characters. Probably UTF8 needs be used to decode.

**Comment by stefdoerr** [comment]
```py
from htmd.ui import *
mol = Molecule("3ptb")
mol.filter("protein")
charmm.build(mol, ionize=False, outdir="/tmp/charmm")
```
I'm not getting the error here and it builds ok. Did you do something different?

**Comment by stefdoerr** [comment]
Reopen if it's reproducible or with a longer code snippet which allows reproduction. Thanks!

**Comment by tonigi** [comment]
I think the reason is the current locale (which ultimately comes from the terminal being used). The open() behavior of text files depends on locale; so if unset or unspecified it may default to "ascii", which is invalid for files containing high bits (such as the one mentioned, which is utf-8).

In short: solution is to specify the correct encoding, which in this case is known: presumably in https://github.com/Acellera/htmd/blob/155e4d46699e50ec274ba706cefd38e050cfe737/htmd/builder/charmm.py#L784 add `encoding="utf-8"` to the `open()` call.

**Comment by stefdoerr** [comment]
Thanks! Fixed here hopefully https://github.com/Acellera/htmd/commit/209befe2df8e0e41beacb2f4582132e5a8261a71
