### ISSUE TITLE
Inconsistent energies error when running the Production for the example

### ISSUE THREAD

**Issue by LabWeng** [Acellera/htmd#1098]
Hi,
I am trying to run the tutorial tutorials/mu-opioid-receptor-gpcr-equilibration.ipynb. In the **Production** step, it raised the error 'ERROR: /home/user/mambaforge/conda-bld/acemd_1726222366510/work/src/mdsim/dynamics.cpp line 180: Inconsistent energies'. The code to run the Production for dynamics is `local = LocalGPUQueue()
local.submit(os.path.join(path,'prod'))
local.wait()`
Have you guys completed this tutorial without this error? Other cases on protein-protein/ligand work well.
My HTMD version is 2.3.31.
Thanks !

**Comment by stefdoerr** [comment]
Hi, can you try again please with the latest HTMD 2.4.1 and ACEMD 3.8.2 versions?

**Comment by LabWeng** [comment]
It works! Thanks a lot.
