### ISSUE TITLE
Tutorials: Getting started with HTMD, Playing with HTMD Molecules and Atom Selections

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#11]
I am going through the tutorials and fixing them.

I think that the ["Getting started with HTMD" tutorial](https://github.com/Acellera/htmd/blob/master/tutorials/getting-started-htmd.ipynb) [1] and the ["Playing with HTMD Molecules" tutorial](https://github.com/Acellera/htmd/blob/master/tutorials/playing-with-htmd-molecule.ipynb) [2] strongly overlap and could be condensed into only one tutorial called "Getting started with HTMD Molecules", where the `Molecule` class and its features are introduced.

Furthermore, the ["Atom selections" tutorial](https://github.com/Acellera/htmd/blob/master/tutorials/atom-selections.ipynb) [3], where @tonigi did an awesome job, is actually more like a documentation page rather than a tutorial. My idea would be to use this material intercalated with snippets of code to take advantage of the notebook capabilities. @giadefa told me this was created as a presentation, but I don't it will lose its purpose as that.

Task list:
- [x] ~~get rid of redundancies in the first two tutorials~~
- [x] ~~create a new tutorial which is a fusion of tutorials [1] and [2]~~
- [ ] incorporate the tutorial [3] into the new tutorial, making an extended and dedicated overview of the `Molecule` class, selection capabilities, features and methods (postponed)

**Comment by j3mdamas** [comment]
First point done.
Tutorial [1] cleaned and small formatting/bug solved. Commit: a1ca92c002dd01fca840a1dca5ea33fd3bc55ec6
Tutorial [2] also cleaned and reformatted. Some parts of tutorial [2] were removed because they were redundant with tutorial [1]. A small section on `Molecule.insert` was moved from [2] to the appropriate part in [1]. **I did not test the trajectories section**, I did not have one to test. Commit: f89e372b32884a1e0375b586cbe1216be373f386

Second point is ongoing. @giadefa, it may not be ready for Thursday, but we'll see.

**Comment by j3mdamas** [comment]
BTW, this SHA links are to Acellera/htmd, but the commits are actually only on my devel branch.

**Comment by j3mdamas** [comment]
Second point done. Commit: j3mdamas/htmd@18a91da930ed26270d0fb685e10c8a8017cdbbe8
More redundancies were removed. The tutorial is also Slide-mode ready. It's a bit clunky in that mode, because of a RISE issue (damianavila/RISE#188), but it works.

@giadefa is possibly going to use it on the Masters classes tomorrow, and if he thinks its OK, it may replace tutorials [1] and [2] in the future.

**Comment by j3mdamas** [comment]
I think the new tutorial was adopted. Tutorials [1] and [2] deleted. Point 3 postponed.
Commit: j3mdamas/htmd@701f4ac81af59bafb0b52fc971913a3e62e85e7a
Issue closed.

**Comment by stefdoerr** [comment]
Beyond adopting it we should also put it online no? :D So I guess we should pull it to the multiscalelab fork and then make a new doc publishing

**Comment by stefdoerr** [comment]
@giadefa I guess we need to first do a pull request from @j3mdamas fork into acellera and then  pull from the acellera repo into our multiscalelab fork. Can you do it?

**Comment by j3mdamas** [comment]
Gianni already did it, but using my file directly instead of pulling from
my branch. It's alright but I'll need to fix the website because it's buggy
on the menus.
