### ISSUE TITLE
AcemdLocal should check ACEMD licence

### ISSUE THREAD

**Issue by stefdoerr** [Acellera/htmd#114]
To prevent from running 4 simulations at once on a single GPU if the license is the free one.
Waiting for Matt to add a license reporting flag to ACEMD executable.

**Comment by mj-harvey** [comment]
Pending CUDA 8 release

**Comment by mj-harvey** [comment]
Stefan:

You can now check the license with
from htmd import license
print(licenseEntitlements())
the return is a dict of license tokens. Look for "ACEMD" or "Legacy" . "O" means unlimited

**Comment by stefdoerr** [comment]
```python
In [5]: licenseEntitlements()
Out[5]: {'ACEMD': {'1.0': 4}}
```
What does 1.0 : 4 mean?

**Comment by j3mdamas** [comment]
@mj-harvey?

**Comment by mj-harvey** [comment]
it means 4 gpus

**Comment by stefdoerr** [comment]
and the 1.0?

**Comment by j3mdamas** [comment]
version of the license, I think

**Comment by j3mdamas** [comment]
moving this to 1.6.0
