### ISSUE TITLE
.pdbqt file incorrectly read by Molecule

### ISSUE THREAD

**Issue by hawk31** [Acellera/htmd#116]
Small replication
```python
In[35]: mol = Molecule('/shared/jose/databases/pdbbind/2x2r/2x2r_ligand.pdbqt')
In[36]: mol.numAtoms
Out[36]: 1
In[37]: mol.coords.shape
Out[37]: (49, 3, 1)
```

**Comment by stefdoerr** [comment]
VMD does not read it either. Format seems broken as only one atom is between ROOT and ENDROOT tags.

**Comment by hawk31** [comment]
This is generated by the `prepare_ligand4.py` script in AutoDockTools. Don't actually know the difference between this one and `prepare_receptor4.py`.
