### ISSUE TITLE
Changes in vmd visualizer in 1.3.3 version?

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#118]
Hi guys,

I am using version 1.3.3. I run a model a couple of days ago using version 1.3.1. It seems now I am unable to visualize its macrostates, and when visualizing a pdb there are just dots. Are there any changes occurring from your side? I'll have a look at mine if not.

For example:
```
mol.read('4_865/filtered/filtered.pdb')
mol.view()
```
<img src="https://cloud.githubusercontent.com/assets/12035024/18214964/26aed066-711d-11e6-9208-2790bd02a91a.png" alt="alt text" width="350 height="350">

Thanks a lot,
Noelia

**Comment by stefdoerr** [comment]
Please attach files to issues for replicating the problem.

Here for some reason it does not guess bonds. Don't know why though

**Comment by noeliaferruz** [comment]
It's happening in all cases I've tried so far. You can try:

```
mol.read('3PBL') # or any other random pdb
mol.view()
```

**Comment by stefdoerr** [comment]
Works fine for everyone here in the lab with 1.3.3. Don't know what to recommend except maybe a fresh install of htmd? 
But we loaded it from the PDB website with:
```python
mol = Molecule('3PBL')
mol.view()
```
Does this give you the same result?

**Comment by noeliaferruz** [comment]
Thanks a lot for testing!

Yes, unfortunately this is what i get:

<img src="https://cloud.githubusercontent.com/assets/12035024/18279415/72903ebc-7423-11e6-8bf3-01630bb98c41.png" alt="alt text" width="350 height="350">

I'll wait to upgrade to 1.3.4 and see if it's fixed.

**Comment by stefdoerr** [comment]
Werid :/ Something must have broken during the update. As I said you could do a reinstall of htmd in conda

```
conda uninstall htmd
conda install htmd
```
maybe even this works
```
conda install htmd --force
```

**Comment by noeliaferruz** [comment]
Thanks for the help. I guess I can close it as no one can reproduce it. Let's see if it persists in future versions.
