### ISSUE TITLE
Does MetricDihedral support homodimer (two chains with same resid) selection?

### ISSUE THREAD

**Issue by funnybomb** [Acellera/htmd#120]
hi, I have a  homodimer structure with **two chains(A,B) with same resid** which I peformed several simulations with ACEMD, How can I analyze these two chains separately by using MetricDiheral ?
```pythonscript
fs = simlist(xtc_file_path,pdb_file)
me_a=Metric(fs) 
me_a.projection(MetricDihedral(protsel='protein and chain A', sincos=True))
a = me_a.project()
------------------------------
me_b=Metric(fs) 
me_b.projection(MetricDihedral(protsel='protein and chain B', sincos=True))
b = me_b.project()
------------------
me_w=Metric(fs) 
me_w.projection(MetricDihedral(protsel='protein', sincos=True))
w = me_w.project()
```
here  a.dat, b.dat and w.dat have exactly the same values and np.shape.

**Comment by stefdoerr** [comment]
Yes, take a look at the last line of your code. There is a little bug there ;)
Also on the first projection I would use `protein and chain A` unless you want the dihedrals of both chains.

**Comment by funnybomb** [comment]
O, I modified the code of last line. But Here my point is that MetricDihedral can't recognize chain A and chain B or whole protein but only return the dihedrals of the first chain. Any selection  ```protein and chain A``` or ```protein and chain B```  or ```protein```  will return the results that have exactly the same values and shapes if I was not wrong.

**Comment by funnybomb** [comment]
I think the problem is caused that residues from different chains have same resid 
Parameters:	
dih (list of str) – You can provide your own list of 4 resid/atom pairs for dihedral angles. See example.
sincos (bool, optional) – Set to True to return the dihedral angles as their sine and cosine components. Makes them periodic.
protsel (str, optional) – Atomselection for the protein segment for which to calculate dihedral angles. Resids should be **unique within that segment**.

**Comment by funnybomb** [comment]
Today I upgrade htmd to 1.3.3, when I use ```protein``` to select both chain I get this error
"Expected one atom from atomselection resid 116 name N. Got 2 instead"

**Comment by stefdoerr** [comment]
Oh yes I see. Indeed it requires different resids. I don't know if I can change it soon to fix that issue.
What you can do instead is just save a new pdb file with different resids.

```python
mol = Molecule(pdb_file)
mol.resid = sequenceID(('resid','chain'))
mol.write('modified.pdb')

fs = simlist(xtc_file_path,'modified.pdb')
```
[sequenceID](https://www.htmd.org/docs/latest/htmd.molecule.util.html?highlight=sequence#htmd.molecule.util.sequenceID) generates a sequence of increasing integers any time it finds a change in either `resid` or `chain` in this case. So this should work.

I know it's a workaround but I think it will take longer to fix the dihedrals code.

**Comment by stefdoerr** [comment]
*fixed a mistake in my code. Check github issues please instead of mail

**Comment by funnybomb** [comment]
Thanks for your solution, but it will cost extra effort to select sub sequences of both chain.  Interestingly, during test I found that MetricData.dat will automatically stack the results in rows if Metric was projected multiple times, Here is my solution:
```pythonscript
fs = simlist(xtc_file_path,pdb_file)
me = Metric(fs)
mol = Molecule(pdb_file)
mol.filter(select_str)
chains = np.unique(mol.get('chain'))
if len(chains) == 1:  ##### only one chain selected, calc straight forward
else:
    for chain_id in chains:
        select_single_chain = select_str+ ' and chain ' + chain_id  
        me.projection(MetricDihedral(protsel = select_single_chain, sincos=True))
        data = me.project()
```
Interestingly, data.dat will automaticlly stack the results in rows if Metric was projected multiple times, e.g.  I got results below separately
python calc_dihe.py my_pdb_identifier --select_str='protein and chain A and resid 116 to 256'
python calc_dihe.py my_pdb_identifier --select_str='protein and chain B and resid 116 to 256'
python calc_dihe.py my_pdb_identifier --select_str='protein and resid 116 to 256'
I have only one xtc file in the xtc_file_path

```pythonscript
chain_a.dat[0].shape
(10000,560)
chain_b.dat[0].shape
(10000,560)
chain_w.dat[0].shape
(10000,1120)

chain_w.dat[0][: , : 560] - chain_a.dat[0]
array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32)

chain_w.dat[0][: , 560 :] - chain_b.dat[0]
array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], 
```

**Comment by stefdoerr** [comment]
Sorry I don't understand what you mean.
Take a look also at `data.map`. In the new version it should be a Pandas array which describes each column of `data.dat`

**Comment by j3mdamas** [comment]
Is this solved @funnybomb?

**Comment by funnybomb** [comment]
yes, I think that I used the method that I described in my previous post is working fine for me.
Here is more detailed description:
I have a homodimer protein contain two chains A,B which have same resids in both chains, e.g. 
chain A 116-334, chain B 116-334
now I want to get dihedral of both chains from 116 -256 according to original paper of the structure.
I project the Metric separately  
```python
fs = simlist(xtc_file_path,pdb_file)
me = Metric(fs)
me.projection(MetricDihedral(protsel='protein and chain A and resid 116 to 256', sincos=True))
data = me.project()
data.dat.shape
(1,)
data.dat[0].shape
(100000,560)
#then project again on the same Metric of chain B
me.projection(MetricDihedral(protsel='protein and chain B and resid 116 to 256', sincos=True))
data = me.project()
data.dat.shape
(1,)
data.dat[0].shape
(100000,1120)
```
data.map 
```python
data.map
                                            description  \
0     Sine of angle of (ARG 116 N) (ARG 116 CA) (ARG...   
1     Cosine of angle of (ARG 116 N) (ARG 116 CA) (A...   
2     Sine of angle of (HSP 117 N) (HSP 117 CA) (HSP...   
3     Cosine of angle of (HSP 117 N) (HSP 117 CA) (H...   
4     Sine of angle of (ARG 116 C) (HSP 117 N) (HSP ...   
5     Cosine of angle of (ARG 116 C) (HSP 117 N) (HS...   
6     Sine of angle of (VAL 118 N) (VAL 118 CA) (VAL...   
7     Cosine of angle of (VAL 118 N) (VAL 118 CA) (V...   
8     Sine of angle of (HSP 117 C) (VAL 118 N) (VAL ...   
9     Cosine of angle of (HSP 117 C) (VAL 118 N) (VA...   
10    Sine of angle of (VAL 119 N) (VAL 119 CA) (VAL
...
1110  Sine of angle of (ASP 254 N) (ASP 254 CA) (ASP...   
1111  Cosine of angle of (ASP 254 N) (ASP 254 CA) (A...   
1112  Sine of angle of (GLN 253 C) (ASP 254 N) (ASP ...   
1113  Cosine of angle of (GLN 253 C) (ASP 254 N) (AS...   
1114  Sine of angle of (VAL 255 N) (VAL 255 CA) (VAL...   
1115  Cosine of angle of (VAL 255 N) (VAL 255 CA) (V...   
1116  Sine of angle of (ASP 254 C) (VAL 255 N) (VAL ...   
1117  Cosine of angle of (ASP 254 C) (VAL 255 N) (VA...   
1118  Sine of angle of (VAL 255 C) (LEU 256 N) (LEU ...   
1119  Cosine of angle of (VAL 255 C) (LEU 256 N) (LE...  

                       indexes      type  
0               [0, 2, 22, 24]  dihedral  
1               [0, 2, 22, 24]  dihedral  
2             [24, 26, 40, 42]  dihedral  
3             [24, 26, 40, 42]  dihedral  
4             [22, 24, 26, 40]  dihedral  
5             [22, 24, 26, 40]  dihedral  
6             [42, 44, 56, 58]  dihedral  
7             [42, 44, 56, 58]  dihedral  
8             [40, 42, 44, 56]  dihedral  
9             [40, 42, 44, 56]  dihedral  
10            [58, 60, 72, 74]  dihedral  
11            [58, 60, 72, 74]  dihedral  
12            [56, 58, 60, 72]  dihedral  
13            [56, 58, 60, 72]  dihedral  
14            [74, 76, 91, 93]  dihedral  
15            [74, 76, 91, 93]  dihedral  
...
1110  [5600, 5602, 5610, 5612]  dihedral  
1111  [5600, 5602, 5610, 5612]  dihedral  
1112  [5598, 5600, 5602, 5610]  dihedral  
1113  [5598, 5600, 5602, 5610]  dihedral  
1114  [5612, 5614, 5626, 5628]  dihedral  
1115  [5612, 5614, 5626, 5628]  dihedral  
1116  [5610, 5612, 5614, 5626]  dihedral  
1117  [5610, 5612, 5614, 5626]  dihedral  
1118  [5626, 5628, 5630, 5645]  dihedral  
1119  [5626, 5628, 5630, 5645]  dihedral  
```

**Comment by stefdoerr** [comment]
You don't need to project twice. This is a confusion that stems from our bad naming of the method `projection` which should have been `appendProjection`.

```python
fs = simlist(xtc_file_path,pdb_file)
me = Metric(fs)
me.projection(MetricDihedral(protsel='protein and chain A and resid 116 to 256', sincos=True))
me.projection(MetricDihedral(protsel='protein and chain B and resid 116 to 256', sincos=True))
data = me.project()
data.dat.shape
(1,)
data.dat[0].shape
(100000,1120)
```

This should work equally well and at half the calculation time.
In newer HTMD versions better do:
```python
fs = simlist(xtc_file_path,pdb_file)
me = Metric(fs)
me.set([MetricDihedral(protsel='protein and chain A and resid 116 to 256', sincos=True),
        MetricDihedral(protsel='protein and chain B and resid 116 to 256', sincos=True)])
data = me.project()
data.dat.shape
(1,)
data.dat[0].shape
(100000,1120)
```

Since we deprecated the `projection` method.

**Comment by j3mdamas** [comment]
It seems like it's clear now. I'm going to close
