### ISSUE TITLE
ValueError: NULL pointer access in XTC step size

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#122]
Hi,

The following raised when I tried to get the eq.distribution of a HMM. Let me know any ideas.

Thanks a lot,
Noelia

```
model=Model()
model.load('model7epochs.dat') 
modelhmm = ModelHMM(model.data)
modelhmm.markovModel(10,5)  # Lag in frames
#modelhmm.plotTimescales(100)  # Max lag in frames. This is slow!
modelhmm.eqDistribution()
modelhmm.viewStates(ligand='resname MOL and noh')

--------------------------------------------------
Active set includes macrostates: [0 1 2 3 4]

ValueError                                Traceback (most recent call last)
<ipython-input-12-4bf5440f94ab> in <module>()
     22 #modelhmm.plotTimescales(100)  # Max lag in frames. This is slow!
     23 modelhmm.eqDistribution()
---> 24 modelhmm.viewStates(ligand='resname MOL and noh')
     25 #kin = KineticsHMM(modelhmm, concentration=0.018, temperature=298)
     26 #kin.getRates()

/path/to/acellera/test/python/lib/python3.5/site-packages/htmd/modelhmm.py in viewStates(self, protein, ligand, nsamples)
     61             frames = self.data.rel2sim(res[i])
     62             for f in frames:
---> 63                 mol._readTraj(f.sim.trajectory[f.piece], frames=[f.frame], append=True)
     64             mol.wrap('protein')
     65             mol.align('protein', refmol=refmol)

/path/to/acellera/test/python/lib/python3.5/site-packages/htmd/molecule/molecule.py in _readTraj(self, filename, skip, frames, append, mdtraj)
    934                     traj.coords = traj.coords[:, :, frames[i]]
    935                 else:
--> 936                     traj = XTCread(f, frames[i])
    937                 self.fileloc.append([f, int(frames[i])])
    938 

/path/to/acellera/test/python/lib/python3.5/site-packages/htmd/molecule/readers.py in XTCread(filename, frames)
    141                 t.box = np.zeros((3, nframes), dtype=np.float32)
    142 
--> 143             t.step[i] = retval[0].step
    144             t.time[i] = retval[0].time
    145             t.box[0, i] = retval[0].box[0]

ValueError: NULL pointer access
```

**Comment by stefdoerr** [comment]
Oooh there seems to a broken XTC trajectory missing the step size and while trying to visualize the system it fails at loading it. I wonder though how that system even got projected.
This is not an HMM issue.

Any chance I can have that xtc?
Debug the program with:
```
%debug
up
print(f)
```
and that should give you the filename.

**Comment by noeliaferruz** [comment]
Hi,

The previous model was from version 1.0.26, perhaps that helps to see why it was projected.
This command run for hours and didn't output anything. Do you run it by running the command that errored first followed by those three lines? I'll try different combinations but I'm not sure in any case.
I decided to start over the metrics again, but got another error earlier than that when running the nr. macros . I'll post that one and keep this one open in case it appears again in the following line.

Thanks,

**Comment by stefdoerr** [comment]
Which command ran for hours?
Once the program throws the error you then type `%debug `and then give the rest of the commands one by one

**Comment by mj-harvey** [comment]
@stefdoerr  this will be a bad XTC. You need to check the return of the XTC C reader more carefully. The only way it has to signal failure is to return NULL

**Comment by stefdoerr** [comment]
This should fix it:
https://github.com/Acellera/htmd/commit/75d720e64daaa443f21408decda521966a485dcf
