### ISSUE TITLE
Convert acemd.commandreference.html into .rst and integrate into /doc

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#127]
It's insecure because docs.acellera.com is on http rather than on https. But rather than changing the protocol, the best should be to convert to .rst and integrate into the /doc

https://www.htmd.org/docs/latest/acemd.commandreference.html

**Comment by mj-harvey** [comment]
done as a one-off

**Comment by j3mdamas** [comment]
where is it?

**Comment by j3mdamas** [comment]
so I can put it in the HTMD doc replacing the iframe
