### ISSUE TITLE
ValueError: all the input array dimensions except for the concatenation axis must match exactly

### ISSUE THREAD

**Issue by giadefa** [Acellera/htmd#128]
I am getting this error on a trajectory that seemed to work last week. Any recent change?

Traj
id = 2017
parent = None
input = []
trajectory = ['/workspace1/D3R/D3R-467/batches/5/filtered/1-7/e5s87_e1s336p2f175/e5s87_e1s336p2f175-NOELIA_c36x467x5-0-4-RND1667_9.filtered.xtc', '/workspace1/D3R/D3R-467/batches/5/filtered/1-7/e5s87_e1s336p2f175/e5s87_e1s336p2f175-NOELIA_c36x467x5-1-4-RND1667_9.filtered.xtc', '/workspace1/D3R/D3R-467/batches/5/filtered/1-7/e5s87_e1s336p2f175/e5s87_e1s336p2f175-NOELIA_c36x467x5-2-4-RND1667_9.filtered.xtc', '/workspace1/D3R/D3R-467/batches/5/filtered/1-7/e5s87_e1s336p2f175/e5s87_e1s336p2f175-NOELIA_c36x467x5-3-4-RND1667_9.filtered.xtc']
molfile = /workspace1/D3R/D3R-467/batches/4/filtered/filtered.pdb

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-da1a022815f7> in <module>()
----> 1 m = Molecule(sims[2017])

/shared/gianni/Code/acellera/htmd/htmd/molecule/molecule.py in __init__(self, filename, name)
    157 
    158         if filename:
--> 159             self.read(filename)
    160             if isinstance(filename, str):
    161                 self.topoloc = os.path.abspath(filename)

/shared/gianni/Code/acellera/htmd/htmd/molecule/molecule.py in read(self, filename, type, skip, frames, append, overwrite)
    669         if isinstance(filename, Sim):
    670             self.read(filename.molfile)
--> 671             self.read(filename.trajectory)
    672             return
    673 

/shared/gianni/Code/acellera/htmd/htmd/molecule/molecule.py in read(self, filename, type, skip, frames, append, overwrite)
    687             self._readPDB(filename, mode='pdbqt', overwrite=overwrite)
    688         elif type == "xtc" or ext == "xtc":
--> 689             self._readTraj(filename, skip=skip, frames=frames, append=append)
    690         elif type == "coor" or ext == "coor":
    691             if append:

/shared/gianni/Code/acellera/htmd/htmd/molecule/molecule.py in _readTraj(self, filename, skip, frames, append, mdtraj)
    857                 self.coords = np.append(self.coords, coords, 2)
    858                 self.box = np.append(self.box, box, 1)
--> 859                 self.boxangles = np.append(self.boxangles, boxangles, 0)
    860 
    861         if skip is not None:

/shared/gianni/miniconda3/lib/python3.5/site-packages/numpy/lib/function_base.py in append(arr, values, axis)
   4584         values = ravel(values)
   4585         axis = arr.ndim-1
-> 4586     return concatenate((arr, values), axis=axis)
   4587 

ValueError: all the input array dimensions except for the concatenation axis must match exactly

**Comment by giadefa** [comment]
it does happen only to few traj

**Comment by stefdoerr** [comment]
Fixed in https://github.com/Acellera/htmd/commit/bba92efa4ebb1b8fb085b547e47e9225de3a814d

**Comment by stefdoerr** [comment]
Added test case to catch similar problems in future: https://github.com/Acellera/htmd/commit/38e32ec16467798f6f3c54bd5ab1f49aae233427
