### ISSUE TITLE
MetricData.combine

### ISSUE THREAD

**Issue by giadefa** [Acellera/htmd#129]
I doubt that this actually works after the panda restructuring

**Comment by stefdoerr** [comment]
I didn't even remember it existed since we now combine them during calculation.

**Comment by j3mdamas** [comment]
Deprecate?

**Comment by stefdoerr** [comment]
I still see some usability for it if someone decides to do a new metric later and does not want to recalculate the first one. So I guess we should update it to work.

**Comment by stefdoerr** [comment]
Fixed: https://github.com/Acellera/htmd/commit/a03d409f2387331dae6fbd07cc80822fd3a36575
