### ISSUE TITLE
caps in amber

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#13]
Hi all,

Got this error when building an amber system. It's a bit strange because I think this same system worked a couple of weeks ago and also works in charmm. The protein I'm using is 5hd0.pdb and saving chain A (attached solvated molecule a txt file, pdbs aren't supported here).

[solvated.txt](https://github.com/Acellera/htmd/files/213285/solvated.txt)

    raise AssertionError('Segment {}, resid {} should have either one H2 or one HT2 atom. Cannot cap.'.format(seg, np.min(resids)))
AssertionError: Segment P0, resid 58 should have either one H2 or one HT2 atom. Cannot cap.

Thanks

**Comment by stefdoerr** [comment]
Yes I believe that it worked before but I don't think it was adding caps.
The thing is that to add caps in AMBER you need to replace some hydrogen atoms of the first and last residues. 
So to do that you need to use Toni's proteinPreparation function which protonates the protein and then it should go through.

**Comment by stefdoerr** [comment]
I guess we should add that to the error message to point people in the right direction.

**Comment by tonigi** [comment]
well the error message is there, but perhaps it should be an exception rather than an assertion :)

**Comment by noeliaferruz** [comment]
Ah I didn't know proteinPreparation was already working. Perfect! 
I'll try it.

**Comment by stefdoerr** [comment]
@tonigi so if there are no hydrogens we warn and don't cap?

**Comment by tonigi** [comment]
No, I'd throw an exception.. i mean, `raise Exception` instead of 
`assert` (assertions are mostly for internal errors). Just a style thing.

**Comment by stefdoerr** [comment]
Ah okay. I changed it to `RuntimeError` since I tend to use that. Is `Exception` more fitting/standard? I haven't used it yet and am a bit confused from the big amount of options. 

Sorry for the off-topic discussion.

**Comment by noeliaferruz** [comment]
How do you actually call proteinPreparation? Are there any examples? 
Cannot find it as proteinPreparation() or similar commands.

**Comment by tonigi** [comment]
@stefdoerr I think the common  way is 
* assertions for situations that should not happen
* exceptions for the others
* python [docs](https://docs.python.org/3.5/library/exceptions.html#exceptions.Exception) recommend using Exception or (better) a custom derived class for user-defined exceptions.

**Comment by tonigi** [comment]
@noeliaferruz it's in the multiscale fork

**Comment by tonigi** [comment]
@noeliaferruz it's in proteinpreparation.py ...   not in the docs yet, but see the docstring :)

**Comment by stefdoerr** [comment]
Ah yes I will add `proteinPreparation` to the __init__

**Comment by stefdoerr** [comment]
@tonigi 
https://docs.python.org/2/library/exceptions.html#exceptions.RuntimeError

> Raised when an error is detected that doesn’t fall in any of the other categories. The associated value is a string indicating what precisely went wrong.

So okay, it works ;)

**Comment by j3mdamas** [comment]
The `_applyCaps` function assumes one has either H2 or HT2 (on the case of the N terminal), which is normally not the case with PDBs, so the `proteinPreparation` (or other kind of hydrogen addition)  will always be necessary to protonate beforehand. My question is: when did this work?

**Comment by tonigi** [comment]
We could add the standard terminal H name - which is it?

**Comment by stefdoerr** [comment]
When there was no capping done even though people thought it was being done ;) Worked when caps were already present

**Comment by noeliaferruz** [comment]
Hey guys, sorry, did you prepare a newest version with proteinPreparation? If so I'ask to update it.
I don't know nyway how to import the function xD.

>>> from htmd.proteinpreparation import proteinPreparation
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'proteinPreparation'
>>> from proteinpreparation import proteinPreparation
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'proteinpreparation'
>>> proteinpreparation
proteinpreparation
>>> proteinpreparation.__
proteinpreparation.__class__(         proteinpreparation.__format__(        proteinpreparation.__le__(            proteinpreparation.__package__        proteinpreparation.__sizeof__(
proteinpreparation.__delattr__(       proteinpreparation.__ge__(            proteinpreparation.__loader__         proteinpreparation.__path__           proteinpreparation.__spec__
proteinpreparation.__dict__           proteinpreparation.__getattribute__(  proteinpreparation.__lt__(            proteinpreparation.__reduce__(        proteinpreparation.__str__(
proteinpreparation.__dir__(           proteinpreparation.__gt__(            proteinpreparation.__name__           proteinpreparation.__reduce_ex__(     proteinpreparation.__subclasshook__(
proteinpreparation.__doc__            proteinpreparation.__hash__(          proteinpreparation.__ne__(            proteinpreparation.__repr__(          
proteinpreparation.__eq__(            proteinpreparation.__init__(          proteinpreparation.__new__(           proteinpreparation.__setattr__(

**Comment by j3mdamas** [comment]
This is because you are using Acellera/htmd, and the module is only on
multiscale/htmd (for now)

**Comment by tonigi** [comment]
should be in the repo already, afaik

**Comment by noeliaferruz** [comment]
Mh, no but I thnk we have now the multiscale version. I can see the script and its functions, I just cannot import it. Or do you mean a different thing @j3mdamas ?

**Comment by j3mdamas** [comment]
From the conda latest version (1.0.11):

```
from htmd.proteinpreparation.proteinpreparation import prepareProtein
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-6d133a828cab> in <module>()
----> 1 from htmd.proteinpreparation.proteinpreparation import prepareProtein

/home/joao/miniconda3/lib/python3.5/site-packages/htmd/proteinpreparation/proteinpreparation.py in <module>()
     13 from pathlib import Path
     14 sys.path.append(Path(__file__).resolve().parents[1])
---> 15 from pdb2pqr.src.pdbParser import readPDB
     16 from pdb2pqr.main import runPDB2PQR
     17 

ImportError: No module named 'pdb2pqr'
```

**Comment by tonigi** [comment]
double check the syntax (was lost in my previous post)

from htmd.proteinpreparation.**proteinpreparation** import proteinPreparation

**Comment by noeliaferruz** [comment]
Ahhh ok.  I was actually importing it wrong and also then I'm missing pdb2pqr. Thanks!
I'll wait then

**Comment by tonigi** [comment]
perhaps not in conda yet

**Comment by giadefa** [comment]
I though that we agreed to include pdb2pqr  in the repository as it was a
strongly modified version. In conda it could conflict with the real one.



On 11 April 2016 at 18:43, Toni G <notifications@github.com> wrote:

> perhaps not in conda yet
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Acellera/htmd/issues/13#issuecomment-208441879>
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>

**Comment by tonigi** [comment]
Correct. It should   work out of this repo.  (Not sure when the htmd conda package was last updated).

**Comment by stefdoerr** [comment]
New conda version is out that fixes the problem and auto-imports `prepareProtein`
