### ISSUE TITLE
Error with calling in PDB files in new update

### ISSUE THREAD

**Issue by waskom** [Acellera/htmd#134]
I just updated the HTMD and was trying to build a new system but the notebook failed to call in the PDB file. I was using the same commands that worked previously.

The output was:
"ValueError: could not convert string to float:"

**Comment by j3mdamas** [comment]
Hi @waskom,

Should be fixed in 1.3.10 (which is being built as we speak). See issue #131

**Comment by stefdoerr** [comment]
New version should be out now!
