### ISSUE TITLE
enhancement to LocalGPUQueue to manage several machines via ssh

### ISSUE THREAD

**Issue by mj-harvey** [Acellera/htmd#139]

**Comment by stefdoerr** [comment]
Is that even "local" anymore? Maybe we will make it a separate class.

**Comment by j3mdamas** [comment]
Yes, it should be another class, from what I understand.

**Comment by j3mdamas** [comment]
Do we still want this, @mj-harvey?

**Comment by mj-harvey** [comment]
Yes, but punt it to 1.8.0

**Comment by j3mdamas** [comment]
Just did. It is still not clear to me how this queue will work, but it's not a priority, so we'll discuss it later
