### ISSUE TITLE
VdW table too large ERROR

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#14]
Hi guys,

I have a system with two ligands. 1 of them parameterized with cgenff latest version through command line the other with parameterize. It's basically running a simulation of pdb file 4MQT.
I run this system with both par/par_all36_prot.prm and par/par_all36_prot_mod.prm.
It turns that the first works straight away the second cannot find atomtype xxxx. which is found in the cgenff ligand.

Let me know if you need all the files.

best
N

**Comment by noeliaferruz** [comment]
Let me find more specifically what's exactly promoting the error.

**Comment by noeliaferruz** [comment]
It turns out that the clash is between the parameterize ligand and c36_mod.
The system which uses c36 also runs in ACEMD. 
The system which uses c36_mod produces this output: (let me know if you need files)

ERROR: file mapmdx.cpp line 751: VDW table too large
 
# ACEMD Molecular Dynamics Version [3212u2]
# (c) 2009-2015 Acellera Ltd. http://www.acellera.com
# See License Agreement for terms and conditions of use
# or write to support@acellera.com
#
# Licensed by Acellera Ltd (http://www.acellera.com)
# No floating licenses available.
# License file locations:
# /nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/acemd/3212u3/license.dat
# /home/ferrun/.acellera/license.dat
# LICENSE INFORMATION:
# Holder  : Simone Sciabola
# Site    : Pfizer
# Expiry  : Sun Jan  1 19:00:00 2017
# GPUS    : Whole host
#
# LICENSE INFORMATION:
# Holder  : Simone Sciabola
# Site    : Pfizer
# Expiry  : Sun Jan 29 19:00:00 2017
# GPUS    : 4
#
# Running on host [adwgpu503.pfizer.com]
# CUDA Synchronisation mode: SPIN
# SWAN: Created context 0 on GPU 0
# SWAN Device 0	:
#	Name		: Tesla K80
#	ECC		: Disabled
#	Global mem	: 12287MB
#	Capability	: 3.7
#	PCI ID		: 0000:08:00.0
#	Device clock	: 823MHz
#	Memory clock	: 2505MHz
#	Memory width	: 384bit
# SWAN: Configuring Peer Access:
# -	
# SWAN device 0 is NVML device 2 with PCI-ID 0000:08:00.0 and serial [0321215002520] 
# NVML : 0 : PCI Width 16x/16x	 Speed 3/3
# NVML : 0 : Fan 0%	 Temp 27C	 Mem Used 123MB Free 12164MB Total 12287MB
# NVML : 0 : Performance state 0
# NVML : 0 : Power 26.64W 
# NVML : 0 : Load 0 GPU 0 Mem 
# Configuration [Tesla K80] [370] [Linux]
#
#WARNING: warning: Conflict in redefined improper parameters for i crn1 nrn2 nrn2 nrc4
#WARNING: warning: Conflict in redefined improper parameters for i nrn2 hrm2 hrm2 crn1
#WARNING: warning: Conflict in redefined improper parameters for i crn1 nrn2 nrc4 nrn1
#WARNING: warning: Conflict in redefined improper parameters for i nrn1 cr33 crn1 hrm1
#WARNING: warning: Conflict in redefined improper parameters for i crn1 nrc4 nrn2 nrn1
#WARNING: warning: Conflict in redefined improper parameters for i nrn1 ct2 crn1 hrm1
# Topology reports 59246 atoms
# -  There are 3 long-range exceptions
# VDW table size 52

**Comment by mj-harvey** [comment]
Firstly, that should have terminated at the "VDW table too large" error. Did it continue past that point, or did you edit down the # of parameters and try again?
Secondly, you should see those 6 improper terms in the parameter. The error indicates that they are present multiple times, and with different values.  The impropers don't get reparameterised, this must be a change between differing versions of ffs being used. 
Could you show them to me, please?

**Comment by noeliaferruz** [comment]
1) I copied literally the output I got. I just removed the [...] part containing the license information. 
2) Right.

Attached files to generate the error and the outputs.
[files.zip](https://github.com/Acellera/htmd/files/217246/files.zip)

**Comment by noeliaferruz** [comment]
To update, it seems the warnings aren't causing the error. 
I just run another simulation with an exact setup and although the warnings were there the error didn't produce and the simulation run. 

Also, it seems independent of the forcefield in this second case, as the old c36 also produced the vdW table too large error.

**Comment by noeliaferruz** [comment]
It is actually a very reproducible error every time I have two large ligands, a membrane, a protein, water and ions. To me it seems something related to having too many atomtype definitions and the way acemd handles that.

I have tried all the possible parameterize-cgenff combinations for the two ligands and only removing one of the two (independently of which one) solves the problem. So it seems indeed something related to the amount of atom-types. It is a rather important bug I think, as it impedes running simulations with agonists and partial agonists at the same time.

**Comment by mj-harvey** [comment]
Yes, charmm has lots of atom types, too many for a particular fixed size
data table within acemd. The good news is it should be easy to expand it.
Will try to fix it tomorrow

**Comment by noeliaferruz** [comment]
Hi Matt,

Thanks for your reply. Did you fix this yesterday in the end?
If so, let me know and I might try to update acemd -if you tell me how-. This issue is currently hampering an important project.

Thanks,
Noelia

**Comment by mj-harvey** [comment]
Hi Noelia

Turns out it's not a straightforward fix. The table is as large as the GPU
memory it inhabits permits. I'm working on some additional code changes to
accommodate the modification. I hope to have something for you tomorrow at
the latest. I will send you an acemd by email

**Comment by noeliaferruz** [comment]
Many thanks Matt.

**Comment by giadefa** [comment]
Partially fixed in the next acemd version.

**Comment by GerardBCN** [comment]
I have a similar situation. Simulations crash with the "VDW table too large" error when running in GPUGRID. But I ran a similar system not too long ago and worked perfectly. In that case we had 306 atomtypes and in the current simulations we have 299 atomtypes.... how does the VDW table get created?

**Comment by stefdoerr** [comment]
Actually it only keeps the atom types that are in the system you simulate and these are hard-coded to 54. You have 78

```pytb
In [2]: mol = Molecule('./Downloads/system.psf')

In [3]: mol.atomtype
Out[3]: array(['CT3', 'HA3', 'HA3', ..., 'CLA', 'CLA', 'CLA'], dtype=object)

In [4]: np.unique(mol.atomtype)
Out[4]: 
array(['C', 'CA', 'CAI', 'CC', 'CEL1', 'CG2O5', 'CG2R61', 'CG301', 'CG314',
       'CG321', 'CG331', 'CG334', 'CL', 'CLA', 'CP1', 'CP2', 'CP3', 'CPH1',
       'CPH2', 'CPT', 'CRL1', 'CRL2', 'CT1', 'CT2', 'CT2A', 'CT3', 'CTL1',
       'CTL2', 'CTL3', 'CTL5', 'CY', 'H', 'HA1', 'HA2', 'HA3', 'HAL1',
       'HAL2', 'HAL3', 'HB1', 'HB2', 'HC', 'HEL1', 'HGA1', 'HGA2', 'HGA3',
       'HGP2', 'HGR61', 'HL', 'HOL', 'HP', 'HR1', 'HR3', 'HS', 'HT', 'N',
       'NC2', 'NG3P1', 'NH1', 'NH2', 'NH3', 'NR1', 'NR2', 'NTL', 'NY', 'O',
       'O2L', 'OBL', 'OC', 'OG2D3', 'OH1', 'OHL', 'OSL', 'OSLP', 'OT',
       'PL', 'S', 'SM', 'SOD'], dtype=object)

In [5]: len(np.unique(mol.atomtype))
Out[5]: 78
```

**Comment by GerardBCN** [comment]
Just for the record, a recent similar system that I simulated had 82 atomtypes (when calculating it using the same protocol) so there must be something else wrong...

**Comment by stefdoerr** [comment]
My bad, it also joins atomtypes which have same LJ parameters. In which case I cannot calculate now by hand how many are left
