### ISSUE TITLE
Failed to install htmd latest version

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#141]
Hello,

Have you guys seen any errors in the latest build? Getting the following:

```
[...]
++ export _LMFILES_
+ which conda
/path/to/acellera/test/python/bin/conda
+ which python
/path/to/acellera/test/python/bin/python
+ conda install htmd
CondaOSError: OS error: failed to link (src='/path/to/acellera/test/python/pkgs/qt-4.8.7-4/mkspecs/default', dst='/path/to/acellera/test/python/mkspecs/default', type=3, error=FileExistsError(17, 'File exists'))



Package plan for installation in environment /path/to/acellera/test/python:

The following NEW packages will be INSTALLED:

    htmd: 1.3.12-py35_0 acellera
    qt:   4.8.7-4               

Linking packages ...
[                    ]|                                                  |   0%
[qt                  ]|                                                  |   0%
Build step 'Execute shell' marked build as failure
Email was triggered for: Failure - Any
Sending email for trigger: Failure - Any
Finished: FAILURE
```

**Comment by stefdoerr** [comment]
Nope :/

**Comment by j3mdamas** [comment]
Mkspecs... Isn't this the same package shozeb was complaining about the
other day?

**Comment by stefdoerr** [comment]
No he had problems with intel mkl. This is QT Mkspecs. Totally other package as far as I know.

**Comment by j3mdamas** [comment]
Hi @noeliaferruz, can you try to run the update again? Maybe it was a temporary bug. Let me know.

**Comment by noeliaferruz** [comment]
Hi,

No, I tried several times and it always failed like that. Then I updated the other module, which was in version 1.0.26 and run fine.  No idea.

**Comment by stefdoerr** [comment]
So we can close it?

**Comment by stefdoerr** [comment]
What do you mean by 'other module'?

**Comment by noeliaferruz** [comment]
We have two conda directories here managed as modules that people can load. One is supposed to be an older stable version (module load acellera/current) the other the latest version (module load acellera/test). I only have permissions to update them but nothing else. acellera/test is the one failing to build.

**Comment by stefdoerr** [comment]
Huh, no clue. Can you force-update all the packages in the one that has problems?

**Comment by noeliaferruz** [comment]
Sure, I'll try that.

**Comment by j3mdamas** [comment]
Let me know

**Comment by noeliaferruz** [comment]
The IT just told me is working now and that it was related to a conda bug:  https://github.com/conda/conda/issues/2837

**Comment by j3mdamas** [comment]
great! thanks Noelia
