### ISSUE TITLE
Parameterisation random error: File "<string>", line 60, in <module>  TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by GerardBCN** [Acellera/htmd#146]
This compound gives a sparse error (sometimes yes, sometimes no, or in different places during a newparameterize run). The first time crashed during minimization, now seems to be running the dihedral optimization already. 

[frag29_neutral.mol2.zip](https://github.com/Acellera/htmd/files/500676/frag29_neutral.mol2.zip)

**Comment by j3mdamas** [comment]
Something to improve for the 1.6.0 release.

**Comment by mj-harvey** [comment]
I might expect the occasional python stack trace to appear if an individual QM job fails. This is quite likely to happen during the dihedral scan if the rotated geometry has a steric clash
