### ISSUE TITLE
proteinPrepare writes N as element for any added atom (except Hydrogen)

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#147]
This is related with issue #101.

Basically, the same problem, but with any atoms added.

Example:
``` python
from htmd import *
m = Molecule('2xzb')
m.get('name', 'resid 405')
m.get('element', 'resid 405')
pm = proteinPrepare(m)
pm.get('name', 'resid 405')
pm.get('element', 'resid 405')
```

For `CD2` and `CE1`, missing atoms in the initial structure, it is putting element `N`. From other examples, it seems like it does it for all non-hydrogen atoms.

I was looking at the fix for the hydrogens 28384f99327dd17c202c5b2c789e103f8e2aba49 but I'm not sure about the right approach to make it general.

**Comment by tonigi** [comment]
I would not set element at all.  They are guesses anyway, and not used in practice (except for cosmetic reasons).
