### ISSUE TITLE
Why can not Kinetics constructor detect source when using MetricDihedral to featurize the simulation?

### ISSUE THREAD

**Issue by funnybomb** [Acellera/htmd#149]
when I use MetricDihedral to build the projection and msm, and use Kinetics model to plot transition pathway,  always get 
RuntimeError('Could not detect source state. Please specify it in the Kinetics constructor.')
In v1.3.4 htmd/kinetics.py or later I found 
```python
        if not dataobj.map.empty:  # Search for distances or contacts in the data
            if dataobj.parent is None:                                     
                distcols = np.where(dataobj.map.type == 'distance')[0]  
                contcols = np.where(dataobj.map.type == 'contact')[0]   
            else:                                                          
                distcols = np.where(dataobj.parent.map.type == 'distance')[0]
                contcols = np.where(dataobj.parent.map.type == 'contact')[0]
                                                                           
        if len(distcols) == 0 and len(contcols) == 0:                      
            raise RuntimeError('Could not detect source state. Please specify it in the Kinetics constructor.')
```
apparently, my msm model built by
```python
data = me.set(MetricDihedral(protsel='protein', sincos=True))
tica = TICA(data, 20)
dataTica = tica.project(3)
dataTica.cluster(MiniBatchKMeans(n_clusters=cluster_num), mergesmall=5)
data = me.project()
model = Model(dataTica)
model.markovModel(lag_frame,macrostate_num)
kin = Kinetics(model, temperature=300)
```
so how can I determine source macrostate when I use MetricDihedral to featurize my simulation?

**Comment by stefdoerr** [comment]
Indeed there is no clear way of defining the source state with dihedrals. Typically our source is:
 * for protein folding: the most extended state
 * for ligand binding: the most detached state

These can be calculated nicely when using distances and contacts, not so nicely from dihedrals.

Therefore the best solution is to throw the error. What you should do is manually select your source state.
To do that just visualize your macrostates with `model.viewStates()` and decide which one should be your source state. Then pass it to the `Kinetics` constructor like `kin = Kinetics(model, temperature=300, source=2)`
