### ISSUE TITLE
Trajectory view with NGL viewer does not show anything

### ISSUE THREAD

**Issue by giadefa** [Acellera/htmd#15]
Reproducer

molTraj = Molecule(htmd.home() + '/data/dhfr/dhfr.psf')
molTraj.read(htmd.home() + '/data/dhfr/dhfr.xtc')
molTraj.view()

**Comment by j3mdamas** [comment]
I tried yesterday with some data from another tutorial and it worked... I can try and see this.

**Comment by j3mdamas** [comment]
It works with `data/dhfr/dhfr.pdb` but not `data/dhfr/dhfr.psf`

**Comment by stefdoerr** [comment]
Yes, sorry for the confusion. If you read a psf only charges and
connectivity are read. No atom information. We should add an error when
someone tries to instantiate a Molecule with a psf file

**Comment by j3mdamas** [comment]
I think one could initiate a `Molecule` with a .psf file, no? Or is it technically impossible?

**Comment by stefdoerr** [comment]
It is possible in the sense that it will only contain charges and bonds but no atoms at all. But I doubt that this is what you want.

VMD can read atoms from a psf but we cannot. If someone wants to write a more fully fledged psf reader you are welcome.

**Comment by giadefa** [comment]
we should just use the acemd ones for me for PDBs, PSF, DCD, etc

On 14 April 2016 at 16:25, Stefan <notifications@github.com> wrote:

> It is possible in the sense that it will only contain charges and bonds
> but no atoms at all. But I doubt that this is what you want.
>
> VMD can read atoms from a psf but we cannot. If someone wants to write a
> more fully fledged psf reader you are welcome.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Acellera/htmd/issues/15#issuecomment-209968823>
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>

**Comment by j3mdamas** [comment]
So, I was checking. `Molecule.view` writes a .pdb and a .xtc file, and loads them with either VMD or NGL. I am guessing the .psf approach is failing when it tries to write the .pdb file.

Yeah, if @giadefa finds it useful, I can modify the `PSFread`. Actually, a `PSFwrite` from a just read .psf file will not be able re-generate the original .psf file.

**Comment by j3mdamas** [comment]
In the particular case of the tutorial, we can just replace the .psf with the .pdb and it will work fine. There will be no bond issues.

**Comment by giadefa** [comment]
that's done already

On 14 April 2016 at 16:47, João M. Damas <notifications@github.com> wrote:

> In the particular case of the tutorial, we can just replace the .psf with
> the .pdb and it will work fine. There will be no bond issues.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Acellera/htmd/issues/15#issuecomment-209980152>
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>

**Comment by j3mdamas** [comment]
I think this is closed now. If we want, we can open an issue about `PSFread` and the `PSF` class.
