### ISSUE TITLE
Adaptive sample notebook/data set

### ISSUE THREAD

**Issue by KendyP** [Acellera/htmd#154]
Hello,
Is there an example ipython notebook and data set available for the Adaptive tutorial found on the htmd site? I am attempting to set up Adaptive and would like some data to run through the tutorial. 

Thank you,
Kendy

**Comment by stefdoerr** [comment]
Practically you only need the generators and an example python script. I can provide you with some for Villin.

http://pub.htmd.org/generators_villin.zip
Here you go.

The adaptive script should then be something like in the tutorial
```python
md = AdaptiveMD()
md.nmin=5
md.nmax=10
md.nepochs = 30
md.app = AcemdLocal(datadir='./data')
md.projection = MetricSelfDistance('protein and name CA')
md.ticadim = 3
md.updateperiod = 14400 # execute every 4 hours
md.run()
```

That should be all you need. Tell me if something goes wrong.
