### ISSUE TITLE
protocols page missing in documentation

### ISSUE THREAD

**Issue by giadefa** [Acellera/htmd#156]

**Comment by stefdoerr** [comment]
I made a temporary one. Someone should add some more content I guess.

**Comment by stefdoerr** [comment]
Also reorganized the docs a bit to put the adaptive, protocols and apps under a common "MD simulation" section since we were double linking them.

**Comment by j3mdamas** [comment]
did you push that to git or just published on www.acellera.com?

**Comment by j3mdamas** [comment]
The holiday came in the middle of the modifications, but Stefan and I will continue tomorrow.
