### ISSUE TITLE
mybinder.org

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#158]
http://mybinder.org/

See example:
http://mybinder.org/repo/binder-project/example-requirements

Could be something interesting to allow people to run the tutorials immediately, even without installing htmd. With https://github.com/binder-project/example-conda-environment, we can use an .yml file to express dependencies of the tutorials.

**Comment by stefdoerr** [comment]
That's really cool! Also a practical way of downloading the tutorials. Only problem is that some tutorials have dependencies on large datasets which we probably won't be able to have there.

**Comment by j3mdamas** [comment]
the tutorials download is already taken care of, with some html kung-fu ;)

yeah, you are right. I am guessing that this server won't allow downloads or running simulations.

Is there a way to save `MetricData` the same way we save `Model`? We could teach people how to do the projections and ship the projected data instead of the actual trajectories

**Comment by stefdoerr** [comment]
Um...yes https://www.htmd.org/docs/latest/htmd.metricdata.html?highlight=metricdata.save#htmd.metricdata.MetricData.save

**Comment by j3mdamas** [comment]
cool. I think in the future we can use this instead of full trajectories for tutorials. much more lightweight.

by the way, mybinder.org also has the problem of accepting a license from it.

**Comment by j3mdamas** [comment]
I'll test this and close it if it doesn't work
