### ISSUE TITLE
Command line parameterize ignores -n/--ncpus flag

### ISSUE THREAD

**Issue by GerardBCN** [Acellera/htmd#159]
Whatever value is passed to parameterize (e.g. parameterize -n 8) is ignored and the default of 12 cores is used...

**Comment by j3mdamas** [comment]
I had already noticed this, but I didn't have the time. I am fixing it.

**Comment by j3mdamas** [comment]
I have got a fix for it, but I am just figuring out something else, because this is going to be part of a clean-up on parameterize.

**Comment by j3mdamas** [comment]
Fixed here: 57f65e00fe6d702d24fbc4655f2d095ec66b73eb
Will be on the next release (1.5.2)
