### ISSUE TITLE
Adding patches charmm22*

### ISSUE THREAD

**Issue by PabloHNieto** [Acellera/htmd#160]
I'm trying to include phosphate patches (SP2, TP2 and THP2) with charmm22\* 
using:

topos = ["top/top_all22star_prot.rtf", 
           "top/top_all36_cgenff.rtf", 
           "top/top_all36_na.rtf",
           "top/top_water_ions.rtf"]

params = ['par/par_all22star_prot.prm',
            "par/par_all36_cgenff.prm", 
            "par/par_all36_na.prm",
            "par/par_water_ions.prm"]

strs = ['str/prot/toppar_all36_prot_arg0.str',
          "str/prot/toppar_all36_prot_na_combined.str"]

I can build the three systems, but when running the equilibration I get the following error messages
1) For serine (atoms highlighted in yellow in the picture)
```
# WARNING: illegal value: no bond parameters exist for ct2 ha2
# WARNING: illegal value: no bond parameters exist for ct2 ha2
# WARNING: illegal value: no angle parameters exist for ct1 ct2 ha2
# WARNING: illegal value: no angle parameters exist for ct1 ct2 ha2
# WARNING: illegal value: no angle parameters exist for ha2 ct2 ha2
```

2) For Threonine
```
# WARNING: illegal value: no bond parameters exist for ct1 ha1
# WARNING: illegal value: no angle parameters exist for ct1 ct1 ha1
# WARNING: illegal value: no angle parameters exist for ct3 ct1 ha1
```
And tyrosine-TP2 runs the equilibration without problem
Any idea of additional files to use?

![sp2](https://cloud.githubusercontent.com/assets/21107845/19640806/acf01894-99de-11e6-90d2-27c77d9392c0.png)

**Comment by j3mdamas** [comment]
I'll look into it.

**Comment by j3mdamas** [comment]
Sorry for the very late reply. So, it's "easy". Your problem arises from mixing CHARMM22* protein with the CHARMM36 patches. For serine, for example, you have:

In `top_all36_prot.rtf`:
```
RESI SER          0.00
GROUP   
ATOM N    NH1    -0.47  !     |       
ATOM HN   H       0.31  !  HN-N       
ATOM CA   CT1     0.07  !     |   HB1
ATOM HA   HB1     0.09  !     |   |  
GROUP                   !  HA-CA--CB--OG
ATOM CB   CT2     0.05  !     |   |     \
ATOM HB1  HA2     0.09  !     |   HB2    HG1
ATOM HB2  HA2     0.09  !   O=C           
ATOM OG   OH1    -0.66  !     |           
ATOM HG1  H       0.43
GROUP   
ATOM C    C       0.51
ATOM O    O      -0.51
```

In `top_all22star_prot.rtf`:
```
RESI SER          0.00
GROUP   
ATOM N    NH1    -0.47  !     |       
ATOM HN   H       0.31  !  HN-N       
ATOM CA   CT1     0.07  !     |   HB1
ATOM HA   HB      0.09  !     |   |  
GROUP                   !  HA-CA--CB--OG
ATOM CB   CT2     0.05  !     |   |     \
ATOM HB1  HA      0.09  !     |   HB2    HG1
ATOM HB2  HA      0.09  !   O=C           
ATOM OG   OH1    -0.66  !     |           
ATOM HG1  H       0.43
GROUP   
ATOM C    C       0.51
ATOM O    O      -0.51
```
As you can see, there is a difference in the atom typing for `HB1` and `HB2`: `HA2` in C36 and `HA` in C22*. Originally, serine in C22* is going to be `HA`, but when the patch is applied, it changes to `HA2` (as per C36 patching), which does not exist in C22* protein forcefield (namely the bonds, and angles).

As for the solution/answer, I think the mixing may be dangerous and may mean that mixing needs to be checked for every patch (even the one that is working). I would say that creating an `.str` file of your own for patching C22*, where you would replace the `HA2` in the patch for `HA`, should work in practice. And check every patch you want to use and put only those on the new `.str` file you create.

For me this solves it, so I am going to close it. If you need more help, let me know.

João
