### ISSUE TITLE
Adaptive Error

### ISSUE THREAD

**Issue by KendyP** [Acellera/htmd#161]
Hello, 
I had posted previously about having a tutorial for adaptive and was sent some example data for villin and a small python script to run. In the text file error.txt I have included the error, as well as the python script used. Simulations were generated and ran to completion, but there was an error with processing the data. Any help is greatly appreciated. Thank you.

Kendy
[error.txt](https://github.com/Acellera/htmd/files/551782/error.txt)

**Comment by stefdoerr** [comment]
AdaptiveRun is looking for your simulations in a folder called `./data` however you are writing all your simulations in the folder generators (which you should not. generators should be left untouched). So it complains that no simulations can be found.

Take a look at the [updated tutorial](https://www.htmd.org/docs/latest/tutorials/adaptive-sampling-example.html#how-to-start), it might help.

Try this:
```python
from htmd import *
from htmd.adaptive.adaptiverun import *

md = AdaptiveRun()
md.nmin=5
md.nmax=10
md.nepochs = 30
md.app = AcemdLocal(datadir='./data/')
md.project = MetricSelfDistance('protein and name CA')
md.ticadim = 3
md.updateperiod = 14400 # execute every 4 hours
md.run()
```
