### ISSUE TITLE
Adaptive error

### ISSUE THREAD

**Issue by KendyP** [Acellera/htmd#162]
Hello,
Utilizing the sample dataset for Villin, the following error was produced while running adaptive. Simulations were completed and filtered, but an error occurred concerning metricsel1. In error2.txt, you'll find the error, as well as the python script used to run adaptive. Any help is greatly appreciated. Thank you.

Kendy
[error2.txt](https://github.com/Acellera/htmd/files/553715/error2.txt)

**Comment by stefdoerr** [comment]
I apologize for not mentioning it before but use `AdaptiveMD` instead of `AdaptiveRun`. `AdaptiveRun` is deprecated. Here it's failing because you are using argument of `AdaptiveMD` in `AdaptiveRun`.
