### ISSUE TITLE
ACEMD syntax error on parameters generated with parameterize

### ISSUE THREAD

**Issue by GerardBCN** [Acellera/htmd#168]
The line in bold produces a syntax error in acemd:

```
#WARNING: syntax error in file "parameters", line number 385: syntax error in CHARMM bond
# failed to read parameter file
```

I suspect that underscore (_) is a forbidden character.

!Following lines added from mol.prm
C261   C261     305.00   1.3750
C261   HG61     340.00   1.0800
C261   CDC1     365.00   1.4500
C261   N311     330.00   1.4000
C261   HG62     340.00   1.0800
CDC1   C321     365.00   1.5020
C321   N301     263.00   1.4740
C321   HGA2     309.00   1.1110
N301   C263     340.00   1.3830
N301   C331     400.00   1.4560
C263   N311     340.00   1.3830
C263   O2D4     660.00   1.2340
N311   HPA1     447.80   1.0190
C331   HGA3     322.00   1.1110
**CDC1   C321_0   365.00   1.5020**
C321_0 N301     263.00   1.4740
C321_0 HGA2     309.00   1.1110
C321_0 N301_0   263.00   1.4740
N301_0 C263     340.00   1.3830
N301_0 C331     400.00   1.4560
N301_0 C331_0   400.00   1.4560
C331_0 HGA3     322.00   1.1110
C331_0 HGA3_0   322.00   1.1110

**Comment by j3mdamas** [comment]
Yes. I already fixed this on: c639b0f79285272c215e28a9b333b4d14f4bb829
It's going to be on the next release (maybe today).
If you want a quick fix, replace all `_` by `x`, for example, or pull the latest github version.

by the way, which version of acemd are you using? in the latest one, this shouldn't be a problem. use the acemd from conda.

**Comment by GerardBCN** [comment]
# ACEMD Molecular Dynamics Version [] (git [222fcc8])


2016-10-28 10:35 GMT+02:00 João M. Damas <notifications@github.com>:

**Comment by j3mdamas** [comment]
Should be this:

`# ACEMD Molecular Dynamics Version [2016.10.27] (git [992255])`

do: `conda update acemd -c acellera`
