### ISSUE TITLE
Warning "Got charge -1 Warning: 1 is an unknown parameter!" when using -c with negative charges

### ISSUE THREAD

**Issue by GerardBCN** [Acellera/htmd#169]
I don't know if there's really any way to solve this. It is purely aesthetics, but -1 should not be seen as a parameter flag in case of "-c -1"

**Comment by j3mdamas** [comment]
Yes, it's aesthetics. It's actually not a problem from the flag you pass to parameterize, but the flag passed to MATCH, which does the atom typing. I'll still try to fix it.

**Comment by mj-harvey** [comment]
@j3mdamas  did you fix this?

**Comment by j3mdamas** [comment]
I don't know how match can accept the -1 as an argument rather than a flag. I was testing match alone, without python's call, and I couldn't make it not issue the warning.

Plus, the -charge flag doesn't seem to be standard. Did you create it for our version of match?

**Comment by mj-harvey** [comment]
Yes, it is specific to our version. Ok, leave it with me.

**Comment by j3mdamas** [comment]
my perl isn't strong. I wasn't being able to escape the - in the -1 for it not to think it was a flag.
ok, i'll leave it with you then

**Comment by mj-harvey** [comment]
Fixed.

**Comment by j3mdamas** [comment]
@GerardBCN you have to do `conda update match -c acellera`
