### ISSUE TITLE
Support for triple bonds

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#17]
Hi all,

I was writing this as a parameterization issue but I thought this is rather general. 

There's a continuous problem on running simulations with ligands containing triple bonds. 
The parameters generated by parameterize crash usually straight away in an ACEMD simulation.
The parameters generated by cgenff aren't unable to run because ACEMD cannot index the topology file for these dihedrals in the parameter file. This is reproducible and occurs with any kind of molecule containing triple bonds. (C-C or C-N)

I have partially found the problem. So basically, dihedrals involving an angle of 180° like in triple bonds are mathematically undefined. As such, CHARMM does not require them to be present in the MD software, and the CGenFF program doesn't generate them accordingly. ACEMD or NAMD need all the topology atoms to be indexed in the parameter file, and then we always miss the dihedral of the triple bond, so the simulation doesnt run. The same applies to parameterize, as it relies on cgennff in first place.

The solution is basically writing manually the dihedral as the charmm MD engine would read it. Given the dihedral formula used in charmm:

V(dihedral) = Kchi(1 + cos(n(chi) - delta))
We need to put an amplitude Kchi = 0, multiplicity of n=  2 and delta = 180 degrees.

We might need to include an automatic way to parse triple bonds which are missing and write out this dihedral automatically.

Thanks,
Noelia

**Comment by mj-harvey** [comment]
Hi Noelia,


Are you currently working around this by adding in the missing parameters,
with zeroed values?

On 21 April 2016 at 15:15, giadefa <notifications@github.com> wrote:

> Assigned #17 <https://github.com/Acellera/htmd/issues/17> to @mj-harvey
> <https://github.com/mj-harvey>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Acellera/htmd/issues/17#event-636225704>
>



-- 
<https://www.acellera.com>


<https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>
    <https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/acellera>
<https://www.acellera.com/md-simulation-blog-news/>     [image:
skype:acellera] <http://is.gd/1eXkbS>

**Comment by noeliaferruz** [comment]
Hi Matt,

I have only had a molecule with a triple bond. But yes, I'm adding this lines manually. It is not actually working around it, it's what charmm does automatically.

Noelia

**Comment by giadefa** [comment]
This is a parametrize problem, triple bonds should be supported by it. Changing title.

**Comment by mj-harvey** [comment]
Match doesn't know how to type them. 
Where Match is inadequate to the task of typing a compound, it will be necessary to start a parameterisation with independently obtained parameters (eg from Paramchem). The next version of parameterise will make this possible.

**Comment by mj-harvey** [comment]
Closing this as it's a limitation of the cgen2b6 we have in parameterise. The alternatives -- starting with the new version of parameterise --  are to start with an independently obtained set of cgen3 parameters, or use gaff
