### ISSUE TITLE
HTMD Documentation update

### ISSUE THREAD

**Issue by mj-harvey** [Acellera/htmd#171]
1) Please change the download page https://www.htmd.org/academic-download.html to reference

the "latest" version of Miniconda from http://conda.pydata.org/miniconda.html -- 
https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh , etc --
rather than the specific old version

2) Omnia channel packages are now included in the acellera channel. Please remove reference to configuring the "omnia" channel.

**Comment by j3mdamas** [comment]
37cc03bf2c5593a5db9048d60af7573a40239ac2
done
will push just the corresponding static page to the server
