### ISSUE TITLE
Add Appveyor CI for true Windows build and testing

### ISSUE THREAD

**Issue by mj-harvey** [Acellera/htmd#174]
Right now our Windows build isn't tested at all, we cut a release from a successful linux build and hope for the best. Travis does have native windows support, we have to use a different CI, Appveyor, for that.

**Comment by j3mdamas** [comment]
What do you need?

**Comment by mj-harvey** [comment]
Alternative: Stay with travis and run under wine (I think I prefer this option)

**Comment by mj-harvey** [comment]
Scratch that, Miniconda doesn't install under Wine within a Travis env.

**Comment by stefdoerr** [comment]
It would be really like REALLY nice if people could have direct access to a
single Travis machine for testing this crap without making whole releases
no? Or it exists and I don't know?
