### ISSUE TITLE
Getting one representative structure of a macrostate

### ISSUE THREAD

**Issue by driesvr** [Acellera/htmd#175]
Hi everyone,

I'm looking to get a single representative structure for a macrostate. I could do this with 
`model.viewStates(numsamples=1)`, but if I read the code correctly this grabs a more or less random sample (depending on the samplemode) from the macrostate? Is there a straightforward manner to do this, or should I just get the frames corresponding to the macrostate and then get a cluster center for that?

Thanks,

Dries

**Comment by stefdoerr** [comment]
Hm, getting the single most representative structure is not trivial.
Practically you can only get the most representative microstate of a macrostate. You cannot assign "representativeness" to the conformations themselves unless you want to do some density clustering inside the microstate or calculate the median conformation (which is possible).

```python
idx = np.argmax(model.msm.metastable_distributions[4, :])
mol = model.getStates(idx, statetype='micro')
```

This should give you random conformations from the microstate which is most representative of macrostate number 4.

**Comment by driesvr** [comment]
Hi Stefan,
Thanks for the reply, that sounds like a good alternative. However, for 4 out of 5 macrostates, this returns the same microstate index.

**Comment by stefdoerr** [comment]
ah okay I see. So there is a microstate which is spread all over your macrostates with a high probability. Could possibly be the bulk state.

To avoid that you can use the metastable_assignments and only get the distributions for the microstates which were hard-assigned to each macrostate.

```python
microsofmacro4 = np.where(model.msm.metastable_assignments == 4)[0]
idx = np.argmax(model.msm.metastable_distributions[4, microsofmacro4])
mol = model.getStates(microsofmacro4[idx], statetype='micro')
```
I think this should work (untested code warning :P )

**Comment by driesvr** [comment]
It was indeed a microstate representative of the bulk state! That code works like a charm, I just had to turn `microsocmacro4[idx] `into a list to get it to work:
```
microsofmacro4 = np.where(model.msm.metastable_assignments == 1)[0]
idx = np.argmax(model.msm.metastable_distributions[4, microsofmacro4])
mol = model.getStates([microsofmacro4[idx]], statetype='micro')  
```

Thanks for the help :)

**Comment by stefdoerr** [comment]
Great! You are welcome :)
