### ISSUE TITLE
code coloring css on documentation

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#176]

**Comment by stefdoerr** [comment]
Hm I have a feeling that the issue here is that the notebooks have not been executed. They are missing the outputs of the commands as well. I added a temporary fix but I think the problem is elsewhere.

**Comment by stefdoerr** [comment]
```
[sdoerr@loro doc]$ make publish
ssh www.acellera.com 'rm -rf ~/www.htmd.org/docs/latest/*'
Enter passphrase for key '/home/sdoerr/.ssh/id_rsa':
rm: cannot remove `/home/sdoerr/www.htmd.org/docs/latest/*': Permission denied
make: *** [publish] Error 1
```

Hm I can't publish docs anymore...

**Comment by j3mdamas** [comment]
Stefan, don't publish docs of non release versions.
Matt has to give you back permissions.
What do you mean by executed notebooks? Executed cells? Some were and
looked the same.

On Nov 4, 2016 11:19 PM, "Stefan Doerr" <notifications@github.com> wrote:

[sdoerr@loro doc]$ make publish
ssh www.acellera.com 'rm -rf ~/www.htmd.org/docs/latest/*'
Enter passphrase for key '/home/sdoerr/.ssh/id_rsa':
rm: cannot remove `/home/sdoerr/www.htmd.org/docs/latest/*': Permission denied
make: *** [publish] Error 1

Hm I can't publish docs anymore...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Acellera/htmd/issues/176#issuecomment-258561757>, or mute
the thread

**Comment by stefdoerr** [comment]
Yeah, cells should be executed manually beforehand otherwise it only prints the code without the results.
I.e. this one: https://www.htmd.org/docs/latest/tutorials/system-building-protein-ligand.html

Also, changing the css is not gonna change the docs that much :P Also since we'll make a new release in the next days.

**Comment by j3mdamas** [comment]
I just don't think it's a good principle, because it will have the devel
changes since last release, and then the doc won't match the conda release.
But in this particular case it's alright.

**Comment by mj-harvey** [comment]
@stefdoerr can publish again now
