### ISSUE TITLE
Learn/Applications tutorials refactoring

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#177]
Forgot to create this issue, which was just on my notebook. Will fill up information ASAP

**Comment by j3mdamas** [comment]
What is already done is the moving of non-tutorials tutorials to documentation: f85957ffa646cf58411b5bc3df82b9e1a67e8899 5b4371b09374f288101f9057e464f175e27cbd33

**Comment by giadefa** [comment]
Consider API, User Guide and tutorials

**Comment by giadefa** [comment]
Do this 
https://github.com/Acellera/htmd/issues/27

**Comment by giadefa** [comment]
Tutorial on parameterization
