### ISSUE TITLE
Amber.build generated structure.pdb doesn't include the predefined segid field

### ISSUE THREAD

**Issue by GerardBCN** [Acellera/htmd#180]
I guess is because of the way you load the .crd ontop of the .prmtop. I think is useful to keep segids fields in case one needs to apply specific restrains (for example on the crystal waters) and also for consistency with charmm.build.

**Comment by stefdoerr** [comment]
tleap throws away segid's. nothing to be done.

**Comment by j3mdamas** [comment]
You have to find another way to set those restrains gerard.
