### ISSUE TITLE
queues: dont use module pwd

### ISSUE THREAD

**Issue by mj-harvey** [Acellera/htmd#182]
In queues/slurm.py
This module isn't portable to Windows
For now I have changed it to a deferred import
@j3mdamas

**Comment by mj-harvey** [comment]
not an urgent fix

**Comment by stefdoerr** [comment]
Replaced with [getpass.getuser()](https://docs.python.org/3.6/library/getpass.html#getpass.getuser) which supposedly works on all 3 platforms.
