### ISSUE TITLE
ITS save plot

### ISSUE THREAD

**Issue by PabloHNieto** [Acellera/htmd#183]
would it be possible to include an option for model.plotTimescales to save the plot?
so far I've using the following:
def plotTimescales(... , outfile=None):
...
if outfile is not None:
            from matplotlib import pylab as plt
            plt.ioff()
            plt.figure()
            mplt.plot_implied_timescales(its, dt=self.data.fstep, units='ns')
            plt.savefig(outfile)
...

**Comment by j3mdamas** [comment]
yeah, I guess so. Let's see when there is more free time

**Comment by stefdoerr** [comment]
https://github.com/Acellera/htmd/commit/350776a203ce11ad7c8fdcf33a310d9053c2c330

Done
