### ISSUE TITLE
Diffuse functions in parameterize

### ISSUE THREAD

**Issue by katkovs** [Acellera/htmd#189]
Is there a way to add diffuse functions in the basis sets used for the QM calculations in parameterize (i.e. 6-31+G* and aug-cc-pVDZ)? This might be important when dealing with anions.

**Comment by j3mdamas** [comment]
When the molecule is an anion, diffuse functions get turned on. Right @mj-harvey?

**Comment by katkovs** [comment]
Thanks for the reply. I've so far tried only one anionic molecule, and, with parameterize version 1.5.1 I get 6-31+G* in the gaussian input files, while with version 1.5.4 I get 6-31G*. Maybe the automatic turning on of the diffuse function got broken on the way? Or is there now a special flag for this?

**Comment by j3mdamas** [comment]
You are right. I looked into the code, and for Gaussian (not for psi4 or Terachem), the diffuse functions are commented out. There should be a reason for that, and @mj-harvey should have an answer for that.

**Comment by j3mdamas** [comment]
You are right. I looked into the code, and for Gaussian (not for psi4 or Terachem), the diffuse functions are commented out. There should be a reason for that, and @mj-harvey should have an answer for that.

**Comment by mj-harvey** [comment]
Hi,

If you parameterise in vacuum (--vacuum), a diffuse basis set is automatically used.
If you parameterise with solvent (the default), it shouldn't be necessary to use a diffuse basis.

**Comment by j3mdamas** [comment]
@mj-harvey: the diffuse basis set seem to be commented out for gaussian:
https://github.com/Acellera/htmd/blob/master/htmd/qm/qmcalculation.py#L762-L771

or am I missing something?

**Comment by mj-harvey** [comment]
that's a bug, it should should match the logic of the psi4 and terachem pathways -- "
charge < 0 && !solvent". Could you fix it please?

**Comment by j3mdamas** [comment]
sure. done in a22590242081f8492fff680432848150dd2281f3
