### ISSUE TITLE
total population not 1

### ISSUE THREAD

**Issue by PabloHNieto** [Acellera/htmd#195]
after creating some models (5 iterations with all the data, no bootstrap, for two differente ligands) I have summed the population of each macrostate by doing

np.sum(model.eqDistribution(plot=False)

and got these results:

Molname	FPop(mean)	FPop-std	
E_TRI	0.38	                   0.34
YP_TRI	1.0	                    0.0	

So, for YP_TRI i got the right result (100% population in all iterations) but not for E_TRI.

**Comment by stefdoerr** [comment]
https://github.com/markovmodel/PyEMMA/issues/996
Made an issue here.

**Comment by j3mdamas** [comment]
Since it depends on PyEMMA, there's nothing we can do but bump this into 1.8.0.

**Comment by j3mdamas** [comment]
There has been some updates on the pyemma issue, @stefdoerr will look at it when he's back
