### ISSUE TITLE
pyemma problem after htmd update

### ISSUE THREAD

**Issue by slovera** [Acellera/htmd#199]
After updating htmd to the last version (1.5.4) on my workstation (SUSE 11) I am experiencing problems in performing the analyses:
e.g. model.plotTimescales() gives me the attached error.
[error.txt](https://github.com/Acellera/htmd/files/627391/error.txt)
It seems to be correlated to pyemma. I have tried to update pyemma but the error persists.

Any advice?

Thank you!

**Comment by stefdoerr** [comment]
Try `conda update thermotools`

**Comment by slovera** [comment]
It works thank you.
Is there any reason why it hasn't updated it automatically as usual?

**Comment by stefdoerr** [comment]
No idea :/ Should have to do with pyemma conda dependencies

**Comment by stefdoerr** [comment]
@marscher maybe some ideas?

**Comment by marscher** [comment]
The default setting of the update option "--update-dependencies" of conda is True, but it does not always seem to do what one would expect...

**Comment by stefdoerr** [comment]
Yeah had similar experience with it :/

**Comment by mj-harvey** [comment]
I recommend routinely updating with  "conda update --all -y"

**Comment by marscher** [comment]
@slovera which version of conda do you have? There are claims in the conda repository, that this issues have been addressed in version 4.x

**Comment by slovera** [comment]
I have conda 4.2.13

**Comment by mj-harvey** [comment]
@slovera, are you also subscribed to the omnia channel or only the acellera one? (I recommend only subbing to the acellera one, that contains all the necessary dependencies)

**Comment by slovera** [comment]
Yes, I have omnia. Thanks for the suggestion!
