### ISSUE TITLE
getting pkas for residues

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#2]
Hello guys,

I am not sure how to use the propka implementation. Following the tutorial I tried:

```
system = Molecule('4xv1_prep.pdb')
pkas = pka(system , pH=6.5 )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'pka' is not defined
```
So then I tried:

```
from htmd.molecule.pka import pka as pka
>>> pkas = pka(system, pH=6.5 )


During handling of the above exception, another exception occurred:

T
NameError: Failed to execute PropKa

```

I am using the pfizer version: You are on the latest HTMD version (0.1.32).

Any help is appreciated.

**Comment by mj-harvey** [comment]
You probably need to get the propka Fonda package updated.

**Comment by giadefa** [comment]
i can replicate the error

**Comment by tonigi** [comment]
For now please use the proteinPreparation with `returnDetails=True`, you'll get pkas . Eventually there will be a separate function.

**Comment by giadefa** [comment]
@tonigi what's the status?

**Comment by tonigi** [comment]
committed a prototype stand-alone function but propka seems to needs proper atom name alignments

**Comment by stefdoerr** [comment]
I fixed the atom name alignments. I am going to push it now

**Comment by stefdoerr** [comment]
Done. Now you can pull and test the atom name alignments.

**Comment by j3mdamas** [comment]
Atom name alignments solved in multiscalelab/htmd#20

**Comment by tonigi** [comment]
Should work as soon as 7bf7b04789f5f1fb9e2d9c72698d9cb96446ed33 is merged.

**Comment by j3mdamas** [comment]
So, @tonigi, we should test this or since you merged it, it is already well tested?

**Comment by tonigi** [comment]
Reasonably tested. I'd close the issue and open new ones if specific cases arise.

**Comment by j3mdamas** [comment]
Maybe close it after @noeliaferruz is able to run her case with the new version? Idk when we do a new release, maybe at next dev meeting.

**Comment by tonigi** [comment]
i can't close issues here

**Comment by j3mdamas** [comment]
i will close it after she tests it.

**Comment by noeliaferruz** [comment]
Hi guys!

I open a console using version (1.0.16).
Then replicate the commands I wrote in the first comment and got the same exact error. I guess I should use this feature through ProteinPreparation, right?

Please let me know if I should be using a different version/ commands.

Thanks all,
Noelia

**Comment by j3mdamas** [comment]
Version 1.0.16 does not have the new pKa Toni implemented. You'd have to download the multiscalelab/htmd fork in order to do it. Or wait until we release a new version. Maybe next week.

**Comment by noeliaferruz** [comment]
Hi, I updated my local conda htmd version, and since the versions are the same -compared to the other global conda we have here-, I'll wait until next release. 

Thanks

**Comment by giadefa** [comment]
solved
