### ISSUE TITLE
Running AdaptiveGoal simulations using Gromacs

### ISSUE THREAD

**Issue by BIORAK** [Acellera/htmd#202]
@stefdoerr @j3mdamas 
Hi, I have some doubts which occurred to me when I was running the AdaptiveGoal simulations.

I have a protein with two conformations one with a Mg bound and another without. So I want to know if I can use AdaptiveGoal class to sample conformations between unbound to bound structures. Since the ligand is not present in the site in the unbound conformation, can AdaptiveGoal be still used. If it can be used then is the following code correct.

```python
from htmd import *

ref = Molecule('/home/rakesh/adaptive/reference_open.pdb')
def mygoalfunction(mol):
    rmsd = MetricRmsd(ref, 'name CA and resid 1787 to 1803').project(mol)
    return 1/rmsd # or even 1/rmsd

lq = LocalGPUQueue()
lq.datadir = './data/'
lq.ngpu = 2
ad = AdaptiveGoal()
ad.app = lq
ad.inputpath = '/home/rakesh/adaptive/input'
ad.nmin = 1
ad.nmax = 8
ad.nepochs = 2
ad.projection = MetricDihedral(protsel='protein and resid 1787 to 1803')
ad.goalfunction = mygoalfunction
ad.updateperiod = 144000
ad.run()
```
Since the mygoalfunction is used is the  ad.projection line still it required. Moreover what is the value of 'mol' or the structure  which is passed to the function ? What are the conformers from epoch1 which is passed onto second epoch and where is it stored so that I can visualize all conformers generated in first epoch ?

How do I select the duration of each simulation, in your ligand binding paper you state to use it according to implied timescale, how would I get the duration for my case since I have initial simulations five replicates which are 200ns long ?

I am using a rhombic dodecahedron during my simulations, so does the htmd.adaptive class take into consideration the appropriate unit cell representation to avoid PBC issues while using Gromacs. How can I also get the macrostates which are sampled after the MSM is generated ?

**Comment by j3mdamas** [comment]
Many questions.

1. So, do you use the Mg or not? Does the ligand binding depend on the Mg? Is it multi-factor binding? Maybe you should look into this paper: http://www.nature.com/articles/srep30275
1. About the syntax, I think that Stefan can help you better with it.
1. ad.projection is still required. the goal functions is just part of the adaptivegoal algorithm.
1. the `mol` passed to the function is the trajectory generated
1. the logic of epoch generation is explained here: https://www.htmd.org/docs/latest/tutorials/adaptive-sampling-basics.html
> Adaptive uses a naming scheme for simulations which follows the pattern: e4s3_e2s1p1f45. This name tells us that this simulation was generated in epoch 4 as the 3rd simulation of the batch. The starting conformation was taken from simulation 1 of epoch 2 from the first piece of the simulation* and from frame 45 of that simulation piece.
1. The ideal simulation length can be estimated if you already have some idea of how slow the process is (timescale). In general, you don't know this value and actually want to obtain it, so you have to go with some guessing.
1. About the box, I think that our wrap is ready for non-cubic boxes. @mj-harvey, can you give your input here?
1. You can do the analysis on the trajectories yourself, without the need of the adaptive code.

**Comment by j3mdamas** [comment]
What's the status on this issue? Can I close it?

**Comment by stefdoerr** [comment]
@BIORAK anything else you want from here? Can we close?

**Comment by BIORAK** [comment]
Hi,
      So I was able to run the simulation but in the folders after first epoch the input pdb file is empty without coordinates https://github.com/BIORAK/GROMACSAdaptiveMD/blob/master/e2s2_e1s2p0f105.tar.gz 

This is causing the input from first epoch not to be used for simulations in second epoch. I have provided a zipped example folder after first epoch.

**Comment by stefdoerr** [comment]
Adaptive in HTMD does not touch any PDB files. It simply copies them from the original folders. Check if the generator `closed1` actually has a PDB with data in it. It would surprise me a lot.

**Comment by stefdoerr** [comment]
Ah I probably understand what you did. Did you set `adaptive.coorfile = 'input.pdb'`?
That will not work. It needs to be a coordinate file format. PDB also contains atom information which we don't read.
As I said in this response https://github.com/Acellera/htmd/issues/173#issuecomment-261239035 it should be `input.gro`

**Comment by BIORAK** [comment]
Hi,

  I am getting the following error after first epoch run is finished.

2017-02-15 20:35:27,164 - htmd.adaptive.adaptive - INFO - Retrieving simulations.
2017-02-15 20:35:27,164 - htmd.adaptive.adaptive - INFO - 0 simulations in progress
2017-02-15 20:35:27,164 - htmd.adaptive.adaptivegoal - INFO - Postprocessing new data
Creating simlist: 100% (4/4) [###################################################################################################################################################################################################] eta 00:01 -
[Parallel(n_jobs=-2)]: Done   1 tasks      | elapsed:    3.0s
[Parallel(n_jobs=-2)]: Done   5 out of   4 | elapsed:    3.0s remaining:   -0.6s
[Parallel(n_jobs=-2)]: Done   5 out of   4 | elapsed:    3.1s remaining:   -0.6s
[Parallel(n_jobs=-2)]: Done   5 out of   4 | elapsed:    3.2s remaining:   -0.6s
[Parallel(n_jobs=-2)]: Done   4 out of   4 | elapsed:    3.2s finished
Projecting trajectories: 100% (4/4) [############################################################################################################################################################################################] eta 00:01 |
2017-02-15 20:35:33,289 - htmd.projections.metric - WARNING - Error in simulation with id: 2. "Trajectory # of atoms 0 mismatch with # of already loaded atoms 3952"
2017-02-15 20:35:33,337 - htmd.projections.metric - WARNING - Error in simulation with id: 3. "Trajectory # of atoms 0 mismatch with # of already loaded atoms 3952"
2017-02-15 20:35:33,701 - htmd.projections.metric - WARNING - Multiple framesteps were read from the simulations. Taking the statistical mode: 5e-06ns. If it looks wrong, you can modify it by manually setting the MetricData.fstep property.
2017-02-15 20:35:33,702 - htmd.metricdata - INFO - Dropped 0 trajectories from 2 resulting in 2
2017-02-15 20:35:33,935 - htmd.metricdata - INFO - Dropped 0 trajectories from 2 resulting in 2
2017-02-15 20:35:35,554 - htmd.model - INFO - 97.8% of the data was used
2017-02-15 20:35:35,555 - htmd.model - INFO - Number of trajectories that visited each macrostate:
2017-02-15 20:35:35,555 - htmd.model - INFO - [2 2 2 2 2 2 2 2]
2017-02-15 20:35:35,556 - htmd.model - INFO - Take care! Macro 0 has been visited only in 2 trajectories:
2017-02-15 20:35:35,556 - htmd.model - INFO - simid = 0
parent = 0
input = None
trajectory = ['filtered/e1s1_closed1/md.filtered.xtc']
molfile = filtered/filtered.pdb
2017-02-15 20:35:35,556 - htmd.model - INFO - simid = 1
parent = 1
input = None
trajectory = ['filtered/e1s2_closed2/md.filtered.xtc']
molfile = filtered/filtered.pdb
2017-02-15 20:35:35,556 - htmd.model - INFO - Take care! Macro 1 has been visited only in 2 trajectories:
2017-02-15 20:35:35,556 - htmd.model - INFO - simid = 0
parent = 0
input = None
trajectory = ['filtered/e1s1_closed1/md.filtered.xtc']
molfile = filtered/filtered.pdb
2017-02-15 20:35:35,556 - htmd.model - INFO - simid = 1
parent = 1
input = None
trajectory = ['filtered/e1s2_closed2/md.filtered.xtc']
molfile = filtered/filtered.pdb
2017-02-15 20:35:35,556 - htmd.model - INFO - Take care! Macro 2 has been visited only in 2 trajectories:
2017-02-15 20:35:35,556 - htmd.model - INFO - simid = 0
parent = 0
input = None
trajectory = ['filtered/e1s1_closed1/md.filtered.xtc']
molfile = filtered/filtered.pdb
2017-02-15 20:35:35,556 - htmd.model - INFO - simid = 1
parent = 1
input = None
trajectory = ['filtered/e1s2_closed2/md.filtered.xtc']
molfile = filtered/filtered.pdb
2017-02-15 20:35:35,557 - htmd.model - INFO - Take care! Macro 3 has been visited only in 2 trajectories:
2017-02-15 20:35:35,557 - htmd.model - INFO - simid = 0
parent = 0
input = None
trajectory = ['filtered/e1s1_closed1/md.filtered.xtc']
molfile = filtered/filtered.pdb
2017-02-15 20:35:35,557 - htmd.model - INFO - simid = 1
parent = 1
input = None
trajectory = ['filtered/e1s2_closed2/md.filtered.xtc']
molfile = filtered/filtered.pdb
2017-02-15 20:35:35,557 - htmd.model - INFO - Take care! Macro 4 has been visited only in 2 trajectories:
2017-02-15 20:35:35,557 - htmd.model - INFO - simid = 0
parent = 0
input = None
trajectory = ['filtered/e1s1_closed1/md.filtered.xtc']
molfile = filtered/filtered.pdb
2017-02-15 20:35:35,557 - htmd.model - INFO - simid = 1
parent = 1
input = None
trajectory = ['filtered/e1s2_closed2/md.filtered.xtc']
molfile = filtered/filtered.pdb
2017-02-15 20:35:35,557 - htmd.model - INFO - Take care! Macro 5 has been visited only in 2 trajectories:
2017-02-15 20:35:35,557 - htmd.model - INFO - simid = 0
parent = 0
input = None
trajectory = ['filtered/e1s1_closed1/md.filtered.xtc']
molfile = filtered/filtered.pdb
2017-02-15 20:35:35,557 - htmd.model - INFO - simid = 1
parent = 1
input = None
trajectory = ['filtered/e1s2_closed2/md.filtered.xtc']
molfile = filtered/filtered.pdb
2017-02-15 20:35:35,557 - htmd.model - INFO - Take care! Macro 6 has been visited only in 2 trajectories:
2017-02-15 20:35:35,558 - htmd.model - INFO - simid = 0
parent = 0
input = None
trajectory = ['filtered/e1s1_closed1/md.filtered.xtc']
molfile = filtered/filtered.pdb
2017-02-15 20:35:35,558 - htmd.model - INFO - simid = 1
parent = 1
input = None
trajectory = ['filtered/e1s2_closed2/md.filtered.xtc']
molfile = filtered/filtered.pdb
2017-02-15 20:35:35,558 - htmd.model - INFO - Take care! Macro 7 has been visited only in 2 trajectories:
2017-02-15 20:35:35,558 - htmd.model - INFO - simid = 0
parent = 0
input = None
trajectory = ['filtered/e1s1_closed1/md.filtered.xtc']
molfile = filtered/filtered.pdb
2017-02-15 20:35:35,558 - htmd.model - INFO - simid = 1
parent = 1
input = None
trajectory = ['filtered/e1s2_closed2/md.filtered.xtc']
molfile = filtered/filtered.pdb
[Parallel(n_jobs=-2)]: Done   3 out of   2 | elapsed:    1.6s remaining:   -0.5s
[Parallel(n_jobs=-2)]: Done   2 out of   2 | elapsed:    1.6s finished
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/htmd/molecule/molecule.py", line 1117, in write
    traj = md.load(tmpxtc.name, top=tmppdb.name)
  File "/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/mdtraj/core/trajectory.py", line 372, in load
    kwargs["top"] = _parse_topology(kwargs["top"], **topkwargs)
  File "/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/mdtraj/core/trajectory.py", line 169, in _parse_topology
    _traj = load_frame(top, 0, **kwargs)
  File "/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/mdtraj/core/trajectory.py", line 311, in load_frame
    return loader(filename, frame=index, **kwargs)
  File "/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/mdtraj/formats/pdb/pdbfile.py", line 156, in load_pdb
    coords = f.positions[[frame], atom_slice, :]
IndexError: too many indices for array

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/joblib/parallel.py", line 130, in __call__
    return self.func(*args, **kwargs)
  File "/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/joblib/parallel.py", line 72, in <listcomp>
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/htmd/adaptive/adaptive.py", line 206, in _writeInputsFunction
    mol.write(path.join(newDir, coorname))
  File "/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/htmd/molecule/molecule.py", line 1123, in write
    raise ValueError("Unknown file type")
ValueError: Unknown file type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rakesh/Softwares/miniconda3/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/joblib/parallel.py", line 140, in __call__
    raise TransportableException(text, e_type)
joblib.my_exceptions.TransportableException: TransportableException
___________________________________________________________________________
ValueError                                         Wed Feb 15 20:35:39 2017
PID: 39326       Python 3.5.2: /home/rakesh/Softwares/miniconda3/bin/python
...........................................................................
/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/joblib/parallel.py in __call__(self=<joblib.parallel.BatchedCalls object>)
     67     def __init__(self, iterator_slice):
     68         self.items = list(iterator_slice)
     69         self._size = len(self.items)
     70 
     71     def __call__(self):
---> 72         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        self.items = [(<function _writeInputsFunction>, (0, sim = simid = 0
parent = 0
input = None
trajecto...ile = filtered/filtered.pdb
piece = 0
frame = 183, 2, '/home/rakesh/adaptive/input', 'input.gro'), {})]
     73 
     74     def __len__(self):
     75         return self._size
     76 

...........................................................................
/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/joblib/parallel.py in <listcomp>(.0=<list_iterator object>)
     67     def __init__(self, iterator_slice):
     68         self.items = list(iterator_slice)
     69         self._size = len(self.items)
     70 
     71     def __call__(self):
---> 72         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        func = <function _writeInputsFunction>
        args = (0, sim = simid = 0
parent = 0
input = None
trajecto...ile = filtered/filtered.pdb
piece = 0
frame = 183, 2, '/home/rakesh/adaptive/input', 'input.gro')
        kwargs = {}
     73 
     74     def __len__(self):
     75         return self._size
     76 

...........................................................................
/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/htmd/adaptive/adaptive.py in _writeInputsFunction(i=0, f=sim = simid = 0
parent = 0
input = None
trajecto...ile = filtered/filtered.pdb
piece = 0
frame = 183, epoch=2, inputpath='/home/rakesh/adaptive/input', coorname='input.gro')
    201     copytree(currSim.input, newDir, symlinks=False, ignore=ignore_patterns('*.coor', '*.rst', '*.out', *_IGNORE_EXTENSIONS))
    202     # overwrite input file with new one. frameNum + 1 as catdcd does 1 based indexing
    203     mol = Molecule()
    204     mol.read(traj)
    205     mol.frame = frameNum
--> 206     mol.write(path.join(newDir, coorname))
        mol.write = <bound method Molecule.write of <htmd.molecule.m... shape: (201,)
time shape: (201,)
viewname: None>
        newDir = '/home/rakesh/adaptive/input/e2s1_e1s1p0f183/'
        coorname = 'input.gro'
    207 
    208 
    209 class Adaptive(object):
    210 

...........................................................................
/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/htmd/molecule/molecule.py in write(self=<htmd.molecule.molecule.Molecule object at 0x7f9...p shape: (201,)
time shape: (201,)
viewname: None, filename='/home/rakesh/adaptive/input/e2s1_e1s1p0f183/input.gro', sel=None, type=None)
   1118                 # traj.xyz = np.swapaxes(np.swapaxes(self.coords, 1, 2), 0, 1) / 10
   1119                 # traj.time = self.time
   1120                 # traj.unitcell_lengths = self.box.T / 10
   1121                 traj.save(filename)
   1122             except:
-> 1123                 raise ValueError("Unknown file type")
   1124 
   1125     def empty(self, numAtoms):
   1126         """ Creates an empty molecule of N atoms.
   1127 

ValueError: Unknown file type
___________________________________________________________________________
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/joblib/parallel.py", line 727, in retrieve
    self._output.extend(job.get())
  File "/home/rakesh/Softwares/miniconda3/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
joblib.my_exceptions.TransportableException: TransportableException
___________________________________________________________________________
ValueError                                         Wed Feb 15 20:35:39 2017
PID: 39326       Python 3.5.2: /home/rakesh/Softwares/miniconda3/bin/python
...........................................................................
/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/joblib/parallel.py in __call__(self=<joblib.parallel.BatchedCalls object>)
     67     def __init__(self, iterator_slice):
     68         self.items = list(iterator_slice)
     69         self._size = len(self.items)
     70 
     71     def __call__(self):
---> 72         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        self.items = [(<function _writeInputsFunction>, (0, sim = simid = 0
parent = 0
input = None
trajecto...ile = filtered/filtered.pdb
piece = 0
frame = 183, 2, '/home/rakesh/adaptive/input', 'input.gro'), {})]
     73 
     74     def __len__(self):
     75         return self._size
     76 

...........................................................................
/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/joblib/parallel.py in <listcomp>(.0=<list_iterator object>)
     67     def __init__(self, iterator_slice):
     68         self.items = list(iterator_slice)
     69         self._size = len(self.items)
     70 
     71     def __call__(self):
---> 72         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        func = <function _writeInputsFunction>
        args = (0, sim = simid = 0
parent = 0
input = None
trajecto...ile = filtered/filtered.pdb
piece = 0
frame = 183, 2, '/home/rakesh/adaptive/input', 'input.gro')
        kwargs = {}
     73 
     74     def __len__(self):
     75         return self._size
     76 

...........................................................................
/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/htmd/adaptive/adaptive.py in _writeInputsFunction(i=0, f=sim = simid = 0
parent = 0
input = None
trajecto...ile = filtered/filtered.pdb
piece = 0
frame = 183, epoch=2, inputpath='/home/rakesh/adaptive/input', coorname='input.gro')
    201     copytree(currSim.input, newDir, symlinks=False, ignore=ignore_patterns('*.coor', '*.rst', '*.out', *_IGNORE_EXTENSIONS))
    202     # overwrite input file with new one. frameNum + 1 as catdcd does 1 based indexing
    203     mol = Molecule()
    204     mol.read(traj)
    205     mol.frame = frameNum
--> 206     mol.write(path.join(newDir, coorname))
        mol.write = <bound method Molecule.write of <htmd.molecule.m... shape: (201,)
time shape: (201,)
viewname: None>
        newDir = '/home/rakesh/adaptive/input/e2s1_e1s1p0f183/'
        coorname = 'input.gro'
    207 
    208 
    209 class Adaptive(object):
    210 

...........................................................................
/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/htmd/molecule/molecule.py in write(self=<htmd.molecule.molecule.Molecule object at 0x7f9...p shape: (201,)
time shape: (201,)
viewname: None, filename='/home/rakesh/adaptive/input/e2s1_e1s1p0f183/input.gro', sel=None, type=None)
   1118                 # traj.xyz = np.swapaxes(np.swapaxes(self.coords, 1, 2), 0, 1) / 10
   1119                 # traj.time = self.time
   1120                 # traj.unitcell_lengths = self.box.T / 10
   1121                 traj.save(filename)
   1122             except:
-> 1123                 raise ValueError("Unknown file type")
   1124 
   1125     def empty(self, numAtoms):
   1126         """ Creates an empty molecule of N atoms.
   1127 

ValueError: Unknown file type
___________________________________________________________________________

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "adaptive.py", line 22, in <module>
    ad.run()
  File "/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/htmd/adaptive/adaptive.py", line 80, in run
    self._algorithm()
  File "/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/htmd/adaptive/adaptivegoal.py", line 206, in _algorithm
    self._writeInputs(datadr.rel2sim(np.concatenate(relFrames)))
  File "/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/htmd/adaptive/adaptive.py", line 172, in _writeInputs
    delayed(_writeInputsFunction)(i, f, epoch, self.inputpath, self.coorname) for i, f in enumerate(simsframes))
  File "/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/joblib/parallel.py", line 810, in __call__
    self.retrieve()
  File "/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/joblib/parallel.py", line 757, in retrieve
    raise exception
joblib.my_exceptions.JoblibValueError: JoblibValueError
___________________________________________________________________________
Multiprocessing exception:
...........................................................................
/home/rakesh/adaptive/adaptive.py in <module>()
     17 ad.nmax = 4
     18 ad.nepochs = 4
     19 ad.projection = MetricRmsd(ref, 'name CA and resid 1787 to 1803')
     20 ad.goalfunction = mygoalfunction
     21 ad.updateperiod = 6000
---> 22 ad.run()
     23 
     24 
     25 
     26 

...........................................................................
/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/htmd/adaptive/adaptive.py in run(self=<htmd.adaptive.adaptivegoal.AdaptiveGoal object>)
     75 
     76                 self._running = self.app.inprogress()
     77                 logger.info(str(self._running) + ' simulations in progress')
     78 
     79                 if self._running <= self.nmin:
---> 80                     self._algorithm()
        self._algorithm = <bound method AdaptiveGoal._algorithm of <htmd.adaptive.adaptivegoal.AdaptiveGoal object>>
     81                     if not self.dryrun:
     82                         self.app.submit(natsorted(glob(path.join(self.inputpath, 'e' + str(epoch+1) + 's*'))))
     83                         logger.info('Finished submitting simulations.')
     84 

...........................................................................
/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/htmd/adaptive/adaptivegoal.py in _algorithm(self=<htmd.adaptive.adaptivegoal.AdaptiveGoal object>)
    201 
    202         reward = dc + self.ucscale * uc
    203 
    204         if not self.nosampledc:
    205             relFrames = self._getSpawnFrames(reward, self._model, datadr)
--> 206             self._writeInputs(datadr.rel2sim(np.concatenate(relFrames)))
        self._writeInputs = <bound method AdaptiveBase._writeInputs of <htmd.adaptive.adaptivegoal.AdaptiveGoal object>>
        datadr.rel2sim = <bound method MetricData.rel2sim of <htmd.metricdata.MetricData object>>
        relFrames = [array([[  0, 183]]), array([[  0, 155]]), array([[  1, 178]]), array([[ 1, 91]])]
    207         else:
    208             print('Spawning only from top DC conformations without sampling')
    209             sortedabs = np.argsort(dc_conf)[::-1]
    210             self._writeInputs(datadr.abs2sim(sortedabs[:self.nmax - self._running]))

...........................................................................
/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/htmd/adaptive/adaptive.py in _writeInputs(self=<htmd.adaptive.adaptivegoal.AdaptiveGoal object>, simsframes=array([ sim = simid = 0
parent = 0
input = None
...filtered.pdb
piece = 0
frame = 91], dtype=object), epoch=2)
    167         if len(test) != 0:
    168             raise NameError('Input dirs of epoch ' + str(epoch) + ' already exists.')
    169 
    170         from htmd.config import _config
    171         Parallel(n_jobs=_config['ncpus'], verbose=11)(
--> 172             delayed(_writeInputsFunction)(i, f, epoch, self.inputpath, self.coorname) for i, f in enumerate(simsframes))
        epoch = 2
        self.inputpath = '/home/rakesh/adaptive/input'
        self.coorname = 'input.gro'
        simsframes = array([ sim = simid = 0
parent = 0
input = None
...filtered.pdb
piece = 0
frame = 91], dtype=object)
    173 
    174     @abc.abstractmethod
    175     def _algorithm(self):
    176         return

...........................................................................
/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/joblib/parallel.py in __call__(self=Parallel(n_jobs=-2), iterable=<generator object AdaptiveBase._writeInputs.<locals>.<genexpr>>)
    805             if pre_dispatch == "all" or n_jobs == 1:
    806                 # The iterable was consumed all at once by the above for loop.
    807                 # No need to wait for async callbacks to trigger to
    808                 # consumption.
    809                 self._iterating = False
--> 810             self.retrieve()
        self.retrieve = <bound method Parallel.retrieve of Parallel(n_jobs=-2)>
    811             # Make sure that we get a last message telling us we are done
    812             elapsed_time = time.time() - self._start_time
    813             self._print('Done %3i out of %3i | elapsed: %s finished',
    814                         (len(self._output), len(self._output),

---------------------------------------------------------------------------
Sub-process traceback:
---------------------------------------------------------------------------
ValueError                                         Wed Feb 15 20:35:39 2017
PID: 39326       Python 3.5.2: /home/rakesh/Softwares/miniconda3/bin/python
...........................................................................
/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/joblib/parallel.py in __call__(self=<joblib.parallel.BatchedCalls object>)
     67     def __init__(self, iterator_slice):
     68         self.items = list(iterator_slice)
     69         self._size = len(self.items)
     70 
     71     def __call__(self):
---> 72         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        self.items = [(<function _writeInputsFunction>, (0, sim = simid = 0
parent = 0
input = None
trajecto...ile = filtered/filtered.pdb
piece = 0
frame = 183, 2, '/home/rakesh/adaptive/input', 'input.gro'), {})]
     73 
     74     def __len__(self):
     75         return self._size
     76 

...........................................................................
/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/joblib/parallel.py in <listcomp>(.0=<list_iterator object>)
     67     def __init__(self, iterator_slice):
     68         self.items = list(iterator_slice)
     69         self._size = len(self.items)
     70 
     71     def __call__(self):
---> 72         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        func = <function _writeInputsFunction>
        args = (0, sim = simid = 0
parent = 0
input = None
trajecto...ile = filtered/filtered.pdb
piece = 0
frame = 183, 2, '/home/rakesh/adaptive/input', 'input.gro')
        kwargs = {}
     73 
     74     def __len__(self):
     75         return self._size
     76 

...........................................................................
/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/htmd/adaptive/adaptive.py in _writeInputsFunction(i=0, f=sim = simid = 0
parent = 0
input = None
trajecto...ile = filtered/filtered.pdb
piece = 0
frame = 183, epoch=2, inputpath='/home/rakesh/adaptive/input', coorname='input.gro')
    201     copytree(currSim.input, newDir, symlinks=False, ignore=ignore_patterns('*.coor', '*.rst', '*.out', *_IGNORE_EXTENSIONS))
    202     # overwrite input file with new one. frameNum + 1 as catdcd does 1 based indexing
    203     mol = Molecule()
    204     mol.read(traj)
    205     mol.frame = frameNum
--> 206     mol.write(path.join(newDir, coorname))
        mol.write = <bound method Molecule.write of <htmd.molecule.m... shape: (201,)
time shape: (201,)
viewname: None>
        newDir = '/home/rakesh/adaptive/input/e2s1_e1s1p0f183/'
        coorname = 'input.gro'
    207 
    208 
    209 class Adaptive(object):
    210 

...........................................................................
/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/htmd/molecule/molecule.py in write(self=<htmd.molecule.molecule.Molecule object at 0x7f9...p shape: (201,)
time shape: (201,)
viewname: None, filename='/home/rakesh/adaptive/input/e2s1_e1s1p0f183/input.gro', sel=None, type=None)
   1118                 # traj.xyz = np.swapaxes(np.swapaxes(self.coords, 1, 2), 0, 1) / 10
   1119                 # traj.time = self.time
   1120                 # traj.unitcell_lengths = self.box.T / 10
   1121                 traj.save(filename)
   1122             except:
-> 1123                 raise ValueError("Unknown file type")
   1124 
   1125     def empty(self, numAtoms):
   1126         """ Creates an empty molecule of N atoms.
   1127

**Comment by stefdoerr** [comment]
Could you please do a `conda update htmd`? This error is from an old version

**Comment by BIORAK** [comment]
Hi, 
   I updated HTMD to version 1.5.15 but still get the following error 

Creating simlist: 100% (4/4) [###################################################################################################################################################################################################] eta 00:01 -
Filtering trajectories: 100% (4/4) [#############################################################################################################################################################################################] eta 00:01 |
Projecting trajectories: 100% (4/4) [############################################################################################################################################################################################] eta 00:01 -
2017-02-17 13:29:38,192 - htmd.projections.metric - WARNING - Error in simulation with id: 2. "Number of atoms in trajectory (3981) mismatch with number of atoms in the molecule (3952)"
2017-02-17 13:29:38,239 - htmd.projections.metric - WARNING - Error in simulation with id: 3. "Number of atoms in trajectory (3981) mismatch with number of atoms in the molecule (3952)"
2017-02-17 13:29:38,593 - htmd.projections.metric - INFO - Frame step 5e-06ns was read from the trajectories. If it looks wrong, redefine it by manually setting the MetricData.fstep property.
2017-02-17 13:29:38,594 - htmd.metricdata - INFO - Dropped 0 trajectories from 2 resulting in 2
Traceback (most recent call last):
  File "adaptive.py", line 22, in <module>
    ad.run()
  File "/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/htmd/adaptive/adaptive.py", line 100, in run
    flag = self._algorithm()
  File "/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/htmd/adaptive/adaptivegoal.py", line 148, in _algorithm
    data = self._getData(sims)
  File "/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/htmd/adaptive/adaptiverun.py", line 164, in _getData
    datadr = tica.project(self.ticadim)
  File "/home/rakesh/Softwares/miniconda3/lib/python3.5/site-packages/htmd/projections/tica.py", line 151, in project
    raise RuntimeError('TICA cannot increase the dimensionality of your data. Your data has {} dimensions and you requested {} TICA dimensions'.format(self.data.numDimensions, ndim))
RuntimeError: TICA cannot increase the dimensionality of your data. Your data has 1 dimensions and you requested 3 TICA dimensions

**Comment by stefdoerr** [comment]
As you see there is an issue with filtering:
```
Number of atoms in trajectory (3981) mismatch with number of atoms in the molecule (3952)
```

So your filtering selection `not water` seems to produce different number of atoms. Could it be that your systems have different numbers of ions?
Try changing the `ad.filtersel` to something better fitter to your system

**Comment by stefdoerr** [comment]
You will also need to delete the `filtered` folder to refilter the trajectories

**Comment by stefdoerr** [comment]
@BIORAK can we close this?
