### ISSUE TITLE
progress_reporter not installed correctly from conda

### ISSUE THREAD

**Issue by stefdoerr** [Acellera/htmd#204]
We have progress_reporter in our dependencies but it's on the omnia channel which we don't add anymore so I guess it doesn't pull it. Had the problem a few times in the lab. @mj-harvey should we mirror it in the acellera conda channel?

**Comment by j3mdamas** [comment]
I think Silvia also reported something like this but it got fixed?

Just checked our sync file and progress_reporter is there. Maybe we should sync again?

**Comment by mj-harvey** [comment]
re-synced.
