### ISSUE TITLE
Include acemd requirement

### ISSUE THREAD

**Issue by giadefa** [Acellera/htmd#21]
TODO

**Comment by giadefa** [comment]
still to todo

**Comment by mj-harvey** [comment]
ACEMD now shipping as a conda packag.e Not adding to the htmd dependencies just yet, as it will break os x and windows installs.

**Comment by j3mdamas** [comment]
thanks matt. but at least now we can tell people to do `conda install acemd` to have a working version from pdb to trajectory.

**Comment by giadefa** [comment]
You could just have a python program printing not available for win and
pax, do that it's a dependency

**Comment by mj-harvey** [comment]
Yes, will do
