### ISSUE TITLE
ACEMD via miniconda

### ISSUE THREAD

**Issue by shozebhaider** [Acellera/htmd#213]
I am trying to use acemd that comes with htmd (via miniconda3 install). I am able to execute and run simulations via the jupyter-notebook, however that is not possible when I do it stand alone. The error message is get is that the default protocols (ff/Amber and run/NPT) that I used to invoke from the protocols folder in stand alone version have been migrated and the input file cannot find them. I tried searching for them but I could not find them. 

Have the default protocols completely been done away with in this version of install ? 
Is there a way to run the default protocols like in the stand alone version of Acemd? 

My input file looks like this
-------------------------------start file---------------
protocol ff/Amber
protocol run/NPT

parmfile 	x.prmtop
bincoordinates	output.coor
binvelocities	output.vel
extendedsystem	output.xsc
wrap 		on

xtcfreq		25000
energyfreq	25000
restartfreq	25000

useflexiblecell off
useconstantratio off

pluginload plug plumed
pluginarg plug input META_INP

run 		215ns

**Comment by stefdoerr** [comment]
Hey Shozeb :) Would you mind posting this to https://github.com/Acellera/acemd_issues/issues ? It seems unrelated to HTMD.
Thanks!

**Comment by shozebhaider** [comment]
Sure. I thought they all belonged under the same package. Sorry.

**Comment by stefdoerr** [comment]
Don't worry. The acemd_issues tracker seems to be a bit underadvertised :stuck_out_tongue:  It's just faster to reach Matt that way

**Comment by stefdoerr** [comment]
I'll tag Matt here anyway @mj-harvey https://github.com/Acellera/acemd_issues/issues/22
