### ISSUE TITLE
Help wanted: mixed metric 

### ISSUE THREAD

**Issue by yongwangCPH** [Acellera/htmd#218]
By following the HTMD document, I used below commands to set contacts and dihedral metric in separate MSM analysis, 

For contacts,
```python
metr.projection(MetricSelfDistance('(protein and name CA) or (resid 114)', metric='contacts'))
```
For dihedral,
```python
metr.projection(MetricDihedral.phi(protsel='protein and resid 95 to 124', sincos=True))
```
Now I want to use the mixed metric. But I could not figure out how to do it. Could you help me on this?

First, mixed phi and psi angles:
1) dihedral.psi and dihedral.phi
Then, mixed contacts and phi and psi:
2) contacts + dihedral.phi + dihedral.psi

Thanks!

**Comment by stefdoerr** [comment]
Actually the way you are doing phi dihedral will not work. The phi function only returns a tuple of atoms that are related to the phi angle. It will not do any projections.

Just take a look at the documentation of MetricDihedral

```python 
metr = Metric()
phipsi = MetricDihedral(protsel='protein and resid 95 to 124')
metr.set(phipsi) # This does phi + psi. Check the data.map after it's done
dataphipsi = metr.project()

dih = MetricDihedral.phi(15, 16))  # phi angle only
phi = MetricDihedral(dih, 'protein and resid 95 to 124')
metr.set(phi)
dataphi = metr.project()

# Mixing metrics: just pass an array of projection objects
co = MetricDistance('protein and resid 95 to 124', metric='contacts')
metr.set([phipsi, co])
dataphipsicontacts = metr.project()
```
