### ISSUE TITLE
remove HTMD forum

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#219]

**Comment by mj-harvey** [comment]
This needs the source for the HTMD website changed. I think the only place the forum link appears is in the header https://www.htmd.org/

**Comment by stefdoerr** [comment]
You just need to modify the template html somewhere in the docs folder.
I can do it if you want tomorrow.

**Comment by stefdoerr** [comment]
Removed. I also added github/issues link and remade all static pages in jinja to be less of a pain in the ass to modify them.
