### ISSUE TITLE
Molecule.append and reordering serials

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#22]
I have a question: shouldn't `Molecule.append` reorder the `Molecule.serial` of the molecule to append to follow the serials of the target molecule?

Example of bug: when appending serials of shorter number than the total number of serials of a protein, they get intercalated between the protein and VMD fails miserably to represent NewCartoon.

**Comment by stefdoerr** [comment]
I seriously doubt that. Check the append code. At the end I do:
`self.serial = np.arange(1, self.numAtoms+1)`
Serials are never preserved in Molecule and should not be assumed to stay the same.

**Comment by j3mdamas** [comment]
You are right... I need to understand why is my cartoon representation breaking then.

**Comment by stefdoerr** [comment]
Bond problems. Can you check if there are bonds in your Molecules? If they are, can you check if after appending they are still correct in Licorice mode? (ignore NewCartoon for the moment)

**Comment by j3mdamas** [comment]
The Licorice representation is fine. Yes, there is bond information in
Molecule.bonds

On Fri, Apr 22, 2016 at 11:09 AM, Stefan <notifications@github.com> wrote:

> Bond problems. Can you check if there are bonds in your Molecules? If they
> are, can you check if after appending they are still correct in Licorice
> mode? (ignore NewCartoon for the moment)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Acellera/htmd/issues/22#issuecomment-213343344>
>



--

**Comment by stefdoerr** [comment]
Before appending both Molecules look fine in newcartoon and after appending not anymore?
VMD uses given bonds but also guesses bonds based on distances. Can you disable it's bond guessing in `mol.view(guessBonds=False)` and try again ?

**Comment by j3mdamas** [comment]
I can give you more detail. I was appending the OPM beads onto the PDB.
Before NewCartoon works, after appending it doesn't. guessBonds=False does
not change.

In fact, the pdb straight from OPM has problems in representing the
cartoon. I thought it was the serial numbering (the OPM beads intercalate
the serials of the protein) but you are right and they are renumbered in
the append. Now I am guessing it's the residue numbering? I am going to
check it.

On Fri, Apr 22, 2016 at 11:18 AM, Stefan <notifications@github.com> wrote:

> Before appending both Molecules look fine in newcartoon and after
> appending not anymore?
> VMD uses given bonds but also guesses bonds based on distances. Can you
> disable it's bond guessing in mol.view(guessBonds=False) and try again ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Acellera/htmd/issues/22#issuecomment-213348390>
>



--

**Comment by j3mdamas** [comment]
No, resid makes no sense...

On Fri, Apr 22, 2016 at 11:30 AM, Joao Damas <j.damas@acellera.com> wrote:

> I can give you more detail. I was appending the OPM beads onto the PDB.
> Before NewCartoon works, after appending it doesn't. guessBonds=False does
> not change.
>
> In fact, the pdb straight from OPM has problems in representing the
> cartoon. I thought it was the serial numbering (the OPM beads intercalate
> the serials of the protein) but you are right and they are renumbered in
> the append. Now I am guessing it's the residue numbering? I am going to
> check it.
>
> On Fri, Apr 22, 2016 at 11:18 AM, Stefan <notifications@github.com> wrote:
>
>> Before appending both Molecules look fine in newcartoon and after
>> appending not anymore?
>> VMD uses given bonds but also guesses bonds based on distances. Can you
>> disable it's bond guessing in mol.view(guessBonds=False) and try again ?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Acellera/htmd/issues/22#issuecomment-213348390>
>>
>
>
>
> --
>
>
>



--

**Comment by stefdoerr** [comment]
Ah then it's normal, if the original PDB also does not show Cartoon correctly. This happens in many cases because the connectivity cannot be guessed correctly. After building the system you will have a psf or prmtop with the correct connectivity and then it will be fine. You need to get used to that and just use Licorice before building if NewCartoon fails.

**Comment by j3mdamas** [comment]
Nope, the original PDB shows it correctly. The OPM beads break it

On Fri, Apr 22, 2016 at 11:36 AM, Stefan <notifications@github.com> wrote:

> Ah then it's normal, if the original PDB also does not show Cartoon
> correctly. This happens in many cases because the connectivity cannot be
> guessed correctly. After building the system you will have a psf or prmtop
> with the correct connectivity and then it will be fine. You need to get
> used to that and just use Licorice before building if NewCartoon fails.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Acellera/htmd/issues/22#issuecomment-213355598>
>



--

**Comment by j3mdamas** [comment]
Test an example from OPM: http://opm.phar.umich.edu/pdb/1uaz.pdb

vmd 1uaz.pdb
Show NewCartoon

Seems more like a VMD than an HTMD issue...

On Fri, Apr 22, 2016 at 11:37 AM, Joao Damas <j.damas@acellera.com> wrote:

> Nope, the original PDB shows it correctly. The OPM beads break it
>
> On Fri, Apr 22, 2016 at 11:36 AM, Stefan <notifications@github.com> wrote:
>
>> Ah then it's normal, if the original PDB also does not show Cartoon
>> correctly. This happens in many cases because the connectivity cannot be
>> guessed correctly. After building the system you will have a psf or prmtop
>> with the correct connectivity and then it will be fine. You need to get
>> used to that and just use Licorice before building if NewCartoon fails.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Acellera/htmd/issues/22#issuecomment-213355598>
>>
>
>
>
> --
>
>
>



--

**Comment by stefdoerr** [comment]
It's definitely a VMD issue. But it's not something that can be fixed without building the system. VMD needs bonds to show Cartoon. If you guess bonds it will fail because of the OPM beads. If you don't guess bonds it will fail because you don't provide all the protein bonds. Only way is to provide all protein bonds but that requires usually building the system first.
