### ISSUE TITLE
Improve deprecation system

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#223]
Put in documentation (this is the most important part): http://www.sphinx-doc.org/en/1.5.1/markup/para.html#directive-deprecated
Deprecate it with a decorator (unifies deprecation messages, makes easier to find what is deprecated): https://wiki.python.org/moin/PythonDecoratorLibrary#Smart_deprecation_warnings_.28with_valid_filenames.2C_line_numbers.2C_etc..29 (for functions, needs to be adapted for classes (and properties?))

Put this on developers page

@stefdoerr, what do you think about this in relation to the deprecation system of `protocolinterface.py`?

**Comment by stefdoerr** [comment]
We can have both in parallel. The one in protocol interface is for attributes. The other one can be used for methods and classes
