### ISSUE TITLE
setting NME and ACE terminal residues for some protein chains

### ISSUE THREAD

**Issue by rcrehuet** [Acellera/htmd#225]
I am working with protein-DNA system that contains 5 protein chains. For 2 of the, I'd like to cap the terminal residues with NME and ACE cappings. Is it possible to do that with HTMD or should I pre-process the PDB somehow?

**Comment by stefdoerr** [comment]
Yes NME and ACE capping is actually done automatically for all protein segments so you need to override the automatical capping by specifying your own like this.

```python
caps = {}
caps['A'] = ['ACE', 'NME']  # Enables capping for segment A
caps['B'] = ['none', 'none']  # Disables capping for segment B
ffs = ['leaprc.lipid14', 'leaprc.ff14SB', 'leaprc.gaff']
molbuilt = amber.build(mol, ff=ffs, caps=caps, outdir='/tmp/build', saltconc=0.15)
```

**Comment by rcrehuet** [comment]
I had defined the following segments:
```
tern_op.set('segid', 'PCNA', sel='chain A B C')
tern_op.set('segid', 'p15', sel='chain D E')
tern_op.set('segid', 'DNA', sel='nucleic')
```
can I then use it like this:
```
caps['PCNA'] = ['none', 'none']  # Disables capping for segment B
caps['p15'] = ['ACE', 'NME'] 
```
Or is it better to define one segment per chain? i.e. define 6 segments and specify the capping for the first 5.

**Comment by stefdoerr** [comment]
Anything inside a segment will get bonded. If you don't want your chains to be bonded then assign them to separate segments.
