### ISSUE TITLE
Why does propka complain of not having a pdb when calling `proteinPrepare`?

### ISSUE THREAD

**Issue by rcrehuet** [Acellera/htmd#226]
I know it is also in the [tutorial](https://www.htmd.org/docs/latest/tutorials/system-building-protein-ligand.html) but I think it is worrying that when you call `proteinPrepare` with a Molecule object that contains a PDB it prints:
```
2017-01-19 11:15:54,027 - propka - INFO - No pdbfile provided
```

**Comment by tonigi** [comment]
It's a confusing message inside the code of propka. The price to pay not to fork code.

**Comment by j3mdamas** [comment]
Nothing to do here. Closed.
