### ISSUE TITLE
Error in manual definition of disulphide bonds

### ISSUE THREAD

**Issue by rcrehuet** [Acellera/htmd#227]
I'm trying to manually define some disulphide bonds. Acoording to the documentation, the argument should be a *2D array where each row is a pair of atom indexes*.
I've created my array with:
```
ss_bonds =np.vstack((smol.atomselect("resid 135 162 and name SG", indexes=True),
smol.atomselect("resid 390 417 and name SG", indexes=True),
smol.atomselect("resid 645 672 and name SG", indexes=True),))
```

But that raises an error. I've been looking at the source code and it seems the array elements should have the `segid1` and `resid1` attribute, which atom indices (being integers) do not have...

**Comment by stefdoerr** [comment]
Oh I forgot to update the docs on AMBER. Thanks for pointing it out.
Use `DisulfideBridge(segid1, resid1, segid2, resid2)`
i.e.
```python
disu = [DisulfideBridge('P', 157, 'P', 13), DisulfideBridge('K', 1, 'K', 25)]
amber.build(disulfide=disu, ...)
```

**Comment by rcrehuet** [comment]
Actually, I still have a problem with the disulphide bridges. When building the model errors such as:

```
Building bond parameters.
Could not find bond parameter for: SH - SH
Could not find bond parameter for: SH - SH
Building angle parameters.
Could not find angle parameter: HS - SH - SH
Could not find angle parameter: SH - SH - 2C
Could not find angle parameter: SH - SH - HS
Could not find angle parameter: 2C - SH - SH
```
Apparently this is because CYS residues should be names CYX (see [here](http://archive.ambermd.org/201407/0024.html) or [here](http://archive.ambermd.org/201204/0052.html)), and this is not automatically done by HTMD. Is there a way I can do that manually? Or is it better if you correct it in HTMD?

**Comment by j3mdamas** [comment]
I see what you mean. The residue name conversion is only being performed for automatic detection. I'll fix that.
