### ISSUE TITLE
Update to Py3 version of Psi4

### ISSUE THREAD

**Issue by mj-harvey** [Acellera/htmd#228]
As soon as the release moves out of test. Watch it here:

https://anaconda.org/psi4/psi4/labels

**Comment by j3mdamas** [comment]
Waiting for mid May

**Comment by j3mdamas** [comment]
It's released. I'll have to test it and change the dependency.

**Comment by j3mdamas** [comment]
Done. I've passed our psi4 and pcmsolver and dftd3 packages to deprecated in the label (didn't delete them yet).

psi4 depends on many stuff. my first try was to sync the dependencies to our channel, but it wasn't working for a reason (psi4 didn't even run with a very weird bug). Nonetheless, I think it's better to rely on their channel. Just need to change the installation to include their channel as well (with our own installed, this won't be a problem).

Closing
