### ISSUE TITLE
www.htmd.org page rendering is poorly formatted while still loading

### ISSUE THREAD

**Issue by mj-harvey** [Acellera/htmd#229]
The rendering of the partially loaded https://www.htmd.org page is rather ugly. Before the images load the accompanying black text is mispositioned over the tile. Would be nice to have this cosmetic wrinkled fixed, please.

Steps to reproduce: load htmd.org from outside the lab / using Chrome with bandwidth throttling enabled.

Ta

Matt

**Comment by j3mdamas** [comment]
If I could reproduce it here at Acellera, I could try to fix it. At home, i don't have that possibility.

**Comment by stefdoerr** [comment]
You can. With chrome you can throttle the network speed. It's quite hard to fix though without redesigning the website as it uses javascript to make the slideshow and expects the images to have loaded beforehand.

**Comment by j3mdamas** [comment]
Oh, with Chrome DevTools. I did not know it.

**Comment by mj-harvey** [comment]
should be as simple as fixing the size of the element that the image is loading into, so that it doesnt get resized from height=0 when the image finishes loading

**Comment by stefdoerr** [comment]
I don't see the resizing issue. I see the other issues with the images loading one under the other before becoming a slidshow and the texts loading on top of each other.

**Comment by j3mdamas** [comment]
not urgent, but I'll look into it

**Comment by j3mdamas** [comment]
yeah, I see the same as you, Stefan.

**Comment by stefdoerr** [comment]
Self-reminder:
```
<div class="slide" style="background-image:url('./img/prot_surface_2.jpg')">
<div class="back-wrapper"></div>
<h1> From molecules to affinities, kinetics and pathways</h1>
</div>
```
Try to replace with simple <img> like [here](http://bxslider.com/) and see if it works better

**Comment by stefdoerr** [comment]
Tried my best and failed. I think this is trivial enough that it doesn't really need to be fixed.

**Comment by j3mdamas** [comment]
I was unsuccessful. Maybe @gerardbcn, the html wizard, could solve it?
