### ISSUE TITLE
psi4 crash on fedora 25

### ISSUE THREAD

**Issue by lmanubens** [Acellera/htmd#231]
Hi,

When using parameterize in a Fedora 25 fresh install the PSI4 minimization crashes. 
HTMD was installed following https://www.htmd.org/academic-download.html and pulling this project.
 
This does not happen in an Ubuntu distribution. 
My guess is that it has to do with maths libraries that might be different between the distributions.

Thanks!

[psi4.out.txt](https://github.com/Acellera/htmd/files/726174/psi4.out.txt)
[mol.zip](https://github.com/Acellera/htmd/files/726165/mol.zip)
![crash_parameterize](https://cloud.githubusercontent.com/assets/16608242/22241228/c7db4876-e21e-11e6-820a-9484743febbe.png)

**Comment by mj-harvey** [comment]
Don't have a Fedora 25 system to reproduce this. I can only recommend that you use your Ubuntu system for this for now, or independently build your own version of psi4.
Alternatively, please check back when we move to Psi4 1.1 once that is released.

Matt
