### ISSUE TITLE
Question about error in ligand-binding analysis

### ISSUE THREAD

**Issue by KendyP** [Acellera/htmd#232]
Hello,
I'm performing ligand-binding analysis based off of the ligand binding analysis notebook from the most recent workshop.  My system is very similar to the one in the notebook.  When I run my notebook one warning and one error message appear in which I need assistance in resolving. The WARNING message `2017-01-24 15:20:34,972 - htmd.projections.metric - WARNING - Cannot calculate description of dimensions due to different topology files for each trajectory.` occurs when performing metric projections and states that there are different topology files for simulations; however, the topology and file being used is the one generated when the system was built and should have been carried through to each simulation in each epoch. Why is this WARNING appearing and how do I resolve it?

The ERROR occurs during tica projections and states:
```pytb
AttributeError                            Traceback (most recent call last)
<ipython-input-15-6d0e37fdaaf8> in <module>()
      1 tica = TICA(data, 1, units='ns', 
      2             dimensions=range(data.dat[0].shape[1]-1))
----> 3 dataTica = tica.project(3)

/Users/pellegrenek/miniconda3/lib/python3.5/site-packages/htmd/projections/tica.py in project(self, ndim)
    153                 keepdim = np.setdiff1d(range(self.data.numDimensions), self.dimensions)
    154                 keepdata = [x[:, keepdim] for x in self.data.dat]
--> 155                 keepdimdesc = self.data.map.ix[keepdim]
    156             proj = self.tic.get_output()
    157             simlist = self.data.simlist

AttributeError: 'NoneType' object has no attribute 'ix'
```

Why is this error appearing and how do I resolve it?

The ipython notebook I'm using is attached to this post.   Thank-you in advance for any insight that you can provide.

[Adaptive_Analysis_New.ipynb.zip](https://github.com/Acellera/htmd/files/727879/Adaptive_Analysis_New.ipynb.zip)

**Comment by stefdoerr** [comment]
```python
metr = Metric(sims)
```

You are projecting the unfiltered trajectories so it complains that they don't have a common PDB file. Change it to fsims and you should be good to go

**Comment by KendyP** [comment]
I made the change and the warning message and error have been resolved. Thank you very much.

**Comment by stefdoerr** [comment]
You are welcome :)
