### ISSUE TITLE
HTMD website -- keep copyright year uptodate

### ISSUE THREAD

**Issue by mj-harvey** [Acellera/htmd#235]
the footer says 2016 still.

**Comment by stefdoerr** [comment]
Just message me those minor things :) Fixed in a sec

**Comment by gph82** [comment]
no please, this stuff is interesting ;)

**Comment by j3mdamas** [comment]
@stefdoerr, I put it automatic on htmd documentation. Can't we do something similar on the htmd.org?

**Comment by stefdoerr** [comment]
Yeah I can. On another subject let's keep internal issues on the private issue tracker? There is no point to post it here in my opinion.

**Comment by j3mdamas** [comment]
agreed.
