### ISSUE TITLE
Pypi packaging

### ISSUE THREAD

**Issue by mj-harvey** [Acellera/htmd#237]
At least basic functionality for  a "pip install"able HTMD.

**Comment by j3mdamas** [comment]
@mj-harvey, I did some changes in your prototype script, in particular I removed the pyEMMA < 2.3 dependency. is this fine? c9e90b10bfb01eff7a583ab7824086570fd2ef7c

**Comment by mj-harvey** [comment]
sure, feel free to play with it

**Comment by j3mdamas** [comment]
The current build works. This is an enhancement that we could think about in the future. This would be cleaner and prettier, but not a priority.
