### ISSUE TITLE
New release for htmd-data necessary [Problem running tests]

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#24]
I was running tests for #19:
```
%run tests/run_inline_file_tests.py
```

And I got this:
```
Traceback (most recent call last):
  File "./htmd/builder/builder.py", line 341, in <module>
    ref = Molecule(path.join(home(), 'data', 'building-protein-membrane', '1ITG.pdb'))
  File "/home/joao/miniconda3/lib/python3.5/site-packages/htmd/molecule/molecule.py", line 143, in __init__
    self.read(filename)
  File "/home/joao/miniconda3/lib/python3.5/site-packages/htmd/molecule/molecule.py", line 591, in read
    self._readPDB(filename)
  File "/home/joao/miniconda3/lib/python3.5/site-packages/htmd/molecule/molecule.py", line 693, in _readPDB
    raise NameError('File {} not found'.format(filename))
NameError: File /home/joao/miniconda3/lib/python3.5/site-packages/htmd/data/building-protein-membrane/1ITG.pdb not found
```

In fact, there is no 1ITG.pdb there. Actually, the `__name__` of ` builder.py` has this two that won't run the inline file tests:
```
    mol = Molecule('1ITG')
    ref = Molecule(path.join(home(), 'data', 'building-protein-membrane', '1ITG.pdb'))
    mol = autoSegment(mol, sel='protein')
    assert np.all(mol.segid == ref.segid)

    mol = Molecule('3PTB')
    ref = Molecule(path.join(home(), 'data', 'building-protein-membrane', '3PTB.pdb'))
    mol = autoSegment(mol, sel='protein')
    assert np.all(mol.segid == ref.segid)
```

Or am I doing something wrong, @stefdoerr?

**Comment by j3mdamas** [comment]
I must be doing something wrong as Travis does not complain running these tests...

**Comment by stefdoerr** [comment]
Its in the repo
https://github.com/Acellera/htmd/tree/master/htmd/data/building-protein-membrane
Maybe you need to do conda update htmd-data or we need to make a new
release of htmd-data

**Comment by j3mdamas** [comment]
```
conda update htmd-data
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ........
# All requested packages already installed.
# packages in environment at /home/joao/miniconda3:
#
htmd-data                 0.0.33                   py35_0    acellera
```

So I guess a new release is necessary? Anyway, now I notice that this means the `home( )` is pointing to the conda repo and not my local one... I should really start using the conda environments or the conda fresh installs you were talking about...

**Comment by stefdoerr** [comment]
I don't know how to make a new htmd-data release though :( Matt?

**Comment by j3mdamas** [comment]
@mj-harvey, I assigned it to you. If you want me to do it, you have to tell me how to.

**Comment by mj-harvey** [comment]
manually change the package version number in
multiscalelab/htmd/package/htmd-data/meta.yaml

On 29 April 2016 at 18:46, Stefan <notifications@github.com> wrote:

> I don't know how to make a new htmd-data release though :( Matt?
>
> On Fri, Apr 29, 2016 at 8:43 PM, João M. Damas <notifications@github.com>
> wrote:
>
> > conda update htmd-data
> > Using Anaconda Cloud api site https://api.anaconda.org
> > Fetching package metadata: ........
> > # All requested packages already installed.
> > # packages in environment at /home/joao/miniconda3:
> > #
> > htmd-data 0.0.33 py35_0 acellera
> >
> > So I guess a new release is necessary? Anyway, now I notice that this
> > means the home( ) is pointing to the conda repo and not my local one... I
> > should really start using the conda environments or the conda fresh
> > installs you were talking about...
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Acellera/htmd/issues/24#issuecomment-215826970>
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Acellera/htmd/issues/24#issuecomment-215827644>
>



-- 
<https://www.acellera.com>


<https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>
    <https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/acellera>
<https://www.acellera.com/md-simulation-blog-news/>     [image:
skype:acellera] <http://is.gd/1eXkbS>

**Comment by stefdoerr** [comment]
You change the version number in the `meta.yaml`
and then use the following two commands:
```
conda build .
anaconda upload /shared/sdoerr/Software/anaconda3/conda-bld/linux-64/htmd-data-0.0.34-py35_0.tar.bz2 -c acellera
```
The last command is given at the end of the first command but you need to add the `-c acellera` so that it uploads it to the acellera conda channel.

**Comment by stefdoerr** [comment]
Ah apparently it's not necessary to run the two commands. Travis should make a new release if you just change the version number

**Comment by mj-harvey** [comment]
htmd-data deployment should be done through travis, just like htmd. The
only difference is that the pacakge version number is hard coded in the
meta.yaml rather than taken from the git tagging.



On 3 May 2016 at 13:18, Stefan <notifications@github.com> wrote:

> You change the version number in the meta.yaml
> and then use the following two commands:
>
> conda build .
> anaconda upload /shared/sdoerr/Software/anaconda3/conda-bld/linux-64/htmd-data-0.0.34-py35_0.tar.bz2 -c acellera
>
> The last command is given at the end of the first command but you need to
> add the -c acellera so that it uploads it to the acellera conda channel.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Acellera/htmd/issues/24#issuecomment-216510393>
>



-- 
<https://www.acellera.com>


<https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>
    <https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/acellera>
<https://www.acellera.com/md-simulation-blog-news/>     [image:
skype:acellera] <http://is.gd/1eXkbS>

**Comment by stefdoerr** [comment]
Yes, I figured as much after checking the travis.yml file, thanks :)
