### ISSUE TITLE
Best defaults for Amber build

### ISSUE THREAD

**Issue by mj-harvey** [Acellera/htmd#242]
Forked from https://github.com/Acellera/htmd/issues/236

@j3mdamas @stefdoerr 
Current best practice for Amber ffs: discuss here for the record please.

**Comment by j3mdamas** [comment]
Here I think we are not discussing which is the "best" force-field, are we?

My opinion is that, whichever is the version of AmberTools we are using, we use the recommendation from the Amber team for that version.

For AmberTools16, from [here](http://ambermd.org/changelog.html), the recommendation is:
> The leaprc.ff14SB has been moved to the oldff subdirectory, but is unchanged from AmberTools15. This means that it can still be used for workflows that benefit from having a "generic" leaprc file, but note that oldff/leaprc.ff14SB does not have the currently-recommended parameters for DNA, and will not be updated as other parts of force fields evolve. Users should make plans to transition away from use of files in the "oldff" subdirectory.

**Comment by stefdoerr** [comment]
Doesn't seem like there is that much to discuss. 
For the moment we stick with ff14SB until we decide in the lab that the new one is better as we usually do for the defaults.
