### ISSUE TITLE
Python 3.6 compatibility

### ISSUE THREAD

**Issue by hawk31** [Acellera/htmd#243]
Stable Anaconda (4.3) version uses Python 3.6 by default. Now `conda install htmd` does not work due to some dependency issue.

```bash
UnsatisfiableError: The following specifications were found to be in conflict:
  - htmd -> pyemma >=2.0.2 -> bhmm >=0.6,<0.7 -> msmtools -> numpy 1.10* -> python 2.7* -> openssl 1.0.1*
  - python 3.6*
```

**Comment by j3mdamas** [comment]
Downgrade anaconda for now?

**Comment by hawk31** [comment]
Sure, just letting you know this issue exists.

**Comment by j3mdamas** [comment]
Thanks for reporting :)

On Feb 1, 2017 13:43, "José Jiménez" <notifications@github.com> wrote:

Sure, just letting you know this issue exists.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Acellera/htmd/issues/243#issuecomment-276648377>, or mute
the thread

**Comment by mj-harvey** [comment]
Since we aren't providing py36 packages yet, I'm surprised that conda finds an HTMD to install.

**Comment by j3mdamas** [comment]
Yeah, it is surprising. I am going to test it.

**Comment by j3mdamas** [comment]
@hawk31 is having this in a fresh installation, so it's really urgent

**Comment by mj-harvey** [comment]
I'm going to add  py36 packages to travis

**Comment by mj-harvey** [comment]
In the mean time, @hawk31 you can create a ython 3.5 environment before installing.

**Comment by j3mdamas** [comment]
@hawk31 this was using Anaconda installer and not the Miniconda one, correct?

**Comment by j3mdamas** [comment]
I just tested the Miniconda, and it works fine, so I'll downgrade the urgency of this matter.

**Comment by hawk31** [comment]
Yeah, it was Anaconda 4.3.

I have no rush to update whatsoever, so don't worry.

El 1 feb. 2017 19:42, "João M. Damas" <notifications@github.com> escribió:

I just tested the Miniconda, and it works fine, so I'll downgrade the
urgency of this matter.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Acellera/htmd/issues/243#issuecomment-276742987>, or mute
the thread

**Comment by j3mdamas** [comment]
Confirmed. There is no dependency issue, it's just that python3.6 and htmd were in conflict.

Good to note though, since maybe Miniconda may move on to py36 too soon, so we'll be ahead.

Thanks for reporting.

**Comment by mj-harvey** [comment]
We'll keep this openfor now, until I'll sorted the dependencies

**Comment by tonigi** [comment]
This should allow the use of htmd in any anaconda. It makes a separate env and do all its best to satisfy dependencies.

    conda create --name htmd htmd
    source activate htmd

**Comment by j3mdamas** [comment]
@mj-harvey I'm going to make a release even though the py3.6 build is failing, because the builds and conda uploads are independent within builds.

**Comment by mj-harvey** [comment]
@j3mdamas py3.6 dependencies are all present now, please put out a release next time the board is green.

**Comment by j3mdamas** [comment]
I need to check if PyEMMA patch is already out. That doesn't pass in our
Travis build yet.

**Comment by mj-harvey** [comment]
2.3.1 just appeared.

**Comment by j3mdamas** [comment]
Cool, I'll make the release later today

**Comment by j3mdamas** [comment]
https://travis-ci.org/Acellera/htmd/jobs/199782363

acecloud-client needs a fix.

I don't know why can the amber and charmm tests pass in py35 and fail in py36... any clues @stefdoerr? maybe PYTHONHASSEED does not work in py36?

**Comment by j3mdamas** [comment]
In amber, the only diff is in `tleap.in`. I will investigate that.

**Comment by tonigi** [comment]
Grr

http://stackoverflow.com/questions/39980323/dictionaries-are-ordered-in-cpython-3-6

seems they changed again the dictionary order.

T

**Comment by j3mdamas** [comment]
that's bad, because it makes py35 and py36 outputs based on dicts incompatible... No?

**Comment by mj-harvey** [comment]
Add an explicit sort. It'll be be a no-op on py36 but will cause py35 to match the new behaviour.

**Comment by j3mdamas** [comment]
Yeah, sort is what I was thinking, but we need to go over the use of dicts in the code...

**Comment by tonigi** [comment]
and regtests, including internals of code we don't control

**Comment by stefdoerr** [comment]
The problem is not our code but external code

**Comment by j3mdamas** [comment]
I am sure that the problems with amber and charmm are due to this, because we use dictionaries to write caps and patches, I think, and they will cause differences, definitely.

**Comment by mj-harvey** [comment]
what external python code are you referring to @stefdoerr ?

**Comment by stefdoerr** [comment]
pdb2pqr/propka which is run before building charmm/amber

**Comment by mj-harvey** [comment]
So what's the difference in the input going into tleap?

**Comment by tonigi** [comment]
pdb2pqr may be the offender (=> different proteinprepare outputs). It 
became non deterministic with py 3 randomization, which then i fixed.   
this change may have exposed more differences. will look next week.

T

**Comment by tonigi** [comment]
But i don't see the relation to cloud

**Comment by mj-harvey** [comment]
@tonigi two separate problems. The acecloud issue is fixed.

**Comment by mj-harvey** [comment]
According to the build tests, for the Amber test only the tleap.in differs. The output prmtop seems unchanged.
 To fix that just canonicalise the order of whater your are serialising in that file.

For Charmm, the psf is different too, probably needs some more investigation

**Comment by tonigi** [comment]
If the number of atoms does not change, then prepare is likely unaffected

T

**Comment by stefdoerr** [comment]
I will need to check tleap.in in 3.6. Will do later and see the diff

**Comment by j3mdamas** [comment]
OK; in amber, the problem is the order on which the disulfide bonds are written. But the disulfide variable is a list of disulfideBridge objects and not a dict. And the way elements are appended to that list depends on a Pandas dataframe and not a dict, from what I see. It can returned a sorted list instead.

(still curious of the outputs not reflecting that change in order...)

**Comment by j3mdamas** [comment]
Ok, the sort of the list of DisulfideBridge objects sorts amber problem in py36.

Now going to look into charmm.py

**Comment by j3mdamas** [comment]
@stefdoerr advised me against using the `__gt__` and I used a lambda function on the `key=` argument of `sorted()` instead.

The only remaining problem is the order of the N-ter hydrogens are placed between py35 and py36. @stefdoerr suggested that it could be `pdb2pqr`:

```
diff -r *
diff -r py35_charmm_3PTB/log.txt py36_charmm_3PTB/log.txt
196d195
< psfgen) Warning: failed to set coordinate for atom H3	 ILE:16	  0
197a197
> psfgen) Warning: failed to set coordinate for atom H3	 ILE:16	  0
diff -r py35_charmm_3PTB/pre-ionize/log.txt py36_charmm_3PTB/pre-ionize/log.txt
196d195
< psfgen) Warning: failed to set coordinate for atom H3	 ILE:16	  0
197a197
> psfgen) Warning: failed to set coordinate for atom H3	 ILE:16	  0
diff -r py35_charmm_3PTB/pre-ionize/segments/segment0.pdb py36_charmm_3PTB/pre-ionize/segments/segment0.pdb
21,22c21,22
< ATOM     20  H3  ILE A  16      -8.072  10.549  20.008  1.00  0.00      0    H  
< ATOM     21  H2  ILE A  16      -8.927   9.431  20.832  1.00  0.00      0    H  
---
> ATOM     20  H2  ILE A  16      -8.072  10.549  20.008  1.00  0.00      0    H  
> ATOM     21  H3  ILE A  16      -8.927   9.431  20.832  1.00  0.00      0    H  
diff -r py35_charmm_3PTB/segments/segment0.pdb py36_charmm_3PTB/segments/segment0.pdb
21,22c21,22
< ATOM     20  H3  ILE A  16      -8.072  10.549  20.008  1.00  0.00      0    H  
< ATOM     21  H2  ILE A  16      -8.927   9.431  20.832  1.00  0.00      0    H  
---
> ATOM     20  H2  ILE A  16      -8.072  10.549  20.008  1.00  0.00      0    H  
> ATOM     21  H3  ILE A  16      -8.927   9.431  20.832  1.00  0.00      0    H  
```

@tonigi do you think this is something that can be fixed?

**Comment by tonigi** [comment]
maybe. i can have a look next week

**Comment by j3mdamas** [comment]
Thanks!

**Comment by j3mdamas** [comment]
I'll bump this into the next stable version, I guess

**Comment by tonigi** [comment]
Should be solved as soon as the dependencies pull htmd-pdb2pqr 2.1.2+htmd3

**Comment by stefdoerr** [comment]
We are 1.6 compatible minus openbabel which is not up to us

**Comment by tonigi** [comment]
Unfortunately not on osx yet, afaik. We either need to add another osx
Travis (just for dependencies), which is slow. But I'll have a go at cross
compiling which could be better.

T


Il 15 mar 2017 12:23 PM, "Stefan Doerr" <notifications@github.com> ha
scritto:

**Comment by stefdoerr** [comment]
Oh yes ok I forgot OSX. I'll reopen

**Comment by j3mdamas** [comment]
I will dedicate a couple of hours to see if I can make Py3.6 in OSX oass Travis.

If not, that will be left for 1.10.0

**Comment by tonigi** [comment]
A suggestion could be to make htmdlib a separate package, which is faster
to build in Travis. Htmd itself would then be noarch, not require the slow
osx runs, and  be generated by conda convert.

Just an idea though.

Il 20 mar 2017 1:38 PM, "João M. Damas" <notifications@github.com> ha
scritto:

**Comment by stefdoerr** [comment]
Hm that sounds like a much better idea

**Comment by j3mdamas** [comment]
How long would that take?

**Comment by stefdoerr** [comment]
Actually it's impossible right now, since htmdlib is private, unless we pay
for private travis.
Although we could make a dummy private project and pull htmdlib privately
like the htmd travis build does now. Convoluted but why not.

**Comment by stefdoerr** [comment]
We would need to add tests as well in that repo. To make sure the so's
actually work since we won't test them directly in Travis for multiple OSs

**Comment by tonigi** [comment]
Well htmdlib is already compiled on Travis somehow

Il 20 mar 2017 1:48 PM, "Stefan Doerr" <notifications@github.com> ha
scritto:

**Comment by stefdoerr** [comment]
Typo:
*dummy public project

**Comment by j3mdamas** [comment]
We need Matt for these decisions. Let's put it on HTMD dev meeting agenda.

Meanwhile: Py3.6 on OSX. Make it or drop it?

**Comment by stefdoerr** [comment]
Yes as I said by pulling a private repo inside a "dummy" public repo

**Comment by j3mdamas** [comment]
OK, Stefan already removed the OSX 3.6 from Travis.

Let's postpone OSX discussion to another issue, including its py 3.6 version
