### ISSUE TITLE
Restart of adaptive does not finish remaining simulations in epoch

### ISSUE THREAD

**Issue by KendyP** [Acellera/htmd#244]
I am inquiring about an issue with Adaptive. My simulations were stopped part way through epoch 1 due to an issue with the computer they were running on.  Roughly 10 out of the 40 simulations in the epoch had finished. I restarted adaptive and found that rather than continuing with the simulations that remained in the first epoch, a second epoch containing 40  simulations was created and began running. This leaves 30 in the first epoch without ever having been run. In the past I had noticed that when restarting adaptive, the remaining simulations in the epoch the job had stopped were finished before another epoch was generated. Is this observation incorrect? Has adaptive always generated a new epoch upon restart rather than finishing previous simulations? Will adaptive return back to the previous epochs simulations and finish epoch 1 after finishing epoch 2? Any insight on this matter is appreciated. Thank you in advance. Please let me know if there is any additional information you need. 

-Kendy

**Comment by stefdoerr** [comment]
Depends what resource you use. If you use LocalQueue it will not be able to recover because you killed the queue. It might even get stuck forever (until you delete some files).
If you use a standalone queue like PBS/LSF etc as long as you didn't kill the queue it should continue working.

If you killed the queue it will not resend the missing simulations out. If there are not enough simulations completed it might get even stuck.

It's actually something that is fixable. Just never happened to have the issue myself since I run mostly on standalone queuing systems. 

But in any case I would not worry too much. One epoch doesn't make the difference.

**Comment by j3mdamas** [comment]
Hi,

The algorithm of adaptive detects which is the last epoch, independent of how many simulations were produced (finished). The creation of a new epoch depends on the amount of simulations that are running (if it's under `nmin`) rather than the amount of simulations that the last epochs has.

**Comment by KendyP** [comment]
Thank you for the responses. There was a power issue with the computer, so the queue was killed. Adaptive does not appear to be stuck or anything, and the second epochs simulations are running smoothly. It is helpful to know how the algorithm works when adaptive is restarted. Thanks again!

**Comment by stefdoerr** [comment]
Hm @j3mdamas I am debating if this is something that should be fixed. The adaptive could theoretically be restarted mid-epoch. Like if the queue crashes (i.e. nothing is running) but not all sims have returned it could resend missing sims. But this might open us up to other issues like failing simulations. We don't want to get stuck resending failing simulations. Needs some thinking.

**Comment by stefdoerr** [comment]
Hm nah forget it. It's probably not a good idea. You were right, I mean as it works now it works correct. It filled up the queue with nmax simulations. Doesn't really matter if one epoch was cut a bit short, we should not count on epochs ever being fully completed.

**Comment by stefdoerr** [comment]
Also @KendyP in the same vein, if you ever decide to plot the progress of the adaptive like RMSD per epoch, don't plot it per epoch but instead by aggregate simulation time, then the x axis will be correct independently if one epoch was shorter than another.

**Comment by j3mdamas** [comment]
yeah, I agree with you, now that I understand it a bit better. It's a little bit like when we discussed the `inprogress` method: adaptive doesn't care if the simulations failed or not, it just cares about what is running.

**Comment by KendyP** [comment]
I was planning to make an epoch vs. RMSD plot once I had more epochs completed, so that is a good point. Thank you!
