### ISSUE TITLE
How to save a Molecule (i.e. how to avoid redoing all the setup steps)

### ISSUE THREAD

**Issue by rcrehuet** [Acellera/htmd#245]
This may seem a very simple question, but is there a way to save the state of a Molecule object (including all the associated files). For example, once I have done the setup, after calling `solvate` or `amber.build` I get a Molecule object. How should it be saved so that I can load its full state in a new session? (I am afraid Pickle is not the right option here, and `Molecule.write` only write a coordinate file)

**Comment by j3mdamas** [comment]
Hi,

What are you trying to achieve? `Molecule.write` saves you the coordinates. Everything else from `amber.build` is saved in the `outdir` of that function.

**Comment by rcrehuet** [comment]
OK, I see, so all the needed files are in the `outdir` directory and the user need not care about their names or anything else. So that when I equilibrate I just need to give that directory:
```
md = Equilibration()
md.write('path_where_I_built','path_to_equilibration_files')
```
And then, to run a production run I simple do:
```
md = Production()
md.write('path_to_equilibration_files','path_to_production_files')
```
Of course I can fine tune and configure all these md objects.

**Comment by j3mdamas** [comment]
Exactly. The `write` method will take the information from the path you provide and do the rest.

**Comment by stefdoerr** [comment]
Indeed @j3mdamas is right. Also nearly all information in the molecule can be written in a PDB file. Excluding trajectory frames in which case you could write a PDB and then an XTC and that should contain all info.
We try not to store information in the Molecule that is not contained in a PDB file, with some minor edge cases which you probably should not care about.

**Comment by rcrehuet** [comment]
I disagree. One clearly needs also information about the topology and the force field parameters. That was what I was asking. But I see that this is automatically seached for.
What if I modify the file names with (as done [here](https://www.htmd.org/docs/latest/tutorials/mu-opioid-receptor-gpcr-equilibration.html))?
```
md.acemd.bincoordinates = 'output.coor'
md.acemd.extendedsystem  = 'output.xsc'
 ```
If I want to extend that run, I guess I need to specify this file names again.

**Comment by stefdoerr** [comment]
Ah yes but that information is never stored in a molecule object. It's stored in files in the build folder.

`md` being the production or equilibration run? What do you mean by extending the run?

**Comment by stefdoerr** [comment]
The tutorial is a bit old. Production protocol v4 should detect those automatically and rename them to input.coor/xsc
