### ISSUE TITLE
Can solvate be used with molecules other than water?

### ISSUE THREAD

**Issue by lmanubens** [Acellera/htmd#248]
Hi,

From the documentation of the solvate module I wonder whether a protein can be solvated with molecules different than water. 

Should the following arguments allow to tweak the module for doing it?
spdb (str) – The path to the water pdb file
spsf (str) – The path to the water psf file
stop (str) – The path to the water topology file

https://www.htmd.org/docs/latest/htmd.builder.solvate.html

I tried, but it seems it's not the case. I guess I'll have to do it manually, but just wanted to check.

Thanks!

[eyfp_solv.tar.gz](https://github.com/Acellera/htmd/files/747513/eyfp_solv.tar.gz)

**Comment by stefdoerr** [comment]
Theoretically should be possible. I will need to take a look at it later. Thanks for the files

**Comment by stefdoerr** [comment]
Okay there was a small bug which I fixed.

But are you sure you are doing this correct? You want to solvate the protein in 4000 molecules? The same ones you want to bind?

Also after the fix the code is a bit slow because it's trying to replicate individual molecules. Normally we replicate a whole water box, not individual water molecules. There might be some optimization possible there though.

**Comment by lmanubens** [comment]
No, sorry, I just played a bit with the size of the box in order to see if it was the problem.
I will also follow your advice and replicate solvate boxes in case I wanted big systems.

Thanks a lot!

**Comment by stefdoerr** [comment]
Well the bug is fixed on github but not on a htmd release yet. But the bug only pops up when you try to create more than 1000 copies of your solvent box. So under normal circumstances it should not crash, and with the new htmd version it's fixed.
Thanks for finding the bug though :)

**Comment by j3mdamas** [comment]
@lmanubens I just did a release before @stefdoerr fixed this. there will be a new release with this fix next week :)

**Comment by lmanubens** [comment]
Okok, thanks both!
