### ISSUE TITLE
amber capping

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#25]
Hi guys,

I was given this protein [attached] which I have to run in Amber.:

```
protein=Molecule('protein.pdb')
protein.filter('protein and noh')
protCaps = autoSegment(protein,'protein','P')
protCaps.center()
D = maxDistance(protCaps, 'all') 
solvated = solvate(protCaps,minmax=[[-D, -D, -D], [D, D, D]])
ffs = ['leaprc.lipid14', 'leaprc.ff14SB', 'leaprc.gaff']
molbuilt = amber.build(solvated, ff=ffs, outdir='.', saltconc=0.15)
```

I try to build it and get this error:
```
Videos from the HTMD2015 workshops are available on the Acellera youtube channel: https://www.youtube.com/user/acelleralive

You are on the latest HTMD version (1.0.16).
Solvating: 100% (1/1) [#########################################################################################################################################################################################################] eta --:-- -
Traceback (most recent call last):
  File "./1.build.py", line 36, in <module>
    molbuilt = amber.build(solvated, ff=ffs, outdir='.', saltconc=0.15)
  File "/path/to/htmd/lib/python3.5/site-packages/htmd/builder/amber.py", line 109, in build
    _applyCaps(mol, caps)
  File "/path/to/htmd/lib/python3.5/site-packages/htmd/builder/amber.py", line 216, in _applyCaps
    raise AssertionError('Segment {}, resid {} should have either one H2 or one HT2 atom. Cannot cap.'.format(seg, np.min(resids)))
AssertionError: Segment P, resid 1 should have either one H2 or one HT2 atom. Cannot cap.
```

So I was wondering what are the conditions of a correct protein to be capped?

[protein.txt](https://github.com/Acellera/htmd/files/252698/protein.txt)

**Comment by noeliaferruz** [comment]
Oh, FYI, it actually runs fine in Charmm. I'll change the issue name.

**Comment by j3mdamas** [comment]
Process it through `prepareProtein` and let me know if it solves it.
I think `tleap` may be more picky than `psfgen` regarding the capping.
Regarding AMBER, we're currently improving the integration to it, going through test phase.

**Comment by stefdoerr** [comment]
We mentioned this in another issue. Maybe we should add it to the documentation.
If you don't have hydrogens tleap cannot cap. Our only way of adding hydrogens before building right now is through `prepareProtein` as Joao said.

**Comment by stefdoerr** [comment]
Noelia, I assume you built systems in the past with Amber. Do you remember how you added the caps? Because when I looked around the only solution that was mentioned around was replacing some atoms (one hydrogen and somethin else I think) from the terminal residues with an atom of the cap.

**Comment by noeliaferruz** [comment]
Thanks guys. Passing it through prepareProtein solved it. 

@stefdoerr yes that's the only option I think I knew of. Replacing the terminal atoms with one NME and ACE atoms respectively and tleap doing the rest.

i think I can close it.
thanks
