### ISSUE TITLE
Adding Cholesterols to a protein

### ISSUE THREAD

**Issue by waskom** [Acellera/htmd#254]
Hello,

I have been trying to add cholesterol molecules to sites on a protein that have been shown to bind to cholesterol on crystal structures. I keep getting issues with HTMD during the building process, which keeps crashing when trying to call the cholesterol molecules. I have tried to have the molecules in the same pdb as the protein and i have tried to call it in like a ligand but nothing seems to work. What is the recommended course of action to call the lipids in the build script?

Thank you,
Mike

**Comment by j3mdamas** [comment]
Hello Mike,

Can you please show us what kind of output you are getting? And also the commands you're running.

**Comment by waskom** [comment]
<img width="1100" alt="screen shot 2017-02-13 at 12 50 27 pm" src="https://cloud.githubusercontent.com/assets/20097577/22895610/20d2e3e0-f1eb-11e6-9528-cbab0729d07d.png">

**Comment by waskom** [comment]
This is where I added the cholesterols to the pdb file with the protein. I have had numerous different errors when doing this. I have added the " and rename CHR". If it is "not resname CHR" it will finish. If the cholesterols are not there, it will finish.

**Comment by j3mdamas** [comment]
See the info: `Removed XXXX atoms. 0 atoms remaining in the molecule`

You should be using `ors` instead of `ands` in the VMD selection. See more here: https://www.htmd.org/docs/latest/atom-selection.html

**Comment by waskom** [comment]
Ok. I will try this. Thank you.

**Comment by waskom** [comment]
Im still having problems. Specifically, I can get it to run through the commands but the cholesterol is missing in the final structure for equilibration. 

If I am following the build script for a protein in a membrane, could i get some advice on how to set up the commands?
1. I will need to essentially place the cholesterol between the protein and the lipid.
     Will I need to put this command before the command to put it in the lipid bi layer?
   I called it like a ligand, but I also need to put an actual ligand in the binding pocket.

2.I am unsure of the correct phrasing to have both. I.e. they both cannot be defined as a lig. (or can they?).
3. Resname for cholesterol? Im fairly certain that the parameters for this molecule is in the library already. In the pdb for the coordinates of cholesterol should the resname be CHL1? I have been playing with multiple variations with little success. 

Any advice on how to set this system up would be appreciated.

Mike

**Comment by stefdoerr** [comment]
Without seeing the script or at least an output file we cannot help you much.

1. Yes I would first add the cholesterol and then embed it into the membrane
2. I don't understand what you mean with phrasing. You can assign the ligand and the cholesterol to different segments
3. You will need to read up on the CHARMM forcefield files on what the resname for cholesterol is. I assume you want to look in this file `lipid/toppar_all36_lipid_cholesterol.str` which you can find in the directory that `charmm.listFiles()` points you at

**Comment by stefdoerr** [comment]
Edit: yes the resname for cholesterol is CHL1 but you will need to add the abovementioned stream file to your charmm.build command like this:
`charmm.build(..., stream=['lipid/toppar_all36_lipid_cholesterol.str',], ...)`
Then it will know to search for CHL1 in there

**Comment by waskom** [comment]
<img width="1109" alt="screen shot 2017-02-14 at 12 21 47 pm" src="https://cloud.githubusercontent.com/assets/20097577/22940551/4416095c-f2b0-11e6-82f4-cccf9846c84e.png">

**Comment by waskom** [comment]
I have been trying to call the python commands like this. Calling the protein 1st, the ligand second, and the cholesterol molecule 3rd. The script runs but the compiled pdb file doesn't contain the ligand or the cholesterol. 

When I comment out the protein, and the lipid ( to put it in a box of water), i get "NameError: name 'mol' is not defined" as an error. But this error doesn't occur in the script if the protein is called before hand as seen in the script above.

**Comment by j3mdamas** [comment]
1) the `filter` you are using is rather convoluted. I assume that you just want to filter the protein, so why not simply `prot.filter('protein and noh')` (and the `noh` is only useful if you want to get rid of existing hydrogens).
2) you are using `mol.append(lig)`, while there is no `mol` instance defined (that we can see). Did you mean `prot.append(lig)`?
3) what's going on with `newprot`? that is not being used anywhere.

**Comment by waskom** [comment]
I updated the script with the changes that you recommended and it seems to have worked as expected. Thank you very much for your help.

**Comment by j3mdamas** [comment]
np
