### ISSUE TITLE
Conda update htmd not getting latest version

### ISSUE THREAD

**Issue by jeiros** [Acellera/htmd#256]
Hi,
I've installed htmd under a Python 3.4 environment in a CentOS 7 64 bit machine. `conda install htmd` works fine and so does `import htmd` in python. Nevertheless, after the import I get the following prompt:
```
$ python
Python 3.4.5 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:47:47)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import htmd

Please cite HTMD: Doerr et al.(2016)JCTC,12,1845. https://dx.doi.org/10.1021/acs.jctc.6b00049

HTMD Documentation at: https://www.htmd.org/docs/latest/

New HTMD version (1.5.15) is available. You are currently on (1.0.24). Use 'conda update htmd' to update to the ne.
```
But updating doesn't seem to work:
```
$ conda update htmd
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/je714/anaconda3/envs/htmd:
#
htmd                      1.0.24                   py34_0    acellera
```
(I've also tried `conda update -c acellera htmd` with the same result.)

Any idea on what's the channel to use to get the latest version of htmd?

**Comment by stefdoerr** [comment]
To me conda is a mystery to me some times. The solution to that mystery most of the time is doing a fresh miniconda install. 

If the channel is right maybe you still need to remove the omnia channels?
`conda config --remove channels omnia`

Or wait, maybe someone has a better suggestion

**Comment by j3mdamas** [comment]
We no longer package for py34 (last time was for 1.0.26, don't know why yours is not updating to that version).

If you want recent versions of HTMD, please create a py35 environment (or update your environment to py35)

**Comment by j3mdamas** [comment]
@stefdoerr maybe we could put a pyXX next to the version? I didn't check the check_versions function

**Comment by stefdoerr** [comment]
Hm but then 3.4 users would not know about new versions?
We could possibly report for which python version the version is available so that some people might notice the discrepancy?

**Comment by j3mdamas** [comment]
your second question is exactly my point. not a priority though.

**Comment by stefdoerr** [comment]
I can look into it tomorrow

**Comment by jeiros** [comment]
Thanks, used a new env with python 3.5 and now I have the latest version. I'm running into issues with docking, which weren't showing up in the old version. Will open an issue about it.
