### ISSUE TITLE
input file error

### ISSUE THREAD

**Issue by KendyP** [Acellera/htmd#260]
Hello,
I'm attempting to equilibrate a solvated and ionized RNA and protein system. I built my system and generated an equilibration directory with htmd in an ipython notebook. When I attempted to run equilibration, I received an error indicating invalid syntax in the first line. The first line does not deviate from previous successfully run input files generated in the same manner.
A link to a dropbox folder is provided so that you may see the notebook used, equilibration directory with the input file in question, and .txt file of the error. 

https://www.dropbox.com/sh/d9h1rnn4007v7ba/AAD3d3XTDGMship5L6J_9in5a?dl=0
Any assistance with this issue is appreciated. Thank you in advance. 
-Kendy

**Comment by j3mdamas** [comment]
Hi @KendyP,

There's no notebook on the dropbox. The error does seems weird, but I'd like to see the entire output.

Running the input.txt manually with acemd gives me no problems, so I'll need more info to see if this is a HTMD bug or maybe a script typo.

João

**Comment by KendyP** [comment]
My apologies. I have updated the dropbox folder now. Let me know if there are other issues or you need any other files. I appreciate your promptness in helping to resolve the issue.

**Comment by j3mdamas** [comment]
The notebook runs fine, as I would expect.

When do you get the error? How are you running the simulation? Are you running the `run.sh` script manually?

Can you give me more information? I continue to be able to run your system.

**Comment by KendyP** [comment]
This issue can be closed. It appears as though there was an issue with the queue I was submitting the job to. I have never had the issue before and thought it may have been with something in HTMD. I appreciate you looking into this. I apologize for wasting time.
