### ISSUE TITLE
Guessing correct elements

### ISSUE THREAD

**Issue by stefdoerr** [Acellera/htmd#263]
proteinPrepare for example guesses wrong elements. Some file formats don't have elements.

Elements are important because their radii are used to guess bonds. So setting them to nothing creates problems in many parts of HTMD such as atomselect, build etc.

We need to find a better way of guessing the elements. I have a `_guessElements` in `Molecule` but for the moment it only guesses Babel elements while we want PDB elements. We should investigate what the best way of guessing PDB elements is.

**Comment by stefdoerr** [comment]
Actually I have an element guesser for PDB elements. Look at this for example:

```python
In [46]: mol = Molecule('3PTB')
In [47]: mol.filter('protein')
In [48]: mol = proteinPrepare(mol)
In [49]: z = mol.element.copy()
In [50]: mol.element[:] = ''
In [51]: y = np.array(mol._guessElements(), dtype=object)
In [52]: z[np.where(z != y)]
Out[52]: 
array(['N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N',
       'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N'], dtype=object)
In [53]: y[np.where(z != y)]
Out[53]: 
array(['O', 'C', 'C', 'O', 'C', 'C', 'O', 'O', 'O', 'O', 'O', 'C', 'C',
       'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O'], dtype=object)
In [54]: mol.name[np.where(z != y)]
Out[54]: 
array(['OD1', 'CD2', 'CE1', 'OE1', 'CD2', 'CE1', 'OE1', 'OD1', 'OD1',
       'OD1', 'OE1', 'CD2', 'CE1', 'OD1', 'OD1', 'OD1', 'OE1', 'OD1',
       'OD1', 'OD1', 'OE1', 'OD1'], dtype=object)
```

proteinPrepare sets all these oxygens and carbons to nitrogens. My element guesser fixes it. Maybe we should call it by default?

**Comment by j3mdamas** [comment]
I guess that the reason why `pdb2pqr` outputs trash element-wise is due to the [PQR format](http://www.poissonboltzmann.org/docs/file-format-info/#pqr) not having an element field.

I think we shouldn't be calling it by default (we want it to keep the original stuff by default, I think), but rather to the output of `pdb2pqr` specifically.

**Comment by stefdoerr** [comment]
No, the function only guesses elements which don't exist already unless I specify otherwise. So we could still use it on PDBs in case they are missing elements

**Comment by j3mdamas** [comment]
Sounds good. But for `proteinPrepare` output it should be doing over everything by default, right?

**Comment by stefdoerr** [comment]
Yeah. For that one I would re-guess them all

**Comment by stefdoerr** [comment]
Done for proteinPrepare https://github.com/Acellera/htmd/commit/f6f98645985d8ef14b9a246ccc49a14eb5b1010b

I will add it now to the pdb reader as well.

**Comment by stefdoerr** [comment]
Complete https://github.com/Acellera/htmd/commit/d9efc7ff93d7bb53b3419546386637716d80f86e. Now all topology files will have missing elements guessed.
