### ISSUE TITLE
htmd-data dependencies

### ISSUE THREAD

**Issue by tonigi** [Acellera/htmd#264]
I get this problem (also on  travis). Possibly it will be solved making htmd-data noarch.

```
[toni@pcgiorgino conda-pdb2pqr]$ conda install htmd-deps
Fetching package metadata ...............
Solving package specifications: .


UnsatisfiableError: The following specifications were found to be in conflict:
  - htmd-deps -> htmd-data 0.0.43 -> python 3.5* -> openssl 1.0.1*
  - htmd-deps -> htmd-data 0.0.43 -> python 3.5* -> xz 5.0.5
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

```

**Comment by tonigi** [comment]
Attempt at the noarch package 373c3b8da2853eae188f624c5b2ceb185ebfca26

**Comment by stefdoerr** [comment]
you have python 3.6 I guess no? We don't have a release for that due to the propka issue with dicts

**Comment by j3mdamas** [comment]
Yes @stefdoerr is right. We can only release py3.6 after propka issue is solved.

**Comment by j3mdamas** [comment]
I'll close this issue and open a new one on dependencies revision
