### ISSUE TITLE
broken I/O of overflowing resids 

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#268]
Writting also breaks resid (insertion overflows)

Test trajectories of acecmd ISBA.

**Comment by stefdoerr** [comment]
This doesn't seem like a bug from our side. If it overflows we are supposed to read it as insertion. The problem is the PDB file that is written badly. It's an old simulation with Thrombin so I don't know who wrote that file but it's broken.

**Comment by j3mdamas** [comment]
so maybe we can replace the test files for non-broken ones?

**Comment by stefdoerr** [comment]
I won't bother but if you feel like it ok. It doesn't affect the results in any way
