### ISSUE TITLE
Molecule.get('coords') returns wrong shape on 1-atom Molecules

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#269]
Finding bugs on the path to fix rotations :D

```
m1 = Molecule()
m1.empty(1)
m1.get('coords').shape
```
Gives: `(3,)`

```
m2 = Molecule()
m2.empty(2)
m2.get('coords').shape
```
Gives: `(2, 3)`

I'm quite sure it's because of the `np.squeeze` on https://github.com/Acellera/htmd/blob/master/htmd/molecule/molecule.py#L369. What is it's purpose? Can't it be removed? Maybe I'm missing something.

**Comment by j3mdamas** [comment]
More importantly, also returns wrongly on 1-atom selections of multiple-atom Molecules

**Comment by stefdoerr** [comment]
It's annoying to handle those cases as they require a separate `if` and `np.newaxis` and cannot be done with `np.atleast_2d` but ok I'll fix it. Really minor though I'd say

**Comment by stefdoerr** [comment]
Squeeze should not be removed. the returned array should be 2D from get. Not 3D

**Comment by j3mdamas** [comment]
That's why I put bug:low :)

It errors for example when one want to do `Molecule.center(sel='selection with one atom')` which is something not common, but not weird either.
