### ISSUE TITLE
No module named protocolinterface

### ISSUE THREAD

**Issue by jeiros** [Acellera/htmd#272]
Hi everyone, 

I've made a fresh conda environment with python 3.5 and a full anaconda installation. After, I've installed htmd with `conda install htmd -c acellera`
But `import htmd` fails in the python interpreter:
```
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import htmd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/je714/htmd/htmd/__init__.py", line 26, in <module>
    from htmd.adaptive.adaptiverun import AdaptiveMD
  File "/home/je714/htmd/htmd/adaptive/adaptiverun.py", line 9, in <module>
    from htmd.adaptive.adaptive import AdaptiveBase
  File "/home/je714/htmd/htmd/adaptive/adaptive.py", line 20, in <module>
    from protocolinterface import ProtocolInterface, val
ImportError: No module named 'protocolinterface'
```
Doing `conda install protocolinterface -c acellera` fixed the error (protocol interface v.0.1.3 is installed). Just reporting on this, as shouldn't it be downloaded automatically if it's a dependency for htmd to work?

Cheers,

Juan

**Comment by stefdoerr** [comment]
yeah I just faced this issue now. It happens if you start with python 3.6 and downgrade to 3.5. Then the package is installed for 3.6 but 3.5 can't see it. Either do:
````
conda uninstall protocolinterface
conda install protocolinterface
```
or wait ~30 minutes when there should be a new 3.6 version of HTMD which you can install on a new miniconda install for example.

**Comment by jeiros** [comment]
OK I'll wait :) Python 3.5 is the recommended python version to be using with htmd, right?

**Comment by j3mdamas** [comment]
Soon it will be py36, as we like to keep up with the conda defaults.

**Comment by stefdoerr** [comment]
As Joao says.

As far as I can tell 3.5 and 3.6 should be equivalent. I mean till now we worked with 3.5 so it's safer but there weren't big changes in python. The reason we didn't have a release for it was that a few of our tests needed some really annoying tweaking, but the user experience should be the same.

**Comment by jeiros** [comment]
Ok thanks! Last question: I've seen the `htmd-stable` package when I do `conda search htmd`.

Should we be using that one as end users?

**Comment by j3mdamas** [comment]
End users should be using htmd package, as it is the one under development and has most features.

**Comment by j3mdamas** [comment]
There is also a package called `htmd-latest`, if I'm not mistaken, which is synced to the last `htmd`

**Comment by stefdoerr** [comment]
Ok 1.7.2 for py36 is out!

**Comment by stefdoerr** [comment]
Hm actually I reopen this. I can't manage to install htmd on 3.6

```bash
[sdoerr@loro Thu14:33 bin] ./conda update htmd
Fetching package metadata .............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /shared/sdoerr/tmp/miniconda:
#
htmd                      0.1.39                        0    acellera
[sdoerr@loro Thu14:33 bin] ./conda install htmd=1.7.2
Fetching package metadata .............
Solving package specifications: 


PackageNotFoundError: Package not found: Conda could not find '

```

**Comment by stefdoerr** [comment]
Pfff I don't have time to sort this out right now. @jeiros better try my initial suggestion till we fix this dependency hell.

```bash
[sdoerr@loro Thu14:34 bin] ./conda install htmd-deps
Fetching package metadata .............
Solving package specifications: .


UnsatisfiableError: The following specifications were found to be in conflict:
  - htmd-deps -> htmd-data 0.0.43 -> python 3.5* -> openssl 1.0.1*
  - htmd-deps -> htmd-data 0.0.43 -> python 3.5* -> xz 5.0.5
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

```

**Comment by j3mdamas** [comment]
@jeiros, it's undergoing. We'll close this issue when there's a working version.

**Comment by jeiros** [comment]
Ok, no worries. Thanks for taking a look into it 😄

**Comment by stefdoerr** [comment]
My god, it works on 3.6. I feel like a conda/travis magician. Have fun!

```
>>> ./conda install htmd
    htmd:               1.7.5-py36_0       acellera
    htmd-data:          0.0.45-py_0        acellera
    htmd-deps:          1.7.5-py36_0       acellera
```

**Comment by stefdoerr** [comment]
Ah forgot to mention a caveat. openbabel doesn't exist for 3.6 meaning that our `dock` function will probably fail.

**Comment by j3mdamas** [comment]
Unless you have your own babel installed manually and on the PATH, which HTMD should detect

**Comment by stefdoerr** [comment]
Check here for possible problems with 3.6
https://github.com/Acellera/htmd/issues/273#issuecomment-285381384

**Comment by stefdoerr** [comment]
If you update htmd the dependencies should be up-to-date now, except for openbabel. The rest should work
