### ISSUE TITLE
Revise HTMD dependencies

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#273]
We need to revise the dependencies that we have:

* which ones are necessary
* are all of them available on all architectures we are trying to build?
* if not, what to do?

**Comment by j3mdamas** [comment]
@stefdoerr, can you put here your findings during the releasing of py36 HTMD?

**Comment by stefdoerr** [comment]
1. openbabel doesn't exist in 3.6 so it pulls a 0.0.0 version which is probably broken

**Comment by stefdoerr** [comment]
nglview is up to us to make a new release (preferably noarch since theirs is noarch as well)

**Comment by j3mdamas** [comment]
Their noarch version has 1 hour xD https://anaconda.org/bioconda/nglview/files

**Comment by j3mdamas** [comment]
We just need to do the sync, I guess?

**Comment by stefdoerr** [comment]
Doing it right now

**Comment by j3mdamas** [comment]
A way to make this transition better for the users, is to fix the Miniconda3 installer to 4.2.12, which installs python 3.5 by default. What do you think, @stefdoerr?

**Comment by j3mdamas** [comment]
Fix in the installation page

**Comment by stefdoerr** [comment]
No, next version (in 30 minutes) will work fine on 3.6 as far as I can tell. Minus maybe the babel thingy

**Comment by stefdoerr** [comment]
Ok synced the deps and am making a 1.7.6 version

**Comment by stefdoerr** [comment]
Only missing the openbabel dep but at least nglview should work fine

**Comment by j3mdamas** [comment]
OK, I'll look into what can be done with openbabel, and then close this issue.

**Comment by stefdoerr** [comment]
We should probably switch to the official openbabel conda channel. It has the latest version including 3.6 version:
https://anaconda.org/openbabel/openbabel/files
