### ISSUE TITLE
proteinPrepare ValueError: too many values to unpack

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#281]
Opening on behalf of @shozebhaider

> Dear Joao
>
> The following error has returned in the latest version when you use proteinPrepare. I know this problem was addressed earlier and was attributed to the incompatibility of pdb2pqr/propka. Is it still the same thing? I thought I shall let you folks know.
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-bd47414dcbe7> in <module>()
      1 
----> 2 mol_op, prepData = proteinPrepare(mol, returnDetails=True)

/usr/local/htmd/htmd/builder/preparation.py in proteinPrepare(mol_in, pH, verbose, returnDetails, hydrophobicThickness, holdSelection)
    266                                                              ph_calc_method="propka31",
    267                                                              ph_calc_options=propka_opts,
--> 268                                                              holdList=hlist)
    269     tmpin.close()
    270 

ValueError: too many values to unpack (expected 4)
```

@shozebhaider, can you tell us about htmd version, operative system, python version?

**Comment by j3mdamas** [comment]
Possibly related #200

**Comment by j3mdamas** [comment]
@tonigi

**Comment by tonigi** [comment]
Pdb2pqr version


Il 17 mar 2017 5:28 PM, "João M. Damas" <notifications@github.com> ha
scritto:

**Comment by shozebhaider** [comment]
htmd-pdb2pqr  2.1.2

**Comment by tonigi** [comment]
Upgrade please. Although installing htmd-deps SHOULD fix it.

Il 17 mar 2017 6:53 PM, "shozebhaider" <notifications@github.com> ha
scritto:

**Comment by shozebhaider** [comment]
Reinstalled the latest htmd 1.7.13 version and updated to htmd-pdb2pqr 2.1.2+htmd3.
htmd-deps also installed. Still same error.

**Comment by tonigi** [comment]
Ok no version s correct, but  there could be leftovers, either of htmd, or
previous pdb2pqr.

Is seems that you are using  htmd installed in /use/local, which is a bit
strange (possibly old version).

T

Il 17 mar 2017 7:22 PM, "shozebhaider" <notifications@github.com> ha
scritto:

Reinstalled the latest htmd 1.7.13 version and updated to htmd-pdb2pqr
2.1.2+htmd3.
htmd-deps also installed. Still same error.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Acellera/htmd/issues/281#issuecomment-287433723>, or mute
the thread

**Comment by j3mdamas** [comment]
@shozebhaider, it's annoying, but sometimes the best way to approach this is to do a fresh conda installation.

**Comment by tonigi** [comment]
Before reinstalling, check that you have only one copy around.

Il 17 mar 2017 8:20 PM, "João M. Damas" <notifications@github.com> ha
scritto:

**Comment by shozebhaider** [comment]
Thanks Joao and Toni. Completely removed everything before reinstalling again. However, some ghost remnants of miniconda still lurk around which is baffling me no end. In any case, thanks for the help.

**Comment by tonigi** [comment]
But.. is it solved? Shall we close the issue?

**Comment by shozebhaider** [comment]
Yes it is solved. 

Best Wishes

Shozeb
