### ISSUE TITLE
Broader metrictypes in adaptive

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#29]
Not really an issue, but I was wondering if it would be interesting to have different metrics other than contacts and distances during the adaptive.

Besides, what happened to a secondary-structure driven adaptive that I recall from the past? Did that work? @stefdoerr  (Did that exist?)

**Comment by stefdoerr** [comment]
Yes, I had my own version of adaptive which accepted any kind of metrics. The Bowman came out with http://www.ncbi.nlm.nih.gov/pubmed/26588361 which is pretty much what I had done and I gave up on it. 
Realistically though we should implement this method because it seems very efficient.

**Comment by tonigi** [comment]
You may want to try the plumed2 metric. Supports really many.

**Comment by j3mdamas** [comment]
They also published a "Methods in Enzymology", don't know how much more information it may have than the paper.

http://www.sciencedirect.com/science/article/pii/S0076687916300672

**Comment by stefdoerr** [comment]
https://github.com/multiscalelab/htmd/commit/2d96dc78f6d0197f476d62b61349ce898abe9977
Done. Any metric type can be used in `AdaptiveRun2` now.

Bowman's FAST not yet implemented. Will come as a separate class I think
