### ISSUE TITLE
Travis yml cleanups

### ISSUE THREAD

**Issue by tonigi** [Acellera/htmd#290]
Some travis features may have changed syntax and don't pass [lint](http://lint.travis-ci.org/) tests, e.g.

    in matrix.include section: unexpected key language, dropping
    in matrix.include section: unexpected key before_install, dropping
    in matrix.include section: unexpected key addons, dropping
    missing key language, defaulting to ruby

(mostly a reminder)

**Comment by j3mdamas** [comment]
what's this @tonigi? do we close?

**Comment by tonigi** [comment]
it's warnings from travis about obsolete or wrong syntax... we can close
