### ISSUE TITLE
Amber.build adds a massive salt concentration

### ISSUE THREAD

**Issue by piia600** [Acellera/htmd#291]
Hi,

I used Amber build with command 

`molbuilt = amber.build(smol, outdir='./build/', topo=['subs.prepi'], param=['bodipy.frcmod', 'frcmod.ionsjc_tip3p'], saltconc=0.1) `

for a solvated structure with about 20000 water molecules (~40x40x40 A) box. 

`2017-03-29 11:16:31,682 - htmd.builder.ionize - INFO - Adding 0 anions + 11 cations for neutralizing and 74 ions for the given salt concentration.`

Isn't this too much (I calculated this concentration to be around 2.4 M)? I have used systems of this size before and the ion amounts have been around 20 and not 80...

**Comment by stefdoerr** [comment]
What's the number of waters?
The formula for calculating the ions is:
`num = int(np.floor(0.5 + 0.0187 * saltconc * nwater)) * 2`

**Comment by stefdoerr** [comment]
To get the number of waters you can do:
`np.sum(mol.atomselect('water and noh'))`

**Comment by piia600** [comment]
The number of waters is 20948. Based on that the equation seems to work...

**Comment by stefdoerr** [comment]
What might be confusing is that this is **salt** concentration and not individual ion concentration which is double that? Sorry my chemistry is crap but I think that's the reason of the confusion.

**Comment by stefdoerr** [comment]
Also when comparing with other systems you should compare umber of waters not box size. The one might contain a bigger protein hence less waters and thus require less ions.
