### ISSUE TITLE
Redesign Acemd class

### ISSUE THREAD

**Issue by stefdoerr** [Acellera/htmd#292]
Right now if you write multiple protocols i.e. Production inside a loop like here: 

https://www.htmd.org/docs/latest/tutorials/docking-simulation-generators.html

it will not work because the Acemd class replaces it's own variables (bincoordinates from output.coor to input.coor) on the first write and then cannot find a file called `input.coor`.

**Comment by stefdoerr** [comment]
Also change the tutorial since it doesn't work

**Comment by j3mdamas** [comment]
Yes, when queues were stripped away from apps, the Acemd class (and the Pmemd classes for what matters) was left a bit orphan. It sure needs small redesign, and a new home (maybe something called mdengines module we discussed before)

**Comment by j3mdamas** [comment]
Stefan made a new Acemd3 class which fixes that problem. Still won't work for Acemd2.
