### ISSUE TITLE
Improve sync_conda_acellera script

### ISSUE THREAD

**Issue by stefdoerr** [Acellera/htmd#294]
Right now it only checks if the latest package versions are on acellera but it doesn't check if all architectures are there. 
For example in some cases people uploaded version 1.45 of a package for python 3.5 and after a week uploaded the one for python 3.6 same version 1.45. Then our script thinks that there is nothing to update since 1.45 is already on our channel.

**Comment by stefdoerr** [comment]
I'll combine this issue with the other one on changing the channel for openbabel as I'll just fix both in a single try.
https://github.com/Acellera/htmd/issues/273

**Comment by stefdoerr** [comment]
Fixed both here: https://github.com/Acellera/htmd/commit/dbd469e4742665dd41650f8ec15577f4f0472b49

**Comment by stefdoerr** [comment]
By the way I had to delete lots of old versions of packages from acellera omnia to make space for the new ones. When it fills up it just silently refuses to upload which is very frustrating to figure out the cause of the issue.

**Comment by j3mdamas** [comment]
@mj-harvey, is there a way to increase space in the acellera channel? maybe we need a clean-up?

**Comment by stefdoerr** [comment]
I'm also deleting all 2.7 packages since we won't ever use them

**Comment by j3mdamas** [comment]
that's good idea
