### ISSUE TITLE
change travis yml to error on failure to upload to anaconda

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#297]
If the upload fails due to lack of space, the Travis build still shows as successful. This should not be the case.

**Comment by j3mdamas** [comment]
It's hard to test. An idea, is to fill up my own anaconda account, and do some tests on that.

Also important to test if the `after_success` is the right section to upload (maybe Travis does not show a fail there)

**Comment by stefdoerr** [comment]
Tested it on my own account. Should work ok with this check.The upload returns exit code 1 when it fails and 0 otherwise despite not printing anything.
