### ISSUE TITLE
Parametrize speed

### ISSUE THREAD

**Issue by tonigi** [Acellera/htmd#299]
Is there anything that can be tweaked for speed (different level of theory, initial guesses, memory)? This 27-atom molecule https://files.rcsb.org/ligands/view/833_model.sdf takes hours.

**Comment by j3mdamas** [comment]
See the tutorial on tips for speed: https://www.htmd.org/docs/latest/acetk/parameterize/parameterize-tutorial.html

**Comment by j3mdamas** [comment]
`--vacuum` is one of my favourites if speed is an issue
