### ISSUE TITLE
plotFES

### ISSUE THREAD

**Issue by slovera** [Acellera/htmd#303]
Hi,

When I am plotting (model.plotFES) choosing a cmap option, other than the default, it doesn't plot the states anymore and it gives this error: "str object is not callable".
e.g.
'''' model.plotFES(0, 1, temperature=298, cmap='Accent', states=True) ''''
Any advise?

Thank you,
Silvia

**Comment by j3mdamas** [comment]
Use `cmap=plt.cm.accent`
