### ISSUE TITLE
dock tries to use conda babel and fails

### ISSUE THREAD

**Issue by stefdoerr** [Acellera/htmd#305]
The babel we distribute on conda seems broken (segfaults). We should stop distributing it or at least not use it as the default for the `dock()` method

**Comment by stefdoerr** [comment]
Default babel also doesn't work as it removes lots of atoms and makes a mess when converting to pdbqt

**Comment by stefdoerr** [comment]
[2bpv.zip](https://github.com/Acellera/htmd/files/910148/2bpv.zip)

**Comment by hawk31** [comment]
Replacing babel with autodocktools in the `dock` module is a solution if the incorrect reading of .pdbqt files detailed in #306 is solved.

It is also the expected behavior.

**Comment by mj-harvey** [comment]
The only reason we ship openbabel is  to write pdbqts. 
Mgltools is the canonical tool for pdb->pdbqt, but it is python 2.7 only.
The porting may be a challenge, and the license may be too proscriptive.

**Comment by stefdoerr** [comment]
I checked a month ago the code in Mgltools involved in writing pdbqt files to see if I could extract the algorithm. It's really non-trivial. Not something I could reimplement in a week I think

**Comment by tonigi** [comment]
Can we ask users to install mgltools if they want to use docking? They do provide installers. http://mgltools.scripps.edu/downloads License is restrictive indeed.

**Comment by j3mdamas** [comment]
let's see if @stefdoerr change proposed in https://github.com/Acellera/htmd/issues/273#issuecomment-296264940 will solve this

**Comment by stefdoerr** [comment]
Trying it now. Openbabel seems to hate the `END` tag at the end of the PDB files, or the `END` after an `ENDMDL`. 
The official PDB format requires it: http://deposit.rcsb.org/adit/docs/pdb_atom_format.html 
`Each file should terminate with a line containing only the word END.`
But openbabel considers is an invalid molecule.

Also atom reordering back to original atom order is not working and is way too flimsy. I'm disabling it.

**Comment by stefdoerr** [comment]
@hawk31 if you want to use it before our next release tell me and I can help you set it up. At the next HTMD release it should work out of the box.

**Comment by hawk31** [comment]
Oh I hacked my way around. I can wait.

2017-04-24 11:12 GMT+02:00 Stefan Doerr <notifications@github.com>:
