### ISSUE TITLE
htmd config file

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#309]
Set variable `HTMD_CONFIG` file

Htmd by default check if it's set, if it is, it executes/reads the config

ProtocolInterfaced and extending the current config

Support for queue variables

**Comment by giadefa** [comment]
actually  it is not important to use protocol interface, as the config script is python as well, it could just set some variables in the queuing system

**Comment by j3mdamas** [comment]
I'll discuss it with @stefdoerr, but since we already have JSON reading into ProtocolInterface, I think that's the best option. Plus, JSON is relatively standard. This help us to standardize stuff and validate whatever the user has in the config file.

**Comment by giadefa** [comment]
But there is no reason to have json either in my view. What's the reason to
have a restricted interface?

**Comment by j3mdamas** [comment]
Closed by #312
