### ISSUE TITLE
Minimizing box dimensions

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#31]
Hi guys,

I know this is a question rather than an issue. 

I tried to minimize a huge simulation box. So I did:
`a=htmd.builder.builder.minimalRotation(systemCaps)`
Where the output was: 1.7853981634 which I thought it is the theta angle for the rotation around Z.
So then I tried:
```
b=htmd.rotationmatrix.rotationMatrix(z, a)
Traceback (most recent call last):
  File "./scripts/1.build.py", line 26, in <module>
    b=htmd.rotationmatrix.rotationMatrix(z, a)
NameError: name 'z' is not defined
```
Also tried` axis=z` or a number (2, as I thought x could be 0 and y could be 1. Just to try XD)
How do I specify the axis? Besides, is this the correct way to find the matrix for my optimal rotation?

Do you think having an example after each function in the documentation would be worth?

**Comment by stefdoerr** [comment]
Yes, examples should and will be added. The thing is that minimalRotation is still a bit new and I don't trust it incredibly much.

`rotationMatrix([0, 0, 1], theta)` I think is how rotationMatrix is used.

**Comment by noeliaferruz** [comment]
Thanks, that gave me a matrix which I could pass to rotateBy.
The protein rotated but the system is the same size though (100K)
So tried to optimize the box size in maestro and it performed a different rotation, but I get similar number of atoms.
My question is,  why are we not rotating a long the the z axis as well? Is it because we're using cubic boxes? In my imagination it would make sense optimizing in the three dimensions but I'm probably not visualizing it correctly. 

I guess I can close the issue after -unless you want to have a look to minimalrotation and remind yourselves hahah-

**Comment by stefdoerr** [comment]
What do you mean? We only rotate along the z axis in membrane systems because rotating along x or y would change the orientation of the protein in the membrane which we assume is given correctly by OPM so we don't want to ruin it.

**Comment by noeliaferruz** [comment]
I don't have a membrane.

aaah I guess maestro's volume optimization wouldn't work for systems like ours,  because the protein could rotate at some point and touch itself in the other box.  I'm trying to figure out if minimalRotation can help to build smaller systems, but I guess it cannot as in any case we need to cover the maximal distance from center to the edge of the protein + solvation shell of minimum 4A.

ok, I think I understand. I think. xD.

Thanks.

**Comment by stefdoerr** [comment]
Yes the name of the function is bad. It only rotates along the z axis. We could consider making this a more complex function that does volume optimization with an option for membrane proteins and which would return a rotation matrix.
I'll add it to the todo list

**Comment by noeliaferruz** [comment]
It probably is good as it is, meaning that in any case the box will be cubic and any rotation would lead to the same box. (I'm thinking of protein-alone systems). So my search for an optimal box was a bit pointless ... hahah

**Comment by stefdoerr** [comment]
I am not understanding something here I guess but taking a straightened out protein and putting it on the box diagonal is much more optimal than putting it horizontal.

**Comment by j3mdamas** [comment]
Ideally, we'd use this: http://pubs.acs.org/doi/abs/10.1021/ct3000662
:smile:

**Comment by noeliaferruz** [comment]
That's what I thought initially, putting it in diagonal, exactly! But would that work? What if the protein alone moved during the simulations to the horizontal position, would it touch itself through boundaries? If it wouldn't then it's perfect!

**Comment by stefdoerr** [comment]
Well, it could and it does :stuck_out_tongue: But we have done such simulations before (NTL9, Ubiquitin) and as most proteins tend to collapse you only have a few cases usually at the start of the simulation where it interacts with itself.

More rigid elongated proteins of course would be a different subject.

**Comment by j3mdamas** [comment]
If the protein remains elongated (rigid, like stefan mentioned), it won't "touch" the periodic images. Only if there are major conformational changes (bending, etc).

In gromacs, one can use gmx mindist to check out minimum distances to the periodic images of the system along trajectories. Maybe something useful for HTMD?

**Comment by j3mdamas** [comment]
Forget about what I said, this is mainly related to Acemd anyway
