### ISSUE TITLE
move the acecloud  command line documentation to htmd.org

### ISSUE THREAD

**Issue by giadefa** [Acellera/htmd#318]
now is in docs.acellera.com

**Comment by j3mdamas** [comment]
In order to make the automatic documentation like parameterize, I need to change acecloud to argparse first (and clean syntax even before). Created issues on the corresponding repo.

The tutorial in ipynb and presentation mode is being prepared by @cuzzo87

**Comment by j3mdamas** [comment]
moved to: https://github.com/Acellera/software.acellera.com/issues/6
