### ISSUE TITLE
mol.dropFrame

### ISSUE THREAD

**Issue by PabloHNieto** [Acellera/htmd#321]
Hi,
executing the following code 

```
mol = Molecule('1sb0')
mol.dropFrames(keep = [1,2])
```
I got the error message
```
Traceback (most recent call last):

  File "<ipython-input-155-9afc47ada0e5>", line 2, in <module>
    mol.dropFrames(keep = [1,2])

  File "/shared/pablo/github/htmd/htmd/molecule/molecule.py", line 1258, in dropFrames
    self.box = np.array(np.atleast_2d(self.box[:, keep]))

IndexError: index 1 is out of bounds for axis 1 with size 1
```
But, despite this message the method drops the frames correctly 
(the 'drop' option works without problem)
Thanks,

Pablo

**Comment by stefdoerr** [comment]
Yeah I know that issue. The PDB reader should return a box of zeros of shape: [nframes, 3]. Joao can fix it since he likes self-assigning :stuck_out_tongue:

**Comment by j3mdamas** [comment]
ahah, yeah, I was looking at it, you can't be always solving these things :P

Yeah, the mistake is at the PDBReader level.
