### ISSUE TITLE
Multiple replicas metadynamics simulations on ACEMD

### ISSUE THREAD

**Issue by yiannisgaldadas** [Acellera/htmd#322]
Dear htmd users,

Has anyone ever tried to perform a replica exchange metadynamic simulation using ACEMD?
I am trying to find a tutorial or something regarding the format of the acemd input files 
but I cannot find anything even though in the manual it says that you can perform replica exchange 
metadynamics with plumed2. 
For instance, in Gromacs you generate a .tpr and a plumed.dat
file for each replica and using a command like to following 
> mpirun -np 4 gmx_mpi mdrun -s topol -plumed plumed -multi 4

Gromacs identifies all the .tpr and plumed files in the current directory. 
So I was wondering what is the equivalent "run" command to do the same in ACEMD. 
I tried to have separate input file for each replica and then submit all the jobs in different GPUs 
at the same time but it didn't work.

Best wishes,
Yiannis

**Comment by yiannisgaldadas** [comment]
Does anyone know if I need ACEMD Pro in order to run multiple replicas simulations?

**Comment by j3mdamas** [comment]
Yes, a ACEMD Basic license only allows running on 1 GPU

**Comment by j3mdamas** [comment]
So, if you don't have a Pro license, you won't be able to use replica exchange.

**Comment by j3mdamas** [comment]
Please, for ACEMD only related issues, non-related with HTMD, please post them here: https://github.com/Acellera/acemd_issues/issues

**Comment by yiannisgaldadas** [comment]
But still, how should the run command look like when you want to perform such a simulation?
Should somebody submit N jobs, where N is the number of replicas? Or should it be like
mpirun -np 8 acemd input_replica1 input_replica2 ... input_replica_N?

**Comment by j3mdamas** [comment]
Open a new issue on acemd_issues, and it will be addressed there

**Comment by yiannisgaldadas** [comment]
Thank you very much and apologies for posting it here!!
