### ISSUE TITLE
Molecule (write function) error

### ISSUE THREAD

**Issue by cuzzo87** [Acellera/htmd#325]
Trying to save a pdb from a trajectory I have noticed that the ```Molecule.write()``` wrongly assigns the last pdb column (element). In the specific case a chlorine was marked as carbon

**MD starting PDB**
```
ATOM   4289  CL1 MOL L   1     -22.200  17.880  48.460  0.00  1.00      L
```
**MD starting PSF**
```
4289 L        1        MOL      CL1      CLR1    -0.064000       35.4500           0
```

**PDB save from trj**
```
ATOM   4289  CL1 MOL L   1     -27.970  -7.410  15.650  0.00  1.00           C
```

**Comment by stefdoerr** [comment]
This is probably done during reading and not during writing. Can you check the element it's assigned inside the Molecule class after reading?

**Comment by j3mdamas** [comment]
@cuzzo87 feedback stefan

**Comment by j3mdamas** [comment]
@cuzzo87 wake up
