### ISSUE TITLE
htmd visualization (vmd)

### ISSUE THREAD

**Issue by cuzzo87** [Acellera/htmd#326]
I was trying to view a trajectory by using the ```Molecule.view()``` function but some weird connection are reported as visible in **Figure 1**. I save the current state and modified the molecules to be load to the original structure files. 
(Htmd creates tmp structure files that are loaded in the visualization). By looking at **Figure 2** the wrong connection are not reported

**Figure 1**
![htmd_vmd](https://cloud.githubusercontent.com/assets/10772443/25703351/853ab140-30d5-11e7-9fd9-6aa72ab4fcd2.png)

**Figure 2**
![same_state_vmd](https://cloud.githubusercontent.com/assets/10772443/25703456/f72bc820-30d5-11e7-87a5-9cc9f1f082d6.png)

**Comment by stefdoerr** [comment]
`mol.view(guessBonds=False)`
