### ISSUE TITLE
Broken links in tutorials

### ISSUE THREAD

**Issue by tonigi** [Acellera/htmd#331]
https://www.htmd.org/docs/latest/tutorials/protein-folding-analysis.html points to https://www.htmd.org/docs/latest/tutorials/protein-folding.py

https://www.htmd.org/docs/latest/tutorials/ligand-binding-analysis.html to https://www.htmd.org/docs/latest/tutorials/ligand-binding.py

which are missing.

**Comment by j3mdamas** [comment]
@cuzzo87 I think you're able to do this

**Comment by stefdoerr** [comment]
No leave them @cuzzo87 . I'm updating them.
