### ISSUE TITLE
Parametrization tutorial failing

### ISSUE THREAD

**Issue by edgarsanp** [Acellera/htmd#332]
Command used:

parameterize -m ben.mol2 -c 0 --no-esp --no-torsions -o ./param-ben-pass

Output:

Please cite HTMD: Doerr et al.(2016)JCTC,12,1845. https://dx.doi.org/10.1021/acs.jctc.6b00049

HTMD Documentation at: https://www.htmd.org/docs/latest/

You are on the latest HTMD version (1.7.31).

 === List of arguments used ===

       mol:  ben.mol2  
      list:  False     
    charge:  0         
       rtf:  None      
       prm:  None      
    outdir:  ./param-ben-pass
   torsion:  all       
     ncpus:  4         
forcefield:  all       
     basis:  cc-pVDZ   
    theory:  B3LYP     
    vacuum:  False     
     nomin:  False     
     noesp:  True      
 notorsion:  True      
      exec:  inline    
    qmcode:  PSI4      
   freezeq:  None      
   geomopt:  True      

 === Parameterizing ben.mol2 ===

 === Fitting for FF CGenFF_2b6 ===

Dihedral 0: 1-0-6-7
 Has equivalent dihedrals through symmetry: 
 Dihedral 5-0-6-7
Dihedral 1: 0-6-7-14
Dihedral 2: 0-6-8-15
 Has equivalent dihedrals through symmetry: 
 Dihedral 0-6-8-16
Got charge 0
Set charge 0
C1     C.3%6A CG2R61 C.3%6A
C2     C.3%6A CG2R61 C.3%6A
C3     C.3%6A CG2R61 C.3%6A
C4     C.3%6A CG2R61 C.3%6A
C5     C.3%6A CG2R61 C.3%6A
C6     C.3%6A CG2R61 C.3%6A
C7     C.3    CG2D1  !C.3(!C)(H.1)([^O])
N1     N.2    NG2D1  !N.2  
N2     N.3    NG321  N.3(H.1)(H.1)
H1     H.1    HGR61  H.1(C.3%6)
H2     H.1    HGR61  H.1(C.3%6)
H3     H.1    HGR61  H.1(C.3%6)
H4     H.1    HGR61  H.1(C.3%6)
H5     H.1    HGR61  H.1(C.3%6)
H6     H.1    HGP1   H.1(!N.2)
H7     H.1    HGP1   H.1(!N.3)
H8     H.1    HGP1   H.1(!N.3)
mol Success!
Net Charge: 0
Equivalent atom groups:
 C1
 C2 C6
 C3 C5
 C4
 C7
 N1
 N2
 H1 H5
 H2 H4
 H3
 H6
 H7 H8
Soft torsions:
 C2 C1 C7 N1
 C1 C7 N1 H6
 C1 C7 N2 H7

 == Minimizing ==

Running QM Calculations: 100% (1/1) [####################################################################################################] eta --:-- -
Traceback (most recent call last):
  File "/home/edgar/miniconda3/bin/parameterize", line 6, in <module>
    sys.exit(htmd.parameterization.cli.main_parameterize())
  File "/home/edgar/miniconda3/lib/python3.6/site-packages/htmd/parameterization/cli.py", line 180, in main_parameterize
    mol.minimize()
  File "/home/edgar/miniconda3/lib/python3.6/site-packages/htmd/parameterization/ffmolecule.py", line 163, in minimize
    raise RuntimeError("QM Optimization failed")
RuntimeError: QM Optimization failed

**Comment by j3mdamas** [comment]
`rm - r param-ben-pass` and run again

**Comment by j3mdamas** [comment]
`rm - r param-ben-pass` and run again

**Comment by j3mdamas** [comment]
Does it solve it?
