### ISSUE TITLE
PARAMATRIZE PROBLEM - babel: Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by ferpozo6** [Acellera/htmd#333]
I am trying to convert from sdf file to mol2. When I type this instruction on my command line:
`babel -isdf BEN_ideal.sdf -omol2 ben.mol2 `
the output generated is: 
`Illegal instruction (core dumped)`
**and I obtain an empty file called ben.mol2**

**Comment by stefdoerr** [comment]
Can you tell me the results of:
`which babel`
`conda list openbabel`
and 
`conda list htmdbabel`

**Comment by ferpozo6** [comment]
I have recently noticed of an installation error on my openbabel. I solved the problem making a reinstallation of it. 

Thanks !!

**Comment by stefdoerr** [comment]
Ok :) Thanks for reporting back
