### ISSUE TITLE
MATCH bug: O1 2 in MOL 1: has too many bonds for its element, structure is warped

### ISSUE THREAD

**Issue by ferpozo6** [Acellera/htmd#335]
When I am trying to get the CGENFF/GAFF parameters for a given ligand I obtain this output.

`parameterize -m fxr1_14.mol2 --no-min --no-esp --no-torsions -o ./param-fxr1_14`
> Please cite HTMD: Doerr et al.(2016)JCTC,12,1845. https://dx.doi.org/10.1021/acs.jctc.6b00049
> 
> HTMD Documentation at: https://www.htmd.org/docs/latest/
> 
> New devel HTMD version (1.7.31 python[==3.6]) is available. You are currently on (1.7.19). Use 'conda update -c acellera htmd' to update to the new version. You might need to update your python version as well if there is no release for your current version.
> 
>  === List of arguments used ===
> 
>        mol:  fxr1_14.mol2
>       list:  False     
>     charge:  None      
>        rtf:  None      
>        prm:  None      
>     outdir:  ./param-fxr1_14
>    torsion:  all       
>      ncpus:  4         
> forcefield:  all       
>      basis:  cc-pVDZ   
>     theory:  B3LYP     
>     vacuum:  False     
>      nomin:  True      
>      noesp:  True      
>  notorsion:  True      
>       exec:  inline    
>     qmcode:  PSI4      
>    freezeq:  None      
>    geomopt:  True      
> 
>  === Parameterizing fxr1_14.mol2 ===
> 
>  === Fitting for FF CGenFF_2b6 ===
> 
> Dihedral 0: 0-1-2-9
> Dihedral 1: 4-5-10-18
> Dihedral 2: 5-6-7-8
> Dihedral 3: 10-18-19-20
> Dihedral 4: 18-19-20-25
>  Has equivalent dihedrals through symmetry: 
>  Dihedral 18-19-20-21
> Dihedral 5: 18-19-26-27
> Dihedral 6: 19-26-28-29
> Dihedral 7: 26-28-29-35
>  Has equivalent dihedrals through symmetry: 
>  Dihedral 26-28-29-30
> Got charge 0
> C1 1 MOL
> C2 3 MOL
> C3 4 MOL
> C8 10 MOL
> O1 2 in MOL 1: has too many bonds for its element, structure is warped at /home/fernanpozo/miniconda3/bin/../share/MATCH/PerlChemistry//lib/Chain.pm line 267.
> Traceback (most recent call last):
>   File "/home/fernanpozo/miniconda3/lib/python3.6/site-packages/htmd/parameterization/fftype.py", line 82, in __init__
>     self._rtf = RTF("mol.rtf")
>   File "/home/fernanpozo/miniconda3/lib/python3.6/site-packages/htmd/parameterization/ff.py", line 524, in __init__
>     f = open(filename, "r")
> FileNotFoundError: [Errno 2] No such file or directory: 'mol.rtf'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/fernanpozo/miniconda3/bin/parameterize", line 6, in <module>
>     sys.exit(htmd.parameterization.cli.main_parameterize())
>   File "/home/fernanpozo/miniconda3/lib/python3.6/site-packages/htmd/parameterization/cli.py", line 175, in main_parameterize
>     outdir=args.outdir)
>   File "/home/fernanpozo/miniconda3/lib/python3.6/site-packages/htmd/parameterization/ffmolecule.py", line 101, in __init__
>     fftype = FFType(self, method=self.method)
>   File "/home/fernanpozo/miniconda3/lib/python3.6/site-packages/htmd/parameterization/fftype.py", line 88, in __init__
>     raise RuntimeError("FFTyping failed running Match")
> RuntimeError: FFTyping failed running Match

_doesn't create any directory_

I suspect that could be an incompatibility with the force field, then I proved with AMBER typing:
`parameterize -m fxr1_14.mol2 -f GAFF2 --no-min --no-esp --no-torsions -o ./param-fxr1_14`

> Please cite HTMD: Doerr et al.(2016)JCTC,12,1845. https://dx.doi.org/10.1021/acs.jctc.6b00049
> 
> HTMD Documentation at: https://www.htmd.org/docs/latest/
> 
> New devel HTMD version (1.7.31 python[==3.6]) is available. You are currently on (1.7.19). Use 'conda update -c acellera htmd' to update to the new version. You might need to update your python version as well if there is no release for your current version.
> 
>  === List of arguments used ===
> 
>        mol:  fxr1_14.mol2
>       list:  False     
>     charge:  None      
>        rtf:  None      
>        prm:  None      
>     outdir:  ./param-fxr1_14
>    torsion:  all       
>      ncpus:  4         
> forcefield:  GAFF2     
>      basis:  cc-pVDZ   
>     theory:  B3LYP     
>     vacuum:  False     
>      nomin:  True      
>      noesp:  True      
>  notorsion:  True      
>       exec:  inline    
>     qmcode:  PSI4      
>    freezeq:  None      
>    geomopt:  True      
> 
>  === Parameterizing fxr1_14.mol2 ===
> 
>  === Fitting for FF GAFF2 ===
> 
> Dihedral 0: 0-1-2-9
> Dihedral 1: 4-5-10-18
> Dihedral 2: 5-6-7-8
> Dihedral 3: 10-18-19-20
> Dihedral 4: 18-19-20-25
>  Has equivalent dihedrals through symmetry: 
>  Dihedral 18-19-20-21
> Dihedral 5: 18-19-26-27
> Dihedral 6: 19-26-28-29
> Dihedral 7: 26-28-29-35
>  Has equivalent dihedrals through symmetry: 
>  Dihedral 26-28-29-30
> 
> Unknown bond type for BOND(C6-C8:un), assuming it is a single bond
> Unknown bond type for BOND(C9-N1:un), assuming it is a single bond
> Unknown bond type for BOND(C17-C22:un), assuming it is a single bond
> Unknown bond type for BOND(C19-C20:un), assuming it is a single bond
> Unknown bond type for BOND(C25-C27:un), assuming it is a single bond
> Unknown bond type for BOND(C5-C6:un), assuming it is a single bond
> Unknown bond type for BOND(N3-C24:un), assuming it is a single bond
> Unknown bond type for BOND(C16-C23:un), assuming it is a single bond
> Unknown bond type for BOND(C23-N3:un), assuming it is a single bond
> Unknown bond type for BOND(C13-C14:un), assuming it is a single bond
> Unknown bond type for BOND(N2-C16:un), assuming it is a single bond
> Unknown bond type for BOND(C25-C26:un), assuming it is a single bond
> Unknown bond type for BOND(C29-C30:un), assuming it is a single bond
> Unknown bond type for BOND(C24-C30:un), assuming it is a single bond
> Unknown bond type for BOND(O1-C2:un), assuming it is a single bond
> Unknown bond type for BOND(C14-C15:un), assuming it is a single bond
> Unknown bond type for BOND(C27-C28:un), assuming it is a single bond
> Unknown bond type for BOND(C6-O2:un), assuming it is a single bond
> Unknown bond type for BOND(C2-C8:un), assuming it is a single bond
> Unknown bond type for BOND(C10-C11:un), assuming it is a single bond
> Unknown bond type for BOND(C17-C18:un), assuming it is a single bond
> Unknown bond type for BOND(C9-N2:un), assuming it is a single bond
> Unknown bond type for BOND(C10-C15:un), assuming it is a single bond
> Unknown bond type for BOND(C3-C4:un), assuming it is a single bond
> Unknown bond type for BOND(C30-C31:un), assuming it is a single bond
> Unknown bond type for BOND(C4-C5:un), assuming it is a single bond
> Unknown bond type for BOND(C24-C25:un), assuming it is a single bond
> Unknown bond type for BOND(C2-C3:un), assuming it is a single bond
> Unknown bond type for BOND(C12-C13:un), assuming it is a single bond
> Unknown bond type for BOND(N1-C10:un), assuming it is a single bond
> Unknown bond type for BOND(C16-C17:un), assuming it is a single bond
> Unknown bond type for BOND(C20-C21:un), assuming it is a single bond
> Unknown bond type for BOND(C1-O1:un), assuming it is a single bond
> Unknown bond type for BOND(C15-N2:un), assuming it is a single bond
> Unknown bond type for BOND(C28-C29:un), assuming it is a single bond
> Unknown bond type for BOND(C5-C9:un), assuming it is a single bond
> Unknown bond type for BOND(C23-O3:un), assuming it is a single bond
> Unknown bond type for BOND(C11-C12:un), assuming it is a single bond
> Unknown bond type for BOND(C18-C19:un), assuming it is a single bond
> Unknown bond type for BOND(C21-C22:un), assuming it is a single bond
> 
> Warning: the assigned bond types may be wrong, please : 
> (1) double check the structure (the connectivity) and/or 
> (2) adjust atom valence penalty parameters in APS.DAT, and/or 
> (3) increase PSCUTOFF in define.h and recompile bondtype.c
>     Be cautious, use a large value of PSCUTOFF (>100) will significantly increase the computation time
> 
> Warning: ATOM N3 has unfilled valence, assuming the linked atom name (in other residue) is "M"
>          change "M" to "-M" if ATOM N3 is linked to the immediate previous residue
>          change "M" to "+M" if ATOM N3 is linked to the immediate after residueUnknown bond type for BOND(O2-C7:un), assuming it is a single bond
> Net Charge: 0
> Equivalent atom groups:
>  C1
>  O1
>  C2
>  C3
>  C4
>  C5
>  C6
>  O2
>  C7
>  C8
>  C9
>  N1
>  C10
>  C11
>  C12
>  C13
>  C14
>  C15
>  N2
>  C16
>  C17
>  C18 C22
>  C19 C21
>  C20
>  C23
>  O3
>  N3
>  C24
>  C25 C30
>  C26 C31
>  C27 C29
>  C28
> Soft torsions:
>  C1 O1 C2 C8
>  C4 C5 C9 N2
>  C5 C6 O2 C7
>  C9 N2 C16 C17
>  N2 C16 C17 C22
>  N2 C16 C23 O3
>  C16 C23 N3 C24
>  C23 N3 C24 C30
> 
>  == Diagnostic Energies == 
> 
>  Bond     : 5656.565456
>  Angle    : 1062.994617
>  Dihedral : 0.000000
>  Improper : 0.000000
>  Electro  : 11.460871
>  VdW      : 5111223753.734774
> 
> 
>  == Output to ./param-fxr1_14/parameters/GAFF2/b3lyp-cc-pVDZ-water ==

_and with this order it creates a directory._

**Is this Parameterization right?**
I also attach my .mol2 file in order to find a solution if it is not right.
[fxr1_14 .txt](https://github.com/Acellera/htmd/files/992751/fxr1_14.txt)

**Comment by j3mdamas** [comment]
Hi,

1. Where did you get this MOL2 file from?
2. Before running any parameterization, you must make sure the molecule makes sense. This MOL2 file does not have any hidrogens.

In CHARMM, we are definitely having a problem, but it relates with the MATCH software we use to guess atom types. It's an hacked script in perl that wasn't written by us, so it may take some time to pin point the bug. Meanwhile, go with AMBER, which does not have this problem.

**Comment by j3mdamas** [comment]
From the MATCH FAQ (https://brooks.chem.lsa.umich.edu/index.php?matchfaq=faq):

> ____ has too many bonds for its element, structure is warped
The atom mentioned has been predicted to bond to too many atoms, this is most likely an error in MATCH's ability to parse a pdb or the actual structure have atoms that are too close together making them appear to be bonded. One can supply the correct bonding using a MOL/MOL2/ SDF file.

Should only be happening with structure without correct bonding. Loading the structure in VMD shows bonding that makes sense, so to identify a problem, we should be looking at the bonding information in the MOL2 file.

But again, this brings to my previous question: where did the MOL2 file come from?

**Comment by j3mdamas** [comment]
@ferpozo6 ?

**Comment by ferpozo6** [comment]
Hi, 

I'm sorry for not answering until now.

We extracted the data from a compound set in a .sdf file. I attached you that dataset. 
Then, we take a single compound, FXR14 (we had in total 102), saving it in a single file and convert it in .mol2 file with this command.
`babel -isdf fxr1_14.sdf -omol2 fxr1_14.mol2`

We are working in D3 challenge, stage 1. https://drugdesigndata.org/about/grand-challenge-2
[compounds_sdf.txt](https://github.com/Acellera/htmd/files/1007475/compounds_sdf.txt)
[fxr14_sdf.txt](https://github.com/Acellera/htmd/files/1007474/fxr14_sdf.txt)

**Comment by j3mdamas** [comment]
Thanks for sharing the data.

I don't have an immediate fix for this in terms of CHARMM, it requires further investigation of why MATCH is misbehaving.

As I said above, for Amber, it should work, but you cannot forget about protons.

**Comment by j3mdamas** [comment]
And the protons goes for any structure you prepare with parameterize

**Comment by ferpozo6** [comment]
Thanks Joao, 

I agree, we think that for Amber it should run fine. We are going to perform the parameterize for more compounds and then, we will report you the results in order to get more info about this problem. 

But, what happened with the protons? 

Cheers,
Fernando

**Comment by j3mdamas** [comment]
Nothing happened. They are normally not there. You have to protonate it yourself.

There are tools available for that (you can use `babel -h`, for example). Creating a tool for adding protons to molecules is on the todo list for HTMD.

**Comment by j3mdamas** [comment]
@raimis I'm assigning this to you

**Comment by raimis** [comment]
Hi @ferpozo6,

Is it still a problem, if you add hydrogens?

**Comment by raimis** [comment]
@ferpozo6?

**Comment by j3mdamas** [comment]
@raimis I think @ferpozo6 was just a student of the Masters, so maybe he's not responsive anymore.

We have the structure, we can try to run it. Do you want me to do it?

**Comment by raimis** [comment]
@j3mdamas OK! I'll try it myself.

**Comment by raimis** [comment]
The original structure file does not contain hydrogen and bond lengths are too short.

After adding hydrogen and optimizing structure:
```
$ mv fxr1_14.txt fxr1_14.mol2
$ obminimize -h fxr1_14.mol2 > fxr1_14.pdb
$ obabel fxr1_14.pdb -O fxr1_14_opt.mol2
```

**HTMD 1.9.7** works without a problem:
```
$ parameterize -m fxr1_14_opt.mol2 --no-min --no-esp --no-torsions -o ./param-fxr1_14

HTMD License accepted automatically. Check license here: https://raw.githubusercontent.com/Acellera/htmd/master/htmd/LICENCE.txt

For advanced features (e.g. parameterize) and to remove this message, we recommend registering. Run htmd_register in your terminal.

Please cite HTMD: Doerr et al.(2016)JCTC,12,1845. https://dx.doi.org/10.1021/acs.jctc.6b00049

HTMD Documentation at: https://www.htmd.org/docs/latest/

You are on the latest HTMD version (1.9.7).

Deprecation warning: "from htmd import *" will be deprecated. 
To import all HTMD shortcuts please from now on use "from htmd.ui import *"
 === List of arguments used ===

       mol:  fxr1_14_opt.mol2
      list:  False     
    charge:  None      
       rtf:  None      
       prm:  None      
    outdir:  ./param-fxr1_14
   torsion:  all       
     ncpus:  8         
forcefield:  all       
     basis:  cc-pVDZ   
    theory:  B3LYP     
    vacuum:  True      
     nomin:  True      
     noesp:  True      
 notorsion:  True      
      exec:  inline    
    qmcode:  PSI4      
   freezeq:  None      
   geomopt:  True      

 === Parameterizing fxr1_14_opt.mol2 ===

 === Fitting for FF CGenFF_2b6 ===

Dihedral 0: 0-1-2-9
Dihedral 1: 4-5-10-18
Dihedral 2: 5-6-7-8
Dihedral 3: 10-18-19-20
Dihedral 4: 18-19-20-25
 Has equivalent dihedrals through symmetry: 
 Dihedral 18-19-20-21
Dihedral 5: 18-19-26-27
Dihedral 6: 19-26-28-29
Dihedral 7: 26-28-29-35
 Has equivalent dihedrals through symmetry: 
 Dihedral 26-28-29-30
Got charge 0
Set charge 0
C1     C.4    CG331  !C.4(H.1)(H.1)(H.1)
O1     O.2    OG301  O.2   
C2     C.3%6A CG2R61 C.3%6A
C3     C.3%6A CG2R61 C.3%6A
C4     C.3%6A CG2R61 C.3%6A
C5     C.3%6A CG2R61 C.3%6A
C6     C.3%6A CG2R61 C.3%6A
O2     O.2    OG301  O.2   
C7     C.4    CG331  !C.4(H.1)(H.1)(H.1)
C8     C.3%6A CG2R61 C.3%6A
C9     C.3%5A CG2R53 C.3%5(N.2%5)(^C%5)
N1     N.2%5A NG2R50 N.2%5 
C10    C.3%5A,6A CG2RC0 C.3%6,5(C.3%6,5)(C.3%6)
C11    C.3%6A CG2R61 C.3%6A
C12    C.3%6A CG2R61 C.3%6A
C13    C.3%6A CG2R61 C.3%6A
C14    C.3%6A CG2R61 C.3%6A
C15    C.3%5A,6A CG2RC0 C.3%6,5(C.3%6,5)(C.3%6)
N2     N.3%5A NG2R51 N.3%5A(C.3%5)
C16    C.4    CG311  C.4(H.1)
C17    C.4%6N CG311  C.4(H.1)
C18    C.4%6N CG321  C.4(H.1)(H.1)
C19    C.4%6N CG321  C.4(H.1)(H.1)
C20    C.4%6N CG321  C.4(H.1)(H.1)
C21    C.4%6N CG321  C.4(H.1)(H.1)
C22    C.4%6N CG321  C.4(H.1)(H.1)
C23    C.3    CG2O1  !C.3(O.1)(N.3)
O3     O.1    OG2D1  O.1(C.3)
N3     N.3    NG2S1  !N.3(H.1)(C.3(!O.1))
C24    C.3%6A CG2R61 C.3%6A
C25    C.3%6A CG2R61 C.3%6A
C26    C.4    CG331  !C.4(H.1)(H.1)(H.1)
C27    C.3%6A CG2R61 C.3%6A
C28    C.3%6A CG2R61 C.3%6A
C29    C.3%6A CG2R61 C.3%6A
C30    C.3%6A CG2R61 C.3%6A
C31    C.4    CG331  !C.4(H.1)(H.1)(H.1)
H1     H.1    HGA3   H.1(C.4(H.1)(H.1))
H2     H.1    HGA3   H.1(C.4(H.1)(H.1))
H3     H.1    HGA3   H.1(C.4(H.1)(H.1))
H4     H.1    HGR61  H.1(C.3%6)
H5     H.1    HGR61  H.1(C.3%6)
H6     H.1    HGA3   H.1(C.4(H.1)(H.1))
H7     H.1    HGA3   H.1(C.4(H.1)(H.1))
H8     H.1    HGA3   H.1(C.4(H.1)(H.1))
H9     H.1    HGR61  H.1(C.3%6)
H10    H.1    HGR61  H.1(C.3%6)
H11    H.1    HGR61  H.1(C.3%6)
H12    H.1    HGR61  H.1(C.3%6)
H13    H.1    HGR61  H.1(C.3%6)
H14    H.1    HGA1   H.1(C.4)
H15    H.1    HGA1   H.1(C.4)
H16    H.1    HGA2   H.1(C.4(H.1))
H17    H.1    HGA2   H.1(C.4(H.1))
H18    H.1    HGA2   H.1(C.4(H.1))
H19    H.1    HGA2   H.1(C.4(H.1))
H20    H.1    HGA2   H.1(C.4(H.1))
H21    H.1    HGA2   H.1(C.4(H.1))
H22    H.1    HGA2   H.1(C.4(H.1))
H23    H.1    HGA2   H.1(C.4(H.1))
H24    H.1    HGA2   H.1(C.4(H.1))
H25    H.1    HGA2   H.1(C.4(H.1))
H26    H.1    HGP1   H.1(!N.3)
H27    H.1    HGA3   H.1(C.4(H.1)(H.1))
H28    H.1    HGA3   H.1(C.4(H.1)(H.1))
H29    H.1    HGA3   H.1(C.4(H.1)(H.1))
H30    H.1    HGR61  H.1(C.3%6)
H31    H.1    HGR61  H.1(C.3%6)
H32    H.1    HGR61  H.1(C.3%6)
H33    H.1    HGA3   H.1(C.4(H.1)(H.1))
H34    H.1    HGA3   H.1(C.4(H.1)(H.1))
H35    H.1    HGA3   H.1(C.4(H.1)(H.1))
mol Success!
Net Charge: 0
Equivalent atom groups:
 C1
 O1
 C2
 C3
 C4
 C5
 C6
 O2
 C7
 C8
 C9
 N1
 C10
 C11
 C12
 C13
 C14
 C15
 N2
 C16
 C17
 C18 C22
 C19 C21
 C20
 C23
 O3
 N3
 C24
 C25 C30
 C26 C31
 C27 C29
 C28
 H1 H2 H3
 H4
 H5
 H6 H7 H8
 H9
 H10
 H11
 H12
 H13
 H14
 H15
 H16 H17 H24 H25
 H18 H19 H22 H23
 H20 H21
 H26
 H27 H28 H29 H33 H34 H35
 H30 H32
 H31
Soft torsions:
 C1 O1 C2 C8
 C4 C5 C9 N2
 C5 C6 O2 C7
 C9 N2 C16 C17
 N2 C16 C17 C22
 N2 C16 C23 O3
 C16 C23 N3 C24
 C23 N3 C24 C30

 == Diagnostic Energies == 

 Bond     : 9.457972
 Angle    : 15.926120
 Dihedral : 82.977096
 Improper : 0.939965
 Electro  : 0.000000
 VdW      : 42.473569


 == Output to ./param-fxr1_14/parameters/CGenFF_2b6/b3lyp-cc-pVDZ-vacuum ==

 === Fitting for FF GAFF2 ===

Dihedral 0: 0-1-2-9
Dihedral 1: 4-5-10-18
Dihedral 2: 5-6-7-8
Dihedral 3: 10-18-19-20
Dihedral 4: 18-19-20-25
 Has equivalent dihedrals through symmetry: 
 Dihedral 18-19-20-21
Dihedral 5: 18-19-26-27
Dihedral 6: 19-26-28-29
Dihedral 7: 26-28-29-35
 Has equivalent dihedrals through symmetry: 
 Dihedral 26-28-29-30

Unknown bond type for BOND(C1-O1:un), assuming it is a single bond
Unknown bond type for BOND(C1-H1:un), assuming it is a single bond
Unknown bond type for BOND(C1-H2:un), assuming it is a single bond
Unknown bond type for BOND(C1-H3:un), assuming it is a single bond
Unknown bond type for BOND(O1-C2:un), assuming it is a single bond
Unknown bond type for BOND(C2-C3:un), assuming it is a single bond
Unknown bond type for BOND(C2-C8:un), assuming it is a single bond
Unknown bond type for BOND(C3-C4:un), assuming it is a single bond
Unknown bond type for BOND(C3-H4:un), assuming it is a single bond
Unknown bond type for BOND(C4-C5:un), assuming it is a single bond
Unknown bond type for BOND(C4-H5:un), assuming it is a single bond
Unknown bond type for BOND(C5-C6:un), assuming it is a single bond
Unknown bond type for BOND(C5-C9:un), assuming it is a single bond
Unknown bond type for BOND(C6-O2:un), assuming it is a single bond
Unknown bond type for BOND(C6-C8:un), assuming it is a single bond
Unknown bond type for BOND(O2-C7:un), assuming it is a single bond
Unknown bond type for BOND(C7-H6:un), assuming it is a single bond
Unknown bond type for BOND(C7-H7:un), assuming it is a single bond
Unknown bond type for BOND(C7-H8:un), assuming it is a single bond
Unknown bond type for BOND(C8-H9:un), assuming it is a single bond
Unknown bond type for BOND(C9-N1:un), assuming it is a single bond
Unknown bond type for BOND(C9-N2:un), assuming it is a single bond
Unknown bond type for BOND(N1-C10:un), assuming it is a single bond
Unknown bond type for BOND(C10-C11:un), assuming it is a single bond
Unknown bond type for BOND(C10-C15:un), assuming it is a single bond
Unknown bond type for BOND(C11-C12:un), assuming it is a single bond
Unknown bond type for BOND(C11-H10:un), assuming it is a single bond
Unknown bond type for BOND(C12-C13:un), assuming it is a single bond
Unknown bond type for BOND(C12-H11:un), assuming it is a single bond
Unknown bond type for BOND(C13-C14:un), assuming it is a single bond
Unknown bond type for BOND(C13-H12:un), assuming it is a single bond
Unknown bond type for BOND(C14-C15:un), assuming it is a single bond
Unknown bond type for BOND(C14-H13:un), assuming it is a single bond
Unknown bond type for BOND(C15-N2:un), assuming it is a single bond
Unknown bond type for BOND(N2-C16:un), assuming it is a single bond
Unknown bond type for BOND(C16-C17:un), assuming it is a single bond
Unknown bond type for BOND(C16-C23:un), assuming it is a single bond
Unknown bond type for BOND(C16-H14:un), assuming it is a single bond
Unknown bond type for BOND(C17-C18:un), assuming it is a single bond
Unknown bond type for BOND(C17-C22:un), assuming it is a single bond
Unknown bond type for BOND(C17-H15:un), assuming it is a single bond
Unknown bond type for BOND(C18-C19:un), assuming it is a single bond
Unknown bond type for BOND(C18-H16:un), assuming it is a single bond
Unknown bond type for BOND(C18-H17:un), assuming it is a single bond
Unknown bond type for BOND(C19-C20:un), assuming it is a single bond
Unknown bond type for BOND(C19-H18:un), assuming it is a single bond
Unknown bond type for BOND(C19-H19:un), assuming it is a single bond
Unknown bond type for BOND(C20-C21:un), assuming it is a single bond
Unknown bond type for BOND(C20-H20:un), assuming it is a single bond
Unknown bond type for BOND(C20-H21:un), assuming it is a single bond
Unknown bond type for BOND(C21-C22:un), assuming it is a single bond
Unknown bond type for BOND(C21-H22:un), assuming it is a single bond
Unknown bond type for BOND(C21-H23:un), assuming it is a single bond
Unknown bond type for BOND(C22-H24:un), assuming it is a single bond
Unknown bond type for BOND(C22-H25:un), assuming it is a single bond
Unknown bond type for BOND(C23-O3:un), assuming it is a single bond
Unknown bond type for BOND(C23-N3:un), assuming it is a single bond
Unknown bond type for BOND(N3-C24:un), assuming it is a single bond
Unknown bond type for BOND(N3-H26:un), assuming it is a single bond
Unknown bond type for BOND(C24-C25:un), assuming it is a single bond
Unknown bond type for BOND(C24-C30:un), assuming it is a single bond
Unknown bond type for BOND(C25-C26:un), assuming it is a single bond
Unknown bond type for BOND(C25-C27:un), assuming it is a single bond
Unknown bond type for BOND(C26-H27:un), assuming it is a single bond
Unknown bond type for BOND(C26-H28:un), assuming it is a single bond
Unknown bond type for BOND(C26-H29:un), assuming it is a single bond
Unknown bond type for BOND(C27-C28:un), assuming it is a single bond
Unknown bond type for BOND(C27-H30:un), assuming it is a single bond
Unknown bond type for BOND(C28-C29:un), assuming it is a single bond
Unknown bond type for BOND(C28-H31:un), assuming it is a single bond
Unknown bond type for BOND(C29-C30:un), assuming it is a single bond
Unknown bond type for BOND(C29-H32:un), assuming it is a single bond
Unknown bond type for BOND(C30-C31:un), assuming it is a single bond
Unknown bond type for BOND(C31-H33:un), assuming it is a single bond
Unknown bond type for BOND(C31-H34:un), assuming it is a single bond
Unknown bond type for BOND(C31-H35:un), assuming it is a single bond
Net Charge: 0
Equivalent atom groups:
 C1
 O1
 C2
 C3
 C4
 C5
 C6
 O2
 C7
 C8
 C9
 N1
 C10
 C11
 C12
 C13
 C14
 C15
 N2
 C16
 C17
 C18 C22
 C19 C21
 C20
 C23
 O3
 N3
 C24
 C25 C30
 C26 C31
 C27 C29
 C28
 H1 H2 H3
 H4
 H5
 H6 H7 H8
 H9
 H10
 H11
 H12
 H13
 H14
 H15
 H16 H17 H24 H25
 H18 H19 H22 H23
 H20 H21
 H26
 H27 H28 H29 H33 H34 H35
 H30 H32
 H31
Soft torsions:
 C1 O1 C2 C8
 C4 C5 C9 N2
 C5 C6 O2 C7
 C9 N2 C16 C17
 N2 C16 C17 C22
 N2 C16 C23 O3
 C16 C23 N3 C24
 C23 N3 C24 C30

 == Diagnostic Energies == 

 Bond     : 2.016563
 Angle    : 27.315682
 Dihedral : 33.631296
 Improper : 0.913637
 Electro  : 3.891511
 VdW      : 5.380733


 == Output to ./param-fxr1_14/parameters/GAFF2/b3lyp-cc-pVDZ-vacuum ==
```

**Comment by raimis** [comment]
@ferpozo6

This issue is solved! If there are other problems with `parameterize`, you are welcome to contact us again.

**Comment by raimis** [comment]
@j3mdamas you can close this!
