### ISSUE TITLE
[ENHANCEMENT] Add a warning when terminal C/N establishes meaningful H-bonds; capping may not be the best option

### ISSUE THREAD

**Issue by GerardBCN** [Acellera/htmd#337]
Hi, together with Adrià, looking at a particular case (the protein 1JWP) with the playmolecule proteinPrepare app, we have noticed that the terminal N, mostly protonated at neutral pH, establishes a possibly important H-bond with the core of the protein. We've seen unfolding of the terminal helix and this may have been caused by wrongly applied capping, which is ON by default during building. Would it be possible to use the new functionality that Toni implemented ( prepData.findHbonds() where prepData is optional argument returned by proteinPrepare() function) to guess when a terminus establishes a possibly important H-bond? The dafult can remain the same, i.e. applying capping, but a **WARNING** would be much appreciated to suggest the researcher further inspection.

**Comment by stefdoerr** [comment]
I think this is a very roundabout way of identifying if a protein is cut. There could be "fake" h-bonds in cut proteins as far as I can imagine which would throw it off.
I would rather prefer to have a checkbox for the user if the protein is whole or just a fragment. It's very rare that proteins are found whole in PDBs from what I've seen either due to crystalization failing at the terminals or due to the protein being cut out of a larger one in the first case.

**Comment by GerardBCN** [comment]
I understand your point, but even if that's true I believe the right way to go is raising the warning. If the protein has residues missing then great, it's just a warning and the user can ignore it safely.

**Comment by j3mdamas** [comment]
I think the easier warning of all would be to check the internalization of the terminal. The less internalized it is, the less it matters. There are cases where the terminal is utmost important (even if not performing H-bonds) just because it's totally inside the protein.

**Comment by tonigi** [comment]
Implemented in checkTerminiHbonds() . "Buried fraction" of the n terminus is also a good indication (already returned). Both are available after prepare.

**Comment by j3mdamas** [comment]
Hence, my comment about the buried factor being more important (for warning)

**Comment by j3mdamas** [comment]
what's the status here? did we arrive any decision?

**Comment by tonigi** [comment]
Now   proteinPrepare issues a warning if a terminus is buried > 50% or involved in H bonds. Criteria are somewhat arbitrary for now. Commit f7c1165320fcf93fbfc96e89c9b941a2b03c1ca9

**Comment by j3mdamas** [comment]
ok, so it's taken care of at the proteinPrepare level. Issue closed then.
