### ISSUE TITLE
Ligand Destroyed During Build

### ISSUE THREAD

**Issue by waskom** [Acellera/htmd#339]
Hello All,

I have been having an issue during the building process where the ligand gets dissected during the building process. The PDB coordinates look the same as the input structure. I am not sure how to proceed. 

Thank you,
Mike
<img width="1139" alt="screen shot 2017-05-16 at 11 00 57 am" src="https://cloud.githubusercontent.com/assets/20097577/26112867/0347bc86-3a27-11e7-98bb-11af651e72cf.png">

**Comment by cuzzo87** [comment]
Hello Mike,

Thank you for the jupyter screenshot, but to help you in this stage I need to ask you more information about your protocol.
First I would like to understand at which stage you see the dissected ligand. Is after the building procedure? If it is this the case, based on the screenshot I cannot see the build command. Can you provide me the jupyter you are using?
Furthermore could you please give me information regarding the ligand parametrization?

**Comment by waskom** [comment]
I see the ligand destroyed after the whole system is built.  I have uploaded the notebook. The parameters have been from the parachem server.

[DAT_MPH_2.ipynb.zip](https://github.com/Acellera/htmd/files/1014564/DAT_MPH_2.ipynb.zip)

**Comment by waskom** [comment]
The ligand is fine when the visualization occurs after the protein, lipid, and ligand are put together.

**Comment by waskom** [comment]
I figured it out. It was an issue with the parameters.
