### ISSUE TITLE
Consider using sparse=True.

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#34]
Hi guys,

One question. When doing an MSM with lot of data i've come across this warning several times:
`
2016-05-11 15:07:26,716 - pyemma.msm.estimators.maximum_likelihood_msm.MaximumLikelihoodMSM[0] - WARNING - Building a dense MSM with 4956 states. This can be inefficient or unfeasible in terms of both runtime and memory consumption. Consider using sparse=True.`

I didn't find where to put the 'sparse=True' flag though. Any ideas?

Thanks,
Noelia

**Comment by stefdoerr** [comment]
It's not the amount of data but the amount of clusters that is very high.
They just advise you to use a pyEMMA property which makes sparse transition matrices to save space. Unless you have memory problems from the 5000x5000 matrix I would just ignore them.

The option was not exposed in our Model class though so you could not choose it. I added it now as an option but no guarantees that it will not break something further on in the pipeline.
