### ISSUE TITLE
htmd py3.6 packages not found by conda; installs old 0.1.39 noarch instead

### ISSUE THREAD

**Issue by afdezt** [Acellera/htmd#344]
Hi,

Recently I have reinstaled miniconda3 and HTMD. The installation of htmd seems to work and I can import it in ipython without problems. However, when I create a Molecule object it reports the following error:

> NameError: name 'Molecule' is not defined

I used the same installation way that I had used one month ago (from HTMD page).

Thanks!

**Comment by j3mdamas** [comment]
Hi,

Can you describe exactly which commands you ran for importing? Does the importing give any output? Can you print it here?

Plus, can you please give the output of: `which ipython`

Thanks,
João

**Comment by afdezt** [comment]
Import:
`from htmd import *`
No output is given.

`which ipython`
> /home/adriaft/miniconda3/bin/ipython

Both the importing comand and the location of miniconda3 folder are the same I have been using before reinstaling it.

**Comment by j3mdamas** [comment]
Can you please do:
```
from htmd import *
print(htmd.__path__)
```

And `ls` that path for me? Thanks.

**Comment by afdezt** [comment]
If I try to do the print with this importing, it give me the following error:

> NameError: name 'htmd' is not defined

If I import the module just using `import htmd`, I can get the following path:
 
> /home/adriaft/miniconda3/lib/python3.6/site-packages/htmd

There is only a folder inside this, called 'data'. If I use `ls` inside the 'data' folder:

> 1kdx                       metricdihedral         test-atomselect
adaptive                   metricdistance         test-charmm-build
amber                      molecule-readers       test-metrics
building-protein-ligand    mor                    test-proteinprepare
building-protein-membrane  package                test-voxeldescriptors
charmm_strfile             pdb                    tmscore
dhfr                       test-adaptive          villin
docking                    test-amber-build
equilibrate                test-amber-build-nopp

**Comment by j3mdamas** [comment]
Your conda installation is broken, the module is empty. I recommend a fresh installation:

- `rm -rf /home/adriaft/miniconda3`
- Download Miniconda3 installer
- Install miniconda.
- `conda install htmd -c acellera -y`

**Comment by afdezt** [comment]
I have reinstalled miniconda from the official page and have executed the htmd installation comand. However, I have the same problem with the same results in all the above steps.

**Comment by j3mdamas** [comment]
That is weird. In which operative system are you trying to install htmd?

Can you give me the output of `conda list`?

Thanks

**Comment by afdezt** [comment]
Linux 4.4.0-040400-generic x86_64

> packages in environment at /home/adriaft/miniconda3:
anaconda-client           1.6.3                    py36_0  
bhmm                      0.6.1               np112py36_0    acellera
bleach                    1.5.0                    py36_0  
cffi                      1.9.1                    py36_0  
clyent                    1.2.2                    py36_0  
conda                     4.3.18                   py36_0  
conda-env                 2.6.0                         0  
cryptography              1.7.1                    py36_0  
cycler                    0.10.0                   py36_0  
cython                    0.25.2                   py36_0  
dbus                      1.10.10                       0  
decorator                 4.0.11                   py36_0  
entrypoints               0.2.2                    py36_1  
expat                     2.1.0                         0  
fontconfig                2.12.1                        3  
freetype                  2.5.5                         2  
glib                      2.50.2                        1  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
hdf5                      1.8.17                        1  
htmd                      0.1.39                        0    acellera
htmd-data                 0.0.45                     py_0    acellera
html5lib                  0.999                    py36_0  
icu                       54.1                          0  
idna                      2.2                      py36_0  
ipykernel                 4.6.1                    py36_0  
ipyparallel               6.0.2                    py36_0  
ipython                   6.0.0                    py36_1  
ipython_genutils          0.2.0                    py36_0  
ipywidgets                6.0.0                    py36_0  
jedi                      0.10.2                   py36_2  
jinja2                    2.9.6                    py36_0  
joblib                    0.11                     py36_0  
jpeg                      9b                            0  
jsonschema                2.6.0                    py36_0  
jupyter_client            5.0.1                    py36_0  
jupyter_console           5.1.0                    py36_0  
jupyter_core              4.3.0                    py36_0  
libffi                    3.2.1                         1  
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libsodium                 1.0.10                        0  
libxcb                    1.12                          1  
libxml2                   2.9.4                         0  
markupsafe                0.23                     py36_2  
matplotlib                2.0.2               np112py36_0  
mdtraj                    1.8.0               np112py36_1    acellera
mistune                   0.7.4                    py36_0  
mkl                       2017.0.1                      0  
mock                      2.0.0                    py36_0  
msmtools                  1.2                 np112py36_0    acellera
natsort                   5.0.3                    py36_0  
nbconvert                 5.1.1                    py36_0  
nbformat                  4.3.0                    py36_0  
nglview                   0.6.2.3                  py36_0    acellera
notebook                  5.0.0                    py36_0  
numexpr                   2.6.2               np112py36_0  
numpy                     1.12.1                   py36_0  
openssl                   1.0.2k                        1  
pandas                    0.20.1              np112py36_0  
pandocfilters             1.4.1                    py36_0  
path.py                   10.3.1                   py36_0  
pbr                       1.10.0                   py36_0  
pcre                      8.39                          1  
pexpect                   4.2.1                    py36_0  
pickleshare               0.7.4                    py36_0  
pip                       9.0.1                    py36_1  
progress_reporter         1.3.1                    py36_0    acellera
prompt_toolkit            1.0.14                   py36_0  
propka                    3.1.7                      py_0    acellera
psutil                    5.2.2                    py36_0  
ptyprocess                0.5.1                    py36_0  
pyasn1                    0.1.9                    py36_0  
pycosat                   0.6.1                    py36_1  
pycparser                 2.17                     py36_0  
pyemma                    2.3.2               np112py36_1    acellera
pygments                  2.2.0                    py36_0  
pyopenssl                 16.2.0                   py36_0  
pyparsing                 2.1.4                    py36_0  
pyqt                      5.6.0                    py36_2  
pytables                  3.3.0               np112py36_0  
python                    3.6.0                         0  
python-dateutil           2.6.0                    py36_0  
pytz                      2017.2                   py36_0  
pyyaml                    3.12                     py36_0  
pyzmq                     16.0.2                   py36_0  
qt                        5.6.2                         4  
readline                  6.2                           2  
requests                  2.12.4                   py36_0  
ruamel_yaml               0.11.14                  py36_1  
scikit-learn              0.18.1              np112py36_1  
scipy                     0.19.0              np112py36_0  
setuptools                27.2.0                   py36_0  
simplegeneric             0.8.1                    py36_1  
sip                       4.18                     py36_0  
six                       1.10.0                   py36_0  
sqlite                    3.13.0                        0  
terminado                 0.6                      py36_0  
testpath                  0.3                      py36_0  
thermotools               0.2.5               np112py36_0    acellera
tk                        8.5.18                        0  
tornado                   4.5.1                    py36_0  
traitlets                 4.3.2                    py36_0  
vina                      1.1.101                       0    acellera
wcwidth                   0.1.7                    py36_0  
wheel                     0.29.0                   py36_0  
widgetsnbextension        2.0.0                    py36_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zeromq                    4.1.5                         0  
zlib                      1.2.8                         3

**Comment by j3mdamas** [comment]
This reminds me of this issue https://github.com/Acellera/htmd/issues/272#issuecomment-285352207

I thought we had solved this.

Can you do `conda install htmd-deps -c acellera`? And what about `conda install htmd=1.7.32 -c acellera`?

Please post here the outputs. Thanks.

**Comment by afdezt** [comment]
`conda install htmd-deps -c acellera`
> Fetching package metadata ...........
> Solving package specifications: 
> UnsatisfiableError: The following specifications were found to be in conflict:
>   - htmd-deps -> htmd-data 0.0.43 -> python 3.5* -> openssl 1.0.1*
>   - htmd-deps -> htmd-data 0.0.43 -> python 3.5* -> xz 5.0.5
>   - python 3.6*
> Use "conda info <package>" to see the dependencies for each package.

`conda install htmd=1.7.32 -c acellera`

> Fetching package metadata ...........
> Solving package specifications: .
> UnsatisfiableError: The following specifications were found to be in conflict:
>   - htmd 1.7.32* -> htmd-deps 1.7.32 -> htmd-data 0.0.43 -> python 3.5* -> openssl 1.0.1*
>   - htmd 1.7.32* -> htmd-deps 1.7.32 -> htmd-data 0.0.43 -> python 3.5* -> xz 5.0.5
>   - python 3.6*
> Use "conda info <package>" to see the dependencies for each package.

**Comment by j3mdamas** [comment]
I'm a bit clueless on how your conda does not find the python 3.6 packages. They are available: https://anaconda.org/acellera/HTMD/files.

Well, it seems like it sees the python 3.5, so I suggest you to change to python 3.5, either by creating a new environment in 3.5, or installing 3.5 instead of 3.6.

I will keep this open and change the title of the issue accordingly.

**Comment by afdezt** [comment]
Perfect, using an environment in 3.5 works. 

Thank you for your time!

Adrià.

**Comment by ismaelresp** [comment]
Same happened to me.
`conda install python=3.6 htmd`
forces to use py36 package.

Problem can be related to [this](https://www.continuum.io/blog/developer-blog/condas-new-noarch-packages) news by anaconda.
