### ISSUE TITLE
Amber solvate function lose segids

### ISSUE THREAD

**Issue by cuzzo87** [Acellera/htmd#345]
Running a simple example for solvate function with Amber I figured out that the segids are lost a part for waters.

Before running solvate the segid are:

```['L' 'P0' 'W' 'X1']```

After the solvate process;
```['' 'WT0' 'WT1' 'WT10' 'WT11' 'WT12' 'WT13' 'WT14' 'WT15' 'WT16' 'WT17'
 'WT18' 'WT19' 'WT2' 'WT20' 'WT21' 'WT22' 'WT23' 'WT24' 'WT25' 'WT26' 'WT3'
 'WT4' 'WT5' 'WT6' 'WT7' 'WT8' 'WT9']```

**Comment by stefdoerr** [comment]
WT are the water segments added by solvate. Are you sure the W is not kept? Maybe it's renamed? Are the atoms missing? Normally they should be kept

On May 22, 2017 8:07:16 AM GMT-05:00, cuzzo87 <notifications@github.com> wrote:
>Running a simple example for solvate function with Amber I figured out
>that the segids are lost a part for waters.
>
>Before running solvate the segid are:
>
>```['L' 'P0' 'W' 'X1']```
>
>After the solvate process;
>```['' 'WT0' 'WT1' 'WT10' 'WT11' 'WT12' 'WT13' 'WT14' 'WT15' 'WT16'
>'WT17'
>'WT18' 'WT19' 'WT2' 'WT20' 'WT21' 'WT22' 'WT23' 'WT24' 'WT25' 'WT26'
>'WT3'
> 'WT4' 'WT5' 'WT6' 'WT7' 'WT8' 'WT9']```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Acellera/htmd/issues/345

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stefdoerr** [comment]
Also what do you mean running solvate with AMBER? Solvate and everything before building is forcefield independent. Do you mean that after building you lost the segment?

On May 22, 2017 8:07:16 AM GMT-05:00, cuzzo87 <notifications@github.com> wrote:
>Running a simple example for solvate function with Amber I figured out
>that the segids are lost a part for waters.
>
>Before running solvate the segid are:
>
>```['L' 'P0' 'W' 'X1']```
>
>After the solvate process;
>```['' 'WT0' 'WT1' 'WT10' 'WT11' 'WT12' 'WT13' 'WT14' 'WT15' 'WT16'
>'WT17'
>'WT18' 'WT19' 'WT2' 'WT20' 'WT21' 'WT22' 'WT23' 'WT24' 'WT25' 'WT26'
>'WT3'
> 'WT4' 'WT5' 'WT6' 'WT7' 'WT8' 'WT9']```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Acellera/htmd/issues/345

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by j3mdamas** [comment]
@stefdoerr, enjoy your holidays! :p 

It is a very weird problem with solvate, and I don't know why we haven't faced it yet. When water segments go over 3 characters, I think this line of code "cleans" the previous segments: https://github.com/Acellera/htmd/blob/a0f18616c729f6d4aaff54d8bd28e0209d6bdedd/htmd/molecule/vmdparser.py#L34

**Comment by stefdoerr** [comment]
Ugh, make a copy of that matrix before setting to ' '. It's a bit confusing sometimes when numpy copies arrays or just passes views or copies.

On May 22, 2017 10:08:45 AM GMT-05:00, "João M. Damas" <notifications@github.com> wrote:
>@stefdoerr, enjoy your holidays! :p 
>
>It is a very weird problem with solvate, and I don't know why we
>haven't faced it yet. When water segments go over 3 characters, I think
>this line of code "cleans" the previous segments:
>https://github.com/Acellera/htmd/blob/a0f18616c729f6d4aaff54d8bd28e0209d6bdedd/htmd/molecule/vmdparser.py#L34
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Acellera/htmd/issues/345#issuecomment-303128620

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by j3mdamas** [comment]
thanks @stefdoerr

**Comment by cuzzo87** [comment]
close and see #347  #346
