### ISSUE TITLE
insert method does not obey the index

### ISSUE THREAD

**Issue by cotufalaguera** [Acellera/htmd#349]
Hi!
I have 2 different lipidic bilayers in 2 molecule objects. I want to remove the lipid of one (resid 1) and insert in that position a lipid of the other (resid 1 too). I use:
m1.remove('resid 1') -> I visulaize it and it works properly
m2.filter('resid 1') -> OK
m1.insert(m2, 1) -> Not OK

The lipid inserted is placed down in the z axis regarding the index 1, so not in the original position of resid 1 in m1. How can I place it in the given index? I have read in the documentation that index is the atom coordinate were you want to place your residue, but which atom of the removed residue? Is it using some atom of the tail of the residue 1 and for that reason it appears in the lower part?

Thanks in advance

**Comment by j3mdamas** [comment]
Hi,

I think you are misunderstanding the meaning of index. Here, index means `atom index`, which basically accounts for the ordering of the atoms. It has nothing to do wit position in space (`coords`).

Example: `m1.insert(m2, 1)` will insert the `m2` object in between atom 0 and atom 1 of the `m1` object. Is it clearer?

João

**Comment by cotufalaguera** [comment]
But so the inserted object must be placed in some coordinates right?


2017-05-22 21:05 GMT+02:00 João M. Damas <notifications@github.com>:

**Comment by cotufalaguera** [comment]
And so in anycase is there any other method that I can use to do what I
want?

2017-05-22 21:51 GMT+02:00 Maria José Falaguera Mata <
mjfalagueramata@gmail.com>:

**Comment by j3mdamas** [comment]
It's the same coordinates as original `m2` object.

There isn't a method to do what you want to, if I understand it correctly. If the residues have the same topology, you can try to replace the `coords` of one for the other. This is what I would do.

**Comment by cotufalaguera** [comment]
The problem is that residue removed and residue inserted may not have the
same number of atoms, so different size of coordinates.
I was thinking on saving the coordinates of the removed residue, centering
the residue I want to insert and use moveby method to place the residue to
be inserted in the coordinates of the previous one.
Does it seem a good option from your point of view?

2017-05-22 22:30 GMT+02:00 João M. Damas <notifications@github.com>:

**Comment by j3mdamas** [comment]
What you want to perform is not implemented.
The best way to do it would be to create an `align` method that does not need the same set of atoms. it's on the pipeline but not for the near future. sorry.

**Comment by stefdoerr** [comment]
For membranes I would maybe just get the mean coordinates of the lipid head
and place the other lipid's head there.

Aligning only works with same number of atoms. Same with replacing the
atoms.

**Comment by cotufalaguera** [comment]
Well I am trying the following:
membrane 1: m1
residue to insert: m2

m11 = m1.copy()
m12 = m1.copy()
m12.filter('resid 1 and P') # head
a = m12.coords # take head coord
m11.remove('resid 1') # remove residue

m2.center
m2.moveBy(a)
m1.append(m2) or m1.insert(m2, 1)

And when making numResidues it looks like it worked because the residue I
removed is then recovered after append but when visualized, my removed
residue is still empty and when selecting for res 1 or the last one it is
not shown.

Is this what you proposed Stefan? What do you mean with 'positioning'
appending, inserting or anothe rmethod??
Thanks a lot

2017-05-23 14:14 GMT+02:00 Stefan Doerr <notifications@github.com>:

**Comment by j3mdamas** [comment]
Hi,

What's `m2`?

Anyway, what Stefan proposed using the molecules you mentioned:

membrane 1: m1
residue to insert: m2

```python
coordp_m1 = m1.get('coords', 'resid 1 and name P')
coordp_m2 = m2.get('coords', 'resid 1 and name P')
m2.moveBy(coordp_m1-coodp_m2)
```

This should do it.

**Comment by j3mdamas** [comment]
That being said, this is a translation only, no reorientation.

**Comment by cotufalaguera** [comment]
m1 is one moelcule object and m2 is another, m1 contains an homogeneous
membrane and m2 an individual lipid different to the ones of m1. So I want
to like 'replace' one individual lipid of m1 with the lipid in m2. I
understand the thing of the coordinates and moveby but then I need somehow
to mix the lipids of one object with the lipids of the other object. It
seems that 'molecule object' understands the insertion and append
statements but then when I try to visulaize the obtained mixed molecule
object with for intance VMD it looks like the membrane 1 without the
residue removed but not with the other one there inserted

2017-05-23 19:46 GMT+02:00 João M. Damas <notifications@github.com>:

**Comment by j3mdamas** [comment]
```
m1 = Molecule('membrane.pdb')
m2 = Molecule('lipid.pdb')
coordp_m1 = m1.get('coords', 'resid 1 and name P')
coordp_m2 = m2.get('coords', 'resid 1 and name P')
m2.moveBy(coordp_m1-coodp_m2)
m1.remove('resid 1 and name P')
m1.append(m2)
m1.view()
```
Should work. If it does not, you need to show us what is `membrane.pdb` and `lipid.pdb`

**Comment by cotufalaguera** [comment]
OK!!! Now it is working!
Thank you very very much
Till next time!

2017-05-23 20:01 GMT+02:00 João M. Damas <notifications@github.com>:
