### ISSUE TITLE
Tutorials: optimization and reorganization

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#35]
- [x] Incorporate the missing fixes from my old branch j3mdamas/htmd
- [x] Organize the current tutorials.

For each tutorial:

1. Fix any outdated part
2. Rename the tutorial to make more sense (people may not know that benzamidin-trypsin is a protein-ligand system, so they need to be more obvious in the navigation bar)
3. Transform it into presentation if not in it already

- [x] Python Primer
- [x] Introduction to Atom Selections
- [x] Getting Started with HTMD Molecules
- [x] System Building Basics
- [x] System Building Protein-Ligand
- [x] System Building Protein in Membrane
- [x] System Building Protein-Protein
- [ ] System Building with Docking
- [ ] Running an Equilibration of Protein in Membrane and Ligand
- [ ] Running Adaptive Sampling
- [ ] Analyzing Ligand Binding
- [ ] Analyzing Protein Folding
- [ ] Analyzing Conformational Dynamics

I'll need to do a new one for 1.2.0

**Comment by j3mdamas** [comment]
The `Makefile` is a bit weird on tutorials and clean rules. Right now, it just creates .rst from the current tutorials list, but it does not clean the previous ones. Of course they are overwritten, but I think that the clean should also delete the source/tutorials directory. This will clean all lingering .rst files that are no longer tutorials, for example. What do you think?

**Comment by stefdoerr** [comment]
Sure. Try it and see.

**Comment by j3mdamas** [comment]
Seems like it's working fine
