### ISSUE TITLE
How to create a Molecule with multiple residues directly

### ISSUE THREAD

**Issue by DavidFunosas** [Acellera/htmd#350]
For example, we have the following data:

resid     atom     x     y     z
1             A       1     0     3
1             B       1     1     1
1             C       0     0     2
2             D       0     1     1
2             E       1     3     3
2             F       0     2     1

And we want to create a Molecule object that contains both residues, with all their atoms' coords. What we do now is to create a Molecule object for the first residue, with resid = 1 and coords = [[1,0,3],[1,1,1],[0,0,2]], and we do the same for the second residue, so that we have two different Molecule objects. Then, we use the method append() to have both residues in a single Molecule object. With this object, we can filter the coords by resid and we'll get the coords of the atoms from the residue we've filtered for (if we filter by resid = 1, we'll get [[1,0,3],[1,1,1],[0,0,2]]). And if we want to remove a residue from the Molecule, we can do it the same way with the remove() method. So far so good. The fact is that we'd like to create the Molecule object with all residues without using the append() method and still be able to filter the atoms by resid afterwards. Is there any other way to create the Molecule specifying that atoms A, B and C correspond to the first residue and atoms D, E and F correspond to the second residue?

We want to avoid using the append() method because it requires to create a Molecule object for each residue, and this is very time consuming when we're reading membranes with thousands of residues.

Thank you very much.

**Comment by j3mdamas** [comment]
`Molecule.set('resid', '<desired number>', '<selection of atoms>')`?

**Comment by j3mdamas** [comment]
Does this answer you?

**Comment by DavidFunosas** [comment]
Yes, thank you! :)

2017-05-25 23:12 GMT+02:00 João M. Damas <notifications@github.com>:
