### ISSUE TITLE
Error in importing HTMD: CompareVersions()

### ISSUE THREAD

**Issue by Marina18** [Acellera/htmd#352]
When importing HTMD I get the following error:

`
from htmd import *

Please cite HTMD: Doerr et al.(2016)JCTC,12,1845. https://dx.doi.org/10.1021/acs.jctc.6b00049

HTMD Documentation at: https://www.htmd.org/docs/latest/

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-1-c6de4ef1ed7f> in <module>()
----> 1 from htmd import *

/home/marina/miniconda3/envs/htmd/lib/python3.5/site-packages/htmd/__init__.py in <module>()
     86     check_registration(product='htmd')
     87     show_news()
---> 88     compareVersions()
     89 
     90 import progress_reporter.bar.gui as __gui  # Disabling pyemma progress widgets

/home/marina/miniconda3/envs/htmd/lib/python3.5/site-packages/htmd/latest.py in compareVersions()
     42             verstring = 'stable'
     43         else:
---> 44             pieces = latestversions[1].split()
     45             latest = pieces[0].strip()
     46             verstring = 'devel'

IndexError: list index out of range
`
I tried to make a specific environment in python 3.5 but the import still gives the same error.

**Comment by j3mdamas** [comment]
Hi Marina,

Weird error. Can you please do: `cat ~/.htmd/.latestversion`?

João

**Comment by Marina18** [comment]
I do not get any result from this command

**Comment by j3mdamas** [comment]
Does the computer have internet?

Can you give me the output of:
```
from htmd.latest import _release_version
print(_release_version('acellera', 'htmd'))
```

**Comment by Marina18** [comment]
The computer has internet. The output is still the same:

`
from htmd.latest import _release_version
   ...: print(_release_version('acellera', 'htmd'))
   ...: 

Please cite HTMD: Doerr et al.(2016)JCTC,12,1845. https://dx.doi.org/10.1021/acs.jctc.6b00049

HTMD Documentation at: https://www.htmd.org/docs/latest/

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-2-4f5f6215fa56> in <module>()
----> 1 from htmd.latest import _release_version
      2 print(_release_version('acellera', 'htmd'))

/home/marina/miniconda3/lib/python3.6/site-packages/htmd/__init__.py in <module>()
     87     check_registration(product='htmd')
     88     show_news()
---> 89     compareVersions()
     90 
     91 import progress_reporter.bar.gui as gui  # Disabling pyemma progress widgets

/home/marina/miniconda3/lib/python3.6/site-packages/htmd/latest.py in compareVersions()
     42             verstring = 'stable'
     43         else:
---> 44             pieces = latestversions[1].split()
     45             latest = pieces[0].strip()
     46             verstring = 'devel'

IndexError: list index out of range

`

**Comment by j3mdamas** [comment]
Of course, sorry. Before starting ipython and running what I said, do first `export HTMD_NONINTERACTIVE=1` in the shell.

**Comment by Marina18** [comment]
Ok, now seems to work fine doing the 'export HTMD_NONINTERACTIVE=1' and using inside ipython ' from htmd import * '

thanks!

**Comment by j3mdamas** [comment]
That is a workaround. If you could please tell me the output of:

```
from htmd.latest import _release_version
print(_release_version('acellera', 'htmd'))
```

I would really appreciate it. Thanks!

**Comment by Marina18** [comment]
`In [1]: from htmd.latest import _release_version
   ...: print(_release_version('acellera', 'htmd'))
   ...: 
Using Anaconda API: https://api.anaconda.org
('1.6.0', '1.7.33', ['==3.5'], ['==3.5', '==3.6'])
`

**Comment by j3mdamas** [comment]
My guess was that, at the first import from htmd, the internet was off or out for a reason, then the empty version file was written, and since the file is younger than 1 day, it does not try to write a new one. As such, the command fails. It's an easy fix, thanks for reporting.
