### ISSUE TITLE
tutorials or supports for metadyanmics

### ISSUE THREAD

**Issue by liyigerry** [Acellera/htmd#353]
Hi,

HTMD is a python-accessible MD engine.
Is there some tutorials or supports for metadyanmics?
Or how can we develop it?

Recently, I focus on PCA based metadynamics.
There is an compile with plumed by [PCAVAR](https://plumed.github.io/doc-v2.3/user-doc/html/_p_c_a_v_a_r_s.html). But it's difficult to use.

For PCA, mdtraj and Prody can do it enough well.
Can we bridge this?

Li Yi

**Comment by tonigi** [comment]
You can use Plumed currently for two different things. 
1. Run biased simulations;  that's more related to ACEMD (there is some documentation around). 
2. Use Plumed syntax and collective variables in analysis. See https://www.htmd.org/docs/latest/htmd.projections.metricplumed2.html

**Comment by liyigerry** [comment]
@tonigi Sorry late for replay.
For point 1: Could you provide some urls for reference?
For point 2: It means we can use plumed for analysis? How can I run metadynamics with your package?

Thanks.

**Comment by tonigi** [comment]
1. To run a biased simulation with ACEMD (e.g. metadynamics) see https://github.com/tonigi/ACEMD-PLUMED
2. It is possible to use PLUMED-based CVs to analyze trajectories in HTMD (likely unbiased, not metadynamics): see https://www.htmd.org/docs/latest/htmd.projections.metricplumed2.html

**Comment by j3mdamas** [comment]
We will incorporate the PLUMED plugin use with ACEMD to the corresponding documentation. I will open a new issue on that.
