### ISSUE TITLE
Pull requests of users that don't have permissions for htmdlib fail on Travis

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#356]
@mj-harvey not really urgent but very annoying, assuming we encourage people to contribute

**Comment by stefdoerr** [comment]
Travis I think has a flag for pull requests. We could disable htmdlib building in that case. I can look into it next week

On June 1, 2017 5:48:22 AM GMT-05:00, "João M. Damas" <notifications@github.com> wrote:
>@mj-harvey not really urgent but very annoying, assuming we encourage
>people to contribute
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Acellera/htmd/issues/356

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stefdoerr** [comment]
This should do it https://github.com/Acellera/htmd/commit/5f12fa53026ba8d3adbe132199f7bf15c7043226

Let's see if it passes travis

**Comment by stefdoerr** [comment]
Hm I noticed that we don't test the new libs in Travis. We only used to build them before pusing to conda. This should probably change

**Comment by j3mdamas** [comment]
How does this work on Appveyour?

**Comment by stefdoerr** [comment]
Same way I assume. There is an env var for PRs

**Comment by stefdoerr** [comment]
Passed Travis.

**Comment by stefdoerr** [comment]
Well, still needs someone to try a PR to see if it works but I assume it should now

**Comment by j3mdamas** [comment]
There's a PR waiting for review that you could look at :P
