### ISSUE TITLE
non-zero exit status 43

### ISSUE THREAD

**Issue by liyigerry** [Acellera/htmd#358]
Hi,

I want use HTMD on GPU clusters.
Firstly, I build the system and run equilibration on a GPU cluster which has 5 GPU.
I got this error
```
You are on the latest HTMD version (1.7.33).

2017-06-03 14:17:20,716 - htmd.queues.localqueue - INFO - Using GPU devices 0,1,2,3,4
2017-06-03 14:17:20,718 - htmd.queues.localqueue - INFO - Queueing /home/liyi/gp120/htmd_apo/equil
2017-06-03 14:17:20,719 - htmd.queues.localqueue - INFO - Running /home/liyi/gp120/htmd_apo/equil on GPU device 0
2017-06-03 14:17:21,764 - htmd.queues.localqueue - INFO - Error in simulation /home/liyi/gp120/htmd_apo/equil. Command '/home/liyi/gp120/htmd_apo/equil/job.sh' returned non-zero exit status 43.
```

And I try to specify the `ngpu` and `devices`  like this:
```
local.ngpu = 4
local.devices = [1,2,3,4]
```
It got this error:
```
ValueError: Parameters `ngpu` and `devices` are mutually exclusive.
```

Any help?
Thanks.

**Comment by stefdoerr** [comment]
The error is relatively explanatory. You should only use ngpu or the device options. Not both. Also devices start from 0 not 1.

On June 3, 2017 1:38:47 AM GMT-05:00, "阿毅Gerry" <notifications@github.com> wrote:
>Hi,
>
>I want use HTMD on GPU clusters.
>Firstly, I build the system and run equilibration on a GPU cluster
>which has 5 GPU.
>I got this error
>```
>You are on the latest HTMD version (1.7.33).
>
>2017-06-03 14:17:20,716 - htmd.queues.localqueue - INFO - Using GPU
>devices 0,1,2,3,4
>2017-06-03 14:17:20,718 - htmd.queues.localqueue - INFO - Queueing
>/home/liyi/gp120/htmd_apo/equil
>2017-06-03 14:17:20,719 - htmd.queues.localqueue - INFO - Running
>/home/liyi/gp120/htmd_apo/equil on GPU device 0
>2017-06-03 14:17:21,764 - htmd.queues.localqueue - INFO - Error in
>simulation /home/liyi/gp120/htmd_apo/equil. Command
>'/home/liyi/gp120/htmd_apo/equil/job.sh' returned non-zero exit status
>43.
>```
>
>And I try to specify the `ngpu` and `devices`  like this:
>```
>local.ngpu = 4
>local.devices = [1,2,3,4]
>```
>It got this error:
>```
>ValueError: Parameters `ngpu` and `devices` are mutually exclusive.
>```
>
>Any help?
>Thanks.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Acellera/htmd/issues/358

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by liyigerry** [comment]
@stefdoerr Thanks.
How to handle the first error?
> `2017-06-03 14:17:21,764 - htmd.queues.localqueue - INFO - Error in simulation /home/liyi/gp120/htmd_apo/equil. Command '/home/liyi/gp120/htmd_apo/equil/job.sh' `
> `returned non-zero exit status 43.`

I use this code, getting the same error.
```
from htmd import *

local = LocalGPUQueue()
# local.ngpu = 4
local.devices = [0,1,2,3,4]
local.submit('./equil/')
local.wait()
```

> Also devices start from 0 not 1.

In my server, GPU No.0 is used for display.
Seeing with nvidia-smi

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro K420         On   | 0000:01:00.0      On |                  N/A |
| 25%   38C    P8    N/A /  N/A |    285MiB /   980MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 0000:05:00.0     Off |                    0 |
| N/A   37C    P8    26W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           On   | 0000:06:00.0     Off |                    0 |
| N/A   31C    P8    30W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           On   | 0000:85:00.0     Off |                    0 |
| N/A   37C    P8    26W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla K80           On   | 0000:86:00.0     Off |                    0 |
| N/A   28C    P8    29W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by stefdoerr** [comment]
Ah ok I didn't expect you to have 5 GPUs :) Then it's okay to do 1-4.

To see what goes wrong try calling `/home/liyi/gp120/htmd_apo/equil/job.sh` from command line.
Then try also calling `/home/liyi/gp120/htmd_apo/equil/run.sh` from command line.
Also check if any `log.txt` files were written in that folder.

**Comment by liyigerry** [comment]
@stefdoerr Thanks.
I run both files as you say.
In log.txt
```
# ACEMD Molecular Dynamics Version [2016.10.27] (git [992255])
# (c) 2009-2016 Acellera Ltd. http://www.acellera.com
# See License Agreement for terms and conditions of use
# or write to support@acellera.com
#
# Licensed by Acellera Ltd (http://www.acellera.com)
# No node-locked license available.
# No floating licenses available.
#
# NO ACEMD Pro license found.
# ACEMD will run in BASIC mode
# Some features are disabled
# Execution limited to the first GPU
# For licensing contact info@acellera.com
#
#
# You must register HTMD in order to use ACEMD in Basic mode
#
```

Can I get an academic license free?

**Comment by stefdoerr** [comment]
You can only run ACEMD with one GPU with the academic license as far as I remember?
@giadefa @mj-harvey ?

Try setting `devices = [1]` as a test. Still this error makes me wonder if HTMD has been registered. When you do `from htmd import *` what does it print?

**Comment by j3mdamas** [comment]
Dear @liyigerry,

You have to register using `htmd_register` from the command-line. This will give you ACEMD Basic License, which will allow you to use one GPU. If you want to use more than one GPU, please [contact Acellera](https://www.acellera.com/contact/) for an Academic license.
