### ISSUE TITLE
Problem with model.createState()

### ISSUE THREAD

**Issue by piia600** [Acellera/htmd#359]
Hi,

I have a system where I would like to combine two out of three Markov states (HTMD 1.7.33). However, if I combine states 0 and 1, the equilibration probabilities start looking weird, and I think I have lost some data in the process as the percentages don't add up to 100. It is possible that there is an error in the combining of the states.

Attached you can find a screenshot of the behavior.

![probabilities](https://cloud.githubusercontent.com/assets/12083029/26777826/f868b85c-49de-11e7-83b3-13886f35d27b.png)

Cheers,
Piia

**Comment by stefdoerr** [comment]
I have a feeling it's related to this issue. https://github.com/Acellera/htmd/issues/195 I am going to take a look into it this week.

**Comment by stefdoerr** [comment]
Could you please do me a favour and do:
```python
model.save('debug.dat')
```
before doing the `createState`
And upload that file here?

**Comment by piia600** [comment]
Here is some data. It is not the same as when I originally posted this, but the problem seems to be reproducible. 

[debug.dat.tar.gz](https://github.com/Acellera/htmd/files/1064287/debug.dat.tar.gz)

**Comment by stefdoerr** [comment]
Oof ok this is complicated. So, when you basically delete two states to create a new one, then the old empty states are ignored by the model even though they still have some membership probability from other microstates which don't belong to them. Then this probability is not counted and thus we end up with less than 1. I will see how to fix this.

Unrelated to the other issue that I mentioned though.

**Comment by stefdoerr** [comment]
Okay fixed :) Thanks a lot for the example, it was really helpful.
@j3mdamas can tell you when we make a new release

**Comment by j3mdamas** [comment]
Will be on 1.7.35 in ~1 week
