### ISSUE TITLE
test Model save/load

### ISSUE THREAD

**Issue by cuzzo87** [Acellera/htmd#364]
I was trying to load a model already created.

```python
model=Model()

model.load("Results_project/model_lag2_2projections.dat")`

and the following error raised:
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-85871247f5b8> in <module>()
      1 model=Model()
----> 2 model.load("Results_project/model_lag2_2projections.dat")

/shared/acellera/miniconda3/lib/python3.6/site-packages/htmd/model.py in load(self, filename)
    648         import pickle
    649         f = open(filename, 'rb')
--> 650         z = pickle.load(f)
    651         f.close()
    652         for k in z:

ModuleNotFoundError: No module named 'pandas.indexes'
```

**Comment by stefdoerr** [comment]
You updated pandas. The new htmd includes a hacky fix for it

On June 14, 2017 10:11:04 AM GMT+02:00, cuzzo87 <notifications@github.com> wrote:
>I was trying to load a model already created.
>
>`model=Model()
>
>model.load("Results_project/model_lag2_2projections.dat")`
>
>and the following error raised:
>ModuleNotFoundError                       Traceback (most recent call
>last)
><ipython-input-2-85871247f5b8> in <module>()
>      1 model=Model()
>----> 2 model.load("Results_project/model_lag2_2projections.dat")
>
>/shared/acellera/miniconda3/lib/python3.6/site-packages/htmd/model.py
>in load(self, filename)
>    648         import pickle
>    649         f = open(filename, 'rb')
>--> 650         z = pickle.load(f)
>    651         f.close()
>    652         for k in z:
>
>ModuleNotFoundError: No module named 'pandas.indexes'``
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Acellera/htmd/issues/364

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cuzzo87** [comment]
I updated pyemma maybe one their dependencies. Should I to downgrade pandas?

**Comment by stefdoerr** [comment]
Either pull the latest htmd, wait for the next htmd release or run this code:

```python
import sys
try:
    import pandas.indexes
except ImportError:
    import pandas.core.indexes
    sys.modules['pandas.indexes'] = pandas.core.indexes  # Hacky fix for new pandas version
```

**Comment by stefdoerr** [comment]
But in general don't expect saved data to work when you update htmd or any of it's dependencies (pyemma, pandas etc). It's only meant to work within a given version

**Comment by j3mdamas** [comment]
@stefdoerr, aren't we saving/loading a test `Model` in the tests? We should, in order to catch this, no?

**Comment by stefdoerr** [comment]
Don't think we do

**Comment by j3mdamas** [comment]
it wouldn't be applied to this case, but we should do it

**Comment by j3mdamas** [comment]
can I assign it to you?

**Comment by j3mdamas** [comment]
you = @stefdoerr

**Comment by stefdoerr** [comment]
ok

**Comment by stefdoerr** [comment]
https://github.com/Acellera/htmd/commit/e9440cd566cfb2027b9988f4e8436a8b28af401c
