### ISSUE TITLE
Fix appveyor tests

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#369]
- They need to work on Acellera/htmd, forks and PRs (like https://github.com/Acellera/htmd/pull/368)
- Create Acellera appveyor account (so we are not relying on @stefdoerr appveyor account)
- Add the badge to the README.md

**Comment by stefdoerr** [comment]
- Added acelleraci account that runs appveyor. 
- Added badge to htmd/README

TODO:

- Make (some) tests work

**Comment by j3mdamas** [comment]
@stefdoerr can we drop Windows support all together?

I doubt major functionalities of HTMD like running simulations or anything that uses bash works anyway, so I believe that Windows support is a dream for now.

**Comment by stefdoerr** [comment]
Mmm when I tested it it kinda worked actually. Basic stuff like Molecule
and atomselections definitely. The rest I didn't run.
I think it's more that we are not bothered with testing it.

**Comment by j3mdamas** [comment]
yeah, but will someone install HTMD to use Molecule? I think it beats its purpose.

We can decide in today's meeting, I guess.

**Comment by j3mdamas** [comment]
So, here's what I'm going to do. Stop CI in Windows for now. If we want to recover it, we should make HTMD more functional on Windows. This means at least being able to run an MD engine.

I won't delete anything, just move the YAML file and everything appveyor related into it's respective directory, so we can salvage the work @stefdoerr already did later (when we have more time and requests to support Windows)
