### ISSUE TITLE
where's data map?

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#37]
Hi guys,
When projecting with the old method:
```
data1 = MetricDistance.project(sims, 
    'resname LIG and noh', 
    'resid 88 172 176 180 187 188 189 192 295 296 297 303 304 305 306 308 310 314 317 and name CA',  metric='contacts')
```
we get some values in data1.map

However if I do the same with the new suggested method:
```
sims = simlist(glob('filtered/*/'), './filtered/filtered.pdb')
metr=Metric(sims)
metr.projection(MetricDistance('resname LIG and noh', 'resid 88 172 176 180 187 188 189 192 295 296 297 303 304 305 306 308 310 314 317 and name CA', metric='contacts'))
data=metr.project()
```
data.map is empty. 

How can I look what are the indexes after using  `getStateStatistic `now?

**Comment by stefdoerr** [comment]
Hm you are right. For some reason the map calculation was disabled. I cannot remember the reason anymore, probably it broke with some classes and we forgot to open an issue on it.

In the meanwhile try this to get the maps
```python
metr = MetricDistance('resname LIG and noh', 'resid 88 172 176 180 187 188 189 192 295 296 297 303 304 305 306 308 310 314 317 and name CA', metric='contacts')
data.map = metr.getMapping(Molecule('./filtered/filtered.pdb'))  
```

I'll open an issue on the map calculation

**Comment by giadefa** [comment]
Could you live without for now?

**Comment by noeliaferruz** [comment]
Absolutely

**Comment by stefdoerr** [comment]
Nice :)
