### ISSUE TITLE
Addaptive Sampling

### ISSUE THREAD

**Issue by yiannisgaldadas** [Acellera/htmd#374]
Dear HTMD users,

I am trying to perform an Adaptive Sampling simulation on our local GPU machine using the following block of code 

```
md.write('./equil', './generators/s1')
queue = LocalGPUQueue()
queue.datadir = './data'
md = AdaptiveMD()
md.app = queue
md.nmin=2  # minimum number of running sims
md.nmax=4  # maximum number of running sims
md.nepochs = 3  
md.generatorspath = './generators/s1'
md.ticadim = 3 # number of TICA dimensions
md.projection = MetricSelfDistance('name CA')
md.updateperiod = 20
md.run()
```
but I get the following error:

> FileNotFoundError: No data folders were given, check your arguments.

Any idea where the problem may come from? 
Moreover, I want to run the simulation on GPUs 1, 2 and 4. In the previous version I could use md.app = AcemdLocal(devices=[1,2,4]) but now the devices flag is no longer an option. Does anyone know what is the new syntax in the new HTMD release?

Best wishes,
Yiannis

**Comment by stefdoerr** [comment]
You should use `LocalGpuQueue`. `AcemdLocal` is deprecated.
You set it up as follows:
```python
queue = LocalGPUQueue()
queue.devices = [1,2,4]
md.app = queue
```

The error you mention is given because it cannot find any simulations in the data folder. That is curious as it would mean that the folders are there but it cannot detect any simulations in them. For this I would either need to see the full log printed in the console or a listing of all the folders you currently have in the adaptive directory (i.e. using the `tree` bash command)

**Comment by yiannisgaldadas** [comment]
Dear Stef,

Thank you very much for your swift response.

Please find bellow the result of the tree command

.
├── 5_dMUT.pdb
├── build
│   ├── input.pdb
│   ├── leap.log
│   ├── log.txt
│   ├── structure.crd
│   ├── structure.pdb
│   ├── structure.prmtop
│   └── tleap.in
├── data
├── dMUT.pdb
├── equil
│   ├── input
│   ├── log.txt
│   ├── output.coor
│   ├── output.idx
│   ├── output.vel
│   ├── output.xsc
│   ├── output.xstfile
│   ├── run.sh
│   ├── structure.pdb
│   └── structure.prmtop
├── generators
│   └── s1
│       ├── input
│       ├── input.coor
│       ├── input.xsc
│       ├── run.sh
│       ├── structure.pdb
│       └── structure.prmtop
├── input
│   ├── e1s1_s1
│   │   ├── input
│   │   ├── input.coor
│   │   ├── input.xsc
│   │   ├── log.txt
│   │   ├── output.coor
│   │   ├── output.idx
│   │   ├── output.vel
│   │   ├── output.xsc
│   │   ├── restart.coor
│   │   ├── restart.coor.bkp
│   │   ├── restart.idx
│   │   ├── restart.idx.bkp
│   │   ├── restart.runtime
│   │   ├── restart.vel
│   │   ├── restart.vel.bkp
│   │   ├── restart.xsc
│   │   ├── restart.xsc.bkp
│   │   ├── run.sh
│   │   ├── structure.pdb
│   │   ├── structure.prmtop
│   │   └── trajectory.xtc
│   ├── e1s2_s1
│   │   ├── input
│   │   ├── input.coor
│   │   ├── input.xsc
│   │   ├── log.txt
│   │   ├── output.coor
│   │   ├── output.idx
│   │   ├── output.vel
│   │   ├── output.xsc
│   │   ├── restart.coor
│   │   ├── restart.coor.bkp
│   │   ├── restart.idx
│   │   ├── restart.idx.bkp
│   │   ├── restart.runtime
│   │   ├── restart.vel
│   │   ├── restart.vel.bkp
│   │   ├── restart.xsc
│   │   ├── restart.xsc.bkp
│   │   ├── run.sh
│   │   ├── structure.pdb
│   │   ├── structure.prmtop
│   │   └── trajectory.xtc
│   ├── e1s3_s1
│   │   ├── input
│   │   ├── input.coor
│   │   ├── input.xsc
│   │   ├── log.txt
│   │   ├── output.coor
│   │   ├── output.idx
│   │   ├── output.vel
│   │   ├── output.xsc
│   │   ├── restart.coor
│   │   ├── restart.coor.bkp
│   │   ├── restart.idx
│   │   ├── restart.idx.bkp
│   │   ├── restart.runtime
│   │   ├── restart.vel
│   │   ├── restart.vel.bkp
│   │   ├── restart.xsc
│   │   ├── restart.xsc.bkp
│   │   ├── run.sh
│   │   ├── structure.pdb
│   │   ├── structure.prmtop
│   │   └── trajectory.xtc
│   └── e1s4_s1
│       ├── input
│       ├── input.coor
│       ├── input.xsc
│       ├── log.txt
│       ├── restart.coor
│       ├── restart.coor.bkp
│       ├── restart.idx
│       ├── restart.idx.bkp
│       ├── restart.runtime
│       ├── restart.vel
│       ├── restart.vel.bkp
│       ├── restart.xsc
│       ├── restart.xsc.bkp
│       ├── run.sh
│       ├── structure.pdb
│       ├── structure.prmtop
│       └── trajectory.xtc
└── Setup_Adaptive_dMUT.ipynb

as well as the log printed in the console 

`FileNotFoundError                         Traceback (most recent call last)
<ipython-input-6-81eb8201a6dd> in <module>()
     13 md.projection = MetricSelfDistance('name CA')
     14 md.updateperiod = 20
---> 15 md.run()
     16 
     17 # Macro states are used for initiating the new simulations

~/miniconda3/lib/python3.6/site-packages/htmd/adaptive/adaptive.py in run(self)
     97                 # If currently running simulations are lower than nmin start new ones to reach nmax number of sims
     98                 if self._running <= self.nmin and epoch < self.nepochs:
---> 99                     flag = self._algorithm()
    100                     if flag is False:
    101                         self._unsetLock()

~/miniconda3/lib/python3.6/site-packages/htmd/adaptive/adaptiverun.py in _algorithm(self)
    123 
    124     def _algorithm(self):
--> 125         data = self._getData(self._getSimlist())
    126         if not self._checkNFrames(data): return False
    127         self._createMSM(data)

~/miniconda3/lib/python3.6/site-packages/htmd/adaptive/adaptiverun.py in _getSimlist(self)
    143         logger.info('Postprocessing new data')
    144         sims = simlist(glob(path.join(self.datapath, '*', '')), glob(path.join(self.inputpath, '*', '')),
--> 145                        glob(path.join(self.inputpath, '*', '')))
    146         if self.filter:
    147             sims = simfilter(sims, self.filteredpath, filtersel=self.filtersel)

~/miniconda3/lib/python3.6/site-packages/htmd/simlist.py in simlist(datafolders, topologies, inputfolders)
    148 
    149     if not datafolders:
--> 150         raise FileNotFoundError('No data folders were given, check your arguments.')
    151     if not topologies:
    152         raise FileNotFoundError('No molecule files were given, check your arguments.')

FileNotFoundError: No data folders were given, check your arguments.`

Thank you once again for your consideration!

Best,
Yiannis

**Comment by stefdoerr** [comment]
Hmm seems like something went wrong with the simulations. Seems like the app didn't change directories or failed at copying them to the `data` folder which should contain the completed simulations. Can you remove the `input` folder? Also the `e1s4_s1` folder seems to be empty and it's contents are spilled out into the outer folder? So delete those too I guess

**Comment by stefdoerr** [comment]
And then try with:
```python
queue = LocalGPUQueue()
queue.devices = [1,2,4]
queue.datadir = './data'
md.app = queue
```

**Comment by yiannisgaldadas** [comment]
Dear Stef, 

Thank you very much for your help!
It seems to work after your recommendations.

Best,
Yiannis
