### ISSUE TITLE
Atom selection

### ISSUE THREAD

**Issue by yiannisgaldadas** [Acellera/htmd#376]
Dear HTMD users,

I am trying to select certain atoms of a protein using htmd and the VMD syntax but I cannot extract a .pdb file to check if the selection is correct.

mol = Molecule('dMUT.pdb')
sel = mol.atomselect('((resid 44 to 52) or (resid 71 to 78)) and (name CA)')
sel.write('test.pdb')

> AttributeError: 'numpy.ndarray' object has no attribute 'write'

I have checked with VMD that the syntax is correct and that indeed it pick the right atoms.

Best,
Yiannis

**Comment by stefdoerr** [comment]
You have a typo
`mol.write('test.pdb')`

**Comment by stefdoerr** [comment]
Actually if you want to write a subselection then do:
`mol.write('test.pdb', sel='((resid 44 to 52) or (resid 71 to 78)) and (name CA)')`

**Comment by stefdoerr** [comment]
Ah I see your confusion. In VMD you can "write" out atomselections. In our case an atomselection is just a boolean numpy array. HTMD does not work the same way VMD does. Check the documentation of the Molecule class a bit closer if you want :)

**Comment by yiannisgaldadas** [comment]
Thank you very much :)

**Comment by stefdoerr** [comment]
Παρακαλώ :smile:

**Comment by yiannisgaldadas** [comment]
:' )
