### ISSUE TITLE
Alternative atom locations

### ISSUE THREAD

**Issue by stefdoerr** [Acellera/htmd#378]
There are multiple issues arising in building and other functions from alternative atom locations. Practically we should never keep them but we should not make the choice for the user in my opinion.

I vote to throw a warning if the PDB reader detects alternative atom locations and tell the user to choose which ones to keep.

Opinions? @giadefa @j3mdamas @tonigi

**Comment by j3mdamas** [comment]
That will make the `Molecule` class interactive by default, and I think that's annoying.

My proposal: by default keep altloc `A` (still keep the field as A), warn the user about the action taken. Create a `Molecule` optional argument that takes a list (or maybe dictionary) that the user provides, and should be of length equal to the number of altloc residues in the molecule. The list would state the altlocs to keep.

If you really want interactive (nice but not priority), that same option could take `interactive` as a string, but should show the user a visualisation, residue by residue, so the user can make an informed decision.

My two cents.
João

**Comment by tonigi** [comment]
I would keep A by default. The argument to Molecule to change behavior seems ok, but  I’d rather have an argument like “keepaltlocs” which creates atoms for all altlocs, which the user can then .filter() with convenient atom selections. 

T

**Comment by stefdoerr** [comment]
Ok I'll keep A and warn the user. If he says keepaltloc I keep all with original naming.
