### ISSUE TITLE
give option to put parameterise files elsewhere than $HOME/.htmd/gaamp

### ISSUE THREAD

**Issue by mj-harvey** [Acellera/htmd#38]

**Comment by mj-harvey** [comment]
Fixed. "--cache" argument added to parameterise cli

**Comment by giadefa** [comment]
Would it be better if CWD is the default?

g

On 25 May 2016 at 11:23, M J Harvey <notifications@github.com> wrote:

> Closed #38 <https://github.com/Acellera/htmd/issues/38>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Acellera/htmd/issues/38#event-671494404>
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>

**Comment by j3mdamas** [comment]
it needs to be centralized because of the resume option?
