### ISSUE TITLE
MATCH does not work on Mac!

### ISSUE THREAD

**Issue by raimis** [Acellera/htmd#388]
MATCH fails on Travis OSX environment due to an incorrect usage of *readlink*:
```bash
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
```
It seems the problem is coming from the wrapper: https://github.com/Acellera/conda-match/blob/master/match/bin/match-typer

**Comment by stefdoerr** [comment]
https://stackoverflow.com/a/4031502/1198173
This seems like the most logical solution.

**Comment by j3mdamas** [comment]
I'll try to follow Stefan's suggestion

**Comment by j3mdamas** [comment]
The suggestion requires the user to install coreutils.

I'll rather go with the solution of making the wrapper equivalent to acemd wrapper, which uses `which` and that works in Mac.
