### ISSUE TITLE
Dihedral angle calculation is inconsistent

### ISSUE THREAD

**Issue by raimis** [Acellera/htmd#393]
At https://github.com/Acellera/htmd/blob/master/htmd/parameterization/ffevaluate.py
```python
    def evaluateTorsion(coords, phis):
        pos1 = coords[0, :]
        pos2 = coords[1, :]
        pos3 = coords[2, :]
        pos4 = coords[3, :]

        r12 = pos1 - pos2
        r23 = pos2 - pos3
        r34 = pos3 - pos4

        r12 = r12.flatten()
        r23 = r23.flatten()
        r34 = r34.flatten()

        A = np.cross(r12, r23)
        B = np.cross(r23, r34)
        C = np.cross(r23, A)

        rA = 1. / np.linalg.norm(A)
        rB = 1. / np.linalg.norm(B)
        rC = 1. / np.linalg.norm(C)

        B = B.dot(rB)

        cos_phi = A.dot(B) * rA
        sin_phi = C.dot(B) * rC

        phi = - math.atan2(sin_phi, cos_phi)
...
```

At https://github.com/Acellera/htmd/blob/master/htmd/parameterization/phi.py
```python
def getPhi(coords, atoms):
    coords = np.atleast_3d(coords)
    pos1 = coords[atoms[0], :, 0]
    pos2 = coords[atoms[1], :, 0]
    pos3 = coords[atoms[2], :, 0]
    pos4 = coords[atoms[3], :, 0]

    r12 = pos1 - pos2
    r23 = pos2 - pos3
    r34 = pos3 - pos4

    A = np.cross(r12, r23)
    B = np.cross(r23, r34)
    C = np.cross(r23, A)

    rA = 1. / np.linalg.norm(A)
    rB = 1. / np.linalg.norm(B)
    rC = 1. / np.linalg.norm(C)

    B = B * rB

    cos_phi = (np.dot(A, B)) * rA
    sin_phi = (np.dot(C, B)) * rC

    phi = - math.atan2(sin_phi, cos_phi)
...
```

Identical code, except:
```python
B = B.dot(rB)
```
versus
```python
B = B * rB
```

**Comment by stefdoerr** [comment]
Keep one, drop the other and import it from the single definition. They should be equivalent given correct orientation of the vectors (one being a row vector, the other column) but just in case I'd keep the `.dot` version since it's more explicit.

**Comment by raimis** [comment]
Yes, row or column vectors don't matter here. However, these lines gives different results: dot product vs. element-wise product.
```python
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a * b)
print(a.dot(b))
```
```
array([ 4, 10, 18])
32
```

**Comment by stefdoerr** [comment]
True, even if I convert them to row/column I just get the outerproduct but
not the dot product

In [9]: print(a[np.newaxis,:] * b[:, np.newaxis])
[[ 4 8 12]
 [ 5 10 15]
 [ 6 12 18]]

**Comment by raimis** [comment]
Yes, `getPhi` is computing some gibberish and probably messing up the dihedral fitting.

I'll make a separate function for dihedral angle and replace them.

**Comment by stefdoerr** [comment]
FYI there is a setDihedral method in the Molecule class which works correct and correct dihedral calculation code in `metricdihedral.py`. Correct as in: I've tested them relatively thoroughly

**Comment by raimis** [comment]
Thank, @stefdoerr. I'll try to reuse the code.
