### ISSUE TITLE
Dependencies issue

### ISSUE THREAD

**Issue by arayasecchi** [Acellera/htmd#394]
Hi,

While tryying to install HTMD following the intructions on the web page I got this error:

conda install htmd -c acellera -y
Fetching package metadata ...........
Solving package specifications: 

PackageNotFoundError: Dependency missing in current linux-64 channels: 
  - htmd -> htmd-deps 1.7.2

Any advice?

Thanks.

**Comment by j3mdamas** [comment]
Hi @arayasecchi,

Is this a new installation or an update? Which is your python version (run `python -V`)?

If this is a new installation, there should be no reason for it to be installing version 1.7.2, since we are already on version 1.9.1.

(The message is correct though, we are missing the htmd-deps package 1.7.2 from how channel)

**Comment by arayasecchi** [comment]
Hi @j3mdamas 

Its a new installation. I installed conda first (following the page instructions) and then added the accellera channels and tried to install htmd.

And if I do python -V I get : Python 2.7.6

**Comment by j3mdamas** [comment]
Hi,

We do not support python 2.7. Are you using conda for other things other than HTMD? If not, I would recommend a fresh installation with the latest installer, which installs python 3.6 by default : https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh

If you are using conda for other applications, the options are: create a separate conda installation (different directory, control the use the different conda installations through PATH env variable), create a conda environment (https://conda.io/docs/using/envs.html#create-a-separate-environment).

Best,
João

**Comment by arayasecchi** [comment]
Hi @j3mdamas 

That’s what I did, I used that same installer to get conda and I got the dependencies error anyway.

**Comment by j3mdamas** [comment]
Is the python version now 3.6?

**Comment by arayasecchi** [comment]
Yes. The python version installed by conda is 3.6.
$ python -V
Python 3.6.1 :: Continuum Analytics

But I tried to install HTMD and I got the same errors
$ conda install htmd
Fetching package metadata ...........
Solving package specifications: 

PackageNotFoundError: Dependency missing in current linux-64 channels: 
  - htmd -> htmd-deps 1.7.2

Can I force it to get the 1.9.1 ?

**Comment by j3mdamas** [comment]
Could you do `which conda` and `conda list conda`?

**Comment by arayasecchi** [comment]
$ which conda
/home/raul/miniconda3/bin/conda

$ conda list conda
# packages in environment at /home/raul/miniconda3:
#
conda                     4.3.21                   py36_0  
conda-env                 2.6.0                         0

**Comment by j3mdamas** [comment]
If `which python` gives the same path and `conda list htmd` is empty, I see
no reason for `conda install htmd -c acellera -c psi4` to not work. You can
try `conda install htmd=1.9.1 -c acellera -c psi4` to try to force it.

**Comment by arayasecchi** [comment]
conda install htmd=1.9.1 -c acellera -c psi4 worked...
But when I did conda install htmd it did not worked.

Thanks for the help.

**Comment by j3mdamas** [comment]
I find it weird, but as long as it's working, good.
