### ISSUE TITLE
Proposal of a 'quality check function' before building

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#4]
Hi guys,

I was checking how htmd supports ions in charmm or amber. In the figure below you can see the ions with occurrences in the PDB database (just to have a reference), the available ions in charmm and amber and their resnames. 
So building a system with a pdb containing K crashes in charmm if not previously renamed to POT. Of course it's up to the users to correctly name the residues in their systems, but what I'm suggesting is that perhaps it doesnt take too long to include a quality check in charmm and amber.build; like if there's present a resname K in the Molecule, rename it automatically to POT. Would this work? The good thing is that in Amber most of the residue names are the same as in the pdb.

Of course it's only a suggestion but it could be a nice feature. 
Noelia
  
   
   

![image of table] (http://i.imgur.com/biCC2DF.png)

**Comment by mj-harvey** [comment]
Hi noelia,

The procedure now is to run automated  tests before making a release. If
you can provide a test program for your problem that checks for correct
function and exits 0 on success 1 on failure, i'll drop it into the test
suite.

M

**Comment by noeliaferruz** [comment]
Hi Matt,

Sorry, the chances that what I write doesn't suit you are way too high, so you and I lose our time. This is most a suggestion that could be coded for those who usually do so. Perhaps @stefdoerr?  

N

**Comment by stefdoerr** [comment]
Er? I think Matt misunderstood your request.

We already have a list of resname aliases for CHARMM so I could include a few more given this list.

**Comment by mj-harvey** [comment]
Indeed I did. I thought you were referring to building the htmd release.

On 25 March 2016 at 20:39, Stefan <notifications@github.com> wrote:

> Er? I think Matt misunderstood your request.
>
> We already have a list of resname aliases for CHARMM so I could include a
> few more given this list.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Acellera/htmd/issues/4#issuecomment-201450613>
>



-- 
<https://www.acellera.com>


<https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>
    <https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/acellera>
<https://www.acellera.com/md-simulation-blog-news/>     [image:
skype:acellera] <http://is.gd/1eXkbS>

**Comment by noeliaferruz** [comment]
Thanks that would work!
N

**Comment by stefdoerr** [comment]
Done.

ps. we close issues when they are implemented, not when we agree on a solution @noeliaferruz :)
