### ISSUE TITLE
Parameterize tutorial

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#40]
benzamidine

**Comment by stefdoerr** [comment]
Maybe we should link to the PNAS paper as a motivational counter-example? Hahaha :laughing:

**Comment by j3mdamas** [comment]
maybe we don't want bad publicity :p

**Comment by j3mdamas** [comment]
I have now a tutorial on Ethanol I gave for class. I am going to change it to benzamidine, and try to clean some edges, and then I'll add it to the tutorials

**Comment by stefdoerr** [comment]
Cool! I could learn something from it :)

**Comment by j3mdamas** [comment]
Ethanol for "Learn HTMD"
Benzamidine or others inside "HTMD Applications"

**Comment by j3mdamas** [comment]
Closing this, as it is included in the more general issue of parameterize official release.

Follow issue Acellera/htmdlib#150
