### ISSUE TITLE
NGLView cannot show structure with waters

### ISSUE THREAD

**Issue by cuzzo87** [Acellera/htmd#402]
I was using NGLview to visualize the system with the Molecule.view():
- protein as NewCartoon 
- ligand as Licorice

The system contains also waters and if I did not remove them before calling the 'view' function I cannot see anything

**1) without removing waters **

```
m =Molecule('structure.pdb')
m.center()
m.reps.add('protein', 'NewCartoon' )
m.reps.add('resname MOL', 'Licorice')
config(viewer='ngl')
m.view()
```

![fig_waters](https://user-images.githubusercontent.com/10772443/28452208-cd511ea2-6df1-11e7-9e22-8083657504c7.png)

**2) removing the waters**

```
m =Molecule('structure.pdb')
m.remove('waters')
m.center()
m.reps.add('protein', 'NewCartoon' )
m.reps.add('resname MOL', 'Licorice')
config(viewer='ngl')
m.view()
```
![fig_no_waters](https://user-images.githubusercontent.com/10772443/28452227-e96c1b0a-6df1-11e7-8780-fd709afe053f.png)

**Comment by stefdoerr** [comment]
Subscribe to nglview issues. I've already made one a week ago. It's fixed in their next release

On July 21, 2017 9:53:22 AM GMT+03:00, Alberto <notifications@github.com> wrote:
>I was using NGLview to visualize the system with the Molecule.view():
>- protein as NewCartoon 
>- ligand as Licorice
>
>The system contains also waters and if I did not remove them before
>calling the 'view' function I cannot see anything
>
>**1) without removing waters **
>
>```
>m =Molecule('structure.pdb')
>m.center()
>m.reps.add('protein', 'NewCartoon' )
>m.reps.add('resname MOL', 'Licorice')
>config(viewer='ngl')
>m.view()
>```
>
>![fig_waters](https://user-images.githubusercontent.com/10772443/28452208-cd511ea2-6df1-11e7-9e22-8083657504c7.png)
>
>
>**2) removing the waters**
>
>
>```
>m =Molecule('structure.pdb')
>m.remove('waters')
>m.center()
>m.reps.add('protein', 'NewCartoon' )
>m.reps.add('resname MOL', 'Licorice')
>config(viewer='ngl')
>m.view()
>```
>![fig_no_waters](https://user-images.githubusercontent.com/10772443/28452227-e96c1b0a-6df1-11e7-8780-fd709afe053f.png)
>
>
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Acellera/htmd/issues/402

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stefdoerr** [comment]
https://github.com/arose/nglview/issues/633
