### ISSUE TITLE
AcecloudQueue Testing

### ISSUE THREAD

**Issue by stefdoerr** [Acellera/htmd#406]
http://software.acellera.com/docs/latest/htmd/htmd.queues.acecloudqueue.html

I have no clue how to use it if I wanted to.
I assume using these instructions? http://software.acellera.com/docs/latest/acecloud/index.html#how-to-setup-acecloud
But does the class need some key/configuration? Or does it autodetect it?

**Comment by j3mdamas** [comment]
Hi Stefan,

Testing the AcecloudQueue class is something on the pipeline. We've been focusing on improving the command-line client, but this is definitely necessary. I'll be working on this with David.

Answering your question, yes, the class should interact with the `.htmd/aws` file that is created using the `acecloud --setup`. But I'll need to review this with David.

**Comment by stefdoerr** [comment]
Finished 4ab6cb8dd9593ac541f045650cdfae7ba560e38a
