### ISSUE TITLE
Parameterization: Could not find binary [g09_wrapper] in PATH

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#41]
I am using the unpackaged HTMD version with the _readXYZ hotfix (using PYTHONPATH).

Running: `parameterize --resume param_at`

gives me:
```
 === Parameterise 2016 ===

      (c) Acellera 
2016-05-25 12:28:25,385 - parameterize - INFO - Resuming job [param_at]
2016-05-25 12:28:25,389 - parameterize - INFO - Could not find binary [g09_wrapper] in PATH 

 Failed to run parameterisation : Prerequisite test failed Could not find binary [g09_wrapper] in PATH 

```

**Comment by giadefa** [comment]
because you don't have gaussian. Use Psi4

On 25 May 2016 at 12:35, João M. Damas <notifications@github.com> wrote:

> I am using the unpackaged HTMD version with the _readXYZ hotfix (using
> PYTHONPATH).
>
> Running: parameterize --resume param_at
>
> gives me:
>
>  === Parameterise 2016 ===
>
>       (c) Acellera
> 2016-05-25 12:28:25,385 - parameterize - INFO - Resuming job [param_at]
> 2016-05-25 12:28:25,389 - parameterize - INFO - Could not find binary [g09_wrapper] in PATH
>
>  Failed to run parameterisation : Prerequisite test failed Could not find binary [g09_wrapper] in PATH
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Acellera/htmd/issues/41>
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>

**Comment by j3mdamas** [comment]
Matt says the g09_wrapper is for both

On Wed, May 25, 2016 at 12:45 PM, giadefa <notifications@github.com> wrote:

> because you don't have gaussian. Use Psi4
>
> On 25 May 2016 at 12:35, João M. Damas <notifications@github.com> wrote:
>
> > I am using the unpackaged HTMD version with the _readXYZ hotfix (using
> > PYTHONPATH).
> >
> > Running: parameterize --resume param_at
> >
> > gives me:
> >
> > === Parameterise 2016 ===
> >
> > (c) Acellera
> > 2016-05-25 12:28:25,385 - parameterize - INFO - Resuming job [param_at]
> > 2016-05-25 12:28:25,389 - parameterize - INFO - Could not find binary
> [g09_wrapper] in PATH
> >
> > Failed to run parameterisation : Prerequisite test failed Could not find
> binary [g09_wrapper] in PATH
> >
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Acellera/htmd/issues/41>
> >
>
>
>
> --
> <http://www.acellera.com>
>
> <https://twitter.com/acellera>
> <https://www.youtube.com/user/acelleracom>
> <
> https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera
> >
> <https://www.acellera.com/md-simulation-blog-news/>
> <http://is.gd/1eXkbS>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Acellera/htmd/issues/41#issuecomment-221537708>
>



--

**Comment by mj-harvey** [comment]
this is a bug only when running unpackaged.

**Comment by j3mdamas** [comment]
bah. really weird. one point for creating a conda dev package like the
pyemma guys do.

On Wed, May 25, 2016 at 4:14 PM, M J Harvey <notifications@github.com>
wrote:

> this is a bug only when running unpackaged.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Acellera/htmd/issues/41#issuecomment-221589443>
>



--

**Comment by mj-harvey** [comment]
Do a "make CC=g++" in htmd/C/parameterize . that will build the C code and put the scripts in place.

**Comment by j3mdamas** [comment]
I'll close it

**Comment by j3mdamas** [comment]
Thanks Matt!

On Wed, May 25, 2016 at 4:26 PM, M J Harvey <notifications@github.com>
wrote:

> Do a "make CC=g++" in htmd/C/parameterize . that will build the C code and
> put the scripts in place.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Acellera/htmd/issues/41#issuecomment-221593149>
>



--
