### ISSUE TITLE
model.sampleStates (improve mutual exclusion argument )

### ISSUE THREAD

**Issue by cuzzo87** [Acellera/htmd#417]
In `model.sampleStates` gives the possibility to sample frames from states based on the statetype provided when it is called. Moreover, the function allows to retrieve all the frames related to the states by using the optional argument `allframes` (see below):
```
sampleStates(states, frames, statetype=’macro’, replacement=False, samplemode=’random’, allframes=False)
```

Due to the fact that the `frames` argument is a positional one, if the user wants all the frame it has to call the function with a useless frames definition.

We should modify the `frames` argument and implement a mutual exclusion check between `frames` and `allframes`

**Comment by stefdoerr** [comment]
Yes that needs some refactoring

On August 1, 2017 10:35:00 AM GMT+03:00, Alberto <notifications@github.com> wrote:
>In `model.sampleStates` gives the possibility to sample frames from
>states based on the statetype provided when it is called. Moreover, the
>function allows to retrieve all the frames related to the states by
>using the optional argument `allframes` (see below):
>```
>sampleStates(states, frames, statetype=’macro’, replacement=False,
>samplemode=’random’, allframes=False)
>```
>
>Due to the fact that the `frames` argument is a positional one, if the
>user wants all the frame it has to call the function with a useless
>frames definition.
>
>We should modify the `frames` argument and implement a mutual exclusion
>check between `frames` and `allframes`
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Acellera/htmd/issues/417

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by j3mdamas** [comment]
Hi,
I am refactoring this a bit. I will be removing the `allframes` flag and replacing it by a `frames=None` to be the default, which defaults to all frames. I'll report if it works and do a PR for @stefdoerr to review.

**Comment by stefdoerr** [comment]
I don't like that. If a user calls it with default args on abig dataset it's going to be stuck for hours there. That's why we put default 50

**Comment by stefdoerr** [comment]
Eh sorry no default or whatever. Let me look at it. I'll fix it
