### ISSUE TITLE
FileNotFoundError: Could not find libs.

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#42]
Hi guys,

I'm in version 1.0.26. I run: `model.viewStates(ligand="resname MOL and noh")`. And got the following error:
What am I missing?

```
/nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/acellera/current/python/lib/python3.5/site-packages/pyEMMA-2.2-py3.5-linux-x86_64.egg/pyemma/util/_ext/shimmodule.py:131: PyEMMA_DeprecationWarning: Access to a moved module 'pyemma.msm.dtraj' detected! Please use 'msmtools.dtraj' in the future.
  category=PyEMMA_DeprecationWarning)
/nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/acellera/current/python/lib/python3.5/site-packages/pyEMMA-2.2-py3.5-linux-x86_64.egg/pyemma/util/_ext/shimmodule.py:131: PyEMMA_DeprecationWarning: Access to a moved module 'pyemma.msm.analysis' detected! Please use 'msmtools.analysis' in the future.
  category=PyEMMA_DeprecationWarning)
/nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/acellera/current/python/lib/python3.5/site-packages/pyEMMA-2.2-py3.5-linux-x86_64.egg/pyemma/util/_ext/shimmodule.py:131: PyEMMA_DeprecationWarning: Access to a moved module 'pyemma.msm.generation' detected! Please use 'msmtools.generation' in the future.
  category=PyEMMA_DeprecationWarning)
/nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/acellera/current/python/lib/python3.5/site-packages/pyEMMA-2.2-py3.5-linux-x86_64.egg/pyemma/util/_ext/shimmodule.py:131: PyEMMA_DeprecationWarning: Access to a moved module 'pyemma.msm.flux' detected! Please use 'msmtools.flux' in the future.
  category=PyEMMA_DeprecationWarning)
/nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/acellera/current/python/lib/python3.5/site-packages/pyEMMA-2.2-py3.5-linux-x86_64.egg/pyemma/util/_ext/shimmodule.py:131: PyEMMA_DeprecationWarning: Access to a moved module 'pyemma.msm.estimation' detected! Please use 'msmtools.estimation' in the future.
  category=PyEMMA_DeprecationWarning)

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-5-119f81c50177> in <module>()
      2 #model.load('model-oldsimdata_25+.dat')
      3 os.chdir('/hpc/grid/wip_cmg_wwmc/workspace/groups/neuro_cc/acellera/tmp/proteins/D3R/batches')
----> 4 model.viewStates(ligand="resname MOL and noh")

/path/to/htmd/model.py in viewStates(self, states, statetype, protein, ligand, viewer, mols, numsamples, wrapsel, alignsel)
    395             states = [states]
    396         if mols is None:
--> 397             mols = self.getStates(states, statetype, numsamples=numsamples, wrapsel=wrapsel, alignsel=alignsel)
    398         colors = [0, 1, 3, 4, 5, 6, 7, 9]
    399         for i, s in enumerate(states):

/path/to/htmd/model.py in getStates(self, states, statetype, wrapsel, alignsel, alignmol, samplemode, numsamples)
    346         # Removed ncpus because it was giving errors on some systems.
    347         mols = Parallel(n_jobs=1, verbose=11)(delayed(_loadMols)(self, i, rel, molfile, wrapsel, alignsel, refmol)
--> 348                                                   for i, rel in enumerate(relframes))
    349         return np.array(mols, dtype=object)
    350 

/nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/acellera/current/python/lib/python3.5/site-packages/joblib/parallel.py in __call__(self, iterable)
    798             # was dispatched. In particular this covers the edge
    799             # case of Parallel used with an exhausted iterator.
--> 800             while self.dispatch_one_batch(iterator):
    801                 self._iterating = True
    802             else:

/nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/acellera/current/python/lib/python3.5/site-packages/joblib/parallel.py in dispatch_one_batch(self, iterator)
    656                 return False
    657             else:
--> 658                 self._dispatch(tasks)
    659                 return True
    660 

/nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/acellera/current/python/lib/python3.5/site-packages/joblib/parallel.py in _dispatch(self, batch)
    564 
    565         if self._pool is None:
--> 566             job = ImmediateComputeBatch(batch)
    567             self._jobs.append(job)
    568             self.n_dispatched_batches += 1

/nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/acellera/current/python/lib/python3.5/site-packages/joblib/parallel.py in __init__(self, batch)
    178         # Don't delay the application, to avoid keeping the input
    179         # arguments in memory
--> 180         self.results = batch()
    181 
    182     def get(self):

/nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/acellera/current/python/lib/python3.5/site-packages/joblib/parallel.py in __call__(self)
     70 
     71     def __call__(self):
---> 72         return [func(*args, **kwargs) for func, args, kwargs in self.items]
     73 
     74     def __len__(self):

/nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/acellera/current/python/lib/python3.5/site-packages/joblib/parallel.py in <listcomp>(.0)
     70 
     71     def __call__(self):
---> 72         return [func(*args, **kwargs) for func, args, kwargs in self.items]
     73 
     74     def __len__(self):

/path/to/htmd/model.py in _loadMols(self, i, rel, molfile, wrapsel, alignsel, refmol)
    522         trajs = np.append(trajs, f.sim.trajectory[f.piece])
    523         frs = np.append(frs, f.frame)
--> 524     mol.read(trajs, frames=frs)
    525     if len(wrapsel) > 0:
    526         mol.wrap(wrapsel)

/path/to/htmd/molecule/molecule.py in read(self, filename, type, skip, frames, append)
    670             self._readPDB(filename, mode='pdbqt')
    671         elif (type is None and firstfile.endswith(".xtc")) or type == "xtc":
--> 672             self._readTraj(filename, skip=skip, frames=frames, append=append)
    673         elif (type is None and firstfile.endswith(".coor")) or type == "coor":
    674             self._readBinCoordinates(filename)

/path/to/htmd/molecule/molecule.py in _readTraj(self, filename, skip, frames, append, mdtraj)
    914                     traj.coords = traj.coords[:, :, frames[i]]
    915                 else:
--> 916                     traj = XTCread(f, frames[i])
    917                 self.fileloc.append([f, int(frames[i])])
    918 

/path/to/htmd/molecule/xtc.py in XTCread(filename, frames)
     52 
     53 def XTCread(filename, frames=None):
---> 54     lib = xtc_lib()
     55     nframes = pack_ulong_buffer([0])
     56     natoms = pack_int_buffer([0])

/path/to/htmd/molecule/xtc.py in xtc_lib()
     35 def xtc_lib():
     36     lib = {}
---> 37     libdir = htmd.home(libDir=True)
     38 
     39     import platform

/path/to/htmd/home.py in home(dataDir, libDir)
     45             return os.path.join(libdir, "pro", platform.system())
     46         else:
---> 47             raise FileNotFoundError('Could not find libs.')
     48     else:
     49         return homeDir

FileNotFoundError: Could not find libs.
```

**Comment by stefdoerr** [comment]
@mj-harvey @j3mdamas libs have disappeared again. Something in the conda release?

**Comment by mj-harvey** [comment]
I don't understand how that could have been released. The tests should have
failed.
'll look into it

On 31 May 2016 at 17:03, Stefan <notifications@github.com> wrote:

> @mj-harvey <https://github.com/mj-harvey> @j3mdamas
> <https://github.com/j3mdamas> libs have disappeared again. Something in
> the conda release?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/42#issuecomment-222736338>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHh-DQ68rn4dhcq6b-K-Gv7UU3wxoE80ks5qHFvsgaJpZM4IqsFS>
> .
>



-- 
<https://www.acellera.com>


<https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>
    <https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/acellera>
<https://www.acellera.com/md-simulation-blog-news/>     [image:
skype:acellera] <http://is.gd/1eXkbS>

**Comment by giadefa** [comment]
.travis_conda_upload.sh  is different between multiscalelan and acellera

On 31 May 2016 at 18:53, M J Harvey <notifications@github.com> wrote:

> I don't understand how that could have been released. The tests should have
> failed.
> 'll look into it
>
> On 31 May 2016 at 17:03, Stefan <notifications@github.com> wrote:
>
> > @mj-harvey <https://github.com/mj-harvey> @j3mdamas
> > <https://github.com/j3mdamas> libs have disappeared again. Something in
> > the conda release?
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/Acellera/htmd/issues/42#issuecomment-222736338>, or
> mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/AHh-DQ68rn4dhcq6b-K-Gv7UU3wxoE80ks5qHFvsgaJpZM4IqsFS
> >
> > .
> >
>
>
>
> --
> <https://www.acellera.com>
>
>
> <
> https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor
> >
> <https://www.youtube.com/user/acelleracom>
> <https://www.linkedin.com/company/acellera>
> <https://www.acellera.com/md-simulation-blog-news/> [image:
> skype:acellera] <http://is.gd/1eXkbS>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/42#issuecomment-222750465>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHaqOlB36i58z-XOchtCflDXCDo_bUViks5qHGefgaJpZM4IqsFS>
> .
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>

**Comment by mj-harvey** [comment]
giadefa ellera/htmd is a long way behind multiscalelab/htmd at this point.

On 31 May 2016 at 17:59, giadefa <notifications@github.com> wrote:

> .travis_conda_upload.sh is different between multiscalelan and acellera
>
> On 31 May 2016 at 18:53, M J Harvey <notifications@github.com> wrote:
>
> > I don't understand how that could have been released. The tests should
> have
> > failed.
> > 'll look into it
> >
> > On 31 May 2016 at 17:03, Stefan <notifications@github.com> wrote:
> >
> > > @mj-harvey <https://github.com/mj-harvey> @j3mdamas
> > > <https://github.com/j3mdamas> libs have disappeared again. Something
> in
> > > the conda release?
> > >
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/Acellera/htmd/issues/42#issuecomment-222736338>,
> or
> > mute
> > > the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/AHh-DQ68rn4dhcq6b-K-Gv7UU3wxoE80ks5qHFvsgaJpZM4IqsFS
> > >
> > > .
> > >
> >
> >
> >
> > --
> > <https://www.acellera.com>
> >
> >
> > <
> >
> https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor
> > >
> > <https://www.youtube.com/user/acelleracom>
> > <https://www.linkedin.com/company/acellera>
> > <https://www.acellera.com/md-simulation-blog-news/> [image:
> > skype:acellera] <http://is.gd/1eXkbS>
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/Acellera/htmd/issues/42#issuecomment-222750465>, or
> mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/AHaqOlB36i58z-XOchtCflDXCDo_bUViks5qHGefgaJpZM4IqsFS
> >
> > .
> >
>
>
>
> --
> <http://www.acellera.com>
>
> <https://twitter.com/acellera>
> <https://www.youtube.com/user/acelleracom>
> <
> https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera
> >
> <https://www.acellera.com/md-simulation-blog-news/>
> <http://is.gd/1eXkbS>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/42#issuecomment-222752057>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHh-DYc6tvRWiJG4zZVZ8ZCAeYnCXq4Xks5qHGj4gaJpZM4IqsFS>
> .
>



-- 
<https://www.acellera.com>


<https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>
    <https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/acellera>
<https://www.acellera.com/md-simulation-blog-news/>     [image:
skype:acellera] <http://is.gd/1eXkbS>

**Comment by giadefa** [comment]
not really. We only tag via acellera now.

On 31 May 2016 at 19:02, M J Harvey <notifications@github.com> wrote:

> giadefa ellera/htmd is a long way behind multiscalelab/htmd at this point.
>
>
> On 31 May 2016 at 17:59, giadefa <notifications@github.com> wrote:
>
> > .travis_conda_upload.sh is different between multiscalelan and acellera
> >
> > On 31 May 2016 at 18:53, M J Harvey <notifications@github.com> wrote:
> >
> > > I don't understand how that could have been released. The tests should
> > have
> > > failed.
> > > 'll look into it
> > >
> > > On 31 May 2016 at 17:03, Stefan <notifications@github.com> wrote:
> > >
> > > > @mj-harvey <https://github.com/mj-harvey> @j3mdamas
> > > > <https://github.com/j3mdamas> libs have disappeared again. Something
> > in
> > > > the conda release?
> > > >
> > > > —
> > > > You are receiving this because you were mentioned.
> > > > Reply to this email directly, view it on GitHub
> > > > <https://github.com/Acellera/htmd/issues/42#issuecomment-222736338>,
> > or
> > > mute
> > > > the thread
> > > > <
> > >
> >
> https://github.com/notifications/unsubscribe/AHh-DQ68rn4dhcq6b-K-Gv7UU3wxoE80ks5qHFvsgaJpZM4IqsFS
> > > >
> > > > .
> > > >
> > >
> > >
> > >
> > > --
> > > <https://www.acellera.com>
> > >
> > >
> > > <
> > >
> >
> https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor
> > > >
> > > <https://www.youtube.com/user/acelleracom>
> > > <https://www.linkedin.com/company/acellera>
> > > <https://www.acellera.com/md-simulation-blog-news/> [image:
> > > skype:acellera] <http://is.gd/1eXkbS>
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/Acellera/htmd/issues/42#issuecomment-222750465>,
> or
> > mute
> > > the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/AHaqOlB36i58z-XOchtCflDXCDo_bUViks5qHGefgaJpZM4IqsFS
> > >
> > > .
> > >
> >
> >
> >
> > --
> > <http://www.acellera.com>
> >
> > <https://twitter.com/acellera>
> > <https://www.youtube.com/user/acelleracom>
> > <
> >
> https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera
> > >
> > <https://www.acellera.com/md-simulation-blog-news/>
> > <http://is.gd/1eXkbS>
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/Acellera/htmd/issues/42#issuecomment-222752057>, or
> mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/AHh-DYc6tvRWiJG4zZVZ8ZCAeYnCXq4Xks5qHGj4gaJpZM4IqsFS
> >
> > .
> >
>
>
>
> --
> <https://www.acellera.com>
>
>
> <
> https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor
> >
> <https://www.youtube.com/user/acelleracom>
> <https://www.linkedin.com/company/acellera>
> <https://www.acellera.com/md-simulation-blog-news/> [image:
> skype:acellera] <http://is.gd/1eXkbS>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/42#issuecomment-222752993>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHaqOuiWH2gaIRpcuMLSwkfBElcMBi73ks5qHGm2gaJpZM4IqsFS>
> .
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>

**Comment by mj-harvey** [comment]
The libraries are all ther and working in 1.0.26. The release couldn't have
happened otherwise. Noelia, what's the output of

from htmd import *
print( htmd.home() )

Is it what you expect?

if you then do a find under that directory for "libxtc.so" is it found?

what's the output of "file /path/to/libxtc.so" ?


On 31 May 2016 at 18:06, giadefa <notifications@github.com> wrote:

> not really. We only tag via acellera now.
>
>
> On 31 May 2016 at 19:02, M J Harvey <notifications@github.com> wrote:
>
> > giadefa ellera/htmd is a long way behind multiscalelab/htmd at this
> point.
> >
> >
> > On 31 May 2016 at 17:59, giadefa <notifications@github.com> wrote:
> >
> > > .travis_conda_upload.sh is different between multiscalelan and acellera
> > >
> > > On 31 May 2016 at 18:53, M J Harvey <notifications@github.com> wrote:
> > >
> > > > I don't understand how that could have been released. The tests
> should
> > > have
> > > > failed.
> > > > 'll look into it
> > > >
> > > > On 31 May 2016 at 17:03, Stefan <notifications@github.com> wrote:
> > > >
> > > > > @mj-harvey <https://github.com/mj-harvey> @j3mdamas
> > > > > <https://github.com/j3mdamas> libs have disappeared again.
> Something
> > > in
> > > > > the conda release?
> > > > >
> > > > > —
> > > > > You are receiving this because you were mentioned.
> > > > > Reply to this email directly, view it on GitHub
> > > > > <https://github.com/Acellera/htmd/issues/42#issuecomment-222736338
> >,
> > > or
> > > > mute
> > > > > the thread
> > > > > <
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe/AHh-DQ68rn4dhcq6b-K-Gv7UU3wxoE80ks5qHFvsgaJpZM4IqsFS
> > > > >
> > > > > .
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > <https://www.acellera.com>
> > > >
> > > >
> > > > <
> > > >
> > >
> >
> https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor
> > > > >
> > > > <https://www.youtube.com/user/acelleracom>
> > > > <https://www.linkedin.com/company/acellera>
> > > > <https://www.acellera.com/md-simulation-blog-news/> [image:
> > > > skype:acellera] <http://is.gd/1eXkbS>
> > > >
> > > > —
> > > > You are receiving this because you are subscribed to this thread.
> > > > Reply to this email directly, view it on GitHub
> > > > <https://github.com/Acellera/htmd/issues/42#issuecomment-222750465>,
> > or
> > > mute
> > > > the thread
> > > > <
> > >
> >
> https://github.com/notifications/unsubscribe/AHaqOlB36i58z-XOchtCflDXCDo_bUViks5qHGefgaJpZM4IqsFS
> > > >
> > > > .
> > > >
> > >
> > >
> > >
> > > --
> > > <http://www.acellera.com>
> > >
> > > <https://twitter.com/acellera>
> > > <https://www.youtube.com/user/acelleracom>
> > > <
> > >
> >
> https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera
> > > >
> > > <https://www.acellera.com/md-simulation-blog-news/>
> > > <http://is.gd/1eXkbS>
> > >
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/Acellera/htmd/issues/42#issuecomment-222752057>,
> or
> > mute
> > > the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/AHh-DYc6tvRWiJG4zZVZ8ZCAeYnCXq4Xks5qHGj4gaJpZM4IqsFS
> > >
> > > .
> > >
> >
> >
> >
> > --
> > <https://www.acellera.com>
> >
> >
> > <
> >
> https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor
> > >
> > <https://www.youtube.com/user/acelleracom>
> > <https://www.linkedin.com/company/acellera>
> > <https://www.acellera.com/md-simulation-blog-news/> [image:
> > skype:acellera] <http://is.gd/1eXkbS>
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/Acellera/htmd/issues/42#issuecomment-222752993>, or
> mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/AHaqOuiWH2gaIRpcuMLSwkfBElcMBi73ks5qHGm2gaJpZM4IqsFS
> >
> > .
> >
>
>
>
> --
> <http://www.acellera.com>
>
> <https://twitter.com/acellera>
> <https://www.youtube.com/user/acelleracom>
> <
> https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera
> >
> <https://www.acellera.com/md-simulation-blog-news/>
> <http://is.gd/1eXkbS>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/42#issuecomment-222754050>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHh-DQFqxp4zuyPOuRfdzTrpS17nvw26ks5qHGqhgaJpZM4IqsFS>
> .
>



-- 
<https://www.acellera.com>


<https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>
    <https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/acellera>
<https://www.acellera.com/md-simulation-blog-news/>     [image:
skype:acellera] <http://is.gd/1eXkbS>

**Comment by noeliaferruz** [comment]
The output is:

```
from htmd import *
print(htmd.home())

Please cite. HTMD: High-Throughput Molecular Dynamics for Molecular Discovery, J. Chem. Theory Comput., 2016, 12 (4), pp 1845-1852. http://pubs.acs.org/doi/abs/10.1021/acs.jctc.6b00049

You are on the latest HTMD version (1.0.26).
/path/to/acellera/current/python/lib/python3.5/site-packages/htmd
```
It is not what I was expecting, but that's another issue I have to look at. Since Friday we now have two modules, acellera/test, and acellera/current. And we have permissions to update them. But it seems they're still interconverted, whenever I update test, current is also updated, and jupyter seems to open htmd from current...I'll ask here.

However I don't have reading permissions in that folder to do the file command, let me ask:
```
ferrun@cclnx928-> find /path/to/acellera/current/python/lib/python3.5/site-packages/htmd -name "libxtc.so"
find: `/path/to/acellera/current/python/lib/python3.5/site-packages/htmd/builder/charmmfiles': Permission denied
find: `/path/to/acellera/current/python/lib/python3.5/site-packages/htmd/clustering': Permission denied
find: `/path/to/acellera/current/python/lib/python3.5/site-packages/htmd/lib': Permission denied
find: `/path/to/acellera/current/python/lib/python3.5/site-packages/htmd/parameterize': Permission denied
```

**Comment by mj-harvey** [comment]
Ok -- it's the lack of file permissions that is causing the problem.

On 31 May 2016 at 18:53, Noelia Ferruz <notifications@github.com> wrote:

> The output is:
>
> from htmd import *
> print(htmd.home())
>
> Please cite. HTMD: High-Throughput Molecular Dynamics for Molecular Discovery, J. Chem. Theory Comput., 2016, 12 (4), pp 1845-1852. http://pubs.acs.org/doi/abs/10.1021/acs.jctc.6b00049
>
> You are on the latest HTMD version (1.0.26).
> /path/to/acellera/current/python/lib/python3.5/site-packages/htmd
>
> It is not what I was expecting, but that's another issue I have to look
> at. Since Friday we now have two modules, acellera/test, and
> acellera/current. And we have permissions to update them. But it seems
> they're still interconverted, whenever I update test, current is also
> updated, and jupyter seems to open htmd from current...I'll ask here.
>
> However I don't have reading permissions in that folder to do the file
> command, let me ask:
>
> ferrun@cclnx928-> find /path/to/acellera/current/python/lib/python3.5/site-packages/htmd -name "libxtc.so"
> find: `/path/to/acellera/current/python/lib/python3.5/site-packages/htmd/builder/charmmfiles': Permission denied
> find: `/path/to/acellera/current/python/lib/python3.5/site-packages/htmd/clustering': Permission denied
> find: `/path/to/acellera/current/python/lib/python3.5/site-packages/htmd/lib': Permission denied
> find: `/path/to/acellera/current/python/lib/python3.5/site-packages/htmd/parameterize': Permission denied
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/42#issuecomment-222767373>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHh-DZ0VCZT9t5ERgjeN0o6vPBkl68mmks5qHHWOgaJpZM4IqsFS>
> .
>



-- 
<https://www.acellera.com>


<https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>
    <https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/acellera>
<https://www.acellera.com/md-simulation-blog-news/>     [image:
skype:acellera] <http://is.gd/1eXkbS>

**Comment by noeliaferruz** [comment]
Ok, thanks a lot

**Comment by noeliaferruz** [comment]
It was finally fixed from here, not sure what happened with the two new modules, apologies for the incoveniences.
