### ISSUE TITLE
question on dihedral metric usage

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#43]
Hi guys,

I want use metric dihedral on four specific atoms. I'm using version 1.0.26.
I tried:
```
sims = simlist(glob('./filtered/*/'), './filtered/filtered.pdb')
metr1=Metric(sims)
sincos=True)) 
metr1.projection(MetricDihedral(dih="index 2629 2625 2623 2608", sincos=True))
data = metr1.project()
NameError: Could not parse selection "i". Is the selection a valid VMD atom selection?
```

And also tried:
```
metr1.projection(MetricDihedral(dih=("index 2629", "index 2625", "index 2623", "index 2608"), sincos=True)) 
2016-06-02 14:36:18,184 - htmd.projections.metric - WARNING - Error in simulation with id: 7 index 1 is out of bounds for axis 0 with size 1
```
This last error happened for all the trajectories.
Any other metrics (contacts, distances) work fine in this system. The selection is valid and correspond to the backbone dihedral of a single aminoacid.

Any ideas?
Thanks,
Noelia

**Comment by j3mdamas** [comment]
I am going to test this, hold on.

**Comment by stefdoerr** [comment]
Easy ;)
```python
MetricDihedral(dih=["index 2629 2625 2623 2608"], sincos=True)
```

**Comment by stefdoerr** [comment]
We could make it safer by checking if it's a string and putting it into an array. Otherwise it thinks the string is the array of stings :/

**Comment by j3mdamas** [comment]
That's what I was trying, but It's not working...

**Comment by j3mdamas** [comment]
It should work, and I am trying to figure out if there is some bug going on

**Comment by stefdoerr** [comment]
what do you mean by "it's not working"? what's the error? Cannot be the same error message.

**Comment by j3mdamas** [comment]
it is. I think I found the bug.

**Comment by j3mdamas** [comment]
well, not exactly finding it. I'm debugging and I see that the `dih` list is a string and not a list inside `MetricDihedral`. Maybe some passing that is not working?

**Comment by stefdoerr** [comment]
Are you like 100% sure you called the command correct? Looking at the code I find it virtually impossible.
```python
sims = simlist(glob('./filtered/*/'), './filtered/filtered.pdb')
metr1=Metric(sims)
sincos=True)) 
metr1.projection(MetricDihedral(dih=["index 2629 2625 2623 2608"], sincos=True))
data = metr1.project()
```

**Comment by j3mdamas** [comment]
I'm copying pasting what Noelia wrote

**Comment by stefdoerr** [comment]
Copy paste what I wrote

**Comment by j3mdamas** [comment]
Sorry, restarted the kernel and it's working. Your're right about the Notebooks after all ;)

**Comment by stefdoerr** [comment]
Ok so Noelia just do what I said. I will add a patch so that it understands strings are not lists.

**Comment by j3mdamas** [comment]
Oh! I know it now! it's the fucking `projection` nomenclature... We really need to change it to `addProjection` or `projection.add`. Basically, I was adding new ones and the first erroneous one was still there... Stupid me.

**Comment by stefdoerr** [comment]
Hahahah perfect example to convince Gianni! :D I'm in.

**Comment by giadefa** [comment]
We have already agreed

On 2 Jun 2016 21:59, "Stefan" <notifications@github.com> wrote:
>
> Hahahah perfect example to convince Gianni! :D I'm in.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
<https://github.com/Acellera/htmd/issues/43#issuecomment-223404333>, or
mute the thread
<https://github.com/notifications/unsubscribe/AHaqOi_QVy9wSvj_izZHvYf_ZCz9C6Zsks5qHzYKgaJpZM4Is2vt>
.

**Comment by stefdoerr** [comment]
It is a 1.1.0 issue, right?

**Comment by giadefa** [comment]
GOn 2 Jun 2016 22:20, "Stefan" <notifications@github.com> wrote:
>
> It is a 1.1.0 issue, right?
>
> —
> You are receiving this because you commented.
>
> Reply to this email directly, view it on GitHub
<https://github.com/Acellera/htmd/issues/43#issuecomment-223409805>, or
mute the thread
<https://github.com/notifications/unsubscribe/AHaqOiFzz09m3lVlLxMp5MDtYMTVg0trks5qHzr4gaJpZM4Is2vt>
.
