### ISSUE TITLE
Dihedral angle guessing is broken for cyclopropane

### ISSUE THREAD

**Issue by raimis** [Acellera/htmd#441]
Let's guess the dihedral angles of [cyclopropane .mol2.txt](https://github.com/Acellera/htmd/files/1270145/cyclopropane.mol2.txt):
```python
>>> from htmd.molecule.molecule import Molecule
>>> from htmd.molecule.vmdparser import guessAnglesAndDihedrals
>>> m = Molecule('cyclopropane.mol2')
>>> a, d = guessAnglesAndDihedrals(m.bonds)
```

It should be **27** of them, but we got just **25**:
```python
>>> len(d)
25
```

Also, this `[0, 2, 1, 1]` obviously is incorrect:
```python
>>> d
array([[0, 2, 1, 3],
       [0, 2, 1, 4],
       [0, 2, 1, 5],
       [0, 2, 1, 1],
       [1, 3, 2, 0],
       [0, 2, 3, 7],
       [0, 2, 3, 8],
       [3, 1, 2, 6],
       [2, 1, 3, 7],
       [2, 1, 3, 8],
       [3, 2, 1, 4],
       [3, 2, 1, 5],
       [1, 2, 3, 7],
       [1, 2, 3, 8],
       [4, 1, 2, 6],
       [5, 1, 2, 6],
       [2, 3, 1, 4],
       [2, 3, 1, 5],
       [1, 3, 2, 6],
       [4, 1, 3, 7],
       [4, 1, 3, 8],
       [5, 1, 3, 7],
       [5, 1, 3, 8],
       [6, 2, 3, 7],
       [6, 2, 3, 8]])
```

**Comment by raimis** [comment]
@cuzzo87, it is the cause of the **5c1w** problem!

**Comment by raimis** [comment]
@stefdoerr, any ideas how to fix it quickly?

**Comment by stefdoerr** [comment]
Are you sure the bonds you are passing are correct? (not missing any?)
This is Matt's code but I could take a look if you give me a small example.

**Comment by raimis** [comment]
The bonds look correct, then I look visually to the structure:
```python
m.write('cyclopropane2.mol2')
```

**Comment by raimis** [comment]
@stefdoerr, you was the last who touched that part of the code.

If you aren't familiar with that algorithm, I can try fix it by myself.

**Comment by stefdoerr** [comment]
Touched is a very generous term :) I didn't even remember such a function existed.
Also when visualizing molecules in htmd use `mol.view(guessBonds=False)` otherwise VMD guesses bonds by default.

**Comment by raimis** [comment]
@stefdoerr, `parameterize` uses `guessAnglesAndDihedrals`  to evaluate force fields, so it need to work correctly. :)

**Comment by stefdoerr** [comment]
Oh wait. That's pure python code. What is it doing in that file?

Give me some time. I'll refactor it once I understand what it does

**Comment by stefdoerr** [comment]
Ok seems trivial

**Comment by stefdoerr** [comment]
@raimis give me the test molecule please

**Comment by stefdoerr** [comment]
On benzamidine it works fine btw

**Comment by stefdoerr** [comment]
Ah sorry it's in the first post. my bad

**Comment by stefdoerr** [comment]
I reimplemented it in a nicer way and it gives the right number of dihedrals so I'll assume it's correct :stuck_out_tongue_closed_eyes: 
https://github.com/Acellera/htmd/commit/abf25b4a4728b4c65908bd9f5af00a311fc86990

I have a feeling it can be done in a more intelligent manner by building trees or by using some algorithm to extract unique triplets and quadruplets but for now I'll stick with the stupid-but-working implementation

**Comment by raimis** [comment]
Thanks @stefdoerr!

**Comment by j3mdamas** [comment]
Nope, it's breaking the parameterize tests now: https://travis-ci.org/Acellera/htmd/jobs/270867508

The angles and dihedrals come out in different order now in the PSF files. Any clue?

**Comment by j3mdamas** [comment]
If it's problematic, can we branch it out of master until it works?

**Comment by stefdoerr** [comment]
It's not problematic. It's fixed :tongue: 
There is no *correct* order of angles and dihedrals.
So I guess someone should update the tests.

**Comment by stefdoerr** [comment]
@raimis should probably look into it since I have no clue about those tests.

**Comment by j3mdamas** [comment]
OK, I'll branch off your commit, revert it in master, Raimis will fix the tests there, and we merge it after its fixed.

**Comment by raimis** [comment]
@stefdoerr, it needs a bit of sorting. I'll take care of it!

**Comment by j3mdamas** [comment]
https://github.com/Acellera/htmd/tree/fixguessangles

**Comment by j3mdamas** [comment]
New build with reversion of the code: https://travis-ci.org/Acellera/htmd/builds/270885082

As soon as the tests are fixed on fixguessangles, we can merge it back into master

Thanks

**Comment by raimis** [comment]
@stefdoerr now this can be closed again!
