### ISSUE TITLE
match-typer broken in osx

### ISSUE THREAD

**Issue by tonigi** [Acellera/htmd#445]
/Users/toni/anaconda3/bin/match-typer: line 10: /../share/MATCH//scripts/MATCH.pl: No such file or directory

Unfortunately due to different `readlink` behavior in `match-typer`

    F=$(dirname $(readlink -f $0))

looking for a cross-platform alternative.

**Comment by tonigi** [comment]
This should work `DIR=$(cd "$(dirname "$0")"; pwd)`. Alternatives here 
* https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac 
* https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within

**Comment by raimis** [comment]
I though that had already been fixed here: #388

**Comment by tonigi** [comment]
sorry, somehow i got an old version...

**Comment by raimis** [comment]
@j3mdamas, have we updated *match* on *conda*?

**Comment by raimis** [comment]
Well, *match* on *conda* is not updatated! So it is still an issue.

**Comment by j3mdamas** [comment]
I did not release after making the fix!

**Comment by j3mdamas** [comment]
Fixed in https://github.com/Acellera/conda-match/commit/d2e94f977c0d1b92a26e76f302818d5b5496e114 and released in https://github.com/Acellera/conda-match/releases/tag/0.0.5

**Comment by j3mdamas** [comment]
btw, I tested on my macox vm and it works
