### ISSUE TITLE
Errors in Molecule class

### ISSUE THREAD

**Issue by quantumania** [Acellera/htmd#449]
Following the HTMD tutorial online http://software.acellera.com/docs/latest/htmd/tutorials/getting-started-with-htmd.html and ran this:

from htmd.ui import *
mol = Molecule('3PTB')

and got this error

ValueError                                Traceback (most recent call last)
<ipython-input-2-80efa9b6c9ef> in <module>()
----> 1 mol=Molecule('3PTB')

~/apps/miniconda3/envs/htmd/lib/python3.6/site-packages/htmd/molecule/molecule.py in __init__(self, filename, name, **kwargs)
    195
    196         if filename:
--> 197             self.read(filename, **kwargs)
    198             if isinstance(filename, str):
    199                 self.topoloc = os.path.abspath(filename)

~/apps/miniconda3/envs/htmd/lib/python3.6/site-packages/htmd/molecule/molecule.py in read(self, filename, type, skip, frames, append, overwrite, keepaltloc, _logger)
    852             for rr in readers:
    853                 try:
--> 854                     to, tr = rr(fname, frame=frame, topoloc=tmppdb)
    855                 except FormatError:
    856                     continue

~/apps/miniconda3/envs/htmd/lib/python3.6/site-packages/htmd/molecule/readers.py in PDBread(filename, mode, frame, topoloc)
    592         mapserials = np.empty(np.max(serials)+1)
    593         mapserials[:] = np.NAN
--> 594         mapserials[serials] = list(range(np.max(serials)))
    595         for i in range(len(parsedbonds)):
    596             row = parsedbonds.loc[i].tolist()

ValueError: shape mismatch: value array of shape (1702,) could not be broadcast to indexing result of shape (1701,)

**Comment by quantumania** [comment]
This error has been persistent in multiple versions of HTMD and I'm surprised it has not been discussed and addressed....

**Comment by stefdoerr** [comment]
Well it's not discussed because it doesn't really happen unless stuff is broken :)

I would take a wild guess and say that the error is caused by an old `pandas` version. I am willing to bet that if you make a fresh conda installation (or manage to update the current one - which can be horribly messy) everything will work fine for you.

Also make sure you are getting the latest version of HTMD (1.9.8).

Installation instructions are here: http://software.acellera.com/academic-download.html 
Note that you need to also add the psi4 channel to make it work correct, as in the instructions.

**Comment by quantumania** [comment]
Thanks... It did work after I completely removed Ananconda and had a freshn installation...
Checked the pandas version in the non-working installation: 
pandas                    0.20.3                   py36_1    conda-forge

It is the latest version. Wonder why it caused the errors??
I'm new to conda. Is it a bad thing to have multiple channels on the channel list? 
Apparently, the pandas was installed from conda-forge channel in the non-working version.

**Comment by stefdoerr** [comment]
Don't worry.
Conda is quite tricky. Having too many channels definitely overcomplicates things. But really there are very few cases in which a `conda update` has not messed up my whole installation. You need to learn how to juggle dependencies like a maniac. On the other side there is no better alternative currently. We are working though on a standalone installer of HTMD to avoid exactly these issues. Should be done this month by @j3mdamas
