### ISSUE TITLE
'Tree' visualization of adaptive sampling?

### ISSUE THREAD

**Issue by jeiros** [Acellera/htmd#451]
I remember seeing some time ago a nice plot that represented the dependencies between the different simulations in an adaptive search. I can't find it anymore. Where is it located?

**Comment by stefdoerr** [comment]
You mean this one? http://pubs.acs.org/appl/literatum/publisher/achs/journals/content/jctcce/2014/jctcce.2014.10.issue-5/ct400919u/production/images/large/ct-2013-00919u_0003.jpeg

Or do you want to generate such a plot

**Comment by jeiros** [comment]
Yes, that one. Sorry, I phrased it badly -- I'd like to replicate such a plot, with my adaptive runs. Is there a function that does that?

**Comment by stefdoerr** [comment]
I doubt I can recover it.
But if you look at the naming scheme of the adaptive **eXsY_eZsW**fNpM you can recreate the chain very easily since it tells you which is the parent of each simulation.
Just export the data then to a graph file.
The plot was done with gephi.
