### ISSUE TITLE
wrong element written after solvate procedure

### ISSUE THREAD

**Issue by cuzzo87** [Acellera/htmd#454]
[5vw2_prep.txt](https://github.com/Acellera/htmd/files/1333357/5vw2_prep.txt)
[input.txt](https://github.com/Acellera/htmd/files/1333359/input.txt)

I have a system with this long atom name `HO2NA`
`HETATM 4758 HO2NANAP A 404      -5.717  20.157  15.168  0.60 31.62      1    H
`
The element in the PDB is an Hydrogen (H from last column). 
By looking at the input.pdb inside the build folder this atom becomes 
`ATOM   4861 HO2N NAP A 404      10.277   2.441   2.093  0.60 31.62      1   HO`
Element `HO`

**Comment by raimis** [comment]
It is a similar issues to #431.

**Comment by stefdoerr** [comment]
Indeed it's the same issue

**Comment by stefdoerr** [comment]
Why open it? It's the same issue. No reason having duplicates open
