### ISSUE TITLE
reconstructAdaptiveTraj  TypeError: object of type 'Sim' has no len()

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#46]
Hello guys,

Not sure what I'm doing wrong.

Thanks,
Noelia

```
mol, chain, pathlist = reconstructAdaptiveTraj(sims, 55)

/path/to/acellera/test/python/lib/python3.5/site-packages/pyEMMA-2.2-py3.5-linux-x86_64.egg/pyemma/util/_ext/shimmodule.py:131: PyEMMA_DeprecationWarning: Access to a moved module 'pyemma.msm.flux' detected! Please use 'msmtools.flux' in the future.
  category=PyEMMA_DeprecationWarning)
/path/to/acellera/test/python/lib/python3.5/site-packages/pyEMMA-2.2-py3.5-linux-x86_64.egg/pyemma/util/_ext/shimmodule.py:131: PyEMMA_DeprecationWarning: Access to a moved module 'pyemma.msm.generation' detected! Please use 'msmtools.generation' in the future.
  category=PyEMMA_DeprecationWarning)
/path/to/acellera/test/python/lib/python3.5/site-packages/pyEMMA-2.2-py3.5-linux-x86_64.egg/pyemma/util/_ext/shimmodule.py:131: PyEMMA_DeprecationWarning: Access to a moved module 'pyemma.msm.analysis' detected! Please use 'msmtools.analysis' in the future.
  category=PyEMMA_DeprecationWarning)
/path/to/acellera/test/python/lib/python3.5/site-packages/pyEMMA-2.2-py3.5-linux-x86_64.egg/pyemma/util/_ext/shimmodule.py:131: PyEMMA_DeprecationWarning: Access to a moved module 'pyemma.msm.dtraj' detected! Please use 'msmtools.dtraj' in the future.
  category=PyEMMA_DeprecationWarning)
/path/to/acellera/test/python/lib/python3.5/site-packages/pyEMMA-2.2-py3.5-linux-x86_64.egg/pyemma/util/_ext/shimmodule.py:131: PyEMMA_DeprecationWarning: Access to a moved module 'pyemma.msm.estimation' detected! Please use 'msmtools.estimation' in the future.
  category=PyEMMA_DeprecationWarning)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-29-a90feffab4cf> in <module>()
      1 #len(sims)
----> 2 mol, chain, pathlist = reconstructAdaptiveTraj(sims, 55)

/path/to/acellera/test/python/lib/python3.5/site-packages/htmd/adaptive/adaptive.py in reconstructAdaptiveTraj(simlist, trajID)
    418     for i, c in enumerate(chain):
    419         tmpmol = Molecule(sim.molfile)
--> 420         tmpmol.read(c[0])
    421         endpiece = c[1]
    422         fileloc = np.vstack(tmpmol.fileloc)

/path/to/acellera/test/python/lib/python3.5/site-packages/htmd/molecule/molecule.py in read(self, filename, type, skip, frames, append)
    634             firstfile = filename[0]
    635         else:
--> 636             if len(filename) != 4 and not os.path.exists(filename):
    637                 raise FileNotFoundError('File {} was not found.'.format(filename))
    638             firstfile = filename

TypeError: object of type 'Sim' has no len()


```

**Comment by stefdoerr** [comment]
Yeah, don't think you are doing something wrong. Is just that the function is so rarely used we don't update it when we change the underlying functionality. Will make a patch for it now but you will have to wait for the next release, or manually replace the 420 line with `tmpmol.read(c[0].trajectory)`.

**Comment by giadefa** [comment]
Add a test

**Comment by stefdoerr** [comment]
Thought about it but it's a bit ugly. It requires a directory of adaptive runs and my xtcs are not that small either.

**Comment by j3mdamas** [comment]
We should create an adaptive test set of dialanine, which would be nice for
adaptive tests.

On Tue, Jun 7, 2016 at 12:19 PM, Stefan <notifications@github.com> wrote:

> Thought about it but it's a bit ugly. It requires a directory of adaptive
> runs and my xtcs are not that small either.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/46#issuecomment-224239241>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AKTzQgLSdYidqZoND4wHNuGGADt-Qli5ks5qJUWigaJpZM4IvJbJ>
> .
>



--

**Comment by stefdoerr** [comment]
I have been saying it for years that we should have dialanine as a test system, for MSMs as well

**Comment by j3mdamas** [comment]
Is it a task for me then?

On Tue, Jun 7, 2016 at 12:32 PM, Stefan <notifications@github.com> wrote:

> I have been saying it for years that we should have dialanine as a test
> system, for MSMs as well
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/46#issuecomment-224242046>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AKTzQq2uoF9GHo5NcNDyMkWUdacEAPCxks5qJUi5gaJpZM4IvJbJ>
> .
>



--

**Comment by stefdoerr** [comment]
If you feel like it :D You should make a non-adaptive set first though. I did not do it before because I did not know how to set up simulations and HTMD building did not exist yet. It should be a piece of cake now really.

**Comment by j3mdamas** [comment]
I'll create an issue for it since this is getting out of this topic

On Tue, Jun 7, 2016 at 12:35 PM, Stefan <notifications@github.com> wrote:

> If you feel like it :D You should make a non-adaptive set first though. I
> did not do it before because I did not know how to set up simulations and
> HTMD building did not exist yet. It should be a piece of cake now really.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/46#issuecomment-224242723>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AKTzQujtmqaMMCBtsdDqWfYMBKrufW7Bks5qJUlugaJpZM4IvJbJ>
> .
>



--

**Comment by j3mdamas** [comment]
this one is solved, right?

**Comment by stefdoerr** [comment]
yes
