### ISSUE TITLE
acecloud improvements

### ISSUE THREAD

**Issue by hawk31** [Acellera/htmd#465]
1.  Test and remove initial configuration files if run --setup
1. For minutes there are no intermediate files even if the run crashes at start and it is reported as RUNNING. This makes debugging errors very slow
1. After retrieving a COMPLETED job the job is still there and need to cancel it manually. Any reason for it?
1. Error message are poor
1. "Retrieving output of group/job via S3" should also say where because it is not obvious

Gianni

**Comment by stefdoerr** [comment]
You probably want to put that in the acecloud issue tracker (if you have access). It's not on the level of HTMD

**Comment by j3mdamas** [comment]
@hawk31 thanks for the feedback. I'll copy this issue to acecloud private repo.
