### ISSUE TITLE
guess bond error in filter

### ISSUE THREAD

**Issue by giadefa** [Acellera/htmd#47]
OSX

2016-06-06 22:37:39,866 - htmd.molecule.molecule - INFO - Attempting PDB query for 2OV5
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-1e6427f95438> in <module>()
      1 m = Molecule('2OV5')
----> 2 m.filter('protein or water')

/Users/gianni/miniconda3/lib/python3.4/site-packages/htmd/molecule/molecule.py in filter(self, sel, _logger)
    491         >>> mol.filter('protein')
    492         '''
--> 493         s = self.atomselect(sel)
    494         if np.all(s):  # If all are selected do nothing
    495             return

/Users/gianni/miniconda3/lib/python3.4/site-packages/htmd/molecule/molecule.py in atomselect(self, sel, indexes, strict, fileBonds, guessBonds)
    457                              chain=self.chain,
    458                              segname=self.segid, insert=self.insertion, altloc=self.altloc, beta=self.beta,
--> 459                              occupancy=self.occupancy, bonds=self._getBonds(fileBonds, guessBonds))
    460             if np.sum(s) == 0 and strict:
    461                 raise NameError('No atoms were selected with atom selection "{}".'.format(sel))

/Users/gianni/miniconda3/lib/python3.4/site-packages/htmd/molecule/molecule.py in _getBonds(self, fileBonds, guessBonds)
    420             bonds = numpy.vstack((bonds, self.bonds))
    421         if guessBonds:
--> 422             bonds = numpy.vstack((bonds, self._guessBonds()))
    423         return bonds
    424 

/Users/gianni/miniconda3/lib/python3.4/site-packages/htmd/molecule/molecule.py in _guessBonds(self)
    526         framecoords = self.coords[:, :, self.frame].copy()
    527         return guessbonds(framecoords, self.element, self.name, self.resname, self.resid, self.chain, self.segid,
--> 528                                 self.insertion, self.altloc)
    529 
    530     def moveBy(self, vector, sel=None):

/Users/gianni/miniconda3/lib/python3.4/site-packages/htmd/molecule/vmdparser.py in guessbonds(coordinates, atomname, atomtype, resname, resid, chain, segname, insertion, altloc)
    236 
    237     if(retval):
--> 238        raise ValueError("Guessed bonding is bad")
    239     #print(retval)
    240     nbonds = c_nbonds[0]

ValueError: Guessed bonding is bad

**Comment by giadefa** [comment]
it works on linux

**Comment by mj-harvey** [comment]
If that's a Mac specific failure, I have no way to debug it.

**Comment by stefdoerr** [comment]
Works for me as well. @giadefa can you test on your mac?

**Comment by j3mdamas** [comment]
Well, I guess the bug comes from his Mac  ;)

On Tue, Jun 7, 2016 at 11:05 AM, Stefan <notifications@github.com> wrote:

> Works for me as well. @giadefa <https://github.com/giadefa> can you test
> on your mac?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/47#issuecomment-224222433>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AKTzQmtRdcmv8g81zUCcWFUxVR1Vhx6bks5qJTRhgaJpZM4IvSsh>
> .
>



--

**Comment by stefdoerr** [comment]
Hahaha, did not see who opened the thread :D

**Comment by j3mdamas** [comment]
I have no experience with Mac. Is there a way to create a VM to test it? I
saw some hits on google

On Tue, Jun 7, 2016 at 11:18 AM, Stefan <notifications@github.com> wrote:

> Hahaha, did not see who opened the thread :D
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/47#issuecomment-224225500>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AKTzQkpJz3TmCCaOOS25nf6BHyH8O2FXks5qJTd0gaJpZM4IvSsh>
> .
>



--

**Comment by mj-harvey** [comment]
you almost certainly need to pull htmdlab, rebuild the OS X dsos and put
them back into the distro.

M

On 7 June 2016 at 10:23, João M. Damas <notifications@github.com> wrote:

> I have no experience with Mac. Is there a way to create a VM to test it? I
> saw some hits on google
>
> On Tue, Jun 7, 2016 at 11:18 AM, Stefan <notifications@github.com> wrote:
>
> > Hahaha, did not see who opened the thread :D
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/Acellera/htmd/issues/47#issuecomment-224225500>, or
> mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/AKTzQkpJz3TmCCaOOS25nf6BHyH8O2FXks5qJTd0gaJpZM4IvSsh
> >
> > .
> >
>
>
>
> --
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/47#issuecomment-224226522>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHh-DfmvFdgjbccQCF7iVkmohtkZD_bmks5qJTh1gaJpZM4IvSsh>
> .
>



-- 
<https://www.acellera.com>


<https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>
    <https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/acellera>
<https://www.acellera.com/md-simulation-blog-news/>     [image:
skype:acellera] <http://is.gd/1eXkbS>

**Comment by mj-harvey** [comment]
@giadefa could you please add this as a test case, t? This should have been caught during CI

**Comment by giadefa** [comment]
it does not compile. how do I do it?

ld: warning: ignoring file support/Linux/lib/libpsprolib.a, file was built for archive which is not the architecture being linked (x86_64): support/Linux/lib/libpsprolib.a
mkdir -p lib/basic/Windows
mkdir -p obj/basic/Windows/parser
mkdir -p obj/basic/Windows/xtc
x86_64-w64-mingw32-g++ -o obj/basic/Windows/parser/AtomLexer.o -c src/parser//AtomLexer.C -g  -fPIC  -Wno-write-strings -DCDATE=1465369419  -Iinclude -Isupport/Windows/include -DDIST_basic
make[1]: x86_64-w64-mingw32-g++: No such file or directory
make[1]: *** [obj/basic/Windows/parser/AtomLexer.o] Error 1
cp -r lib/basic/Linux/* ../../htmd/htmd/lib/basic/Linux/
cp -r lib/pro/Linux/* ../../htmd/htmd/lib/pro/Linux/
cp: lib/pro/Linux/*: No such file or directory
make[1]: *** [install] Error 1
make: *** [dummy] Error 2

**Comment by giadefa** [comment]
have some better documentation in the repo. Also how to upload it.

**Comment by giadefa** [comment]
the compiling on Mac is still not working fully but I managed to make a lib. 
Revise it when Matt is here.

**Comment by stefdoerr** [comment]
We need an OSX VM for building the Mac version

**Comment by mj-harvey** [comment]
Closing this and opening a new case
