### ISSUE TITLE
Parameterization threads

### ISSUE THREAD

**Issue by tonigi** [Acellera/htmd#476]
When running the torsion scans, a queue of N processes as spawned (one per each angle). However, each of them uses as many threads as available cores. So each processor is overbooked by a large factor, which I guess is unintended?

**Comment by j3mdamas** [comment]
Hi Toni,

Please paste the code that you're running. Plus, are you running on a released version or on the master?

**Comment by tonigi** [comment]
Nothing fancy, just the tutorial

    parameterize -m ben.mol2 -c 0 -o ./param-ben-fullqm

on the master branch.

**Comment by j3mdamas** [comment]
Yeah, you are right. But we have two open PRs on this right now, so wait for them to be merged. Probably that is already fixed in one of them. @raimis

**Comment by raimis** [comment]
@j3mdamas, it isn't fixed by my PRs. It seems, it is a problem with `LocalCPUQueue` .

**Comment by raimis** [comment]
`LocalCPUQueue.ncpu` is for the total number of CPU the queue is managing, or the number of CPU per task. It seems, this concept is mixed.

**Comment by j3mdamas** [comment]
Actually, I meant closes
