### ISSUE TITLE
Parametrize a .sdf file using htmd

### ISSUE THREAD

**Issue by alejandrovr** [Acellera/htmd#48]
Hello,
Is there any way to parametrize a molecule in .sdf format using htmd? If there is not, is there any way to convert .sdf into .mol2? I guess .mol2 format is the standard one to use in htmd.

Thanks in advance,
Alejandro.

**Comment by stefdoerr** [comment]
Did you close the issue because you found an answer?
If not, [babel](http://openbabel.org/wiki/Main_Page) should be able to turn sdf into mol2.

**Comment by stefdoerr** [comment]
I will also look into adding support for them into HTMD in the future.

**Comment by alejandrovr** [comment]
I found the files I needed in zinc.docking.org,  thanks anyway for answering!
