### ISSUE TITLE
repulsionconstant, repulsionrange, repulsionadd in ACEMD.

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#49]
Hello,

Are these functions still available in acemd? I get the following error when I try to use any or them:

```
#WARNING: cannot open file "restart.coor"
#     Step	      Bond	     Angle	     Dihed	      Elec	       VDW	        PE	        KE	  External	     Total	      Temp	      Pres	   PresAve
         0	 6154.7087	23437.9278	17360.4020	-190868.8324	 2286.8527	-141628.9413	48289.0165	    0.0000	-93339.9248	  302.4192	    0.0000	    0.0000
9.0
TCL error at line #1 []
ERROR: file deven.cpp line 807: TCL evaluation of [calcforces_init] 
```

PS: I'm trying to set a potential among neutral ligands in a membrane. It would be ideal to have only one ligand per box but that's of course too consuming. If you come up with a better idea of setting a potential among them it'd highly appreciate it!

Noelia

**Comment by stefdoerr** [comment]
Please post pure ACEMD issues to the acemd-issue tracker https://github.com/Acellera/acemd_issues
