### ISSUE TITLE
Parameterize output is disordered

### ISSUE THREAD

**Issue by raimis** [Acellera/htmd#494]
`parameterize` uses `print` and `logging` for output. `print` sends to `stdout`, while `logging` sends to `stderr`. 

The former is buffered, while the later is not. It causes the messages to appeare in disorder ways, if `stdout` and `stderr` are merged into the same file.

**Comment by stefdoerr** [comment]
It should all be on logging really. Any reason for using print?

**Comment by raimis** [comment]
Legacy!

**Comment by j3mdamas** [comment]
We could update the prints to logger.info, yes.

**Comment by raimis** [comment]
Yes! Just needs some work... ;)

**Comment by raimis** [comment]
Nope, the issue is present.
