### ISSUE TITLE
Problems with 'import' after update

### ISSUE THREAD

**Issue by smar966** [Acellera/htmd#498]
Hello. I am new to HTMD. But I had it installed days ago and it seemed to be working except for a few things (such as visualization in VMD not showing cartoons). So yesterday I updated it as recommended on the webpage (conda update -c acellera -c psi4 htmd) . After that the htmd is unable to be imported (see below).
How can I solve this?

Thanks in advance.
Sergio

# By running:

from htmd import *

# I obtain:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/miniconda3/lib/python3.6/site-packages/numpy/core/__init__.py in <module>()
     15 try:
---> 16     from . import multiarray
     17 except ImportError:

ImportError: libiomp5.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-5-3b486bdf413a> in <module>()
----> 1 from htmd import *
      2 

~/miniconda3/lib/python3.6/site-packages/htmd/__init__.py in <module>()
----> 1 from htmd.ui import *  # TODO: This will be deprecated in a few versions
      2 from htmd.version import version as _version
      3 import os
      4 from htmd.config import _config
      5 

~/miniconda3/lib/python3.6/site-packages/htmd/ui.py in <module>()
      7 import htmd.home
      8 from htmd.session import htmdsave, htmdload
----> 9 from htmd.simlist import simlist, simfilter, simmerge
     10 from htmd.metricdata import MetricData
     11 from htmd.projections.metricdistance import MetricDistance, MetricSelfDistance, reconstructContactMap

~/miniconda3/lib/python3.6/site-packages/htmd/simlist.py in <module>()
     13 from os import makedirs
     14 from glob import glob as glob
---> 15 import numpy as np
     16 import logging
     17 logger = logging.getLogger(__name__)

~/miniconda3/lib/python3.6/site-packages/numpy/__init__.py in <module>()
    144         return loader(*packages, **options)
    145 
--> 146     from . import add_newdocs
    147     __all__ = ['add_newdocs',
    148                'ModuleDeprecationWarning',

~/miniconda3/lib/python3.6/site-packages/numpy/add_newdocs.py in <module>()
     11 from __future__ import division, absolute_import, print_function
     12 
---> 13 from numpy.lib import add_newdoc
     14 
     15 ###############################################################################

~/miniconda3/lib/python3.6/site-packages/numpy/lib/__init__.py in <module>()
      6 from numpy.version import version as __version__
      7 
----> 8 from .type_check import *
      9 from .index_tricks import *
     10 from .function_base import *

~/miniconda3/lib/python3.6/site-packages/numpy/lib/type_check.py in <module>()
      9            'common_type']
     10 
---> 11 import numpy.core.numeric as _nx
     12 from numpy.core.numeric import asarray, asanyarray, array, isnan, \
     13                 obj2sctype, zeros

~/miniconda3/lib/python3.6/site-packages/numpy/core/__init__.py in <module>()
     22 files not under version control).  Otherwise reinstall numpy.
     23 """
---> 24     raise ImportError(msg)
     25 
     26 for envkey in env_added:

ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

**Comment by j3mdamas** [comment]
Hi @smar966,

Unfortunately there was a break in updates from versions 1.7.x to 1.8.x onwards. My recommendation is to do a fresh conda instalation, unfortunately.

I apologize for the inconvenience.
João

**Comment by smar966** [comment]
It worked, thanks!
