### ISSUE TITLE
PBSQueue()

### ISSUE THREAD

**Issue by piia600** [Acellera/htmd#499]
Hi,

I would like to test and make the PBSQueue work, as now nothing goes through this class. 

Here is my file:
`from htmd.ui import *
app = PBSQueue()
app.queue = 'gpu@arien-pro.ics.muni.cz'
app.submit('./prod/')`

And here is the error message:
`Traceback (most recent call last):
  File "single_run.py", line 2, in <module>
    app = PBSQueue()
TypeError: Can't instantiate abstract class PBSQueue with abstract methods memory, ncpu, ngpu`

The problem here is that I have really limited access on updating the HTMD on the supercomputing system. However, I remember this class being able to at least print files at some point...

Cheers,
Piia

**Comment by stefdoerr** [comment]
@j3mdamas seems like you didn't implement those methods in PBSQueue after refactoring the queues

**Comment by j3mdamas** [comment]
@stefdoerr true that. it's a quick fix.

**Comment by j3mdamas** [comment]
@piia600 as the warning in the documentation says, this queue is untested, so it's bound to fail. that being said, we welcome suggestions and PRs.
