### ISSUE TITLE
Amber aliasing

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#5]
Hi guys,

One question. Is amber.build aliasing residues in the same way as charmm.build does? 
I just built a system in charmm whose initial receptor structure contained a terminal patch called 'NMA' (not appearing in the final structure.pdb). However the same system didnt work in amber.build giving the following error: 
FATAL:  Atom .R< NMA 466 >.A<N 1> does not have a type

But I remember charmm was also having this issue some weeks ago, so I guess charmm.build is now automatically removing terminal patches from the initial structure. Is this correct?

Thanks,
Noelia

**Comment by j3mdamas** [comment]
Hi Noelia.

I think that cap is called **NME** in amber. From what I see, `amber.build` does not have a alias for NMA.

João

João

**Comment by noeliaferruz** [comment]
Hi João!

Welcome :)!!
And thanks!
ok, i will simply remove patches for the moment.

Noelia

**Comment by j3mdamas** [comment]
I'm still starting and just commented after a cursory check. Maybe Stefan
will comment further.
João

On Fri, Apr 1, 2016 at 5:44 PM, Noelia Ferruz <notifications@github.com>
wrote:

> Hi João!
>
> Welcome :)!!
> And thanks!
> ok, i will simply remove patches for the moment.
>
> Noelia
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Acellera/htmd/issues/5#issuecomment-204442681>
>



-- 
João M. Damas
Tel:+351962414282
skype: jmdamas

**Comment by stefdoerr** [comment]
Yes, in charmm.build I remove NMA and replace it with the equivalent CHARMM cap which is CT3

**Comment by stefdoerr** [comment]
If Joao is right about the cap name and you really want to build in AMBER then rename the reside to NME. 
I have not done any work with aliases in AMBER because I need to look into tleap and what the corresponding residue names are there. CHARMM build is for the moment much more advanced (since pretty much everyone uses it).

**Comment by noeliaferruz** [comment]
Thanks!!

**Comment by tonigi** [comment]
Maybe we can add an alias in tleap to simplify life.
