### ISSUE TITLE
 list indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#50]
Hello guys,

Sorry, it seems this function in the documentation might be outdated. Do you perhaps know how can I get the simulation name from data after having used data.dropTraj()?

Thanks a lot,
Noelia

```
simframes = data.rel2sim([100,56])  
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-84-a4d8c00fd89b> in <module>()
      8 #    if np.any(data.dat[i]<2): print(i,data.dat[i])
      9 #len(sims865)
---> 10 simframes = data.rel2sim([100,56])
     11 #data.plotTrajSizes()
     12 #print(sims865[80])
/path/to/acellera/test/python/lib/python3.5/site-packages/htmd/metricdata.py in rel2sim(self, relFrames)
    369         frames = []
    370         for i in range(np.size(relFrames, 0)):
--> 371             trajID = relFrames[i, 0]
    372             trajFrame = relFrames[i, 1]
    373             sims.append(self.simlist[trajID])
TypeError: list indices must be integers or slices, not tuple
```

**Comment by noeliaferruz** [comment]
Unrelated with the bug, I tried with abs2sim and seemed to work, but i'm not sure if it's actually correct :s (but maybe you know? :D)

Thanks a lot!
```
datconcat=np.concatenate(data.dat, axis=0)
x=[frame for frame, rmsd in enumerate(datconcat) if rmsd < 2]
for i in range(len(x)): print(data.abs2sim(x)[i])
```

**Comment by stefdoerr** [comment]
Uh oh, I smell the same bug we had this morning with the reconstructAdaptive. At some point we changed how simlists work and since we didn't have tests we didn't notice stuff that broke. I will fix it tomorrow.

Your second code looks correct (and nice, hehe).

**Comment by j3mdamas** [comment]
@stefdoerr, you already fixed this, no?

**Comment by stefdoerr** [comment]
No, give me a minute and it will be done. Was much simpler than I thought.

**Comment by j3mdamas** [comment]
no, it's fine! take your time. I thought I saw a commit related to this already

**Comment by stefdoerr** [comment]
Fixed https://github.com/multiscalelab/htmd/commit/1b002479be50cd94cefb941cb21d96fa61316226
