### ISSUE TITLE
help wanted: Simulation unstable. Flag 6 value 1 

### ISSUE THREAD

**Issue by federicachi** [Acellera/htmd#508]
Hi to all!
I'm a new user of Acemd. 
I have find several input files for minimize and equilibrate my system. The minimization step reach always the end, while the equilibration step stops at the beginning of the simulation.
In particular the last version (
amber 		on
parmfile           $parameters
coordinates     $structure.pdb 
bincoordinates  $input.coor 
binvelocities  	$input.vel 
binindex        $input.idx
temperature	$temperature
extendedsystem	$input.xsc
restart		on
restartfreq     5000
outputname      $output
xtcfile         $output.xtc
xtcfreq         25000
timestep        4
rigidbonds      all 
hydrogenscale   4
switching       on
switchdist      7.5
cutoff          9
exclude         scaled1-4
1-4scaling      0.83333
langevin        on
langevintemp    $temperature
langevindamping 1
pme             on
pmegridspacing  1.0
fullelectfrequency 2
energyfreq      1000
constraints on
consref $structure.pdb
constraintscaling 1.0
berendsenpressure  on
berendsenpressuretarget 1.01325
berendsenpressurerelaxationtime  800 
useconstantratio on
run $numSteps
)

report this error:
"Simulation unstable. Flag 6 value 1"

I'm running the simulation with the last version of HTMD on an Ubuntu.
have anyone an idea?

Thank you
Federica

**Comment by j3mdamas** [comment]
Hi @federicachi,

For acemd issues, please use this: https://github.com/Acellera/acemd_issues/issues

Thanks!
João
