### ISSUE TITLE
XTC writer really slow for many frames

### ISSUE THREAD

**Issue by stefdoerr** [Acellera/htmd#509]
The looping over the frames is done in python where each frame is converted to a ctypes object one by one. This results in excruciatingly slow xtc writing for i.e. 100.000 frames with only 10 atoms (still waiting after 20 minutes). We need to move the frame loop inside the C xtc writer and convert all frames once to ctypes in python.

**Comment by stefdoerr** [comment]
Already done. Problem is that people who use the git will need to do a
conda update with the next release to get the updated *.so

**Comment by j3mdamas** [comment]
you rather mean that we need to replace the .so files in the git repo, and the people using git need to repull the repo, right?

the new .so files are rebuilt on travis and distributed in conda

**Comment by stefdoerr** [comment]
Right, I forgot we ship the so's in the git as well.
https://github.com/Acellera/htmd/commit/4d6ae927649584c48039e6394f5fbdc626f6a440
Done.

**Comment by stefdoerr** [comment]
Holy ****! I went down from 20 minutes to 200ms! This ought to have great impact on HTMD. Trajectory filtering (adaptive) and VMD visualization will be the most obvious improvements in cases of many frames.

**Comment by stefdoerr** [comment]
It's an obvious improvement but somehow I never looked much into the XTCwriter as I assumed it was already all in C.

**Comment by j3mdamas** [comment]
thanks @stefdoerr! @cuzzo87 will appreciate a lot when his adaptives take 2 hours to do the analysis :P
