### ISSUE TITLE
charmm.search(key='RESI', name = 'CHL1')

### ISSUE THREAD

**Issue by giadefa** [Acellera/htmd#51]
I propose this function which should simply grep inside all charmm files to tell me which file provides the RESI CHL1 residue

**Comment by noeliaferruz** [comment]
Hi,

How do you actually add str files in htmd? I just added str/lipid/

**Comment by stefdoerr** [comment]
https://github.com/multiscalelab/htmd/commit/1e722bb88ebf9c12ce519c8f574ca05d612edb08
Done
