### ISSUE TITLE
update nglview to 1.0 and test

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#512]
https://github.com/arose/nglview/releases/tag/v1.0

**Comment by j3mdamas** [comment]
- [ ] Ensure it works on jupyter and update instructions (any way to test without actually visualising?)

**Comment by stefdoerr** [comment]
Tested and works. I doubt we can test without visualizing, unless we can catch javascript errors from jupyter through command-line which sounds like the definition of hell

**Comment by j3mdamas** [comment]
@stefdoerr thanks!
