### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by federicachi** [Acellera/htmd#515]
Hello. I am a new HTMD user.
I have a GPCR, so I have build the system with htmd, now I'm trying to equilibrate the system, as  described in the tutorial (Equilibration protocol for the mu opioid GPCR). 
I have a slurm queue system, so I've substitute the "mdx" portion with:
>>> from htmd import *
>>> s = SlurmQueue()
>>> s.partition = 'multiscale'
>>> s.submit('/my/runnable/folder/')  # Folder containing a run.sh bash script

The minimization fished ok, when the equilibration starts, an error is returned:

# SWAN : FATAL : Cuda driver error 700 : CUDA_ERROR_ILLEGAL_ADDRESS : an illegal memory access was encountered
# SWAN : occured in file 'swanlibnv2.cpp' in line 2009. 

Can anyone help me?

Thanks
Federica

**Comment by j3mdamas** [comment]
Hi Federica,

This seems like an ACEMD error. Let's move it there: https://github.com/Acellera/acemd_issues/issues/45

I'm closing this one.

**Comment by jmhenriques** [comment]
Did this issue get solved? The link @j3mdamas posted is broken and I'm getting the same error.

**Comment by j3mdamas** [comment]
@jmhenriques we've closed the acemd issues repo. Could you post a new report? Thanks!
