### ISSUE TITLE
charmm.built WARNING - Failed/poorly guessed coordinates can cause simulations to crash since failed atoms are all positioned on (0,0,0).

### ISSUE THREAD

**Issue by giadefa** [Acellera/htmd#52]
This is kind of wrong, because it is saying that even when there are no [0,0,0] coordinates.
On the other hands it should be make it very clear that it is likely wrong to have it. Like SEVERE WARNING

**Comment by j3mdamas** [comment]
This warning still puzzles me. I've had it, and simulations did not crash.

On Wed, Jun 8, 2016 at 12:25 PM, giadefa <notifications@github.com> wrote:

> This is kind of wrong, because it is saying that even when there are no
> [0,0,0] coordinates.
> On the other hands it should be make it very clear that it is likely wrong
> to have it. Like SEVERE WARNING
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/52>, or mute the thread
> <https://github.com/notifications/unsubscribe/AKTzQnmagOdvlLweOHtxCiMOprpfwCzpks5qJpiigaJpZM4Iw0EB>
> .
>



--

**Comment by stefdoerr** [comment]
Removed useless warning.
Added severe warning when atoms are actually at 0,0,0
