### ISSUE TITLE
Fix change of directory with PCMSolver

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#528]
From here: https://github.com/Acellera/htmd/pull/409#discussion_r139696856

Psi4 team fixed it here: https://github.com/psi4/psi4/pull/818

We should fix ours as soon as their fix is on main

**Comment by raimis** [comment]
Too early for 1.14.0 -- Psi4 1.2 will be available just on June 30... :D

**Comment by j3mdamas** [comment]
ahah let's keep it as a reference. I'll move it further ahead when we have another milestone

**Comment by raimis** [comment]
@j3mdamas we already using *Psi4* 1.2.1! Should we close this?

**Comment by j3mdamas** [comment]
https://github.com/Acellera/htmd/pull/409/files/a43918d2642585e61882f1f22d4502809611374c#r139968559

We just need to remove the use of the ugly `HTMD_PSI4_DIRECTORY` that was used to circumvent this issue :)

**Comment by j3mdamas** [comment]
(and make sure it works)
