### ISSUE TITLE
progress_reporter major changes on 1.4

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#531]
I noticed it with last time I synced the packages. The code is very much rewritten, the initial import fails right away:

```
import progress_reporter.bar.gui as __gui  # Disabling pyemma progress widgets
__gui.ipython_notebook_session = False
```

Release: https://github.com/marscher/progress_reporter/releases/tag/v1.4

Right now, I'm still fixing travis (should build now, let's see). @stefdoerr, can you adapt to it when you have some free time and after builds are stable?

**Comment by j3mdamas** [comment]
It could be an opportunity to see if we still need our progress bar or not

**Comment by stefdoerr** [comment]
Oh seems like they went for extending tqdm which is also my fav. I will see if we can just replace our progress bars for tqdm. The problem is mostly with parallel computations

**Comment by j3mdamas** [comment]
Thanks! Let me just fix travis first, ok?

**Comment by stefdoerr** [comment]
Done https://github.com/Acellera/htmd/commit/6ab26e2b1c7af45ad6476e30a8b14450de4081ca

**Comment by stefdoerr** [comment]
Oh, I just saw your message. Sorry

**Comment by j3mdamas** [comment]
It's OK. It's going to fail travis anyway.

It requires the new progress_reporter version, correct? So I sync it before-hand testing this.

**Comment by stefdoerr** [comment]
No I dropped progress_reporter. We will use tqdm instead. I added it to the
deps and afaik it should be on default conda so no need to sync either

**Comment by j3mdamas** [comment]
sorry, should have seen your commit :P ok, all good now then!
