### ISSUE TITLE
conda rdkit fails on import on OSX

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#532]
This means that smallmol is failing there.

More information here: https://github.com/rdkit/rdkit/issues/1617

The work around are a mess (downgrade to python 3.6.1). Let's follow the issue with rdkit.

**Comment by j3mdamas** [comment]
No solution from rdkit team, MacOS build is disabled for now anyway, so I'll bump this up and lower bug priority

**Comment by stefdoerr** [comment]
OSX is no longer officially supported but actually works again with the new rdkit.
