### ISSUE TITLE
Set fstep for adaptive sampling? 

### ISSUE THREAD

**Issue by mikeoconnor0308** [Acellera/htmd#534]
Hi, 

There doesn't appear to be a way to manually specify the frame step property when running adaptive sampling. E.g.:

```
2018-01-16 17:34:08,577 - htmd.projections.metric - INFO - Frame step 9.999999974752427e-07ns was read from the trajectories. If it looks wrong, redefine it by manually setting the MetricData.fstep property.
```

Indeed, this frame step does look wrong. 

Seems like this would be pretty easy to add as an optional parameter, which I'm happy to submit as a contribution, but I want to check I'm not missing something?

**Comment by stefdoerr** [comment]
Hm yes indeed there is no option. But practically you don't need a correct frame step since the lag and ticalag are specified in frames. The fstep is really only necessary when plotting timescales or calculating kinetics.

**Comment by stefdoerr** [comment]
Maybe we could disable that warning for the adaptive so it doesn't confuse the users.

**Comment by j3mdamas** [comment]
@stefdoerr did you do anything about this?

**Comment by stefdoerr** [comment]
As I said, there is no need to do anything. Unless you want to disable the warning but I don't see it as a priority right now.

**Comment by j3mdamas** [comment]
ok perfect.
