### ISSUE TITLE
parameterize: CGENFF issue

### ISSUE THREAD

**Issue by quantumania** [Acellera/htmd#543]
MOL2 file https://isu.box.com/s/pfea1gw7qpjlndnthqxijy67ikbe4g9e
A dry run with default GAFF2 is fine, but when -ff CGENFF is turned on, KeyError: 'HN1' comes up:

parameterize 5TVN_Prepped_7LD.mol2 -ff CGENFF --charge 1 --no-min --no-esp --no-dihed --outdir initial

 === Arguments ===
 filename: 5TVN_Prepped_7LD.mol2
 charge: 1
 list: False
 rtf_prm: None
 forcefield: ['CGENFF']
 fix_charge: []
 dihedral: []
  code: Psi4
 theory: B3LYP
 basis: cc-pVDZ
 environment: vacuum
  minimize: False
 fit_charges: False
fit_dihedral: False
optimize_dihedral: True
  queue: local
 ncpus: None
 memory: None
 groupname: None
  outdir: initial
  seed: 20170920
 fake_qm: False

 === Parameterizing 5TVN_Prepped_7LD.mol2 ===

 === Fitting for CGenFF_2b6 ===

Got charge 1
Set charge 1
N1     N.3%5A NG2R51 N.3%5A(C.3%5)
N2     N.3    NG2S0  N.3(!C.3(O.1))
C1     C.3%6A CG2R61 C.3%6A
C2     C.3%6A CG2R61 C.3%6A
C3     C.3%6A,6N CG2R67 C.3%6(C.3%6)(C.3%6)(C.3%6)
C4     C.3%5A,6N CG2DC? C.3%*N(=C.3)(C.3(=C.3))
C5     C.3%5A CG2R51 C.3%5
C6     C.3%6N CG2DC? C.3%*N(=C.3(C.3(=C.3)))
C7     C.4%6N CG324  C.4(H.1)(H.1)(N+)
C8     C.4%6N CG321  C.4(H.1)(H.1)
C9     C.4    CG321  C.4(H.1)(H.1)
C10    C.4    CG331  !C.4(H.1)(H.1)(H.1)
N3     N.4%6N NG3P1  N.4(H.1)
C11    C.4    CG334  !C.4(H.1)(H.1)(H.1)(N+)
C12    C.4%6N,6N CG314  C.4(H.1)(N+)
C13    C.3%5A,6A,6N CG2R67 C.3%6(C.3%6)(C.3%6)(C.3%6)
C14    C.3%5A,6A CG2RC0 C.3%6,5(C.3%6,5)(C.3%6)
C15    C.3%6A CG2R61 C.3%6A
C16    C.3%6N,6N CG2DC? C.3%*N(=C.3)(C.3(=C.3))
C17    C.4%6N CG311  C.4(H.1)
C18    C.3    CG2O1  !C.3(O.1)(N.3)
O1     O.1    OG2D1  O.1(C.3)
C19    C.4    CG321  C.4(H.1)(H.1)
C20    C.4    CG331  !C.4(H.1)(H.1)(H.1)
H1     H.1    HGP1   H.1(N.3%5)
H2     H.1    HGR61  H.1(C.3%6)
H3     H.1    HGR61  H.1(C.3%6)
H4     H.1    HGR52  H.1(C.3%5([^C]%5))
H5     H.1    HGA4   H.1(C.3%*N)
H6     H.1    HGA2   H.1(C.4(H.1))
H7     H.1    HGA2   H.1(C.4(H.1))
H8     H.1    HGA2   H.1(C.4(H.1))
H9     H.1    HGA2   H.1(C.4(H.1))
H10    H.1    HGA2   H.1(C.4(H.1))
H11    H.1    HGA2   H.1(C.4(H.1))
H12    H.1    HGA3   H.1(C.4(H.1)(H.1))
H13    H.1    HGA3   H.1(C.4(H.1)(H.1))
H14    H.1    HGA3   H.1(C.4(H.1)(H.1))
H15    H.1    HGP2   H.1(N.4)
H16    H.1    HGA3   H.1(C.4(H.1)(H.1))
H17    H.1    HGA3   H.1(C.4(H.1)(H.1))
H18    H.1    HGA3   H.1(C.4(H.1)(H.1))
H19    H.1    HGA1   H.1(C.4)
H20    H.1    HGR61  H.1(C.3%6)
H21    H.1    HGA1   H.1(C.4)
H22    H.1    HGA2   H.1(C.4(H.1))
H23    H.1    HGA2   H.1(C.4(H.1))
H24    H.1    HGA3   H.1(C.4(H.1)(H.1))
H25    H.1    HGA3   H.1(C.4(H.1)(H.1))
H26    H.1    HGA3   H.1(C.4(H.1)(H.1))
mol Success!
Traceback (most recent call last):
  File "/garlic/apps/anaconda3/envs/htmd_1.11.7/bin/parameterize", line 11, in <module>
    sys.exit(main_parameterize())
  File "/garlic/apps/anaconda3/envs/htmd_1.11.7/lib/python3.6/site-packages/htmd/parameterization/cli.py", line 183, in main_parameterize
    outdir=args.outdir)
  File "/garlic/apps/anaconda3/envs/htmd_1.11.7/lib/python3.6/site-packages/htmd/parameterization/ffmolecule.py", line 92, in __init__
    self.atomtype[:] = [self._rtf.type_by_name[name] for name in self.name]
  File "/garlic/apps/anaconda3/envs/htmd_1.11.7/lib/python3.6/site-packages/htmd/parameterization/ffmolecule.py", line 92, in <listcomp>
    self.atomtype[:] = [self._rtf.type_by_name[name] for name in self.name]
KeyError: 'HN1'

**Comment by raimis** [comment]
It will be fixed when #544 is merged:
```
$ parameterize 5TVN_Prepped_7LD.mol2 -ff CGENFF --charge 1 --no-min --no-esp --no-dihed --outdir initial

HTMD Config file /shared/raimis/opt/acellera/conf.py executed.

 === Arguments ===

    filename: 5TVN_Prepped_7LD.mol2
      charge: 1
        list: False
     rtf_prm: None
  forcefield: ['CGENFF']
  fix_charge: []
    dihedral: []
        code: Psi4
      theory: B3LYP
       basis: cc-pVDZ
 environment: vacuum
    minimize: False
 fit_charges: False
fit_dihedral: False
optimize_dihedral: True
       queue: local
       ncpus: None
      memory: None
   groupname: None
      outdir: initial
        seed: 20170920
     fake_qm: False

 === Parameterizing 5TVN_Prepped_7LD.mol2 ===

 === Fitting for CGenFF_2b6 ===

Got charge 1
Set charge 1
N1     N.3%5A NG2R51 N.3%5A(C.3%5)
N2     N.3    NG2S0  N.3(!C.3(O.1))
C1     C.3%6A CG2R61 C.3%6A
C2     C.3%6A CG2R61 C.3%6A
C3     C.3%6A,6N CG2R67 C.3%6(C.3%6)(C.3%6)(C.3%6)
C4     C.3%5A,6N CG2DC? C.3%*N(=C.3)(C.3(=C.3))
C5     C.3%5A CG2R51 C.3%5 
C6     C.3%6N CG2DC? C.3%*N(=C.3(C.3(=C.3)))
C7     C.4%6N CG324  C.4(H.1)(H.1)(N+)
C8     C.4%6N CG321  C.4(H.1)(H.1)
C9     C.4    CG321  C.4(H.1)(H.1)
C10    C.4    CG331  !C.4(H.1)(H.1)(H.1)
N3     N.4%6N NG3P1  N.4(H.1)
C11    C.4    CG334  !C.4(H.1)(H.1)(H.1)(N+)
C12    C.4%6N,6N CG314  C.4(H.1)(N+)
C13    C.3%5A,6A,6N CG2R67 C.3%6(C.3%6)(C.3%6)(C.3%6)
C14    C.3%5A,6A CG2RC0 C.3%6,5(C.3%6,5)(C.3%6)
C15    C.3%6A CG2R61 C.3%6A
C16    C.3%6N,6N CG2DC? C.3%*N(=C.3)(C.3(=C.3))
C17    C.4%6N CG311  C.4(H.1)
C18    C.3    CG2O1  !C.3(O.1)(N.3)
O1     O.1    OG2D1  O.1(C.3)
C19    C.4    CG321  C.4(H.1)(H.1)
C20    C.4    CG331  !C.4(H.1)(H.1)(H.1)
H1     H.1    HGP1   H.1(N.3%5)
H2     H.1    HGR61  H.1(C.3%6)
H3     H.1    HGR61  H.1(C.3%6)
H4     H.1    HGR52  H.1(C.3%5([^C]%5))
H5     H.1    HGA4   H.1(C.3%*N)
H6     H.1    HGA2   H.1(C.4(H.1))
H7     H.1    HGA2   H.1(C.4(H.1))
H8     H.1    HGA2   H.1(C.4(H.1))
H9     H.1    HGA2   H.1(C.4(H.1))
H10    H.1    HGA2   H.1(C.4(H.1))
H11    H.1    HGA2   H.1(C.4(H.1))
H12    H.1    HGA3   H.1(C.4(H.1)(H.1))
H13    H.1    HGA3   H.1(C.4(H.1)(H.1))
H14    H.1    HGA3   H.1(C.4(H.1)(H.1))
H15    H.1    HGP2   H.1(N.4)
H16    H.1    HGA3   H.1(C.4(H.1)(H.1))
H17    H.1    HGA3   H.1(C.4(H.1)(H.1))
H18    H.1    HGA3   H.1(C.4(H.1)(H.1))
H19    H.1    HGA1   H.1(C.4)
H20    H.1    HGR61  H.1(C.3%6)
H21    H.1    HGA1   H.1(C.4)
H22    H.1    HGA2   H.1(C.4(H.1))
H23    H.1    HGA2   H.1(C.4(H.1))
H24    H.1    HGA3   H.1(C.4(H.1)(H.1))
H25    H.1    HGA3   H.1(C.4(H.1)(H.1))
H26    H.1    HGA3   H.1(C.4(H.1)(H.1))
mol Success!

 == Molecule report ==

Total number of atoms: 50
Total charge: 1
Equivalent atom groups:
  N1
  N2
  C1
  C2
  C3
  C4
  C5
  C6
  C7
  C8
  C9, C19
  C10, C20
  N3
  C11
  C12
  C13
  C14
  C15
  C16
  C17
  C18
  O1
  H1
  H2
  H3
  H4
  H5
  H6, H7
  H8, H9
  H10, H11, H22, H23
  H12, H13, H14, H24, H25, H26
  H15
  H16, H17, H18
  H19
  H20
  H21
Rotatable dihedral angles:
  N2-C18-C17-C6
  C9-N2-C18-C17
    Equivalents:
      C17-C18-N2-C19
  C18-N2-C9-C20
    Equivalents:
      C10-C19-N2-C18

 == Writing results ==


== Diagnostic Energies ==

Bond     : 48.447854989972186
Angle    : 30.40560847608331
Dihedral : 39.86205832461928
Improper : 0.004763618892472505
Electro  : 0.0
VdW      : 120.33068587549562
```

**Comment by quantumania** [comment]
So, how do I access the fixed code?

**Comment by raimis** [comment]
@quantumania

The fixes already on `master` branch and they will be available on *HTMD* 1.11.8.

**Comment by stefdoerr** [comment]
Which should be available in a few hours if everything goes well

**Comment by raimis** [comment]
@quantumania, *HTMD* 1.11.8 is already available on *conda*. You can update!
