### ISSUE TITLE
ESP fitting warning

### ISSUE THREAD

**Issue by quantumania** [Acellera/htmd#549]
All the molecules I tried so far has this warning. Is it something to be concerned with??

 == Fitting ESP charges ==

/garlic/apps/anaconda3/envs/htmd_1.11.7/lib/python3.6/site-packages/htmd/parameterization/ffmolecule.py:201: RuntimeWarning: invalid value encountered in true_divide
  return np.dot(self.masses, self.coords[:, :, self.frame])/np.sum(self.masses)
MM dipole cannot be computed. Check if elements are detected correctly.

**Comment by raimis** [comment]
Hi @quantumania 

This does not affect the results of the ESP calculations. Just a waning, I had not time to fix.
