### ISSUE TITLE
.wait() method should report if acemd is stuck

### ISSUE THREAD

**Issue by alejandrovr** [Acellera/htmd#56]
Hello,
we are trying to equilibrate the system but when it arrives to "mdx.wait()" it takes too long (more than 2 hours and still running) and in the documentation says it will take 5 minutes.

```python
from htmd.protocols.equilibration_v1 import Equilibration
from natsort import natsorted
md = Equilibration()
md.numsteps = 1000
md.temperature = 298

builds = natsorted(glob('./docked/build/*/'))
for i, b in enumerate(builds):
    md.write(b, 'docked/equil/{}/'.format(i+1))

mdx = AcemdLocal()
mdx.submit(glob('./docked/equil/*/'))

mdx.wait()
```

It does not give any errors, should we still waiting or is there any errors?

**Comment by stefdoerr** [comment]
Can you check in the directory which it's simulating what is written in the log.txt files and the FINISH_TIME file?

**Comment by stefdoerr** [comment]
I've had ACEMD get stuck in an infinite minimization loop before. To debug it actually try running acemd directly from the simulation folder (from command line). Then you will see what's happening.

**Comment by giadefa** [comment]
maybe the wait() could give more info also

On 9 June 2016 at 13:42, Stefan <notifications@github.com> wrote:

> I've had ACEMD get stuck in an infinite minimization loop before. To debug
> it actually try running acemd directly from the simulation folder (from
> command line). Then you will see what's happening.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/56#issuecomment-224871182>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHaqOuWyDgJDyqhXrcT4EHtwhn_R338Wks5qJ_w2gaJpZM4Ix3Zi>
> .
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>

**Comment by stefdoerr** [comment]
Like what info? Projected runtime maybe? But it would still not help in debugging this I think. Only looking at the acemd realtime output helps for such problems and printing that would be impossible (and messy).

**Comment by nesilin** [comment]
Hi! 
For your knowledge , in fact the tutorial barnase-barstar-building-simulation of htmd which also uses ACEMD like 
mdx = AcemdLocal()
mdx.submit('./equil')
mdx.wait()

also got stuck at this point. 
A part from that, we have tried what you suggested but the FINISH_TIME file does not exist and the log.txt does not say anything about trouble in the wait method. 
Moreover, the log.txt did not report any problem. 
We have tried ACEMD  with the input file inside the /docked/equil/1 directory and we have obtained the output.coor and output.xsc and others. 
Could it be that we are missing the driver of nvidia? Because we have tried to run ACEMD from command line in another machine and as I said it worked but in alejandrovr 's computer did not. In alejandrovr 's computer the error has been the following:
 /home/alejandro/miniconda3/bin/acemd.bin:
 error while loading shared libraries: libcuda.so.1: 
cannot open shared object file: No such file or directory

**Comment by stefdoerr** [comment]
Hm ok that error means you don't have cuda installed on the machine. ACEMD needs cuda and an NVIDIA GPU to work.

So the `mdx.wait()` problem was only on the machine of @alejandrovr ?

**Comment by j3mdamas** [comment]
yeah, gianni said that some of their machines wouldn't be able to run acemd...

**Comment by stefdoerr** [comment]
Would be nice though if AcemdLocal did not get stuck and reported something. But I need a test machine to see what goes wrong.

**Comment by giadefa** [comment]
workspace1

On 9 June 2016 at 16:06, Stefan <notifications@github.com> wrote:

> Would be nice though if AcemdLocal did not get stuck and reported
> something. But I need a test machine to see what goes wrong.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/56#issuecomment-224905259>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHaqOnwZIJgcyPtfjEgk4ySQ7bxvx42rks5qKB39gaJpZM4Ix3Zi>
> .
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>

**Comment by j3mdamas** [comment]
So, this is issue is about changing AcemdLocal (anything that runs acemd really), to report stuff if stuck.

For the students, well, there are large groups, I hope that there is at least one person per group which can run acemd

**Comment by giadefa** [comment]
only 4 people need to run

On 9 June 2016 at 16:16, João M. Damas <notifications@github.com> wrote:

> So, this is issue is about changing AcemdLocal (anything that runs acemd
> really), to report stuff if stuck.
>
> For the students, well, there are large groups, I hope that there is at
> least one person per group which can run acemd
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/56#issuecomment-224908186>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHaqOhc-RWF0j94vPIOpTQrkafoN3DFYks5qKCBMgaJpZM4Ix3Zi>
> .
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>

**Comment by alejandrovr** [comment]
@stefdoerr it did not work for me, neither for my colleagues who does not have nvidia. Thanks for answering, running from command line has helped us.

**Comment by giadefa** [comment]
Why are you not running on the provided machines with Nvidia GPUs?

On 10 June 2016 at 11:12, alejandrovr <notifications@github.com> wrote:

> @stefdoerr <https://github.com/stefdoerr> it did not work for me, neither
> for my colleagues who does not have nvidia. Thanks for answering, running
> from command line has helped us.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/56#issuecomment-225132079>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHaqOgqBbPpbueP686NnmzbGNzjEalPuks5qKSp8gaJpZM4Ix3Zi>
> .
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>

**Comment by alejandrovr** [comment]
Because vmd was not installed. Now it is, however vmd is not fullly working, because it will only run if one does ssh without -Y option, but then no window will appear, only the command line from vmd. That seems enough to make the scripts that use vmd run.

**Comment by giadefa** [comment]
hmm, no script use VMD if not for visualization?

On 10 June 2016 at 11:24, alejandrovr <notifications@github.com> wrote:

> Because vmd was not installed. Now it is, however vmd is not fullly
> working, because it will only run if one does ssh without -Y option, but
> then no window will appear, only the command line from vmd. That seems
> enough to make the scripts that use vmd run.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/56#issuecomment-225135371>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHaqOhuoFHWBT0a-Qp3TntPhj4IhuRO0ks5qKS1YgaJpZM4Ix3Zi>
> .
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>

**Comment by alejandrovr** [comment]
We found this piece of code that saves a view into a variable:

from ipywidgets.widgets import Box
w = []
for i, m in enumerate(molbuilt):
    m.view(sel='protein', style='NewCartoon', hold=True)
    m.view(sel='water', style='Lines', hold=True)
    h = m.view(sel='resname MOL', style='Licorice', color=0) 
    w.append(h)
b = Box(children=(w[0],w[1]))
b
Now our script fails at Box, but we think that's some kind of Jupyter stuff not really needed for the simulation process so we are trying to run the script with it. Is that correct? Thanks.

**Comment by stefdoerr** [comment]
If there is still an issue please report it. Closing for now

**Comment by mj-harvey** [comment]
What I take from this is that there's a problem with ACEMD sometimes getting stuck minimizing  ill-conditioned input. There's a case about that open elsewhere, so I'm oging to close this one. If you think there's another problem, please reopen and elaborate.
