### ISSUE TITLE
Improve Element guessing in Molecule

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#563]
This is a hard task in general (how can we know programatically thata `CA` stands for a carbon and not a calcium or vice-versa).

I've already discussed this in a previous issue and I'll try to dig it out again, and a general solution needs to be found.

**Comment by stefdoerr** [comment]
In general? I don't see how it can be done. For PDBs it's specified by the alignment of the `[ ]CA` or `CA[ ]` as our code already tries to identify correctly

**Comment by j3mdamas** [comment]
I know it's very hard, hence why it's not done, but I will try to find a solution for it

**Comment by stefdoerr** [comment]
I actually believe it's impossible. How do you want to guess the element of an atom from it's 3d coordinates? The amount of information you get from arbitrary file formats is limited to each file format. If that format gives incomplete information you can't do anything about it.

**Comment by j3mdamas** [comment]
I don't know yet.

**Comment by stefdoerr** [comment]
Closed by this https://github.com/Acellera/htmd/pull/713

**Comment by j3mdamas** [comment]
Don't close this one

**Comment by stefdoerr** [comment]
Why?
