### ISSUE TITLE
Problems in parameterization of charged ligands

### ISSUE THREAD

**Issue by marionatf** [Acellera/htmd#57]
Hello,
We are parameterizing charged ligands following the script:

```python
from htmd import *
from htmd.parameterize import Configuration, Parameterisation
glutamate = Molecule('./glutamate.mol2')
config = Configuration()
config.FileName = "./glutamate.mol2"
config.JobName = "glu-1"
config.NetCharge = "-1"
param = Parameterisation(config=config)
paramfiles = param.getParameters()
shutil.copyfile(paramfiles['RTF'], "glutamate.rtf")
shutil.copyfile(paramfiles['PRM'], "glutamate.prm")
shutil.copyfile(paramfiles['PDB'], "glutamate-final.pdb")
```

But we don't know if we are doing it right, since sometimes it gives error and other times takes a really long time, so we are not sure.
The error we obtain is:
ValueError: run(): Step [preoptimize] did not produce the expected output: ['mol-opt.xyz'] in directory /home/student1/htmd/gaamp/ben-6/010-preoptimize

We think the problem may be at config.NetCharge = "-1"  , is it correct? 
And for positive charged ligands should we put "+1", or just "1"?

Thanks.

**Comment by j3mdamas** [comment]
Hi,

Glutamate should in theory be -1. How is it protonated? The preoptimization can be erroring due to a charge and spin that is not allowed for that atom configuration.

See here:
![](http://butane.chem.uiuc.edu/cyerkes/Chem104ACSpring2009/Lecture_Notes_104/27-7.gif)

**Comment by j3mdamas** [comment]
I guess this is solved, correct @marionatf?

**Comment by marionatf** [comment]
yes, thank you!
