### ISSUE TITLE
Uniformize and Improve batch queues LsfQueue, SlurmQueue and PbsQueue

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#575]
Follows from https://github.com/Acellera/htmd/issues/525#issuecomment-369069037

- [ ] Create helper class `_BatchQueue`
    - [ ] Centralize common methods
    - [ ] Set abstract methods and properties that need to be implemented on child classes
- [ ] Child `LsfQueue`, `SlurmQueue` and `PbsQueue` on `_BatchQueue`
    - [ ] Fix these classes according to what was implemented on `_BatchQueue`
- [ ] Create tests for batch queues
    - [ ] Set `_testmode=Bool` hidden argument to bypass `_findbinary`
    - [ ] Create instatiation tests (probably use the object `__dict__` to compare?)
    - [ ] Figure out if the methods that use binaries can be tested or not (probably not...)
    - [ ] Test `_createJobScript` (diff files to see if results are the same)

**Comment by stefdoerr** [comment]
Already all been moved to jobqueues repo and works as expected.
