### ISSUE TITLE
Finish 1.12.x release

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#583]
- [x] Fix repository `README.md` (old links, and https://github.com/Acellera/htmd/issues/514#issuecomment-373086049)
- [x] Update headers from 2017 to 2018
~- [ ] Create release notes~ -> after release

**Comment by j3mdamas** [comment]
these are aesthetic changes, I'll push directly, if there's no problem

**Comment by stefdoerr** [comment]
nah
