### ISSUE TITLE
NGLview is not showing structures

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#584]
I still don't understand why, probably a browser problem. I've opened this issue https://github.com/arose/nglview/issues/733.

I'll try to see if I can get more information, but it needs a solution before 1.12.x is released.

**Comment by j3mdamas** [comment]
It's better now, I've been able to fix it and have some nice tips for when things are not working.

We probably need to either use the conda-forge one, or use the bioconda one (which they recommend) but block some dependencies on some versions.

There is still a bug on showing a black background, let's see if I can solve it.

**Comment by j3mdamas** [comment]
Seems like in Firefox I do not experience the problem with black background. I'm going through the tutorials and see how they are looking. I'm also probably changing the nglview copy on acellera channel from bioconda/omnia to conda-forge, which is not recommended, but at least has the correct dependencies (see discussion in arose/nglview#733)

**Comment by j3mdamas** [comment]
For some reason, using the nglview from conda-forge causes Jupyter notebook kernel instabilities (problems starting, crashing all the time) which I cannot sort out (probably due to the ipykernel older version that nglview from conda-forge is requiring).

I finally found a solution:
- [x] Pin the `ipywidgets ==7.0.0` and `widgetsnbextension==3.0.0` on HTMD dependencies (even though widgetsnbextension is not even an HTMD dependency)
- [x] Manually upload `widgetsnbextension==3.0.0` (copy from conda-forge) to acellera channel, because that particular version does not exist on defaults (this will not be included in the )
- [ ] Fix everything that works with the `DEPENDENCIES` file (basically the meta.yml generator for htmd-deps)

Will make a PR as soon as I do the last point.

**Comment by cesaravila79** [comment]
Hi Joao,
So, I am trying to reopen this issue since I am facing the same problem on the latest release of HTMD. I have read your post on https://github.com/arose/nglview/issues/733 so I checked the version of the packages installed in conda
 ipykernel                 5.1.0            py36h39e3cac_0  
ipywidgets                7.0.0            py36h7b55c3a_0  
nglview                   1.0                      py36_1    acellera
notebook                  5.7.8                    py36_0  
widgetsnbextension        3.0.0                    py36_0    acellera

The ipykernel is different from the version recommended in the post. Could this be the reason?

I also tried 
jupyter-nbextension enable nglview --py --sys-prefix
with no success. 
Let me know if you need more info on the problem. 
Cheers, 
Cesar

**Comment by stefdoerr** [comment]
Hey Cesar, Joao has left Acellera so I'll take it on. What exactly happens, does it open a viewer but it's empty or it fails to even open the viewer? Can you open the browser console and see if javascript has thrown some error? You might need to refresh the page after opening the console and re-run the commands.

**Comment by cesaravila79** [comment]
Hi Stefan, 
The problem arises when I try to play with the visualization notebook from 
https://software.acellera.com/docs/latest/htmd/tutorials/visualization.html
When I execute the 3rd notebook cell
mol = Molecule('3PTB') # reloading the molecule
mol.view(gui=False)

I get a blank space. If i use (gui=True), I get the menu but the molecule does not show up. 
The browser console shows

Could not instantiate widget extension.js:62763:33
    _make_model http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js?v=20190729114758:62763
    step http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js?v=20190729114758:62533
    verb http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js?v=20190729114758:62514
    rejected http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js?v=20190729114758:62506
<unavailable> extension.js:21509:21
    promiseRejection http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js?v=20190729114758:21509
Couldn't process kernel message Class NGLModel not found in module nglview-js-widgets main.min.js:37995:42
    _msg_queue http://localhost:8888/static/notebook/js/main.min.js?v=eef572336006937e9a017afbdebc65fe:37995
uncaught exception: Class NGLModel not found in module nglview-js-widgets

**Comment by stefdoerr** [comment]
This seems an error of the installation of nglview. I would create a new clean conda environment and try there.

**Comment by stefdoerr** [comment]
I checked and it works fine here with htmd 1.15.2 and nglview 1.0 once you run the `jupyter-nbextension enable nglview --py --sys-prefix` command

**Comment by cesaravila79** [comment]
Hi Stefan, 
Thanks for your support. It is working now. 
I made a fresh new install of conda, executed the command 
nbextension enable nglview --py --sys-prefix 

and then 
jupyter notebook
