### ISSUE TITLE
Travis refactoring with Docker images

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#609]
OK, I'm done with this.

I'm going to create a branch to change the `.travis.yaml` in order to reduce the time taken to do the tests.

Approach:
- [x] Register on Docker Hub --> created Acellera organization as well
- [ ] Create `docker-recipes` repo for a daily build of an image with centos6 + conda with htmd dependencies
- [ ] Change Travis trigger to use our pre-built docker image instead of building it on every commit.

Expected outcome:
Reduce the time-to-build by at least 15 minutes

**Comment by stefdoerr** [comment]
Oh dear god yes!

**Comment by j3mdamas** [comment]
By the way, this is only possible because we're just supporting Linux currently.

**Comment by stefdoerr** [comment]
I'll drop this issue since we are splitting repos, htmdmol is separate and parameterize will leave sooner or later.
