### ISSUE TITLE
Queue failures improvements

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#610]
Taken from old PR #504 and old issue #491 (which will be closed)

This started being addressed on `fix_queuefailures` (that branch needs to be updated).

- [x] Failures of submission do not inform the user nicely about the reason for failure (normally the submission commands throw to stdout/stderr the reason the job was not submitted)
- [ ] Management of scratch/temporary space (create variables in Queues, manage those variables appropriately, make relevant applications (Psi4, Gaussian) use those variables, cleaning of the temporary files of any exit, successful or unsuccessful) (#491)
- [ ] Creation of sentinel file on any exit, successful or unsuccessful (solves hangs of processes requiring sentinel files; if cleaning is figured out on the point above, just replicate)

**Comment by stefdoerr** [comment]
I think we can close this until we have a request or bug. @j3mdamas opinions?

**Comment by j3mdamas** [comment]
Fine for me. Thanks.
