### ISSUE TITLE
dock function not working

### ISSUE THREAD

**Issue by marionatf** [Acellera/htmd#62]
Yesterday dock function was working but now it gives this error:
```python
from htmd import *
prot = Molecule('ethtryp/trypsin.pdb')
prot.center()
lig = Molecule('ethtryp/ethanol.pdb')
print(lig,prot)
poses, scores = dock(prot, lig)
```

```
/home/student1/miniconda3/bin/htmd_babel: line 2: /usr/bin/htmd_babel.bin: El fitxer o directori no existeix
/home/student1/miniconda3/bin/htmd_babel: line 2: /usr/bin/htmd_babel.bin: El fitxer o directori no existeix
Traceback (most recent call last):
  File "docking-simulation-generators.py", line 20, in <module>
    poses, scores = dock(prot, lig)
  File "/home/student1/miniconda3/lib/python3.5/site-packages/htmd/dock.py", line 103, in dock
    raise NameError('Ligand could not be converted to PDBQT')
NameError: Ligand could not be converted to PDBQT
```
Thanks,
Mariona

**Comment by mj-harvey** [comment]
Mariona,

You need to ensure that the PATH environment variable includes /home/student1/miniconda3/bin and gives priority to that over /usr/bin . 

Matt

**Comment by j3mdamas** [comment]
Mariona,

It's what Matt said. Probably because you installed `openbabel`.

On Tue, Jun 14, 2016 at 1:37 PM, M J Harvey <notifications@github.com>
wrote:

> Mariona,
>
> You need to ensure that the PATH environment variable includes
> /home/student1/miniconda3/bin and gives priority to that over /usr/bin .
>
> Matt
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/62#issuecomment-225855375>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AKTzQs2gSD9--gNxBXsTTUlVMv9BibMbks5qLpJ3gaJpZM4I1NmN>
> .
>



--

**Comment by giadefa** [comment]
I swapped the PATHs so that ACEMD was calling the correct version. This has
messed up other things.

I'll try to fix it later.

g

On 14 June 2016 at 13:39, João M. Damas <notifications@github.com> wrote:

> Mariona,
>
> It's what Matt said. Probably because you installed `openbabel`.
>
> On Tue, Jun 14, 2016 at 1:37 PM, M J Harvey <notifications@github.com>
> wrote:
>
> > Mariona,
> >
> > You need to ensure that the PATH environment variable includes
> > /home/student1/miniconda3/bin and gives priority to that over /usr/bin .
> >
> > Matt
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/Acellera/htmd/issues/62#issuecomment-225855375>, or
> mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/AKTzQs2gSD9--gNxBXsTTUlVMv9BibMbks5qLpJ3gaJpZM4I1NmN
> >
> > .
> >
>
>
>
> --
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/62#issuecomment-225855847>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHaqOpWMf-GsJVhRp49VxvP36L0Biod-ks5qLpMKgaJpZM4I1NmN>
> .
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>

**Comment by j3mdamas** [comment]
@marionatf, is this still an issue with our feedback?

**Comment by alejandrovr** [comment]
Your feedback helped. We have done: 
export PATH=/home/student1/miniconda3/bin:$PATH
and it has worked. But as Gianni said, maybe this change has broken other things. We will inform you if it is the case.

Thanks!

**Comment by giadefa** [comment]
I have fixed it

On 14 June 2016 at 16:30, alejandrovr <notifications@github.com> wrote:

> Your feedback helped. We have done:
> export PATH=/home/student1/miniconda3/bin:$PATH
> and it has worked. But as Gianni said, maybe this change has broken other
> things. We will inform you if it is the case.
>
> Thanks!
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/62#issuecomment-225899633>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHaqOh5SlE2Ry3OmhYD6LUAK-Pwtu_d9ks5qLrsVgaJpZM4I1NmN>
> .
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>
