### ISSUE TITLE
acemdhtmd

### ISSUE THREAD

**Issue by giadefa** [Acellera/htmd#63]
* rename acemd to acemdhtmd
* require the new version in conda
* fix AcemdLocal
* test it

**Comment by stefdoerr** [comment]
Done from my side

**Comment by j3mdamas** [comment]
Any news on this?

**Comment by mj-harvey** [comment]
On today's todo list. Not got there just yet.

On 17 June 2016 at 14:23, João M. Damas <notifications@github.com> wrote:

> Any news on this?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/63#issuecomment-226767460>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHh-DdZ_S1aOWloErLDAsboW1bhdoU7Mks5qMp-5gaJpZM4I1S7j>
> .
>



-- 
<https://www.acellera.com>


<https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>
    <https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/acellera>
<https://www.acellera.com/md-simulation-blog-news/>     [image:
skype:acellera] <http://is.gd/1eXkbS>

**Comment by j3mdamas** [comment]
Thanks Matt :)

On Fri, Jun 17, 2016 at 3:25 PM, M J Harvey <notifications@github.com>
wrote:

> On today's todo list. Not got there just yet.
>
> On 17 June 2016 at 14:23, João M. Damas <notifications@github.com> wrote:
>
> > Any news on this?
> >
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/Acellera/htmd/issues/63#issuecomment-226767460>, or
> mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/AHh-DdZ_S1aOWloErLDAsboW1bhdoU7Mks5qMp-5gaJpZM4I1S7j
> >
> > .
> >
>
>
>
> --
> <https://www.acellera.com>
>
>
> <
> https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor
> >
> <https://www.youtube.com/user/acelleracom>
> <https://www.linkedin.com/company/acellera>
> <https://www.acellera.com/md-simulation-blog-news/> [image:
> skype:acellera] <http://is.gd/1eXkbS>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/63#issuecomment-226768059>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AKTzQi65gWv9vKsZNZ1njwwgu_yAlqPvks5qMqBkgaJpZM4I1S7j>
> .
>



--
