### ISSUE TITLE
Integration of ACEMD3

### ISSUE THREAD

**Issue by raimis** [Acellera/htmd#632]
- [x] Merge ACEMD2 and ACMED3 classes
  - [x] #707 (@stefdoerr and @j3mdamas)
  - [x] https://github.com/Acellera/acemd3/pull/36 (@stefdoerr )
~- [ ] HTMD uses ACEMD3~
~- [ ] Print a warning to an user that ACEMD3 is used by default~
~- [ ] Implement a `version` argument to switch back to ACEMD2~
~- [ ] Update documentation, test, and tutorials (@cuzzo87)~

Solves https://github.com/Acellera/acemd3/issues/59

**Comment by raimis** [comment]
@stefdoerr I think you are the best for this task as you know HTMD and ACEMD3. We will discuss with @j3mdamas how to proceed then you are back.

**Comment by stefdoerr** [comment]
If we really want to do this though we would need to do mappings of old commands to new as Acemd3 does and errors for non-existent ones. Overall I am not a big fan of the `Acemd` class and it has always confused me on how it should be used and what `setup` does with the files. I would ideally prefer some redesigning of it but if we are really time-constrained I can try to merge the two.

**Comment by raimis** [comment]
For ACEMD release, we need something that works. For HTMD 1.14 release, it should work and have a good design.

**Comment by cuzzo87** [comment]
@stefdoerr @j3mdamas 
I agree with joao. We should take some time to redesign it all together. After that I think it would be easier also to manage sub tasks.

**Comment by j3mdamas** [comment]
This is now #707, and it's about to get merged.

Right now, ACEMD3 won't be used by default. I think that should be done only when it is a released product. Just needs some coordination. Also, it needs to follow this comment: https://github.com/Acellera/htmd/pull/656#issuecomment-385476663. We'll do change to ACEMD3 together with deprecation of Protocols.
