### ISSUE TITLE
2018-04-11 11:02:43,713 - htmd.molecule.readers - WARNING - No time information read from output.xtc. Defaulting to 0.1ns framestep.

### ISSUE THREAD

**Issue by giadefa** [Acellera/htmd#642]
This becomes too much if it is in the reader. It is safe to read an xtc without such information. 
It should be Model that warns, not the reader.

**Comment by giadefa** [comment]
Also the default should probably be 0 not 0.1 from the reader.
The reader is taking care of something that really is a requirements for higher level objects

**Comment by stefdoerr** [comment]
Good point. We should crash instead of default when the timesheet is needed. I'll take a look at it

On April 11, 2018 11:17:24 AM GMT+02:00, Gianni De Fabritiis <notifications@github.com> wrote:
>Also the default should probably be 0 not 0.1 from the reader.
>The reader is taking care of something that really is a requirements
>for higher level objects
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Acellera/htmd/issues/642#issuecomment-380385186

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by j3mdamas** [comment]
OK, I assign this one to you @stefdoerr

**Comment by stefdoerr** [comment]
This has been merged already. I opened a new PR for Gianni's extra comments on being independent of fstep
