### ISSUE TITLE
use Conda-forge msmtools

### ISSUE THREAD

**Issue by giadefa** [Acellera/htmd#644]
You are still using msmtools from the deprecated Omnia channel. Please switch to conda-forge to catch future updates.
In order to do so please set conda-forge channel to highest priority by:

    conda config --add channels conda-forge

and update this package by:

    conda update msmtools

**Comment by j3mdamas** [comment]
They did a new build of `msmtools` that does not depende on numpy versions anymore. Let me try to upload that one. Nonetheless, until a version number really changes (from 1.2.1), older installations will always keep that one unless there is a forced installation.

**Comment by j3mdamas** [comment]
Actually, not need to update the builds. The current one, with a fresh installation, already does not show this message. So, I think we can close this.
