### ISSUE TITLE
ite-packages/pyemma/__init__.py:91: UserWarning: You are not using the latest release of PyEMMA. Latest is 2.5.2, you have 2.4.

### ISSUE THREAD

**Issue by giadefa** [Acellera/htmd#645]
within HTMD we decide what version to use, so these messages should not appear

**Comment by stefdoerr** [comment]
True true :) will fix

On April 11, 2018 12:11:36 PM GMT+02:00, Gianni De Fabritiis <notifications@github.com> wrote:
>within HTMD we decide what version to use, so these messages should not
>appear
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Acellera/htmd/issues/645

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by j3mdamas** [comment]
It's an easy fix.

**Comment by j3mdamas** [comment]
Meh. It should be easy but I can't call the argument to silence it without importing pyemma. I've asked them about the best way to do it: https://github.com/markovmodel/PyEMMA/issues/1287

**Comment by j3mdamas** [comment]
It's easy by just doing:

```python
import warnings
with warnings.catch_warnings():
    warnings.simplefilter('ignore', category=UserWarning)
    #do the imports here
```

But we do so many separate pyemma imports, that doing this wrap on all of them is kind of repetition. I was trying to see if I could wrap the import inside a function/decorator, but only using `exec()`:

```python
def wrap_import(statement):
    import warnings
    with warnings.catch_warnings():
        warnings.simplefilter('ignore')
        exec(statement)
wrap_import('import pyemma')
```

But @stefdoerr already told me not to use `exec()`. What do you think @stefdoerr?

**Comment by stefdoerr** [comment]
Do they use warning or logger? You can disable specific logger warnings. I think you can also disable warning warnings. I think I did it in metricdata.cluster to get rid of sklearn warnings

On April 11, 2018 5:40:23 PM GMT+02:00, "João M. Damas" <notifications@github.com> wrote:
>It's easy by just doing:
>
>```python
>import warnings
>with warnings.catch_warnings():
>    warnings.simplefilter('ignore', category=UserWarning)
>    #do the imports here
>```
>
>But we do so many separate pyemma imports, that doing this wrap on all
>of them is kind of repetition. I was trying to see if I could wrap the
>import inside a function/decorator, but only using `exec()`:
>
>```python
>def wrap_import(statement):
>    import warnings
>    with warnings.catch_warnings():
>        warnings.simplefilter('ignore')
>        exec(statement)
>wrap_import('import pyemma')
>```
>
>But @stefdoerr already told me not to use `exec()`. What do you think
>@stefdoerr?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Acellera/htmd/issues/645#issuecomment-380498514

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by j3mdamas** [comment]
warnings. Did you see my proposal? I can check what you did for scikitlearn.

**Comment by j3mdamas** [comment]
I've just talked with @stefdoerr and he suggested a fake import pyemma file which has this wrap and every pyemma import imports that file instead. seems the cleanest hack. I'll implement it.

**Comment by stefdoerr** [comment]
Taking some stuff off of you ;)

**Comment by j3mdamas** [comment]
this is done
