### ISSUE TITLE
AMBER example

### ISSUE THREAD

**Issue by raimis** [Acellera/htmd#653]
We need an AMBER example for the trypsin-benzamidine tutorial (https://acellera.mojohelpdesk.com/ma/#/tickets/18958762).

- [x] Update https://github.com/Acellera/htmd/blob/rel-1.12.x/tutorials/system-building-protein-ligand.ipynb
- [x] Make PR on `rel-1.12.x`
- [x] Update online (@j3mdamas )

**Comment by stefdoerr** [comment]
You just swap `charmm.build` with `amber.build`. That's the whole idea of the builders, do be easily swappable. I don't think we need an extra tutorial on it.

**Comment by stefdoerr** [comment]
Obviously if it doesn't build with the default FF files you might need to add the ones needed, but that depends on each system and we cannot cover that.

**Comment by j3mdamas** [comment]
Maybe we can update just the end of the tutorial, to explain a bit that both CHARMM and Amber can be used, do some considerations about the file formats (that we may need ligand parameters in those different formats), and do one example for each?

I'll add myself to the assignees, as I can do the last part. @cuzzo87, do you want me to do it all? It's fine for me.

**Comment by stefdoerr** [comment]
Yes I agree with @j3mdamas . A comment on the current tutorial would be enough.

**Comment by cuzzo87** [comment]
@j3mdamas as  you want.If you can manage it would be easier also for publish it.Let me know what you prefer

**Comment by j3mdamas** [comment]
@raimis can you give a deadline for this?

**Comment by raimis** [comment]
Franck wanted during this week, if possible.

**Comment by j3mdamas** [comment]
OK, so I can organize myself. Thanks

**Comment by j3mdamas** [comment]
@cuzzo87, just sharing the load.
The current tutorial is just fine until the end. In the end, when we parameterize for charmm, we can have another option to parameterize for amber, but one needs to talk about and pass the right parameter files (in the correct formats)

**Comment by cuzzo87** [comment]
ipynb modified
PR done #667 

Update online --> @j3mdamas

**Comment by j3mdamas** [comment]
I'll be releasing two new HTMD versions, and publishing documentation on both. I'll close this issue afterwards

**Comment by raimis** [comment]
#667 has been merged, but the tutorial on the website is still no updated. @j3mdamas when are you planning the release?

**Comment by j3mdamas** [comment]
Depending on https://github.com/Acellera/htmd/issues/660

**Comment by raimis** [comment]
That stuff is already stuck for 24 days.

**Comment by j3mdamas** [comment]
agreed. working on it.

**Comment by raimis** [comment]
The documentation of the stable release has been updated (https://software.acellera.com/docs/stable/htmd/tutorials/system-building-protein-ligand.html), but the latest release has an old version (https://software.acellera.com/docs/latest/htmd/tutorials/system-building-protein-ligand.html).

@j3mdamas  is it intentional?

**Comment by j3mdamas** [comment]
Done: https://software.acellera.com/docs/latest/htmd/tutorials/system-building-protein-ligand.html

**Comment by stefdoerr** [comment]
we might want to truncate the outputs of the calls a bit... I think
nbconvert can do that

**Comment by stefdoerr** [comment]
Nah I like the functions themselves but the printing is 4 screens long
