### ISSUE TITLE
Installing htmd failed using anaconda 3

### ISSUE THREAD

**Issue by zhenglz** [Acellera/htmd#654]
Trying to install htmd using the command "conda install -c acellera -c psi4 htmd" with python 3.6 on a GPU cluster. 
"Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:39:56)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
"

However, it keeps giving the following error massage:

'''
    widgetsnbextension: 3.2.1-py36_0          conda-forge

Proceed ([y]/n)? y

Linking packages ...
Error: Error: post-link failed for: conda-forge::widgetsnbextension-3.2.1-py36_0    
'''

The installation failed then. when type "import htmd", showing "No such module " error.

Any solution to this problem?

**Comment by tonigi** [comment]
Just a guess: is gcc installed?

**Comment by zhenglz** [comment]
Hi @j3mdamas Thanks for your suggestions. Problem solved now.

Yes, I installed miniconda3 and tried to install acemd again, and it works fine so far.

@tonigi Thanks for your reply. I think we have gcc installed in the system.

**Comment by j3mdamas** [comment]
Perfect
