### ISSUE TITLE
htmd-data versioning

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#660]
As I commented on Slack already: we need to move htmd-data out of htmd repository (a bit like we have the htmd-lib now). Git sub-moduling (or sub-tree) can be used to keep a pointer to that new repository but it isn't necessary.

Any alternative to this mode of action?

@stefdoerr @giadefa

**Comment by stefdoerr** [comment]
Why don't you release a `htmd-data-stable` from the stable branch? The stable branch already can have it's own data since it's a branch, so this should solve the problems.

**Comment by j3mdamas** [comment]
I'm not a particular fan of having two different packages (`htmd-data` and `htmd-data-stable`) dependencies on the same project (specially considering you could have both installed and you don't know which data you actually have), but I think it's the best solution (actually, I don't what I proposed even works)

**Comment by j3mdamas** [comment]
OK, I'm finishing a proposal to fix this is a PR. Hopefully it gets accepted.

One thing that I noticed while doing this, is that we're also setting the wrong htmd-data dependency when building in Travis: the htmd-deps package meta.yaml is generated before the current htmd-data is built and installed, meaning we test against the current but ship and set as dependency the version before the current. Fixing that on this PR as well but mentioning it in case the PR is not accepted it needs to be fixed separately.
