### ISSUE TITLE
error at importing on new install

### ISSUE THREAD

**Issue by giadefa** [Acellera/htmd#664]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-0b28f71ac4f9> in <module>()
----> 1 from htmd.ui import *

~/miniconda3/lib/python3.6/site-packages/htmd/ui.py in <module>()
     19 from htmd.projections.metrictmscore import MetricTMscore
     20 from htmd.projections.metric import Metric
---> 21 from htmd.projections.tica import TICA
     22 from htmd.projections.kmeanstri import KMeansTri
     23 from htmd.projections.gwpca import GWPCA

~/miniconda3/lib/python3.6/site-packages/htmd/projections/tica.py in <module>()
      9 from htmd.util import _getNcpus
     10 from htmd.projections.metric import Metric, _projectionGenerator
---> 11 from htmd.units import convert as unitconvert
     12 from joblib import Parallel, delayed
     13 import logging

~/miniconda3/lib/python3.6/site-packages/htmd/units.py in <module>()
      4 # No redistribution in whole or part
      5 #
----> 6 from pint import UnitRegistry
      7 import numpy as np
      8 

ModuleNotFoundError: No module named 'pint'

but pint is installed

**Comment by j3mdamas** [comment]
Try it again (maybe something did not go well). If it does not work, let me
know and I'll investigate when I have some time.

**Comment by stefdoerr** [comment]
I mean it's impossible to replicate on other systems, otherwise we would
have seen it before and it would not pass travis either. So I concurr with
Joao. Give it a few more tries.

Having said that I remember a similar problem when conda installed a
package for 2.7 and the you tried to import it from 3.6 python. It would
claim it was installed but then would not find it

**Comment by giadefa** [comment]
close. Today it works
