### ISSUE TITLE
htmd.mutualinformation needs to be fixed: networkx method was not available

### ISSUE THREAD

**Issue by cuzzo87** [Acellera/htmd#669]
Trying to load ``` from_pandas_dataframe``` from ``` networkx`` it complains that this method does not exists anymore.  Anyway from their documentation:
https://networkx.github.io/documentation/stable/release/release_2.1.html
* [#2811] Removed to_pandas_dataframe and from_pandas_dataframe, please use to_pandas_adjacency, from_pandas_adjacency, to_pandas_edgelist, or from_pandas_edgelist. (https://github.com/networkx/networkx/pull/2811)

```
In [2]: import networkx as nx
In [3]: nx.from_pandas_dataframe
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-14e96fa3f8ed> in <module>()
----> 1 nx.from_pandas_dataframe

AttributeError: module 'networkx' has no attribute 'from_pandas_dataframe'
```

**Comment by j3mdamas** [comment]
@cuzzo87 is this something urgent? I've marked it as low priority.
