### ISSUE TITLE
update rdkit and boost?

### ISSUE THREAD

**Issue by raimis** [Acellera/htmd#670]
HTMD depends on rdkit, rdkit depends on Boost. Our channel contains Boost package, which is incomplete. I guess, only the files need for rdkit are there. rdkit package is pinned to a specific (1.63.0) Boost version, so it is not possible to upgrade to a complete package.

This effectively will screw up or make installation impossible of any other package depending on Boost.

Possible resolution: package a complete Boost. I suspect, the current package was taken from conda-forge and trimmed down.

**Comment by giadefa** [comment]
is it worth aborting using boost as @mj-harvey suggested?

**Comment by raimis** [comment]
I don't know another cross-platform (Linux, Windows) replacement.

**Comment by j3mdamas** [comment]
we can try to update our rdkit, which no longer uses the boost from its on channel but the one from conda-forge

**Comment by raimis** [comment]
The problem might be that the Boost package from `conda-forge` pulls it own dependencies of numpy and other libraries, which might make a mess with the main channel.

**Comment by j3mdamas** [comment]
I see your point. How high priority is this? I assume low.

**Comment by stefdoerr** [comment]
rdkit has been updated. boost is not being used by htmd or rdkit anymore apparently
