### ISSUE TITLE
license

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#68]
I've seen that the first time a user calls htmd is requested to fill the affiliation/name/city/email information for the academic license.  Is this what we should expect?

Because today a user filled that information, and after that wasn't successfully registered, so now the information is requested again every time htmd is called. 

Thanks a lot,
Noelia

**Comment by giadefa** [comment]
no, we need to improve this. Thanks for pointing it out.

On 17 June 2016 at 21:49, Noelia Ferruz <notifications@github.com> wrote:

> I've seen that the first time a user calls htmd is requested to fill the
> affiliation/name/city/email information for the academic license. Is this
> what we should expect?
>
> Because today a user filled that information, and after that wasn't
> successfully registered, so now the information is requested again every
> time htmd is called.
>
> Thanks a lot,
> Noelia
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/68>, or mute the thread
> <https://github.com/notifications/unsubscribe/AHaqOiuKM54zMc0xKSmrK5a5XH-hI7r4ks5qMvpLgaJpZM4I4rRh>
> .
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>

**Comment by noeliaferruz** [comment]
Aah ok I actually thought it was something much complicated related with the permissions of some users... much better.

**Comment by giadefa** [comment]
maybe that's also the case, but he should not be asked to accept an
academic license.

On 17 June 2016 at 22:46, Noelia Ferruz <notifications@github.com> wrote:

> Aah ok I actually thought it was something much complicated related with
> the permissions of some users... much better.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/68#issuecomment-226877406>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHaqOnydayEfurhSYv_ArSkgDMW01RR7ks5qMweogaJpZM4I4rRh>
> .
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>

**Comment by giadefa** [comment]
@mj-harvey any idea on the specific problem?

**Comment by mj-harvey** [comment]
At the moment  the htmd-pro package erroneously includes the academic
license. Need to fix that.

On 17 June 2016 at 21:49, Gianni De Fabritiis <notifications@github.com>
wrote:

> @mj-harvey <https://github.com/mj-harvey> any idea on the specific
> problem?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/68#issuecomment-226878093>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHh-DSvGy8Sut8LMsn5CmBTmpLFuvGz4ks5qMwhxgaJpZM4I4rRh>
> .
>



-- 
<https://www.acellera.com>


<https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>
    <https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/acellera>
<https://www.acellera.com/md-simulation-blog-news/>     [image:
skype:acellera] <http://is.gd/1eXkbS>

**Comment by mj-harvey** [comment]
Opening a new issue that better reflects the thing to do
