### ISSUE TITLE
Improvements for parameterize/queues

### ISSUE THREAD

**Issue by stefdoerr** [Acellera/htmd#680]
- [ ] Make names more sensible to distinguish them on queueing systems (i.e. for parameterize add `prm` at the beginning, or anything the user specifies?)
- [x] Queue.wait should have an option for reporting current `inprogress` every `x` minutes. Dihedral jobs with thousands of angles/dihedrals look quite dead after a few days.

@raimis you think you could do number 1?

**Comment by raimis** [comment]
Ideally, the job name should identify molecule, dihedral, and rotomer index, but in practice queue systems limit job names to a few characters. I'll think about a naming scheme.

**Comment by j3mdamas** [comment]
The current name is automatically generated through `_autoJobName`. Example for LSF:

https://github.com/Acellera/htmd/blob/584eb2af1570861e268492e46811be2456a161d9/htmd/queues/lsfqueue.py#L214-L215

If we draw the parallelism with adaptive, where a single jobname is used for all epochs and replicas, we could do the same in parameterize cli:

```python
SimQueue.jobname = args.filename.split('.')[0]
```
If one wants, we can also add `-min`, `-esp`, and `-dihe` to the end, if necessary to distinguish between all.

**Comment by j3mdamas** [comment]
For 2, here:
https://github.com/Acellera/htmd/blob/584eb2af1570861e268492e46811be2456a161d9/htmd/queues/simqueue.py#L75
we can add a `report=None` argument, which throws a logging message every `report` seconds, which we can set in the parameterize cli.

**Comment by stefdoerr** [comment]
For 2: https://github.com/Acellera/htmd/compare/waitprogress?expand=1

**Comment by stefdoerr** [comment]
#1 is very queue specific. Considering we have PM now we will just solve this there
