### ISSUE TITLE
Logging setup failed after installation

### ISSUE THREAD

**Issue by herbert0525** [Acellera/htmd#691]
Hi, we believe we've followed instruction of the documentation during the process of installation, but the error 'Logging setup failed' continued to occur as we tried the import command. So could you inform us  of what the matter was please, was our registration invalid? If so, what is the correct output of the registration command?

**Comment by stefdoerr** [comment]
No, this should be unrelated to registration. Could you try in ipython
```python
from htmd.home import home
from glob import glob
print(home())
print(glob(home()+'/logging.ini'))
```
You could also ignore it as it's a warning, not an error. It will just use the default logging behaviour of python which might be either too verbose or too little verbose :P But better to find out what causes it anyway.

**Comment by herbert0525** [comment]
@stefdoerr Yeah, your advice works in ipython. Nevertheless, does there exist a way to solve this problem just in Python, not ipython, thanks.

**Comment by j3mdamas** [comment]
Hi @herbert0525,

You mean the logging works on ipython interpreter but not on python interpreter?

What is your output of `os.path.join(htmd.home.home(), 'logging.ini')`?

Joao

**Comment by herbert0525** [comment]
@j3mdamas In Python interpreter, the output of your advice is "name 'htmd' is not defined". Besides, in ipython, we are able to import htmd, but 'from htmd.ui import *' does not work, traceback is 'No module named 'htmd.ui', do you have any solutions, thanks

**Comment by stefdoerr** [comment]
Sounds like a failed conda installation to me. I would advise to make a new miniconda install from scratch.

**Comment by j3mdamas** [comment]
@herbert0525 then I don't understand how the `Logging setup failed` was being achieved.

Rather than a failed conda installation, it seems like the conda environment is not even activated, which can be verified by doing:
```
which python
which ipython
which conda
```
João

**Comment by j3mdamas** [comment]
Dear @herbert0525,

We cannot help without further feedback. Please see my previous message.

I'll close this for now, please feel free re-open it if necessary.

Best,
João
