### ISSUE TITLE
Errors in Molecule class

### ISSUE THREAD

**Issue by AspirinCode** [Acellera/htmd#694]
Following the HTMD tutorial online http://software.acellera.com/docs/latest/htmd/tutorials/getting-started-with-htmd.html and ran this:

from htmd.ui import *
mol = Molecule('3PTB')

and got this error

ValueError                                Traceback (most recent call last)
<ipython-input-2-3958d2af6d28> in <module>()
----> 1 mol = Molecule('3PTB.pdb')

/usr/anaconda3/lib/python3.6/site-packages/htmd/molecule/molecule.py in __init__(self, filename, name, **kwargs)
    195 
    196         if filename:
--> 197             self.read(filename, **kwargs)
    198             if isinstance(filename, str):
    199                 self.topoloc = os.path.abspath(filename)

/usr/anaconda3/lib/python3.6/site-packages/htmd/molecule/molecule.py in read(self, filename, type, skip, frames, append, overwrite, keepaltloc, _logger)
    852             for rr in readers:
    853                 try:
--> 854                     to, tr = rr(fname, frame=frame, topoloc=tmppdb)
    855                 except FormatError:
    856                     continue

/usr/anaconda3/lib/python3.6/site-packages/htmd/molecule/readers.py in PDBread(filename, mode, frame, topoloc)
    592         mapserials = np.empty(np.max(serials)+1)
    593         mapserials[:] = np.NAN
--> 594         mapserials[serials] = list(range(np.max(serials)))
    595         for i in range(len(parsedbonds)):
    596             row = parsedbonds.loc[i].tolist()

ValueError: shape mismatch: value array of shape (1702,) could not be broadcast to indexing result of shape (1701,)

**Comment by j3mdamas** [comment]
Hi @AspirinCode,

That is very strange. Could you us more about your installation? Which version of HTMD do you have?

**Comment by j3mdamas** [comment]
also, please tell us the result of `conda list pandas`

**Comment by stefdoerr** [comment]
Seems like a really old HTMD version. This is a bug that's fixed probably a while ago.
The current code looks like this
```python
        mapserials = np.empty(np.max(serials)+1)
        mapserials[:] = np.NAN
        mapserials[serials] = list(range(len(serials)))
```
See how the last command has `len(serials)` instead of `np.max`? It used to be a bug.

@AspirinCode can you force-update htmd with `conda install -c acellera -c psi4 htmd=1.13.2`?

**Comment by j3mdamas** [comment]
If it's very old, I'd recommend a complete reinstallation. Furthermore, we always recommend using Miniconda3 instead of Anaconda3.

**Comment by AspirinCode** [comment]
delete anaconda，reinstall anaconda and htmd，solve it.

**Comment by j3mdamas** [comment]
Perfect!
