### ISSUE TITLE
HTMD: Logging setup failed

### ISSUE THREAD

**Issue by AspirinCode** [Acellera/htmd#695]
In [1]: from htmd.ui import *
HTMD: Logging setup failed

Please cite HTMD: Doerr et al.(2016)JCTC,12,1845.
https://dx.doi.org/10.1021/acs.jctc.6b00049
Documentation: http://software.acellera.com/
To update: conda update htmd -c acellera -c psi4

You are on the latest HTMD version (unpackaged : D:\Program Files\Anaconda3\lib\site-packages\htmd).

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-564a56619ae0> in <module>()
----> 1 from htmd.ui import *

ModuleNotFoundError: No module named 'htmd.ui'

how to solve it？

**Comment by j3mdamas** [comment]
From the path, it seems like you're in a Windows machine. We haven't supported Windows for a long time now.

**Comment by stefdoerr** [comment]
Admittedly we still have windows and mac versions on our download page. We
should remove those.

**Comment by alejandrovr** [comment]
Done!

**Comment by j3mdamas** [comment]
Closing this.

@AspirinCode please use HTMD on Linux. Thank you.
