### ISSUE TITLE
Segmentation Fault in 'Parameterise' doing the Tutorial

### ISSUE THREAD

**Issue by dprada** [Acellera/htmd#7]
Hi,

I followed the last htmd workshop via streaming and I was amazed by the work done by MJ Harvey with GAAMP in Parameterise. Yesterday I wanted to check if it is a tool we have to try in the lab and I found the following:

##### anaconda2/envs/mylab3/bin/htmd_babel 
After installing htmd with conda I had to change the `bin/htmd_babel` script to:
```
DIR="path_to/anaconda2/pkgs/htmdbabel-2.3.93-py35_0"; BABEL_DATADIR="$DIR/share/openbabel" "$DIR/bin/htmd_babel.bin" $@
```

##### parameterise/share/scripts/nonpolar/000-input
There is a typo in the openbabel output format `-o xyz` producing the error:
```
Failed to run parameterisation : run(): Step [input] did not produce the expected output: ['ligand.xyz'] in directory /home/diego/.htmd/gaamp/ethanol/000-input
```

##### htmd_babel.bin
The openbabel executable compiled in the htmd conda package gives the following message:
```
==============================
*** Open Babel Error  in RegisterOptionParam
  The number of parameters needed by option "r" in Point cloud on VDW surface differs from an earlier registration.
==============================
*** Open Babel Error  in RegisterOptionParam
  The number of parameters needed by option "x" in Point cloud on VDW surface differs from an earlier registration.
==============================
*** Open Babel Error  in RegisterOptionParam
  The number of parameters needed by option "s" in VDW surface in binary STL format suitable for 3D printing differs from an earlier registration.
==============================
*** Open Babel Error  in RegisterOptionParam
  The number of parameters needed by option "c" in VDW surface in binary STL format suitable for 3D printing differs from an earlier registration.
1 molecule converted
4 errors 9 info messages 6 audit log messages 
```
These errors disappear in this first step (000-input) when Parameterisation is invoked calling to my local babel. Is there any reason not to include openbabel as a dependency?

##### parameterise/share/scripts/nonpolar/scripts
The command `source ../routines` is not recognized by `/bin/sh` in those distributions where this is a symbolic link to `/bin/dash`. The header of the scripts were replaced with `#!/bin/bash`.

##### Segmentation Fault with parameterise/share/bin/equiv_atom
The tutorial stops in the step `030-generate_structure` with:
```
../routines: line 42: 21467 Segmentation fault      (core dumped) $@ > .$b.txt
```
Commenting the lines regarding `equiv_atom` produces a similar error this time with binary `add_tip3`.

What am I doing wrong? 

----

**Comment by giadefa** [comment]
Hi thanks. Sorry for the late replay.
We are soon making available the source code within htmd, but we are a bit overwhelmed at the moment.

**Comment by j3mdamas** [comment]
Hi @dprada,

The paramerize function will be soon fully documented according to the integration inside HTMD.

Some of your errors were related to babel rather than parameterize. We have fixed some errors in hmtd_babel. Can you update it and let us know if you still face these errors?

Thank you for your interest and patience,
João

**Comment by giadefa** [comment]
Still a problem or we can close it?

**Comment by mj-harvey** [comment]
close it

On 23 May 2016 at 13:48, giadefa <notifications@github.com> wrote:

> Still a problem or we can close it?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Acellera/htmd/issues/7#issuecomment-220970688>
>



-- 
<https://www.acellera.com>


<https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>
    <https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/acellera>
<https://www.acellera.com/md-simulation-blog-news/>     [image:
skype:acellera] <http://is.gd/1eXkbS>
