### ISSUE TITLE
support other traj types in simlist (I can't create a list of simulations with simlist)

### ISSUE THREAD

**Issue by lguarneros** [Acellera/htmd#70]
Hello!
I'm new working with HTMD, following the paper, I have a list of directories, each containing a single trajectory, but when I want read whit simlist, return a empty array.
This is my code:

```python
fsims = simlist(glob('./data/*/'), glob('./data/ionized.pdb'))
2016-06-20 18:37:01,131 - htmd.simlist - INFO - Starting listing of simulations.
Creating simlist: 100% (3/3) [#####################################] eta 00:01 -
2016-06-20 18:37:01,134 - htmd.simlist - INFO - Finished listing of simulations.
```

```python
metr = Metric(fsims)
metr.projection(MetricDihedral(protsel='protein', sincos=True))
data = metr.project()
data.fstep = 0.1

2016-06-20 18:37:04,018 - htmd.projections.metric - INFO - Metric: Starting projection of trajectories.
[Parallel(n_jobs=-2)]: Done   0 out of   0 | elapsed:    0.0s finished
2016-06-20 18:37:04,209 - htmd.projections.metric - INFO - Finished projecting the trajectories.

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-46-dba99273471f> in <module>()
      1 metr = Metric(fsims)
      2 metr.projection(MetricDihedral(protsel='protein', sincos=True))
----> 3 data = metr.project()
      4 data.fstep = 0.1

/home/guarneros/miniconda3/lib/python3.5/site-packages/htmd/projections/metric.py in project(self)
    158 
    159         if len(metrics) == 0:
--> 160             raise NameError('No trajectories were read')
    161 
    162         # Constructing a MetricData object
```

Where is the error?

I'm working with the latest HTMD version (1.0.27).

**Comment by stefdoerr** [comment]
Hm what does `len(fsims)` give? Also what trajectory format are you using?

**Comment by lguarneros** [comment]
**1) Output len(fsims)**
```
len(fsims)
0
```

**2) Output print(fsims[0])**
```
print(fsims[0])
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-5-d8e0c7ef2e9b> in <module>()
----> 1 print(fsims[0])

IndexError: index 0 is out of bounds for axis 0 with size 0

```

**3) Trayectory format is dcd generated with acemd**

Regards!

**Comment by stefdoerr** [comment]
Try calling it like this:
`fsims = simlist(glob('./data/*/'), './data/ionized.pdb')`
If this fails tell me what  this glob command returns
`glob('./data/*/')`

**Comment by lguarneros** [comment]
**1) fsims = simlist(glob('./data/*/', ), './data/ionized.pdb')**
```

2016-06-21 12:54:29,663 - htmd.simlist - INFO - Starting listing of simulations.

Creating simlist: 100% (3/3) [#####################################] eta 00:01 |

2016-06-21 12:54:29,665 - htmd.simlist - INFO - Finished listing of simulations.
```

**2) glob('./data/*/')**
```
['./data/run010/', './data/run001/', './data/run020/']
```

**3) len(fsims)**
`0`
 
**4) print(fsims[0])**
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-19-517b1fb7e7fa> in <module>()
      1 len(fsims)
----> 2 print(fsims[0])

IndexError: index 0 is out of bounds for axis 0 with size 0

```

**Comment by stefdoerr** [comment]
I am pretty sure we support DCD reading through MDTraj. How curious. Sorry for making you try all this but can you do also `glob('./data/*/*.dcd')` as a last test for me please?

**Comment by stefdoerr** [comment]
Ah wait! Ok I apologize. `simlist` is a bit limited right now and only reads xtc files, even though it could read other formats as well.
For the moment please convert your dcds to xtcs and in future versions we will add support for that as well. Also ACEMD can write out directly XTC files which is what we use because they take up less space and the extra precision is unnecessary.

**Comment by stefdoerr** [comment]
To convert from dcd to xtc you can do:
```bash
for file in *.dcd; do file=`basename $file .dcd`; catdcd -otype trr -o $file.trr $file.dcd ; trjconv -f $file.trr -o $file.xtc; done
```
It's a bit ugly but should work if you have `catdcd` and `trjconv` installed

**Comment by stefdoerr** [comment]
Or you could risk it a bit more and do it through HTMD :D (never tested it myself, but it should work and it's cleaner)
```python
mol = Molecule('./data/ionized.pdb')
mol.read('./data/run010/traj.dcd')
mol.write('./data/run010/traj.xtc')
```

**Comment by j3mdamas** [comment]
Changed title of issue. Tagged as enhancement (rather than bug)

**Comment by lguarneros** [comment]
That's right! Only support XTC files.
I convert DCD to XTC and work fine.
I wait the next version support for DCD.
Thanks!

**Comment by lguarneros** [comment]
That's right! Only support XTC files.
I convert DCD to XTC and work fine.
I wait the next version support for DCD.
Thanks!

**Comment by lguarneros** [comment]
That's right! Only support XTC files.
I convert DCD to XTC and work fine.
I wait the next version support for DCD.
Thanks!

**Comment by stefdoerr** [comment]
This was implemented a few months ago
