### ISSUE TITLE
Deprecate htmdx and check_registration functionalities

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#706]
`liblicense.so` disappeared from htmdlib, so there needs to be some cleaning on this side.

Lots of other stuff either don't work or aren't necessary.

Will take care of it on beginning on next week.

João

**Comment by stefdoerr** [comment]
I cleaned it up in this commit https://github.com/Acellera/htmd/commit/d7ebb489e687ac1e315b5d5a03d07cc1742319a7
We need the check_registration since we check against the webserver which hands out the keys
