### ISSUE TITLE
Method .as_matrix will be removed in a future version. Use .values instead

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#717]
`/home/joao/maindisk/software/repos/Acellera/htmd/htmd/molecule/readers.py:778: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.`

A few calls of `as_matrix` should be replaced. Not urgent.

**Comment by stefdoerr** [comment]
I'll just do it on the PDBreader PR

**Comment by stefdoerr** [comment]
https://github.com/Acellera/htmd/pull/713/commits/2e36e2dcd5b96747268942b76ef2bfecc798c754
Done

**Comment by j3mdamas** [comment]
Stefan, do the closing on the commit message, so it gets closed automatically only when merged to master

**Comment by stefdoerr** [comment]
ok
