### ISSUE TITLE
Equilibration fails after first run.

### ISSUE THREAD

**Issue by alejandrovr** [Acellera/htmd#72]
Hello,
We are trying to run equilibration on 5 different built systems, it works fine in the first system, and it does not gives any error, but when creating the generators, it only finds the .xsc file of the first equilibrated system, as the others do not have it. So, the error is:

```python
[Errno 2] No such file or directory: './docked/equil/2/output.xsc'
```
I have found that in the log.txt file in .docked/equil/1/ (the only system that was succesfull in equilibration) says:

#VIRIAL: Table size is 3333489, rounded up to 3333504
#WARNING: Setting ACEMD to low-memory mode. Need 1080MB. Available 841MB
#WARNING: cannot open file "restart.coor"
#Removing existing trajectory file output.dcd
#Removing existing trajectory file output.vel.dcd
#Removing existing trajectory file output.xtc
#Removing existing xst file output.xstfile

Is maybe the memory lack the reason why the other 4 systems were not equilibrated?

Thanks.

PD:

I have tried to run each system by hand and it has worked for those that have failed previously, except the number 2:

```python
>>> aa
['docked/equil/3/', 'docked/equil/5/', 'docked/equil/2/', 'docked/equil/4/']
>>> mdx.submit(aa[0])
2016-06-22 14:25:59,315 - htmd.apps.acemdlocal - INFO - Queueing /home/student1/avarela/DRUGG/choline_adaptative_sampling/docked/equil/3
2016-06-22 14:25:59,315 - htmd.apps.acemdlocal - INFO - Running /home/student1/avarela/DRUGG/choline_adaptative_sampling/docked/equil/3 on GPU device 3
>>> mdx.wait()
2016-06-22 14:29:50,715 - htmd.apps.acemdlocal - INFO - Completed /home/student1/avarela/DRUGG/choline_adaptative_sampling/docked/equil/3

#system number 3 has worked now, it did not before

>>> aa
['docked/equil/3/', 'docked/equil/5/', 'docked/equil/2/', 'docked/equil/4/']
>>> mdx.submit(aa[2])
2016-06-22 14:30:36,305 - htmd.apps.acemdlocal - INFO - Queueing /home/student1/avarela/DRUGG/choline_adaptative_sampling/docked/equil/2
2016-06-22 14:30:36,305 - htmd.apps.acemdlocal - INFO - Running /home/student1/avarela/DRUGG/choline_adaptative_sampling/docked/equil/2 on GPU device 3
>>> 2016-06-22 14:30:36,315 - htmd.apps.acemdlocal - ERROR - Error in ACEMD for path: /home/student1/avarela/DRUGG/choline_adaptative_sampling/docked/equil/2. Check the /home/student1/avarela/DRUGG/choline_adaptative_sampling/docked/equil/2/log.txt file.

```

I then read equil/2/log.txt file and it only says:

/bin/sh: /home/student1/miniconda3/bin/acemd: No existe el fichero o el directorio

**Comment by j3mdamas** [comment]
You updated to 1.1.0, right?

**Comment by giadefa** [comment]
Just now. Give it a try

On 22 June 2016 at 14:58, João M. Damas <notifications@github.com> wrote:

> You updated to 1.1.0, right?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/72#issuecomment-227734805>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHaqOkcrcN367jjjQvvMlCQtpwu7YNGpks5qOTFggaJpZM4I7t8e>
> .
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>

**Comment by j3mdamas** [comment]
@alejandrovr, can you try it?

**Comment by alejandrovr** [comment]
It has worked now. Thanks! 

By the way, can the lack of memory be responsible for this kind of troubles? Like doing only the first system and nothing else without saying it?

**Comment by j3mdamas** [comment]
Low memory should not be a problem
