### ISSUE TITLE
Advice / Help with Ligand Binding Analysis

### ISSUE THREAD

**Issue by waskom** [Acellera/htmd#73]
Hello,
I have also posted this on the HTMD forum but was recommended to post here as well. 

I am trying to run the script to filter my data. This step was basically skipped during the tutorial and I am confused on how to set up my data directories to work with the script.

I have played around with setting up the data in different directories and edited the command in what seemed logical to me, but I cannot seem to get it to work.
<img width="1206" alt="screen shot 2016-06-22 at 12 19 02 pm" src="https://cloud.githubusercontent.com/assets/20097577/16281544/ecafa6e6-3892-11e6-818f-c2fbc8fc2b8b.png">

What I am looking for is advice on how to either separate my data in an appropriate fashion for HTMD to execute the command or setting up the command to pull the necessary files. 

Thank you,
Mike

**Comment by stefdoerr** [comment]
Ok, so for HTMD to read your simulations, each independent simulation needs to be located in a folder whose name will be used as the simulation name.
I.e.
```
simulations/
---------sim1/
------------traj1.xtc
------------traj2.xtc
---------sim2/
------------traj1.xtc
------------traj2.xtc
------------traj3.xtc
```
Any simulations inside a folder like traj1-3.xtc in sim2 will be considered to be consecutive pieces of the same simulation and will be joined internally in HTMD into a single simulation.

Concerning your error above, is that simlist needs a list of directories. So give a structure like the above, you would call it like:
```python
sims = simlist(glob('./simulations/*/'), glob('./simulations/*/structure.pdb'))
```

**Comment by stefdoerr** [comment]
Then if you want to filter you would do:
```python
fsims = simfilter(sims, './filtered/', filtersel='not water')
```
which would produce a new folder with the same structure but different file names, so:
```
filtered/
---------sim1/
------------traj1.filtered.xtc
------------traj2.filtered.xtc
---------sim2/
------------traj1.filtered.xtc
------------traj2.filtered.xtc
------------traj3.filtered.xtc
```
If you use simfilter there is no need to call simlist again. But if next time you want to skip the first step (because for example you lost your unfiltered data), you can do:
```python
sims = simlist(glob('./filtered/*/'), './filtered/filtered.pdb')
```

**Comment by waskom** [comment]
I will try this today. Thank you very much for your help.

**Comment by j3mdamas** [comment]
@waskom, is this solved?

**Comment by waskom** [comment]
Yes. I have solved the filtering problem.
