### ISSUE TITLE
Can Charmm force field be used with all bonds constrained?

### ISSUE THREAD

**Issue by rcrehuet** [Acellera/htmd#733]
This is more a question than an issue. I've read in several places that Charmm Force Field was parametrized constraining only bonds containing a hydrogen atom. In that case, one cannot use large timesteps of 4fs. Do you think Charmm force fields can be used with all bonds constrained so that one can use a large time-step? Is there any test to compare the error one incurs?

**Comment by j3mdamas** [comment]
Hi @rcrehuet,

In the case of ACEMD, we use hydrogen mass rescaling, so we can increase the time step to 4. You can check the documentation on `rigidbonds`: https://software.acellera.com/docs/latest/acemd/commandreference.html?highlight=rigidbonds

For the current version of ACEMD, there's no option to change the constraints for all bonds, I believe. In the future, ACEMD will not have any option to control this constraints or hydrogen mass rescaling: they will be set depending on the time step chosen (less control, but much safer)

For more in-depth discussions of the CHARMM force-field, their forums can also be a valuable source of information.

Best,
João
