### ISSUE TITLE
maximalSubstructureAlignment does not work

### ISSUE THREAD

**Issue by alejandrovr** [Acellera/htmd#738]
I was trying this function and I got an argument type error. The _pp_align function in Molecule class expects the selection of both molecules (reference and query) to be boolean arrays. This is not the case for the output of maximalSubstructureAlignment, which returns two list of indexes. If one changes the signature of the __pp_align function to: 

```
@jit('float32[:, :, :](float32[:, :, :], float32[:, :, :], int64[:], int64[:], int64[:], int64)', nopython=True,
     nogil=True)
```

and converts the two list of indexes from maximalSubstructureAlignment into two numpy arrays, it works. Converting these indexes to boolean arrays does not solve it, as the pairing between the nodes in reference and query breaks.

Script to reproduce the result:

```
from htmd.ui import *
from htmd.molecule.graphalignment import maximalSubstructureAlignment

reference_crystal = Molecule('2Y02')
reference_crystal.filter('protein or resname WHJ')
reference_ligand = reference_crystal.copy()
reference_ligand.filter('resname WHJ')
#there are two ligands with the same resname, so we select one of them
reference_ligand.filter('residue 1') 

#extract other ligand from this congeneric series from protein 2Y03
ligand_to_align = Molecule('2Y03')
ligand_to_align.filter('resname 5FW')
#residue 1 happens to be already align with the reference ligand, so we use residue 0
ligand_to_align.filter('residue 0') 

reference_crystal.view('alrefprot')
ligand_to_align.view(name='toalign')
reference_ligand.view(name='reflig')

#now we align the extracted ligand to the crystal of the reference
lig_aligned = maximalSubstructureAlignment(reference_ligand,ligand_to_align)
lig_aligned.view(name='shouldbealign')
```

I think that, in general, using boolean arrays instead of the indexes will break any correspondence between two sets of coordinates if they are not ordered in the same way (index 0 of ref corresponds to index 10 of query,  and index 2 of ref goes with index 5 of query, for example).

**Comment by alejandrovr** [comment]
Maybe the tests were done using the same molecule, but randomly rotated. That can make the boolean arrays keep the pairing.

**Comment by alejandrovr** [comment]
Same issue with ```htmd.molecule.util.sequenceStructureAlignment```, changing:

```alignedmol.align(molboolidx, ref, refboolidx)```

for 

´´´alignedmol.align(np.array(molidx), ref, np.array(refidx))´´´

together with the signature shown in the first comment makes it work. Maybe this new signature conflicts with other functions.

**Comment by j3mdamas** [comment]
Yeah, this is a bug. I'll propose a change based on @alejandrovr's ideas and ask @stefdoerr to review it.

**Comment by j3mdamas** [comment]
@stefdoerr, ok, so now I see `_pp_align` fails on other align calls in projections. I've done another commit, but I really need your review on this one xD

**Comment by stefdoerr** [comment]
There are no tests for maximalStructureSubalignment and yes indeed this is a bug.

**Comment by stefdoerr** [comment]
@j3mdamas which projections fail? They shouldn't fail if used as specified in the docs, unless you are expecting atomselect strings to give you custom ordered results which they don't. The bug is only in maxSubAlign as far as I can tell.
