### ISSUE TITLE
Parametrization generates multiple dihedrals

### ISSUE THREAD

**Issue by spyda90** [Acellera/htmd#74]
Hi,

after solving issues within running parametrization module, now I want to discuss you about the output.

I've parametrized 4-phenylimidazole. The .pdb of the optimized structure is correct, since the structure is planar.
## Following, the .pdb generated:

MODEL 1
HETATM 1 C1 0MOL 0 00 -3.135 -0.316 -0.886 0.00 0.00 0 C
HETATM 2 C2 0MOL 0 00 -2.261 0.390 -1.698 0.00 0.00 0 C
HETATM 3 C3 0MOL 0 00 -0.933 0.532 -1.338 0.00 0.00 0 C
HETATM 4 C4 0MOL 0 00 -0.450 -0.043 -0.165 0.00 0.00 0 C
HETATM 5 C5 0MOL 0 00 -1.335 -0.755 0.641 0.00 0.00 0 C
HETATM 6 C6 0MOL 0 00 -2.667 -0.886 0.287 0.00 0.00 0 C
HETATM 7 C7 0MOL 0 00 0.968 0.100 0.201 0.00 0.00 0 C
HETATM 8 C8 0MOL 0 00 2.102 0.146 -0.542 0.00 0.00 0 C
HETATM 9 N1 0MOL 0 00 3.206 0.278 0.258 0.00 0.00 0 N
HETATM 10 C9 0MOL 0 00 2.750 0.311 1.463 0.00 0.00 0 C
HETATM 11 N2 0MOL 0 00 1.406 0.196 1.502 0.00 0.00 0 N
HETATM 12 H1 0MOL 0 00 -4.168 -0.420 -1.163 0.00 0.00 0 H
HETATM 13 H2 0MOL 0 00 -2.616 0.840 -2.608 0.00 0.00 0 H
HETATM 14 H3 0MOL 0 00 -0.268 1.104 -1.959 0.00 0.00 0 H
HETATM 15 H4 0MOL 0 00 -0.978 -1.233 1.537 0.00 0.00 0 H
HETATM 16 H5 0MOL 0 00 -3.334 -1.442 0.920 0.00 0.00 0 H
HETATM 17 H6 0MOL 0 00 2.192 0.068 -1.605 0.00 0.00 0 H
HETATM 18 H7 0MOL 0 00 3.340 0.415 2.351 0.00 0.00 0 H
HETATM 19 H8 0MOL 0 00 0.833 0.276 2.310 0.00 0.00 0 H
ENDMDL
## END

Then, I've tried running an MD with ACEMD using the .rtf and the .prm generated from my parametrization.
## Here you are the .rtf

```
*Charmm RTF built by MATCH
*
22 0
MASS 125 HGP1 1.008000 H
MASS 129 N251 14.00700 N
MASS 128 N250 14.00700 N
MASS 126 HG52 1.008000 H
MASS 127 HG61 1.008000 H
MASS 122 C251 12.01100 C
MASS 123 C253 12.01100 C
MASS 124 C261 12.01100 C
MASS 9 C261x0 12.011000
```

AUTO ANGLES DIHE

RESI PIM 0.000
GROUP
ATOM C1 C261 -0.152
ATOM C2 C261 -0.144
ATOM C3 C261x0 -0.120
ATOM C4 C261 -0.029
ATOM C5 C261 -0.120
ATOM C6 C261 -0.144
ATOM C7 C251 0.142
ATOM C8 C251 0.008
ATOM N1 N250 -0.587
ATOM C9 C253 0.352
ATOM N2 N251 -0.505
ATOM H1 HG61 0.143
ATOM H2 HG61 0.148
ATOM H3 HG61 0.113
ATOM H4 HG61 0.113
ATOM H5 HG61 0.148
ATOM H6 HG52 0.161
ATOM H7 HG52 0.092
ATOM H8 HGP1 0.381
BOND C1 C2
BOND C1 C6
BOND C1 H1
BOND C2 C3
BOND C2 H2
BOND C3 C4
BOND C3 H3
BOND C4 C5
BOND C4 C7
BOND C5 C6
BOND C5 H4
BOND C6 H5
BOND C7 C8
BOND C7 N2
BOND C8 N1
BOND C8 H6
BOND N1 C9
BOND C9 N2
BOND C9 H7
BOND N2 H8
IMPR C8 C7 N1 H6
IMPR C9 N1 N2 H7
IMPR N2 C7 C9 H8
PATCH FIRST NONE LAST NONE

MASS 101 HTXW 1.008000 H ! TIPS3P WATER HYDROGEN
MASS 102 OTXW 15.999400 O ! TIPS3P WATER OXYGEN

RESI TIP3 0.000 ! tip3p water model, generate using noangle nodihedral
GROUP
## ATOMATOMATOMBONDANGLE H1 OH2 H2 ! required

I've suddendly noticed that something in my ligand was wrong during the MD; in particular the dihedral that involves the conjunction atoms of the two rings was different from 180 degrees. I didn't have this issue when I've parametrized through ParachemTool.

Looking into the .prm file, I have noticed that for a single dihedral, multiple values and K have been generated. What does it mean?
## Here you are the .prm dihedrals:

DIHEDRALS
C261 C261 C261 C261 3.1000 2 180.00
HG61 C261 C261 C261 4.2000 2 180.00
HG61 C261 C261 HG61 2.4000 2 180.00
C261 C261 C261 C251 3.1000 2 180.00
HG61 C261 C261 C251 4.2000 2 180.00
C261 C261 C251 C251 3.0000 2 180.00
C261 C261 C251 N251 1.5000 2 180.00
C261 C251 C251 N250 3.0000 2 180.00
C261 C251 C251 HG52 1.5000 2 180.00
C261 C251 N251 C253 14.0000 2 180.00
C261 C251 N251 HGP1 1.0000 2 180.00
C253 N251 C251 C251 14.0000 2 180.00
HGP1 N251 C251 C251 1.0000 2 180.00
N251 C251 C251 N250 14.0000 2 180.00
N251 C251 C251 HG52 3.0000 2 180.00
C251 C251 N250 C253 14.0000 2 180.00
C251 N251 C253 N250 14.0000 2 180.00
C251 N251 C253 HG52 3.0000 2 180.00
HG52 C251 N250 C253 3.0000 2 180.00
C251 N250 C253 N251 14.0000 2 180.00
C251 N250 C253 HG52 2.0000 2 180.00
N250 C253 N251 HGP1 1.0000 2 180.00
HG52 C253 N251 HGP1 1.0000 2 180.00
C261 C261 C261x0 C261 3.100000000000000 2 180.0
C261 C261 C261x0 HG61 4.200000000000000 2 180.0
C261 C261x0 C261 C251 3.100000000000000 2 180.0
C261x0 C261 C261 C261 3.100000000000000 2 180.0
C261x0 C261 C261 HG61 4.200000000000000 2 180.0
C261x0 C261 C251 C251 3.000000000000000 2 180.0
C261x0 C261 C251 N251 0.001144190021000 1 180.0
C261x0 C261 C251 N251 4.131675347783000 2 0.0
C261x0 C261 C251 N251 0.003493447386000 3 180.0
C261x0 C261 C251 N251 0.060572906878000 4 0.0
C261x0 C261 C251 N251 0.389691907194000 6 0.0
C261 C261x0 C261 HG61 4.200000000000000 2 180.0
C251 C261 C261x0 HG61 4.200000000000000 2 180.0
## HG61 C261 C261x0 HG61 2.400000000000000 2 180.0

The "C261x0 C261 C251 N251 " is the one I'm talking about. If I set it as 4.2 / 2 / 180.0 (as the others), I don't have any problem in my MD.

But what does it mean and what should I do?

Thank you in advance.

Francesco

**Comment by j3mdamas** [comment]
Hi Francesco. Can you share the plot of the dihedral?

The multiple values are just different functions that added up to reproduce the QM dihedral.

**Comment by j3mdamas** [comment]
And could you tell me what do you mean by "something wrong in the MD simulation"?

**Comment by spyda90** [comment]
"Something wrong" means that the dihedral that involeves C8, N2, C7, C4 goes far from 180 degrees during the MD, as C7-C4 bond isn't a link between two aromatic ring.

I'm sorry, but what do you mean with "the plot of the dihedral"?

Thank you.

Francesco

**Comment by j3mdamas** [comment]
If you're using the command-line version, a completed parameterize outputs an .svg file on the folder, which shows how well the dihedrals parameterization went.

**Comment by spyda90** [comment]
This is the only svg that has been generated.
Here you are.

[torsion-potential-C3-C4-C7-N2.svg.zip](https://github.com/Acellera/htmd/files/329617/torsion-potential-C3-C4-C7-N2.svg.zip)

**Comment by j3mdamas** [comment]
So, the MD is following the parameterization (look at the minima of the red/green lines in the .svg file). So, what do you mean is that it is know, experimentally, that this compound behaves like the original MM (blue line)?

**Comment by spyda90** [comment]
Sorry, I've made a mistake. The multiple dihedrals generated are for the same dihedral of the svg. But, the one that shows strange progress during MD is C4-C7-N2-C8, that correspond to C261-C251-N251-C251. If I'm not wrong, I didn't see this angle in the .prm! Can you check it too?

Thank you!

**Comment by spyda90** [comment]
I attach the ligand trj extracted from the entire system (protein+ligand).
[PIM_trj.pdb.zip](https://github.com/Acellera/htmd/files/329910/PIM_trj.pdb.zip)

**Comment by j3mdamas** [comment]
I see your point, but I have to think about it. The angle you're describing corresponds to an improper. That improper isn't, for example, defined in CHARMM HID residue (which is also an imidazole ring). Give me some time.

Thanks for reporting,
João

**Comment by spyda90** [comment]
Thank you, I appreciate that.

I will wait for your answer.

Francesco

**Comment by j3mdamas** [comment]
Can you give me also your files from ParaChem which you say that were working?

**Comment by spyda90** [comment]
Here you are. I have generated it including also the parameters that are in the cfgen yet, so you can have a look into all of them considered for PIM. There are no impropers.

[par_PIM.prm.zip](https://github.com/Acellera/htmd/files/331545/par_PIM.prm.zip)

Francesco

**Comment by spyda90** [comment]
The atom type is different (of course) but I simply renamed the htmd output ones into the ParamChem way.

**Comment by spyda90** [comment]
The complete .inp file used is this.
[PIM.inp.zip](https://github.com/Acellera/htmd/files/331551/PIM.inp.zip)

**Comment by spyda90** [comment]
To complete, the .rtf is:
[top_PIM.rtf.zip](https://github.com/Acellera/htmd/files/331553/top_PIM.rtf.zip)

**Comment by spyda90** [comment]
Hi, 
any news?

Furthermore, is it possible to parameterize some co-factor as heme through thi module?

Francesco

**Comment by j3mdamas** [comment]
The parameterize module is still in a very alpha version. We are currently working on this issue and appreciate your input.

About the heme, in theory, yes. But there will be concerns about the eventual iron parameterization and also the computation time (heme is a big molecule).

João

**Comment by spyda90** [comment]
Hi again,

I was trying to run the param for the HEME and I've obtain the error 
---
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /export131/home/mjharvey/working/psi4public/src/lib/libscf_solver/rhf.cc on line: 73
---

There is a way to switch from RHF (default for PSI) to UHF (or others)? Is tehre a keyword that I can use in the input file to do that?

Thank you

Francesco

**Comment by j3mdamas** [comment]
Hi Francesco,

No, RHF is hard-wired into the code. We'll discuss if we want to expose it to the user.

**Comment by j3mdamas** [comment]
I am going to bump this to 1.6.0, as it will need to be reanalyzed in the new parameterize

**Comment by spyda90** [comment]
Hi!
So is the 1.6.0 available right now?
Which is the right command to cleanly update htmd?

Francesco

**Comment by j3mdamas** [comment]
1.6.0 will be due by January 13, 2017.

1.4.0 should be up by the end of the week, hopefully. It has a new version of parameterize, but this issue will probably not be solved.

Thanks for reporting it though. We will do our best to improve the parameterization tool.

**Comment by spyda90** [comment]
Thank you! So I'll wait for trying both versions...!

**Comment by mj-harvey** [comment]
@spyda90 please try the new parameterise available now in version 1.5.4.

**Comment by mj-harvey** [comment]
@spyda90 Please let us know if the current parameterisation is still producing a suspect parameterisation. If I don't hear back in a week we'll close this case. 
If Heme parameters are still relevant to you, please open a separate case.

**Comment by spyda90** [comment]
I'm sorry, I've been very busy last two months. I'll try and I'll let you know.

**Comment by j3mdamas** [comment]
I'll close this issue, as I think it's related with the more recent issue #198. @spyda90, if you think it's not related or have any further problems, please open another issue.
