### ISSUE TITLE
Cannot import Configuration()

### ISSUE THREAD

**Issue by alejandrovr** [Acellera/htmd#75]
We are trying to parameterize a ligand and we are getting this error. It is strange because it was working like one week ago. Maybe the update is causing trouble?
```python
from htmd import *
from htmd.parameterize import Configuration, Parameterisation
```
This is the error:
```
You are on the latest HTMD version (1.3.1).
Traceback (most recent call last):
  File "SimulationModule.py", line 6, in <module>
    from htmd.parameterize import Configuration, Parameterisation
ImportError: cannot import name 'Configuration'
```

Thanks.

**Comment by j3mdamas** [comment]
Hi Alejandro,

A little bit of changes to the parameterize lately. Now it's automatically imported when you do `from htmd import *`, so no need for the second import.

The `Configuration` and `Parameterisation` are now called `ParameterizationConfig` and `Parameterization`. All the rest should work the same.

Sorry for the confusion,
João

**Comment by alejandrovr** [comment]
Ok, thank you!
Alejandro.

**Comment by alejandrovr** [comment]
param.getParameters() has not changed? It is returning me a NoneType.

```python
molec = Molecule(mol2)
    config = ParameterizationConfig()
    config.FileName = mol2
    molec_name = mol2
    molec_name = molec_name.split(".")[0]
    config.JobName = molec_name.split("/")[-1]+str(random.randint(1,1000))
    config.NetCharge = netcharge
    param = Parameterization(config=config)
    paramfiles = param.getParameters()
    shutil.copyfile(paramfiles['RTF'], molec_name+".rtf")
```

```
shutil.copyfile(paramfiles['RTF'], molec_name+".rtf")
TypeError: 'NoneType' object is not subscriptable
```

**Comment by j3mdamas** [comment]
yes, it has ahah

I made it simpler, now you don't have to copy the file. See the help of `getParameters`, where now you can define a outdir and a outname. Actually, you should have the parameters there, on ./

**Comment by j3mdamas** [comment]
and nothing is returned from the command.

**Comment by alejandrovr** [comment]
Okey, I have found the documentation in HTMD. Thanks!
