### ISSUE TITLE
Projections and Memory issues

### ISSUE THREAD

**Issue by shozebhaider** [Acellera/htmd#750]
Hi

I have a set of 500 trajectories (each 60ns long/600 frames each) of a protein of 200aa from an adaptive simulation, which I load from a simlist. When I do any projections (RMSD or selfdistance on 20 aa or dihedral or RMSF) it freezes the machine and takes over 4-5 hours to finish. Is there a way to speed this up and over come these memory issues.

Many thanks 

Shozeb

**Comment by j3mdamas** [comment]
Hi @shozebhaider,

Can you share the code you're using and a sample structure? Any of those metrics under only 20 aas should not be taking much memory. How much RAM memory do you have on that machine?

**Comment by stefdoerr** [comment]
200aa @j3mdamas. This might kill self-distances but should not bother RMSD

**Comment by j3mdamas** [comment]
@shozebhaider said the protein had 200 aas, but then said the projection was on 20 aa. Unless that was a typo

**Comment by shozebhaider** [comment]
Yes its a selection of 20 aa (only CA) from 200 that I am just doing a self-distance on.

**Comment by j3mdamas** [comment]
@shozebhaider can you tell us how many CPUs does your machine have and how many python processes you see on `top` during the Metric calculation?

**Comment by j3mdamas** [comment]
Also, you can try to do:

```python
from htmd import config
config(ncpus=1)
```
on the beginning of your script, and then try if it causes the same problem

**Comment by shozebhaider** [comment]
I have 12 CPUs, can only see one python process on top but if I do ps -ef  | grep python then I can count 12 process. 

Using 
from htmd import config
config(ncpus=1)

I do not face any such issues that I had reported. However, if I tweek ncpus to any other number apart from 1 then I see those issues come back again. 

So thank you once again team HTMD.

**Comment by giadefa** [comment]
Practically you don't have enough ran to support your cores. Python is
using a lot of memory in parallel.
