### ISSUE TITLE
Projecting a dihedral angle

### ISSUE THREAD

**Issue by fellache** [Acellera/htmd#752]
Dear maintainers,

I would kindly ask your for your support on a probably rather simple issue I am facing currently. After running adaptive MD I would be interested in analyzing huge conformational changes occurring in an enzyme, specifically the opening of a cap helix which allows substrate to enter the active site.

MSM building already works decently when using just a distance metric between two atoms, but I would like to further enhance the quality of the model. For this, I tried to define a dihedral angle metric to be included, which would follow the clapping open of the cap domain as repeatedly seen in the simulations.

I consulted your documentation and tried to apply it to my problem, but unfortunately I do get an error when using the following code:

```
atom1_DihAng = {'name': 'CA', 'resid': 145, 'segid': 'P', 'chain': 'A', 'insertion': 'A'}
atom2_DihAng = {'name': 'CA', 'resid': 216, 'segid': 'P', 'chain': 'A', 'insertion': 'B'}
atom3_DihAng = {'name': 'CA', 'resid': 250, 'segid': 'P', 'chain': 'A', 'insertion': 'C'}
atom4_DihAng = {'name': 'CA', 'resid': 157, 'segid': 'P', 'chain': 'A', 'insertion': 'D'}
dih = Dihedral(atom1_DihAng, atom2_DihAng, atom3_DihAng, atom4_DihAng)
print(dih)
metrMSMCap3 = Metric(fsims)
metrMSMCap3.set(MetricDihedral(dih, protsel='protein'))
dataMSMCap3 = metrMSMCap3.project()
```

And I get the following output:

name	resid	insertion	chain	segid
CA	145	A	A	P
CA	216	B	A	P
CA	250	C	A	P
CA	157	D	A	P

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-36-0c501747636a> in <module>()
     16 print(dih)
     17 metrMSMCap3 = Metric(fsims)
---> 18 metrMSMCap3.set(MetricDihedral(dih, protsel='protein'))
     19 dataMSMCap3 = metrMSMCap3.project()
     20 

/software/Miniconda3/envs/HTMD/lib/python3.6/site-packages/htmd/projections/metricdihedral.py in __init__(self, dih, sincos, protsel)
    542     """
    543     def __init__(self, dih=None, sincos=True, protsel='protein'):
--> 544         if dih is not None and not isinstance(dih[0], Dihedral):
    545             raise RuntimeError('Manually passing dihedrals to MetricDihedral requires use of the Dihedral class. Check the example in the documentation')
    546         self._protsel = protsel

TypeError: 'Dihedral' object does not support indexing_

Do you have any suggestions on how I could use this metric for projecting my data?
Thanks a lot

**Comment by stefdoerr** [comment]
Could you try `dih = [Dihedral(atom1_DihAng, atom2_DihAng, atom3_DihAng, atom4_DihAng)]` please? Seems like something we should check on our side, sorry

**Comment by stefdoerr** [comment]
Practically the class is expecting a list of dihedral angles instead of just one and then it errors. If you just put it in a list it ought to work. The dihedral class will go through some refactoring soon though to improve it so we will just fix it there.

**Comment by fellache** [comment]
Dear Stefan,

thank you for your response. I tried the following code:

`atom1_DihAng = {'name': 'CA', 'resid': 145, 'segid': 'P', 'chain': 'A'}
atom2_DihAng = {'name': 'CA', 'resid': 216, 'segid': 'P', 'chain': 'A'}
atom3_DihAng = {'name': 'CA', 'resid': 250, 'segid': 'P', 'chain': 'A'}
atom4_DihAng = {'name': 'CA', 'resid': 157, 'segid': 'P', 'chain': 'A'}
dih = [Dihedral(atom1_DihAng, atom2_DihAng, atom3_DihAng, atom4_DihAng)]
print(dih)
metrMSMCap3 = Metric(fsims)
metrMSMCap3.set(MetricDihedral(dih, protsel='protein'))
dataMSMCap3 = metrMSMCap3.project()`

I could project the dihedral metric on my data now, but I had to remove the insertions from the section where i defined the atoms. Not sure what this parameter exactly specifies (according to your documentation it is the > The insertion letter of the residue

Anyways, thanks for the fix!

Best regards,
Hannes

**Comment by stefdoerr** [comment]
Yes don't worry about the insertion. 
As per: http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM
> Alphabet letters are commonly used for insertion code. The insertion code is used when two residues have the same numbering. The combination of residue numbering and insertion code defines the unique residue. 

You probably didn't have any insertion code in those residues. The new Dihedral class will make it easier to define them, with atom selections in VMD style.

Thanks for confirming it works!
