### ISSUE TITLE
parametrize CGenFF

### ISSUE THREAD

**Issue by vsalmaso90** [Acellera/htmd#754]
I am using parametrize with CGenFF. QM calculation successfully finishes, but parametrize fails while writing topologies and parameters files. The error is: 

```pytb
== Writing results ==

Traceback (most recent call last):
  File "/opt/miniconda3/bin/parameterize", line 11, in <module>
    sys.exit(main_parameterize())
  File "/opt/miniconda3/lib/python3.6/site-packages/htmd/parameterization/cli.py", line 288, in main_parameterize
    writeParameters(mol, parameters, qm, method, netcharge, args.outdir, original_coords=orig_coor)
  File "/opt/miniconda3/lib/python3.6/site-packages/htmd/parameterization/writers.py", line 312, in writeParameters
    writePRM(mol, parameters, file_)
  File "/opt/miniconda3/lib/python3.6/site-packages/htmd/parameterization/writers.py", line 154, in writePRM
    val = parameters.bond_types[type]
KeyError: ('C251x0',   'C251x1')
```

It seems that the error arises due to the fact that in the list returned by getSortedAndUniqueTypes the order of the atomtypes within each bond_type tuple may in some cases differ from those stored in the "parameters" object. (the same for angles, dihedrals, impropers).
For example in my case ('C251x0', 'C251x1') key is not found within parameters.bond_types, because it was stored as ('C251x1', 'C251x0')

It seems that with the following changes to getSortedAndUniqueTypes function it works (at least in my case):

```python
def getSortedAndUniqueTypes(types, field):
    if field == 'atom_types':
        return np.unique(types)
    #if field == 'bond_types':
    #     for i in range(types.shape[0]):
    #       types[i] = sorted(types[i])
    #elif field == 'angle_types':
    #     for i in range(types.shape[0]):
    #       types[i][0], types[i][2] = sorted([types[i][0], types[i][2]])
    #elif field == 'dihedral_types':
    #     for i in range(types.shape[0]):
    #        if types[i][0] > types[i][3]:
    #            types[i] = types[i][::-1]
    #elif field == 'improper_types' or field == 'improper_periodic_types':
    #    for i in range(types.shape[0]):
    #        types[i][0], types[i][1], types[i][3] = sorted([types[i][0], types[i][1], types[i][3]])
    #else:
    #    raise RuntimeError('Invalid field')
    return sorted(list({tuple(row) for row in types.tolist()}))
```

**Comment by j3mdamas** [comment]
Dear @vsalmaso90,

Which version of htmd are you using? parameterize is highly developed, so you may have an older version.

**Comment by vsalmaso90** [comment]
Dear @j3mdamas,
version 1.13.6.

**Comment by j3mdamas** [comment]
thanks. Can you share the input molecule?

**Comment by stefdoerr** [comment]
I assume this is an issue with `parmed`. Can you tell us which `parmed` version you use with `conda list parmed`?

**Comment by vsalmaso90** [comment]
Dear @stefdoerr,
parmed version 2.7.3 .

**Comment by j3mdamas** [comment]
Thanks for the info @vsalmaso90. Is it possible to share the input molecule? This way we can debug it faster.

**Comment by stefdoerr** [comment]
@vsalmaso90 this is fixed in the newest github version of HTMD. You can either use the github version or wait for the next HTMD release.
