### ISSUE TITLE
proteinPrepare strange results

### ISSUE THREAD

**Issue by giadefa** [Acellera/htmd#76]
If I run this code
```
protein = Molecule('2OV5')
protein.filter('chain A and (protein or water)')  # can I keep water if I use proteinPrepare?
protein_prep, report = proteinPrepare(protein,returnDetails=True)

2016-06-30 02:40:22,403 - htmd.molecule.molecule - INFO - Attempting PDB query for 2OV5
2016-06-30 02:40:25,485 - htmd.molecule.molecule - INFO - Removed 4094 atoms. 2080 atoms remaining in the molecule.
2016-06-30 02:40:25,676 - propka - INFO - No pdbfile provided
2016-06-30 02:40:35,088 - htmd.builder.residuedata - WARNING - Dubious protonation state: the pKa of 3 residues is within 1.0 units of pH 7.0.
2016-06-30 02:40:35,092 - htmd.builder.residuedata - WARNING - Dubious protonation state:    HIS 219  A
2016-06-30 02:40:35,092 - htmd.builder.residuedata - WARNING - Dubious protonation state:    LYS 234  A
2016-06-30 02:40:35,093 - htmd.builder.residuedata - WARNING - Dubious protonation state:    N+ 30  A
```

* why propka complains of no pdbfile?
* resid 30 is actally alanine, no N+?

```
report.data[report.data.resid==219]

resname	resid	insertion	chain	pKa	protonation	flipped	patches	buried	z	membraneExposed	pka_group_id	pka_residue_type	pka_type	pka_charge	pka_atom_name	pka_atom_sybyl_type
188	HIS	219		A	6.510094	HIE	False	[PEPTIDE]	0.0	9.923	NaN	43.0	HIS	HIS	1	CG	
```
* actually HIS 219 looking at the crystal water structure should probably be protonated but it does not. Does propka looks at water  as well? Because the result is the same with and without passing water

* these NAN are errors ?

**Comment by tonigi** [comment]
> Does propka looks at water as well? 

No, propKa doesn't consider water as far as I know. pdb2pqr does, but after the protonation decision is taken.  Note that the warning message is already telling you that the protonation is not to be trusted (borderline with pH).

> resid 30 is actally alanine, no N+?

Terminals have their own pKa values, independent of the sidechain of the corresponding residue. They are called N+ and C-. Feel free to ignore them if you are capping.

> Why propka complains of no pdbfile?

A useless log messages in propka upstream code, but I would not like to fork the code for minor things.

> these NAN are errors ?

No, just "not applicable", but things like NA or empty are not allowed in float columns.

**Comment by giadefa** [comment]
Maybe the initial log could also say what other residues were mutated with certainty and show the pKa of the dubious ones

**Comment by tonigi** [comment]
pKa done. list of protonations may be annoying long and needs some reformatting

**Comment by giadefa** [comment]
not a list just the residues that were changed. I am sure they are just  a
few for a  normally sized protein

On 1 July 2016 at 10:04, Toni G <notifications@github.com> wrote:

> pKa done. list of protonations may be annoying long and needs some
> reformatting
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/76#issuecomment-229883033>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHaqOtDOZCwTryIhJm2FEGczm3rzoqFFks5qRMofgaJpZM4JBtMm>
> .
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>

**Comment by tonigi** [comment]
In 5f5b982b406fcdb67fa0caf661627a9549449bb6

    2016-07-01 10:46:37,659 - htmd.builder.residuedata - INFO - The following residues are in a non-standard state: CYS    69  A (CYX), HIS   219  A (HID), LYS   234  A (LYN), CYS   238  A (CYX), ASP   246  A (ASH), HIS   274  A (HID)

T
