### ISSUE TITLE
TICA lag unit

### ISSUE THREAD

**Issue by andt88** [Acellera/htmd#771]
Hi all,

it is not clear to me from the documentation whether the default lag time in the htmd.projections.tica module is in frames or ns (as in some examples).

**Comment by stefdoerr** [comment]
https://software.acellera.com/docs/latest/htmd/htmd.projections.tica.html#htmd.projections.tica.TICA
It's in the signature of the function
`class htmd.projections.tica.TICA(data, lag, units='frames', dimensions=None)`
We don't document defaults outside of the signature to avoid inconsistencies.
