### ISSUE TITLE
Different box sizes per frame. Still unsupported by mindist.

### ISSUE THREAD

**Issue by andt88** [Acellera/htmd#773]
I am getting this warning: 

> "Different box sizes per frame. Still unsupported by mindist. Contact Stefan Doerr."

This is a bit strange since I've been already working on these trajectories with HTMD without any problem so far. The trajectories were generated using pmemd.cuda. Loading them into cpptraj works fine.

This is my code:
```python
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from htmd.ui import *
from pylab import *
from htmd.config import config
config(viewer='vmd', ncpus=2)

#import simulation data
sims = simlist(glob('data/*/'), '../build_amber_7/dry.pdb')

print('calculating metrics')
metr = Metric(sims)
protsel='protein and noh'
ligsel='resname MOL and (oxygen or nitrogen or carbon not within 1.4 of hydrogen)'

metric1=MetricDistance(protsel, ligsel, metric='contacts', groupsel1='residue', threshold=5)
metric2=MetricDistance('name CA', ligsel, metric='contacts', threshold=10, groupsel1='all', groupsel2='all')

metr=Metric(sims)

metr.set([metric1, metric2])
data = metr.project()
```

**Comment by j3mdamas** [comment]
@stefdoerr we run NVT as the standard for production, but many people run NPT (before coming to Acellera I always ran NPT, for example). That being said, I don't know how much effort do we want to put it into supporting it, I assume the box size influences the mindist calculations across PBC? Is that it?

**Comment by stefdoerr** [comment]
It seems easy enough but its like maybe an hour of debugging and testing changes in the C code (to not break things). Not the end of the world but not something I'm willing to do just now.

**Comment by j3mdamas** [comment]
Sure, of course.

@andt88, there will be a waiting time. If you want to be able to do the analysis, you'll have to run in NVT.

**Comment by andt88** [comment]
Thanks for the quick feedback. I'm still surprised by that this is coming up only just now even though I've been working with this trajectory for a while now. I ran through the whole process from featurization, TICA, clustering to MSM multiple times.

**Comment by j3mdamas** [comment]
Yes. If you started using groupsel, that's the reason for it.

**Comment by andt88** [comment]
Ok thanks!

**Comment by andt88** [comment]
Hi all,
I have a question regarding mindist. How does it handle situations in which the protein crosses the PBC box as depicted in the attached picture:

![screenshot at 2018-10-18 20-19-26](https://user-images.githubusercontent.com/36545428/47175265-0403d700-d313-11e8-9cb9-ef8ce3ce3ebc.png)

Is it able to measure across the boundaries of the box? Or is it necessary to restrain the protein to the center of the box? 
Thanks a lot for your help!

**Comment by stefdoerr** [comment]
It should handle it fine. As long as the box size is fixed which is the only current limitation.

**Comment by stefdoerr** [comment]
@andt88 I fixed the issue now. HTMD should support different box sizes per frame for mindist calculations. There is no release yet but if you use the github version of HTMD you can do a pull and try it out

**Comment by andt88** [comment]
Thanks a lot!
