### ISSUE TITLE
NGL Viewer using a virtual desktop

### ISSUE THREAD

**Issue by Micah-C** [Acellera/htmd#775]
Hello,

I'm attempting to use HTMD via Ubuntu 16.04 LTS running using Virtual Box. I use jupyter notebooks to operate HTMD. Whenever I try to display a molecule using ngl viewer nothing actually happens. For example, take the sample code:

from htmd.ui import *
m = Molecule('2HBA')
m.filter('(protein and chain A) or waters within 5 of (protein and chain A)')
m.view(viewer='ngl')

The first three lines seem to operate well but nothing happens on the fourth line. Is this a problem stemming from trying to do this on a virtual desktop? Is there an issue with my code? 

Many thanks.

**Comment by stefdoerr** [comment]
Hey, did you try calling `jupyter-nbextension enable nglview --py --sys-prefix`?
If this still doesn't work check the javascript console of your viewer to see if there is any error.

**Comment by Micah-C** [comment]
> Hey, did you try calling `jupyter-nbextension enable nglview --py --sys-prefix`?
> If this still doesn't work check the javascript console of your viewer to see if there is any error.

This solved the issue! Thanks for the help.
