### ISSUE TITLE
FutureWarning

### ISSUE THREAD

**Issue by raimis** [Acellera/htmd#779]
*HTMD* logs are full of these message:
```
/home/raimis/htmd.git/htmd/molecule/readers.py:200: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if np.issubdtype(mol._dtypes[field], np.float) \
```
```
/home/travis/miniconda/envs/travis-env/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
_nan_object_mask = _nan_object_array != _nan_object_array
```

**Comment by stefdoerr** [comment]
I take it back. Seems like I have fixed the first one but not commited. I will on Monday

**Comment by stefdoerr** [comment]
We can keep on silencing things but in the end it might bite us in the ass if we just disable loggers. We can just wait for their next version instead.

**Comment by stefdoerr** [comment]
I will close this issue. The ones posted above have been resolved. The only ones I get now is for pyemma being old but we cannot update it due to dependency conflicts.
