### ISSUE TITLE
Parameterization tool

### ISSUE THREAD

**Issue by slovera** [Acellera/htmd#78]
Hi guys,

I am trying to use the parameterization tool but I got this error:

"Failed to run parameterization : 
 Failure in step   : input
    -- 
/work/miniconda3/bin/htmd_babel: line 2: 82245 Segmentation fault      LD_LIBRARY_PATH="$DIR/../lib/compat-libc" "$DIR/htmd_babel.bin" 

I have deleted and then installed again conda.
I have also tried 'conda install compat-libc' with no success.
Could you advice please?

Thank you very much!
Silvia

**Comment by stefdoerr** [comment]
The parametrization is currently being rewritten by @mj-harvey. I don't know if he has anything to say on the old version.

**Comment by slovera** [comment]
I am working on version 1.3.1

**Comment by j3mdamas** [comment]
Hi @mj-harvey,
silvia is working on an OpenSuse linux distribution machine. Here is the output of:
```
$ cat /etc/SuSE-release
SUSU Linux Enterprise Desktop 11 (x86_64)
Version=11
patchlevel=4
```

**Comment by stefdoerr** [comment]
Install openbabel from omnia and symlink it to htmdbabel

**Comment by slovera** [comment]
Unfortunately still not working:

/work/miniconda3/bin/htmd_babel: line 2: 75010 Segmentation fault LD_LIBRARY_PATH="$DIR/../lib/compat-libc" "$DIR/babel" $@
Non-zero exit code from /work/miniconda3/bin/htmd_babel:

**Comment by mj-harvey** [comment]
Hi,

The workaround for this is to remove the "htmd-babel" package and install
the openbabel one, then symlink "babel" to "htmd_babel".
This problem will be fixed in the next release.

Matt

On 13 July 2016 at 15:19, slovera <notifications@github.com> wrote:

> Unfortunately still not working:
>
> /work/miniconda3/bin/htmd_babel: line 2: 75010 Segmentation fault
> LD_LIBRARY_PATH="$DIR/../lib/compat-libc" "$DIR/babel" $@
> Non-zero exit code from /work/miniconda3/bin/htmd_babel:
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/78#issuecomment-232369471>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHh-DW57D_b8aJDvk0bgbqjKQf_w9rl9ks5qVPPdgaJpZM4JFJ4U>
> .
>



-- 
<https://www.acellera.com>


<https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>
    <https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/acellera>
<https://www.acellera.com/md-simulation-blog-news/>     [image:
skype:acellera] <http://is.gd/1eXkbS>

**Comment by j3mdamas** [comment]
Maybe this was my fault then, because I told Silvia to install openbabel and modify the `htmd_babel` to point to `babel` instead of `htmd_babel.bin`

**Comment by giadefa** [comment]
The old parametrization tool is deprecated. A new one will appear in a couple of weeks for testing.
