### ISSUE TITLE
Add py3.7, deprecate py3.5

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#780]
Miniconda3 seems to be already on py3.7 by default, I think we should add it and deprecate 3.5.

**Comment by j3mdamas** [comment]
OK, Travis supports 3.7, just had to change the distribution to `xenial`.

Now it's a question of the dependencies. First fail, pyemma (actuall, bhmm, but it's general). I've asked them about future support: https://github.com/markovmodel/PyEMMA/issues/1369

**Comment by j3mdamas** [comment]
I guess the priority depends on dependencies, so I've marked it as such

**Comment by j3mdamas** [comment]
thanks @raimis. I'll keep the branch open and we'll see as dependencies update to py 3.7.

**Comment by raimis** [comment]
*Psi4* 1.3 was released: https://github.com/psi4/psi4/releases/tag/v1.3

It doesn't support *Python* 3.5 anymore.

**Comment by j3mdamas** [comment]
@stefdoerr already deprecated py3.5. I don't know when it is ready for py3.7 though.

**Comment by stefdoerr** [comment]
rdkit doesn't have a correctly working version for 3.7 so we need to wait
for them to fix this bug https://github.com/rdkit/rdkit/issues/2386 before
making a 3.7 release.

**Comment by j3mdamas** [comment]
OK; so the Priority is well set. Thanks for the feedback!

**Comment by stefdoerr** [comment]
Added 3.7 version now in moleculekit. Newest rdkit (2019.03.4) does not break SMILES and SMARTS anymore, only the 2D depictions which we don't need as much as the newer features. Additionally the latest version works on OSX.

**Comment by stefdoerr** [comment]
Done.
