### ISSUE TITLE
"Molecule" importing takes too long

### ISSUE THREAD

**Issue by raimis** [Acellera/htmd#784]
```bash 
$ time python -c 'from htmd.molecule.molecule import Molecule'

Copyright by Acellera Ltd. By executing you are accepting the License. In order to register, run htmd_register on your terminal


HTMD Config file /shared/raimis/opt/acellera/conf.py executed.

real	0m4.225s
user	0m3.911s
sys	0m0.247s
```

**Comment by raimis** [comment]
@stefdoerr can you look at this, please. It seriously impeding @j3mdamas 's 1.5 s goal. :)

**Comment by stefdoerr** [comment]
This is kind of a joke at this point. We have had long discussions about this and I gave up.

**Comment by stefdoerr** [comment]
https://github.com/Acellera/htmd/pull/785 moved the jits to `htmd.molecule.utils`. 
Still this is a game you cannot win. If you now import `htmd.molecule.utils` you will be slow again. If `htmd.molecule.molecule` one day imports `utils` in the header it will be slow again. 
Delayed imports is the solution to your problem

**Comment by j3mdamas** [comment]
To wrap up the discussion here: we do not care if the python module takes a long time to load - if you're on python, you're a developer and understand the time it takes and wait. The concern is when using command-line interfaces (for end-users), where the responsiveness of something as simple as `-h` should be instantaneous. For those, we need to take care of the imports and make them lazy.
