### ISSUE TITLE
Get TICA dimensions, kinetic variance

### ISSUE THREAD

**Issue by andt88** [Acellera/htmd#794]
Hi all,

I am trying to get the number of dimensions after running TICA and the percentage of kinetic variance they represent. Is this possible?

**Comment by stefdoerr** [comment]
Yes sure. The pyemma object is inside the htmd object so if you called `tica = TICA(...)` then you can to `pyemmatica = tica.tic` and get the pyemma tica object and do whatever you want with it.
The number of dimensions you can also simply get by the output of `tica.project` by doing `datatica.numDimensions`. You probably need to check the [tica.tic.cumvar](http://www.emma-project.org/v2.5.2/api/generated/pyemma.coordinates.transform.TICA.html#pyemma.coordinates.transform.TICA.cumvar) variable.
