### ISSUE TITLE
acemd-protocols package

### ISSUE THREAD

**Issue by tonigi** [Acellera/htmd#795]
This is still around, not sure if intended.

https://anaconda.org/acellera/acemd-protocols

**Comment by j3mdamas** [comment]
Hi @tonigi,

Yes, we no longer support them. I can kill them at some point but people haven't been coming to us for them, except for the people that already had them shipped before, so I think it's OK. The HTMD acceptance is high, fortunately.

João

**Comment by tonigi** [comment]
What I meant is that protocols are already included in the htmd package, there is no need for a separate one.

**Comment by j3mdamas** [comment]
these are the old tcl protocols, which HTMD replaced. this package will eventually be deprecated and deleted,
