### ISSUE TITLE
Writing .latestversion on readonly filesystem

### ISSUE THREAD

**Issue by giadefa** [Acellera/htmd#8]
By starting HTMD on a readonly installation it has no permission to write latestversion. What is writing?  

  f = open(fname, 'w')
OSError: [Errno 30] Read-only file system: '/acellera/current/python/lib/python3.5/site-packages/htmd/.latestversion

**Comment by stefdoerr** [comment]
Ah yes, I think Noelia also had that problem. It writes the latest version of HTMD in a file. That way I don't need to poll the htmd server every time you start htmd for new versions but instead only once per day.

**Comment by giadefa** [comment]
Yes, but it cannot be assumed that the installation directory is writable.



On 2 April 2016 at 09:13, Stefan <notifications@github.com> wrote:

> Ah yes, I think Noelia also had that problem. It writes the latest version
> of HTMD in a file. That way I don't need to poll the htmd server every time
> you start htmd for new versions but instead only once per day.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Acellera/htmd/issues/8#issuecomment-204664429>
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>

**Comment by stefdoerr** [comment]
So we write to the home directory then? `~/.htmd/` ?

**Comment by giadefa** [comment]
or shutdown version identification if the install directory is not writable

On 2 April 2016 at 10:00, Stefan <notifications@github.com> wrote:

> So we write to the home directory then? ~/.htmd/ ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Acellera/htmd/issues/8#issuecomment-204669042>
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>

**Comment by stefdoerr** [comment]
I made a commit now that writes to the home dir. But someone should check it

**Comment by stefdoerr** [comment]
Added a few more checks for folder existence and write permissions. But please someone check it because I am doing the changes through firefox...

**Comment by stefdoerr** [comment]
The changes are in multiscalelab/htmd, not directly here

**Comment by giadefa** [comment]
fixed
