### ISSUE TITLE
Questions about values in Ligand Binding Analysis Script

### ISSUE THREAD

**Issue by waskom** [Acellera/htmd#80]
The tutorial uses:    
tica = TICA(data, 20)
dataTica = tica.project(3)

How did the 20 and the 3 get chosen?

**Comment by stefdoerr** [comment]
That is a good question :)
Theoretically it depends on your system. If you read the original TICA papers they say that TICA is relatively robust to variations in the TICA lag-time (here 20 frames). I definitely depends on the system you are analyzing and you might need a bigger value. 
TICA however is not very good at high dimensional projections. I am writing something on that these days. So I would not go much over i.e. 5 dimensions.

In the tutorial these are just values that we tested and worked. If they don't work in your case you a free to try others. It's unfortunate that there are no real robust ways of determining these values right now.
