### ISSUE TITLE
update problems

### ISSUE THREAD

**Issue by smar966** [Acellera/htmd#806]
Hi,
I've just updated the htmd as requested wjile running some analysis notebooks, and now these notebook are not running.
I've already tried to re-install it with 'conda install -c acellera -c psi4 htmd', and still not working.
What should I do?

Thanks in advance

**Comment by stefdoerr** [comment]
Could you please post the error? Otherwise it's hard to guess what went wrong.

**Comment by smar966** [comment]
/home/sergio/miniconda3/compiler_compat/ld: cannot find -lpthread
/home/sergio/miniconda3/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/home/sergio/miniconda3/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/home/sergio/miniconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 46, in <module>
    from zmq.eventloop import ioloop
  File "/home/sergio/miniconda3/lib/python3.6/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/home/sergio/miniconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/sergio/miniconda3/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/sergio/miniconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/sergio/miniconda3/lib/python3.6/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/sergio/miniconda3/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: libsodium.so.23: cannot open shared object file: No such file or directory

**Comment by stefdoerr** [comment]
This is not related to HTMD. This is related to the `zmq` package which is not used by HTMD. So it seems like your conda installation possibly broke after updating other packages not related to HTMD.

My best suggestion is to reinstall the whole miniconda. Trying to fix broken packages in conda is a lose-lost game.

**Comment by smar966** [comment]
OK, I'll try to do that. 
Thanks

**Comment by stefdoerr** [comment]
Generally I'd suggest against updating stuff in conda or at least keeping in mind the risks. I would say from my experience that around 50% of the time something breaks if you update. I either create a new environment which is faster or reinstall conda from scratch.

**Comment by stefdoerr** [comment]
@j3mdamas maybe we should stop suggesting to people to update to the latest HTMD version and just say there is a new version available without giving the update command?

**Comment by smar966** [comment]
The command for the updating was given and I used it. But still got into these troubles.
And it's actually the second time something like this happens

**Comment by stefdoerr** [comment]
Yes, I agree that's why I'm suggesting we should remove the command suggestion from the news post. It's not really an issue of HTMD, conda sometimes decides to update other packages with HTMD which then break for random reasons. I know it's a decent bit of time and trouble reinstalling all the packages, I'm sorry.

**Comment by j3mdamas** [comment]
> @j3mdamas maybe we should stop suggesting to people to update to the latest HTMD version and just say there is a new version available without giving the update command? Then at least it's not our responsibility when conda breaks.

I agree. I've already removed from the news. It's also displayed when there's a newer version. What do you think we should recommend? New environment creation? New conda installation?

I would propose the following text (adapted from the current one):

``` python
print('New {} HTMD version ({}{}) is available. You are currently on ({}).'
      'There are several methods to update:'
      '    - Run: `conda update htmd -c acellera -c psi4` (NOT RECOMMENDED)'
      '    - Create a new conda python environment from scratch and run `conda install htmd -c acellera -c psi4`'
      '    - Create a brand new conda installation and run `conda install htmd -c acellera -c psi4`'
      'Note: A new Python version may also be needed if the current Python version is no longer supported'.format(verstring, latest, pydeps, currver))
```

What do you think?

**Comment by stefdoerr** [comment]
Yes, remove the python version message though since we don't recommend updating anyway. Also maybe you should put the update option last.

Also you could give directly the command like:
```
- Create a new conda HTMD environment with `conda create -n htmd htmd={} -c acellera -c psi4`
- Create a brand new conda installation and run `conda install htmd -c acellera -c psi4`'
- Run: `conda update htmd -c acellera -c psi4` (NOT RECOMMENDED)'
```
