### ISSUE TITLE
htmd.builder.amber parameter param

### ISSUE THREAD

**Issue by piia600** [Acellera/htmd#81]
Hi,

I am trying to build a system using amber force field, but I can't seem to load an frc_mod2-file for the ligand parameters. Even though I can submit it in the commands, the value of param is not even written anywhere in the tleap.in file. This seems to be some sort of bug, since by adding the line manually to the tleap.in (loadamberparams frcmod_lig2) the parametrization will work (except that the resulting structure is not ionized).

The command I am using
molbuilt = amber.build(solvated, ff=['leaprc.ff14SB'], topo=['subs.prepi'], param=['frcmod_lig2'], ionize=True, outdir='./build/', saltconc=0.1)

and the tleap.in and the log
[tleap.txt](https://github.com/Acellera/htmd/files/357173/tleap.txt)
[log.txt](https://github.com/Acellera/htmd/files/357172/log.txt)

Cheers,
Piia

**Comment by stefdoerr** [comment]
Oh yes, it is indeed a bug. I apologize. It will be fixed together with some other AMBER issues in the next release.

**Comment by stefdoerr** [comment]
Fixed in https://github.com/multiscalelab/htmd/commit/d72a5d9c0e8ff1a116431859d463d6f9269eb053

**Comment by j3mdamas** [comment]
ahhh, but if this is a bugfix, it should have been done on the stable version, no? We do no longer release from multiscalelab or merge it into stable.

**Comment by stefdoerr** [comment]
I don't know. Add it manually to the stable. It's getting a bit too confusing for me working on branches on multiscalelab and then having to do fixes with other branches on acellera. I guess I will try to keep in mind from now on to do fixes on acellera and then merge them back into multiscalelab.

Actually in that sense, is there any reason for multiscalelab to exist anymore, if we have stable and devel versions on acellera?

**Comment by j3mdamas** [comment]
for me there isn't, but we have to discuss it on the next development meeting. I am going to send an e-mail about development meeting.
