### ISSUE TITLE
Installing a dev version using miniconda3

### ISSUE THREAD

**Issue by MBenabderrahmane** [Acellera/htmd#811]
Hi,
As the Fix PRM writer for CGENFF #777 was included, I'd like to install the version(which one ?) containing the fix. Can someone help on this ? I will appreciate it 

MB

**Comment by j3mdamas** [comment]
Hi @MBenabderrahmane,

We have been working on parameterize. We should release this week.

I'll write here when we do.

João

**Comment by MBenabderrahmane** [comment]
@j3mdamas  @stefdoerr 
Thanks a lot 
M.B
