### ISSUE TITLE
remove htmd-data from htmd dependencies

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#812]
- [ ] test if `run_constrained` works as expected
- [ ] move `htmd-data` from `run` to `run_constrained` in `htmd-deps`

**Comment by j3mdamas** [comment]
Oh, apparently it's much easier to do this, by using a conda feature that is not documented:
https://github.com/conda/conda/issues/1696#issuecomment-300309736
https://github.com/conda/conda-build/issues/1964

Basically, we just need to move `htmd-data` run dependency to `run_constrained`, which means that it is not required, but when one asks to install, it will install the correct htmd-data version for that htmd version, which is exactly what is needed here.

**Comment by stefdoerr** [comment]
https://github.com/Acellera/htmd/commit/dfc0fd8bebc8916223e0d1080523e5c31e32f9f1 This ought to fix it

**Comment by j3mdamas** [comment]
did you test it?

**Comment by stefdoerr** [comment]
![image](https://user-images.githubusercontent.com/7935362/59499755-b5f2a380-8ea0-11e9-9133-4519f0cf0e7a.png)

**Comment by j3mdamas** [comment]
now seriously, did you test if it works?

**Comment by stefdoerr** [comment]
j/k but yes I ran it locally to see if it built and it built fine. If it works on the level of pulling the correct deps I will have to see when it's up on conda. I don't see how else I can test it locally.

**Comment by stefdoerr** [comment]
In any case, the repercursion if it doesn't work are close to 0. HTMD does not depend on htmd-data really. Just for some deployments you want to test which are not going to happen in the time between me uploading it to conda and downloading it to test.

**Comment by stefdoerr** [comment]
Tested and indeed it does not pull htmd-data. 

```
$ conda search htmd-deps=1.15.2 --info
[...]
constraints : 
  - htmd-data ==0.1.hash356a8e8
dependencies: 
  - acecloud-client >=1.0.42
  - acemd >=2019.01.24
  - ambermini >=16.16.0
  - anaconda-client >=1.7.2
  - dftd3 >=3.2.1
  - htmd-pdb2pqr >=2.1.1+htmd.5
  - ipyparallel >=6.2.4
```
Seems legit

**Comment by j3mdamas** [comment]
perfect, thanks! Let me confirm it in production and I'll close the issue

**Comment by stefdoerr** [comment]
It works as expected but only if you version-lock htmd or htmd-deps when requesting htmd-data.
So `conda install htmd=1.15.2 htmd-data -c acellera -c psi4` will work, same with `htmd-deps=1.15.2` but not just `conda install htmd-data -c acellera` because it will try to pull the "latest" htmd-data by sorting the hashes of the packages and then downgrade htmd-deps.

**Comment by j3mdamas** [comment]
hi @stefdoerr,
I don't remember if we tested if this worked in the end, so maybe it should be closed, but I'm going to unassign myself.
