### ISSUE TITLE
Need OS X build environment / cross-compile for closed-source DSOs

### ISSUE THREAD

**Issue by mj-harvey** [Acellera/htmd#83]

**Comment by mj-harvey** [comment]
Reminder to look at the cross-compile environmetn toni mentioned to me

**Comment by giadefa** [comment]
checking cross compiler

**Comment by mj-harvey** [comment]
@tonigi  what was the cross-compiler you mentioned?

**Comment by tonigi** [comment]
https://github.com/tpoechtrager/osxcross

Il 08 set 2016 2:00 AM, "M J Harvey" <notifications@github.com> ha scritto:

**Comment by giadefa** [comment]
compiling on mac, needs to move to 1.6

**Comment by j3mdamas** [comment]
How are we on Mac compilation?

**Comment by mj-harvey** [comment]
We can clsoe this now - the building it done in the travis environment
