### ISSUE TITLE
Will be nice to have a 'How to Install' for Mac Os X

### ISSUE THREAD

**Issue by pathri** [Acellera/htmd#835]
Thanks for the kind response and pointing me to your Git repo. Is it possible to provide quick-install instructions for a Mac? 
Thanks in advance,
Prashanth

**Comment by j3mdamas** [comment]
Dear @pathri,
There is no conda installation support for MacOs. You may install HTMD dependencies (if available) and then use this repository by cloning it and adding it to `PYTHONPATH`

João

**Comment by stefdoerr** [comment]
To elaborate:
```
git clone https://github.com/Acellera/htmd/
# add to your bashrc the path via `export PYTHONPATH=/path/to/htmd/folder/:$PYTHONPATH`
cd htmd
conda install --file package/htmd-deps/DEPENDENCIES
```
and good luck!

**Comment by pathri** [comment]
That helped a lot. Thanks so much.
