### ISSUE TITLE
Faulty GPU metrocubo check 

### ISSUE THREAD

**Issue by shozebhaider** [Acellera/htmd#836]
Hi,

I am running adaptive sampling on a Metrocubo workstation (with 4x1080 Ti GPUs) and it keeps crashing.  However, if I run a simple simulation on individual GPU, it runs fine. A combination of two GPU is also fine. I suspect a faulty GPU but then I might be wrong. 
Is there a rational way to find out a faulty GPU on Metrocubo ? 
Using HTMD 1.13.9, Nvidia driver 390.87 , Cuda 9.2.88, Ubuntu 18.04.1

Many thanks.

**Comment by stefdoerr** [comment]
How does it crash? What's the error?

**Comment by shozebhaider** [comment]
There is no error message from the sampling. However, there is a message of GPU being lost. There no info via nvidia-smi and ghost simulations keep running without any output.

**Comment by stefdoerr** [comment]
You could go into one of the `input` subfolders inside the adaptive folder and run `acemd --device X` to see which one fails

**Comment by j3mdamas** [comment]
Hi @shozebhaider,
Furthermore, you can also try to look at the `log.txt` of ACEMD from the last epoch, to see if there's some extra information there.

**Comment by shozebhaider** [comment]
Thanks guys. It was indeed a faulty GPU. There is no automated way to figure out which one was faulty. However, running acemd --device X. on the faulty GPU crashes the run. 
Thanks for your help.
