### ISSUE TITLE
Parameterize error

### ISSUE THREAD

**Issue by giopina** [Acellera/htmd#843]
I'm running parameterize with the following command:
`parameterize linker_model.mol2 --charge -1 --charge-type ESP --outdir final1 --fix-charge C3p O3p O1P O2P P`

And getting the following error:
`Traceback (most recent call last):
  File "/group/ag_cmb/scratch/giopina/software/miniconda/envs/htmd/bin/parameterize", line 11, in <module>
    sys.exit(main_parameterize())
  File "/group/ag_cmb/scratch/giopina/software/miniconda/envs/htmd/lib/python3.6/site-packages/htmd/parameterization/cli\
.py", line 721, in main_parameterize
    parameters = df.run()
  File "/group/ag_cmb/scratch/giopina/software/miniconda/envs/htmd/lib/python3.6/site-packages/htmd/parameterization/dih\
edral.py", line 398, in run
    self._fit()
  File "/group/ag_cmb/scratch/giopina/software/miniconda/envs/htmd/lib/python3.6/site-packages/htmd/parameterization/dih\
edral.py", line 354, in _fit
    assert np.allclose(initial_energies, const_energies + actual_enegies, rtol=0, atol=1e-5) # TODO debug
AssertionError
`

**Comment by raimis** [comment]
Could you share the molecule and the full log, so I could reproduce the problem.

**Comment by giopina** [comment]
[linker_model.zip](https://github.com/Acellera/htmd/files/2796276/linker_model.zip)
Here you are.

Thanks for your help

**Comment by giopina** [comment]
Is there any update? did you manage to reproduce the error?

**Comment by raimis** [comment]
@giopina 

I would recommend to use MM-based scanner:
```
parameterize linker_model.mol2 --charge -1 --charge-type ESP --outdir final1 --fix-charge C3p O3p O1P O2P P --min-type mm --scan-type mm
```
Is much faster (no QM minimization, just single point calculations) and produces better results: [parameters.zip](https://github.com/Acellera/htmd/files/2831633/parameters.zip)

**Comment by giopina** [comment]
Thanks for the advice!
The optimization that you suggested worked without crashes.

However, I now have a problem with fixing the charges (opening another issue for that)

**Comment by j3mdamas** [comment]
I think this is solved and can be closed
