### ISSUE TITLE
acemd3 instability

### ISSUE THREAD

**Issue by almman** [Acellera/htmd#846]
I've been testing acemd3 (v3.0.2) against acemd and have noticed a stability issue. Further testing seemed to suggest that by default acemd3 is not effective in keeping water molecules rigid, even though it did report the following on start-up:

"# Constraining H-x bonds"
"# Making all waters rigid"

Using several input files that work ok in acemd and other software, the result is unusually large bond energies and overall instability.

Does anyone know how it detects water molecules and what parameters it uses to keep water molecules rigid, or could this be a bug?

**Comment by raimis** [comment]
@almman thanks for reporting. Could you share the input files to reproduce the issue, please.

**Comment by almman** [comment]
Here's a simple example - a small water box

#   Timestep      Time/ps         Bond        Angle        Dihed         Impr         CMAP           NB          Ext           PE           KE       TotalE       Temp/K         nm^3       ns/day
            0         0.00        0.204        0.000        0.000        0.000        0.000    -4524.811        0.000    -4524.608     1216.597    -3308.011      290.564       27.000        0.000
        25000       100.00      383.006        0.000        0.000        0.000        0.000    -5525.033        0.000    -5142.026     1174.355    -3967.672      280.476       27.000     1080.000

After a 100ps the bond energy is high and it is unstable with thermostatDamping<10. I have also tested with a reduced force constant on the water H-H constraint "bond" and while the energy is now stable the water molecules lose their shape. Normally programs use this bond length in the SHAKE algorithm but do not calculate its energy.

I suspect ACEMD3 is calculating the H-H bond energy and not applying SHAKE for some reason. If true I believe this is incorrect. There may also be another way to turn on SHAKE.

[test.zip](https://github.com/Acellera/htmd/files/2808286/test.zip)

**Comment by raimis** [comment]
Thanks @almman I'll try to reproduce the problem.

**Comment by almman** [comment]
Thanks.

Just for information these are the AMBER TIP3P parameters. The two bonds (bold) have huge force constants and as far as I am aware are only supposed to be calculated during energy minimization; during dynamics they should be constrained to the equilibrium length.

MASS
OW    16.0
HW     1.008   0.000
 
BOND
**OW-HW  553.0    0.9572      TIP3P water
HW-HW  553.0    1.5136      TIP3P water**
 
ANGLE

DIHE

NONBON
  OW          1.7683  0.1520             TIP3P water model
  HW          0.0000  0.0000             TIP3P water model

**Comment by j3mdamas** [comment]
@raimis isn't this a major issue?

**Comment by raimis** [comment]
Fixed in ACEMD 3.1.0rc1
