### ISSUE TITLE
mol2 writer atom types format

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#847]
The mol2 writer could offer the possibility of compatibility with chemoinformatics tools (e.g. openbabel, rdkit).

Rdkit expects Corina atom types or Tripos sybyl (not as assured): http://rdkit.org/docs/source/rdkit.Chem.rdmolfiles.html
Openbabel uses Tripos sybyl atom types: https://media.readthedocs.org/pdf/open-babel/latest/open-babel.pdf

Tripos sybyl atom types example reference: http://www.cmbi.ru.nl/samsam/tutorials/studs/mopac/force_field3.html

MDAnalysis provides the "official" format, for example: https://www.mdanalysis.org/docs/documentation_pages/coordinates/MOL2.html

**Comment by stefdoerr** [comment]
I don't see this as a meaningful addition. Molecule is not meant to have any sort of chemical understanding/fixing. This is the job of rdkit and other packages. If we don't read in atom types we should not expect atom types out.
