### ISSUE TITLE
Simulating Zinc

### ISSUE THREAD

**Issue by shozebhaider** [Acellera/htmd#848]
I am trying to run a simulation which has two non-bonded zinc ions (ff14SB) that are positioned inside a surface cavity. Not surprisingly they fly away during equilibration. 

There are other ways to hold them in place. One of them is described in https://www.mayo.edu/research/labs/computer-aided-molecular-design/projects/zinc-protein-simulations-using-cationic-dummy-atom-cada-approach
When I follow this approach I get an error just after initial minimisation:
**# Launch failure: Kernel [scale_coords] grid [0,1,1] block [256,1,1] Shmem [0] Error [1]**

A second approach, which is what I would like to follow is a restrained non-bonded model as described here (http://ambermd.org/tutorials/advanced/tutorial20/rnb.htm). While I can provide a **consref** pdb file that has the applied restraints, how do I treat constraintscaling for a production run? Is there an example that you can provide that has worked for restraints on zinc, water and histidines. 

Many thanks 

Shozeb

**Comment by stefdoerr** [comment]
Is this with ACEMD2 or ACEMD3?

**Comment by shozebhaider** [comment]
ACEMD2

**Comment by j3mdamas** [comment]
Hi @shozebhaider,

Can you share the files to reproduce that issue?

Regarding the second approach, I am afraid it is not implemented in HTMD, as we do not have MCPB compatibility as of now.

**Comment by j3mdamas** [comment]
OK, will follow there. Closing.
