### ISSUE TITLE
Parameterize equiv-org.txt, fixq.txt and neutral.txt files ignored

### ISSUE THREAD

**Issue by dieAnto** [Acellera/htmd#85]
I am using parameterize to optimize ligand parameters. To speed up the procedure, I use the divide and conquer approach suggested by MacKerell by breaking the molecules and capping the boundaries with methyl groups (or whatever more appropriate group) and define equivalent atoms, neutral groups and fixed charges atoms. Equivalent atoms not always apply of course, however the definition of neutral groups is fundamental to allow me to recycle the parameterized scaffold, by removing capping groups and adding the new desired functional group. Fixed charges atoms (such as an example aliphatic hydrogen atoms have a charge of +0.090) are also required for the optimized charges to be consistent with cgenff. I therefore created three text files where I specified atom indexes (one entry per line) with a format compliant to the input files accepted by gaamp.
Here is how my input file looks like:

JobName 23
FileName 23.mol2
NetCharge 0
Equivalent **23_eq.txt**
FixCharges **23_fc.txt**
Neutral **23_neu.tx**t

Apparently, it looks like parameterize accepts them as it prints out the following:
You are on the latest HTMD version (1.3.1).
 === Acellera Small Molecule Parameterization 2016 (c) === 

```
    AsymmetricTorsion False
                Debug False
               E14Fac 1.0
           Equivalent 23_eq.txt
        ExecutionMode Inline
             FileName 23.mol2
           FixCharges 23_fc.txt
         GAUSS_SCRDIR /tmp
              JobName 23
               MEMORY 16
           MaxTorsion 25
                Model Nonpolar
         Multiplicity 1
               NCORES 12
            NetCharge 0
              Neutral 23_neu.txt
             Torsions None
   w_H_Donor_Acceptor 1.0
              w_alpha 0.4
             w_charge 3.0
              w_thole 0.2
        w_water_E_min 0.4
        w_water_R_min 8.0
             wd_alpha 0.4
            wd_charge 1.0
             wd_thole 0.2
       wd_water_E_min 0.4
       wd_water_R_min 8.0
```

Moreover, in the .htmd/gaamp/23/ directory, in the 000-input subdirectory, I can find the following files: **equiv-org.txt**, **fixq.txt** and **neutral.txt**, with their content corresponding to 23_eq.txt, 23_fc.txt and 23_neu.txt, respectively.

However, when I inspect the output charges there is no trace of neither the constrained neutral groups nor the fixed charges. Moreover, by looking at the "configuration" file in the .htmd/gaamp/23/ directory, it looks like the program is pointing at the wrong file when defining the equivalent groups whereas it does not define any path for the other two.

```
    AsymmetricTorsion False
                Debug False
               E14Fac 1.0
           Equivalent /home/XXX/.htmd/gaamp/23/000-input/fixq.txt
        ExecutionMode Inline
             FileName 23.mol2
           FixCharges 23_fc.txt
         GAUSS_SCRDIR /tmp
              JobName 23
               MEMORY 16
           MaxTorsion 25
                Model Nonpolar
         Multiplicity 1
               NCORES 12
            NetCharge 0
              Neutral 23_neu.txt
   w_H_Donor_Acceptor 1.0
              w_alpha 0.4
             w_charge 3.0
              w_thole 0.2
        w_water_E_min 0.4
        w_water_R_min 8.0
             wd_alpha 0.4
            wd_charge 1.0
             wd_thole 0.2
       wd_water_E_min 0.4
       wd_water_R_min 8.0
```

Can somebody help me in understanding what is going wrong and, most importantly, if I am doing something wrong?

**Comment by j3mdamas** [comment]
I will try to look into the code. 
A test case would help me, so is it possible for you to share the files with me or is it confidential?

**Comment by dieAnto** [comment]
The second option you said, unfortunately.
If it can help, I can try to run a model compound and see if I get the same problem.

**Comment by j3mdamas** [comment]
that would be helpful, if you can. thanks!

**Comment by dieAnto** [comment]
I am running the procedure on a model compound. I will be able to provide you with more details and the input files tomorrow.

**Comment by dieAnto** [comment]
I run parameterize on a model compound. In the input file [NMC.inp.txt](https://github.com/Acellera/htmd/files/366153/NMC.inp.txt), the three files with indexes for equivalent atoms [NMC_eq.txt](https://github.com/Acellera/htmd/files/366141/NMC_eq.txt), fixed charges [NMC_fc.txt](https://github.com/Acellera/htmd/files/366143/NMC_fc.txt), and neutral groups [NMC_neu.txt](https://github.com/Acellera/htmd/files/366144/NMC_neu.txt) are specified.

Those files are copied as "equiv-org.txt", "fixq.txt", and "neutral.txt", in the following directories:
000-input
030-generate_structure
120-fit_esp

But not in the following ones:
150-fit_water 
250-refitcharges 

In the configuration file, still the program seems pointing to the wrong equivalent file. However, I checked the content of the equiv-org.txt and it matches the correct user provided input file.

        AsymmetricTorsion False
                    Debug False
                   E14Fac 1.0
               Equivalent /home/XXX/.htmd/gaamp/NMC/000-input/fixq.txt
            ExecutionMode Inline
                 FileName NMC.mol2
               FixCharges NMC_fc.txt
             GAUSS_SCRDIR /tmp
                  JobName NMC
                   MEMORY 16
               MaxTorsion 25
                    Model Nonpolar
             Multiplicity 1
                   NCORES 12
                NetCharge 0
                  Neutral NMC_neu.txt
       w_H_Donor_Acceptor 1.0
                  w_alpha 0.4
                 w_charge 3.0
                  w_thole 0.2
            w_water_E_min 0.4
            w_water_R_min 8.0
                 wd_alpha 0.4
                wd_charge 1.0
                 wd_thole 0.2
           wd_water_E_min 0.4
           wd_water_R_min 8.0

Even if they are copied in some of the directories, the instructions provided in the files are not taken into account during the charge fitting procedure. Please look at the attached "DIR_final-para.txt" files:
[120-fit_esp_final-para.txt](https://github.com/Acellera/htmd/files/366147/120-fit_esp_final-para.txt) [150-fit_water_final-para.txt](https://github.com/Acellera/htmd/files/366149/150-fit_water_final-para.txt) [250-refitcharges_final-para.txt](https://github.com/Acellera/htmd/files/366148/250-refitcharges_final-para.txt)

In the output topology file [mol.rtf.txt](https://github.com/Acellera/htmd/files/366157/mol.rtf.txt) in the provided optimized charges there is no trace of fixed charges constraints nor of neutral groups.

Please find attached the input/output structures and other relevant files here [Structures.zip](https://github.com/Acellera/htmd/files/366165/Structures.zip)

Thanks in advance for any help you can provide.

**Comment by j3mdamas** [comment]
Thanks for giving me files to test this. I'll try to look into it soon.

**Comment by mj-harvey** [comment]
Hi,

Apologies for the very long delay in following this up. We have a new version of parameterise in HTMD now (1.5.4). This doesn't presently have the capability that you need, but now I see and understand your use case, I will add support for this

**Comment by mj-harvey** [comment]
@dieAnto 1.5.5 will include support for freezing specific atom's charges with the argument --freeze-charge, eg

parameterize -m input.mol2 --freeze-charge C1 --freeze-charge N1 

the value initially specified in the mol2 will be used. Will that be sufficient?

**Comment by dieAnto** [comment]
Hi @mj-harvey thank you for adding this feature!
It is a big step forward and, in my opinion, the need for specifying atom labels makes it much more user friendly than dealing with atom indexes. Still it does require some user's expertise but it is an improvement I will definitely take advantage of!
Thank you

**Comment by j3mdamas** [comment]
@dieAnto, I'll let you know when 1.5.5 is out, and maybe you can test it and give us some feedback?

**Comment by dieAnto** [comment]
@j3mdamas sure!

**Comment by mj-harvey** [comment]
@dieAnto For any further discussion please follow up on issue #186 which relates to implementation of that feature, rather than this bug against the old version of parameterise
