### ISSUE TITLE
# Nvidia driver is too old. Please update to the latest driver for your hardware

### ISSUE THREAD

**Issue by sfsdrake** [Acellera/htmd#852]
acemd 2019.01.24 gives a driver too old error.

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

NVIDIA-SMI 410.93       Driver Version: 410.93       CUDA Version: 10.0

**Comment by sfsdrake** [comment]
acemd.2019.01.24 runs with nvidia 384.111 (no CUDA toolbox installed).

**Comment by stefdoerr** [comment]
@raimis @j3mdamas ?
This is not HTMD related but ACEMD. Could you respond?

**Comment by j3mdamas** [comment]
@sfsdrake if it runs with 384.111, use that driver instead. ACEMD 
2019.01.24 is compiled with CUDA 9.0 and maybe there is a particular driver version of CUDA 10 that may not be working very well regarding back compatibility.
