### ISSUE TITLE
"conda install htmd" does not work

### ISSUE THREAD

**Issue by lunnali** [Acellera/htmd#857]
Dear Users 

I cannot download htmd according to the instructions at https://software.acellera.com/academic-download-htmd.html

$ conda install htmd
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - htmd

Current channels:

  - https://conda.anaconda.org/psi4/osx-64
  - https://conda.anaconda.org/psi4/noarch
  - https://conda.anaconda.org/acellera/osx-64
  - https://conda.anaconda.org/acellera/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Best Wishes
Luna

**Comment by stefdoerr** [comment]
This is on OSX I assume? We don't provide anymore OSX builds since it was too complicated to test and we don't have any OSX machines. Maybe they'll come back in the future if I find time to fix them. You could try cloning the github repo and adding it to your PYTHONPATH and see if that works.

**Comment by lunnali** [comment]
Thanks for the advice! I am not very familiar with this but I will certainly try. 
On the windows machine I have encountered the same problem, I assume it might be the same platform issue? 

Best

**Comment by lunnali** [comment]
> This is on OSX I assume? We don't provide anymore OSX builds since it was too complicated to test and we don't have any OSX machines. Maybe they'll come back in the future if I find time to fix them. You could try cloning the github repo and adding it to your PYTHONPATH and see if that works.

Thanks for the advice! I am not very familiar with this but I will certainly try.
On the windows machine I have encountered the same problem, I assume it might be the same platform issue?

Best

**Comment by stefdoerr** [comment]
Yes we currently only support Linux. We used to have OSX and Windows builds but it was impossible to test and support. I do plan to eventually try at least OSX.

```
git clone https://github.com/Acellera/htmd.git
```
then add the path to the `htmd` folder to your `~/.bashrc` file like
`export PYTHONPATH=/path/to/htmd/folder/:$PYTHONPATH`
