### ISSUE TITLE
Can we change dump frequency??

### ISSUE THREAD

**Issue by RishikeshMagar** [Acellera/htmd#868]
I am running a simulation for 30 ns. When I open the output files to visualize them, I get 300 frames, this indicates that dump frequency is 100ps. 100ps*300 frames = 30 ns. Can I change the dump frequency to 10ps. So that I can have 3000 frames.
I just wanted to know if we can change the dump frequency parameter. Any help would be much appreciated

**Comment by stefdoerr** [comment]
Sure. In the HTMD protocols or with acemd directly? The option is called
xtcfreq
https://software.acellera.com/docs/latest/acemd/commandreference.html

**Comment by RishikeshMagar** [comment]
Thanks a lot. I will close the issue
