### ISSUE TITLE
add constraints to production protocol?

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#87]
I was thinking about adding constraints to the production protocol. maybe create a v3?

I think they are useful, some people use soft constraints for production so that the protein does not rotate and translate. I see at least both Gerard and Noelia are using it.

If people agree, I can add it.

**Comment by j3mdamas** [comment]
Oh, and I know it can be done manually.

**Comment by stefdoerr** [comment]
Sure, play around with it. I think protocols are a nice place for playing with new functionality since you don't have to care about backwards compatibility or anyone using them soon, hahaha :D

**Comment by j3mdamas** [comment]
Hi,
Just added a new production protocol with contraints 63ae2b0e395c7647fee627ab2e0ed0e9d7f1c05b
@stefdoerr, if you'd like to see if it's good or not :P
@noeliaferruz, @GerardBCN, can you please test it, when you have some time? I think you've been defining things manually until now. It will be available on the next release.

**Comment by GerardBCN** [comment]
What's the novelty in this protocol? I believe production protocol already
included the possibility of defining a box, and so on. See production of
this tutorial
https://www.htmd.org/docs/latest/tutorials/mu-opioid-receptor-gpcr-equilibration.html

2016-09-28 15:53 GMT+02:00 João M. Damas <notifications@github.com>:

**Comment by stefdoerr** [comment]
Atom constraints, not flat bottom potentials

**Comment by j3mdamas** [comment]
yeah, what Stefan said. For example, when you wanted to do those umbrella samplings, and wanted to keep the protein fixed (not rotating), you were using constraints, defined manually. Now you can define them with `useconstraints` and `constraints` variables.

**Comment by GerardBCN** [comment]
OK! Thank you!


2016-09-28 16:40 GMT+02:00 João M. Damas <notifications@github.com>:
