### ISSUE TITLE
Join trajectories into one file

### ISSUE THREAD

**Issue by GasparPinto** [Acellera/htmd#880]
I was trying to find in the manual if there was a way to join all the trajectories into one trajectory file so it's easier to work with for some other analysis. 
Is it possible in HTMD?

cheers
G

**Comment by j3mdamas** [comment]
Hi @GasparPinto 

I think the `Molecule.append` method does what you're looking for: https://software.acellera.com/docs/latest/moleculekit/moleculekit.molecule.html#moleculekit.molecule.Molecule.appendFrames

Something like:
```python
m = Molecule('structure.prmtop')
m.read('traj1.xtc')
m.appendFrames('traj2.xtc')

João
```

**Comment by stefdoerr** [comment]
@j3mdamas answered the question correctly so I'll just close this.

**Comment by GasparPinto** [comment]
Hey, yes he did! 

Didn't have time to try it til now! 
Thanks for the help.
