### ISSUE TITLE
Add tests for MetricData and Model loading

### ISSUE THREAD

**Issue by stefdoerr** [Acellera/htmd#883]
Seems like there is an issue with the dicts and loading metricdata and models so we should add some tests.

**Comment by stefdoerr** [comment]
Closed by https://github.com/Acellera/htmd/pull/887

**Comment by j3mdamas** [comment]
Lol, closing before accepting xD

**Comment by stefdoerr** [comment]
In my mind it's solved :laughing:

**Comment by j3mdamas** [comment]
Just do self-merge and it's done :)
