### ISSUE TITLE
psfgen from psfgen-1.6.9-0 segmentation fault

### ISSUE THREAD

**Issue by aqred1** [Acellera/htmd#885]
I am unable to run `charmm.build` due to a failure from the psfgen binary. 

Concretely, after obtaining this error:
`BuildError: 'No structure pdb/psf file was generated. Check /tmp/build/log.txt for errors in building.'`

I manually tried to run `psfgen build.vmd` in the build folder. But the output is  `Segmentation fault (core dumped)`.
Running psfgen alone in the console also gives a segmentation fault.

I circumvented the error by building the systems with `vmd -dispdev text -e build.vmd` instead (which is commented in builder/charmm.py). But are there any particular system specifications to run psfgen? I'm running on an ubuntu 16.04 64-bit workstation. The psfgen binary comes from the conda package psfgen1.6.9  from the acellera channel. Thanks.

**Comment by stefdoerr** [comment]
Could you post the log.txt that it mentions?

**Comment by aqred1** [comment]
Thanks for the quick response. The file is empty.

**Comment by j3mdamas** [comment]
Could you share files for us to reproduce it?

**Comment by aqred1** [comment]
Here are the files:
[build.zip](https://github.com/Acellera/htmd/files/3258772/build.zip)

It is unlikely you will reproduce it. I unzipped the file above and run `psfgen build.vmd` on a macOS and it built fine. However, the same process on my workstation leads always to:
```
aqred1@btjx1:/tmp/build$ psfgen build.vmd 
Segmentation fault (core dumped) 
```
 Also simply running psfgen:
```
aqred1@btjx1:/tmp/build$ psfgen
Segmentation fault (core dumped) 
```
I removed psfgen from my conda environment and downloaded it from the conda-forge channel but the issue persisted. It looks like something specific from psfgen running on our workstations so perhaps there's nothing you can do.

**Comment by stefdoerr** [comment]
Yes, I tested your files and it builds fine here (Ubuntu 19.04, conda psfgen 1.6.9 from acellera)
So if it runs with VMD it means that the psfgen shipped by vmd works on your computer. You could try finding out where it's stored and pass that to `charmm.build`. I don't really know the requirements. But feel free to build it yourself if you want. HTMD charmm.build just needs the path to the psfgen executable and it ought to work fine.

ps.  do you want to run it in implicit solvent? Because I didn't see any waters.

**Comment by stefdoerr** [comment]
By the way, we don't support Mac so use at your own risk ;) Although it's funny that it works on Mac and not on Ubuntu in your case, haha.
Ah also if you want try running `strace psfgen build.vmd`

**Comment by aqred1** [comment]
I could not find a standalone psfgen binary within vmd, but I downloaded NAMD which includes one and passed it to charmm.build as the executable. This worked.
Yes, no waters, the system is in vacuum.

Thanks for your support.

**Comment by stefdoerr** [comment]
You are welcome :) Glad you solved it!
