### ISSUE TITLE
getStates, sampleStates and msm.sample_by_distributions

### ISSUE THREAD

**Issue by andt88** [Acellera/htmd#891]
Hi all,

I am analyzing a Protein-Ligand trajectory using HTMD.
When visualizing Macrostates from an MSM, I obtain very nice visualizations, where the binding sites are well defined. 

When I try to visualize the same model using PyEMMA's sample_by_distribution, the visualization is much fuzzier, and even unbound states are included. 

So I was wondering what getStates actually does different to sample_by_distribution. Shouldn't the outcome be the same, apart from the alignment step?

Thanks a lot for your help!

**Comment by stefdoerr** [comment]
I don't know how pyemma does it. We simply renormalize the probabilities of the microstates inside a macrostate and then sample from that as you can see here in the `weighted` mode 
https://github.com/Acellera/htmd/blob/master/htmd/model.py#L1095

Are you talking about the exact same model here?

**Comment by andt88** [comment]
I did not use the exact same model, but generated it in the same way. My understanding is that PyEMMA does not renormalize the probabilities so that may be an explanation. Thanks a lot!
