### ISSUE TITLE
Parameters for ligand bound to residue

### ISSUE THREAD

**Issue by GasparPinto** [Acellera/htmd#894]
I want to simulate a ligand covalently bound to the catalytic residue. I built the parameters for the ligand bound to the residue (Asp) but now I do am not able to insert the residue and ligand in the protein with the parameters that I built. 
I have both the mol2 and the frcmod but I am not able to run these parameters together with the main protein. 
Have you come across this issue?

**Comment by stefdoerr** [comment]
Could you share some script to see how you are doing it? Or at least what the issue/error is

**Comment by GasparPinto** [comment]
Hey Stefan,

Sure. I have the "noncanonical"  residue in the pdb and then I was giving
the mol2 and the frcmod files, which I will attach to this email.
The problem occurs when I try to build the molecule:


*from htmd.ui import *prot = Molecule('Protein.pdb')prot =
autoSegment(prot, sel='protein', basename='P')*
It creates two segments of the protein (residue 103 is the noncanonical):

2019-07-22 14:54:47,456 - htmd.builder.builder - INFO - Created
segment P0 between resid 9 and 102.
2019-07-22 14:54:47,457 - htmd.builder.builder - INFO - Created
segment P1 between resid 104 and 305.


And later on the error from this input:




*topos  = amber.defaultTopo() + ['SML.mol2']params = amber.defaultParam() +
['SML.frcmod'] molbuilt = amber.build(smol, outdir='./build/',
saltconc=0.1, param=params, topo=topos)molbuilt.view()*
is:

BuildError: UnknownResidueError("Unknown residue(s) ['SML'] found in
the input structure. You are either missing a topology definition for
the residue or you need to rename it to the correct residue name",)



Thank you for your help,

Gaspar

**Comment by stefdoerr** [comment]
Hi Gaspar, sorry but the files never came. Can you upload them to the issue tracker directly instead of per mail? Maybe it works that way. Thanks!

**Comment by GasparPinto** [comment]
Hey Stefan,

I actually found the mistake, it was on the names of some atoms.
I was thinking they would be recognized anyway, but it worked when I
changed the names. I will still send you the files to ask you if there is a
way of doing it automatically.
Right now, however, I am out of the office till the 8th of August. When I
get back I'll upload it directly to github and explain in a better way what
I want to accomplish.

Thank you for your help
Kind regards,
Gaspar

**Comment by stefdoerr** [comment]
Hey @GasparPinto if it still interests you give us an update on this, otherwise I will close the issue as resolved. 
Best,
Stefan

**Comment by GasparPinto** [comment]
Hey @stefdoerr, 
You can close it since I got it to work in the end. It was a problem in naming the atoms on the PDB file.

Best, 
G

**Comment by stefdoerr** [comment]
Merci :)
