### ISSUE TITLE
Equilibration failed

### ISSUE THREAD

**Issue by smar966** [Acellera/htmd#897]
Dear support team,

I am posting this issue here because so far no one has replied on the helpdesk platform.

I have been trying to run the equilibration MD of a large system (1863 residues), and it keeps failing or not moving forward, with many lines in the log file containing "CG:search exceeded 50 force evaluations" (log.txt).

[log.txt](https://github.com/Acellera/htmd/files/3491426/log.txt)

I have run an equilibration cycle in AMBER (involving 5 minimization steps and 12 MD steps with heating and then slowly decreasing the restraints), and after that 100 ns MD. I had no problems.
I have also tried to run an equilibration cycle in ACEMD starting from the endpoint of a successful 4-ns equilibration MD run with AMBER (I used the endpoint PDB in the flags 'consref' and 'coordinates'). The equilibvration simulation in AceMD still blew up with the log file attached (log1.txt). I have tried to decrease 'timestep' from 4 to 2, but I got the same result.

[log1.txt](https://github.com/Acellera/htmd/files/3491440/log1.txt)

Can you please help me finding the problem? 
Solving this is now becoming urgent.

Thank you!
Sergio

PS- If needed, please download the input file at: https://www.dropbox.com/s/cm1gtru49sp4udt/input?dl=0
- the PDB file at: https://www.dropbox.com/s/nafapo6yytg8rig/structure.pdb?dl=0
- prmtop file at: https://www.dropbox.com/s/rughax4btk1xkuf/structure.prmtop?dl=0

**Comment by stefdoerr** [comment]
Hi, I answered on the helpdesk. Sorry but I was out on holidays due to it being mid-August.
We can continue there the discussion :)
Best,
Stefan
