### ISSUE TITLE
How to use plot_free_energy() from pyemma into HTMD?

### ISSUE THREAD

**Issue by lguarneros** [Acellera/htmd#91]
Hi everybody!
I need the plot_free_energy() of trajs after calculate TICA in HTMD.

In pyemma, I use:

```
tica_obj = coor.tica(inp, lag=8, dim=4,  kinetic_map=True)
print 'TICA dimension ', tica_obj.dimension()
Y = tica_obj.get_output() # get tica coordinates
print 'number of trajectories = ', np.shape(Y)[0]
print 'number of frames = ', np.shape(Y)[1]
print 'number of dimensions = ',np.shape(Y)[2]

figure(figsize(10,8))
mplt.plot_free_energy(np.vstack(Y)[:,0], np.vstack(Y)[:,1])
```

But, in HTMD, TICA is calculated how:

```
tica = TICA(data, 20)
dataTica = tica.project(4)
```

How to use plot_free_energy() in this case?
Regards!
Luis

**Comment by stefdoerr** [comment]
Sure. The two coordinates of `Y` are stored in `dataTica.dat`
You would need to concatenate first all of your trajectory data like `Y = np.concatenate(dataTica.dat)` and then proceed as before :)
Write back if this worked because I can't test it right now.

**Comment by lguarneros** [comment]
Hi my friend!
Thanks for information..
This is the code for plot free energy

```
import pyemma.plots as mplt
Y = np.concatenate(dataTica.dat)
mplt.plot_free_energy(np.vstack(Y)[:,0].astype(float), np.vstack(Y)[:,1].astype(float));
```

Now.. how to plot the clusters?
With pyemma I use this code

```
clustering = coor.cluster_kmeans(Y,k=n_clusters, max_iter=50)
figure(figsize(10,8))
mplt.plot_free_energy(np.vstack(Y)[:,0], np.vstack(Y)[:,3])
cc_x = clustering.clustercenters[:,0]
cc_y = clustering.clustercenters[:,3]
plot(cc_x,cc_y, linewidth=0, marker='o', markersize=5, color='black')

```
But in HTMD the clusters is with the next code
`
dataTica.cluster(MiniBatchKMeans(n_clusters=1000), mergesmall=5)`

Regards! 
Luis

**Comment by stefdoerr** [comment]
check if the centers are in data.centers or data.Centers. I don't remember now if we store them. @j3mdamas can you check it?

**Comment by j3mdamas** [comment]
Sorry about the delay.

Yes, the centers of the clusters are stored in `dataTica.Centers`.

**Comment by giadefa** [comment]
is this solved?

**Comment by giadefa** [comment]
@lguarneros

**Comment by stefdoerr** [comment]
I think we can safely close this.
