### ISSUE TITLE
SmallMol object

### ISSUE THREAD

**Issue by albertma-evotec** [Acellera/htmd#914]
I came across a literature paper (https://github.com/compsciencelab/ligdream) which used the htmd module. Somewhere in their code they tried to import the SmallMol object. I am running the jupyter notebook file they provided and got this error.
"
    from htmd.smallmol.smallmol import SmallMol
"
ModuleNotFoundError: No module named 'htmd.smallmol'

Has this object been moved somewhere else?

**Comment by stefdoerr** [comment]
Yes, sorry we made a split between htmd and moleculekit. Import it via `from moleculekit.smallmol.smallmol import SmallMol`. moleculekit comes installed with HTMD so you already have it.

**Comment by albertma-evotec** [comment]
Thanks for the help.
I got a similar error for another code:
"
from htmd.molecule.voxeldescriptors import _getOccupancyC, _getGridCenters
"
ModuleNotFoundError: No module named 'htmd.molecule.voxeldescriptors'

Would you mind guiding me to the right place for it?
Thanks

**Comment by stefdoerr** [comment]
Same. It got moved to moleculekit. You can find the docs here:
https://software.acellera.com/docs/latest/moleculekit/index.html where you
can either read them or search the documentation API to find where
everything is located now :)

**Comment by stefdoerr** [comment]
You can even check the tutorial on voxelization
https://software.acellera.com/docs/latest/moleculekit/tutorials/voxelization_tutorial.html
