### ISSUE TITLE
acemd and rtx2080 ti

### ISSUE THREAD

**Issue by Golovin-Andrey** [Acellera/htmd#932]
We doing acemd with plumed simulation (funnel metadynamics), and it's a very pitty that acemd does not support RTX20XX and acemd3 does not support plumed, is there any walkaround for this?

**Comment by stefdoerr** [comment]
@raimis are there any timelines for plumed in acemd3?

**Comment by raimis** [comment]
@Golovin-Andrey 

At the moment, we don't have concrete date for PLUMED support.

As an alternative, you should try the adaptive sampling: https://software.acellera.com/docs/latest/htmd/tutorials/adaptive-sampling.html

**Comment by Golovin-Andrey** [comment]
@raimis 
Thanks! shure, will try.
