### ISSUE TITLE
question about crossing states in TICA

### ISSUE THREAD

**Issue by Zahratehrani** [Acellera/htmd#933]
Hi all,
I am new in HTMD and I am using the same feature given in ligand-binding site into my model. Have done 260 ns of MD for 5 different ligands with different activity to the same protein and wondering how ligand interaction changes the conformation of the protein in pocket site. For “Metric” done with 2 different approaches for selected residues in protein pocket as attachment. I am wondering why states are not stale or showing sine/cosine graphs and how they can be modified.
Any help will be appreciated
Bests
Zahra

[HTMD-question.docx](https://github.com/Acellera/htmd/files/3751160/HTMD-question.docx)

**Comment by stefdoerr** [comment]
I don't really understand your question but the second approach shows much higher timescales so I would use distances. RMSD is a single number so it's not ideal for clustering. Keep in mind this is not pairwise RMSD clustering between all conformers but just a single RMSD to a reference structure.
Other than that I'd suggest you change your `data.fstep` to be correct. In our case we sample every 100ps in out trajectories so we set `data.fstep = 0.1` (it's set in nanoseconds).

**Comment by Zahratehrani** [comment]
Dear Stefan,
Hi.. thanks for your suggestion .. I will repeat calculation with data.fstep = 0.001 (based on my time frame) with second approach.. will post if come up with any question.
Bests
Zahra

**Comment by stefdoerr** [comment]
Ah sorry, so you are actually sampling every 1ps? I thought it was a mistake in our trajectory readers. Then adding the line I told you will not make any change.

Unless your system is really tiny and fast I would not expect to have any meaningful MSM with only 2ns long simulations though.

**Comment by Zahratehrani** [comment]
Hi Stefan, 
I was posting the result that got your comment. I have set data.fstep = 0.001 as it was suggested. For 2 out of 5 ligands the result is same as before assigning data.fstep. Seems that it takes correct value (its just warring giving the notice the user checking the values). for other 3 ligands I got couple of errors/warnings in model.plot.time scale and markov model (using the same values in TICA and model.plot.time for all of ligands) 
“estimation has failed at list of lag time or so...." 
Could not fix the issue by changing TICA and model.plot.time values. 
PS: you can find the results as attached files 
Your suggestion will be appreciated 
Bests
Zahra
![HTMD-error-AMP-1](https://user-images.githubusercontent.com/50322948/67275902-dcb28d80-f4c3-11e9-8310-21adeb7edaab.png)

![HTMD-error-AMP-3](https://user-images.githubusercontent.com/50322948/67275914-e0deab00-f4c3-11e9-8600-7bf55799e85d.png)
t.com/50322948/67275908-df14e780-f4c3-11e9-8506-5ec19025af19.png)
![timescales](https://user-images.githubusercontent.com/50322948/67275922-e3d99b80-f4c3-11e9-96cc-7b6c9be2902d.png)

![HTMD-error-AMP-2](https://user-images.githubusercontent.com/50322948/67275968-fe137980-f4c3-11e9-91e4-cd97d5b633b6.png)

**Comment by stefdoerr** [comment]
All these warnings on PCCA having empty macrostates and timescales not computing are due to no connections between your states. Than can be either due to:

1. Too few statistics. Simulate more
1. Too many clusters can lead to too few statistics (transitions) between states
1. Bad projections can cause most conformations to end up in a small subset of states thus giving very bad statistics.

I would say, try with 500 clusters. Then try playing around with your projections. Otherwise just simulate more.

**Comment by stefdoerr** [comment]
As I mentioned, this is all due to lack of sampling which leads to lack of statistics. Either sample more or settle for a coarser discretization.
