### ISSUE TITLE
Error Loading Model

### ISSUE THREAD

**Issue by PabloHNieto** [Acellera/htmd#935]
Hi,

when loading a model I get

```
model = Model(file="model.dat")                                                                                                                         
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-3-71984bcdeefc> in <module>
----> 1 model = Model(file="model.dat")

/shared/pablo/github/htmd/htmd/model.py in __init__(self, data, file)
     47         if data is None:
     48             if file is not None:
---> 49                 self.load(file)
     50             return
     51         else:

/shared/pablo/github/htmd/htmd/model.py in load(self, filename)
    738             if k == 'data':
    739                 m = MetricData()
--> 740                 m.load(z[k])
    741                 self.__dict__[k] = m
    742             else:

/shared/pablo/github/htmd/htmd/metricdata.py in load(self, filename)
    734             if k == 'description' and 'map' in vardict:  # Patch for loading old data
    735                 self.description = vardict['map']
--> 736             elif k == 'trajectories' and 'dat' in vardict:  # Patch for loading old data
    737                 self._loadTrajectories(vardict['dat'], vardict['ref'], vardict['simlist'], vardict['St'])
    738             elif k != 'parent':

UnboundLocalError: local variable 'vardict' referenced before assignment
```
filename in metricdata.py is expected to be a string but is a MetricData object

Thanks

Pablo

**Comment by stefdoerr** [comment]
Old versions. Either saved with an old version or you are using an old HTMD version.

**Comment by PabloHNieto** [comment]
I created this model months ago, and I got this error this afternoon after updating htmd

**Comment by stefdoerr** [comment]
do `%debug` and see what type `filename` is. It's neither `str` nor `dict` which it could read

**Comment by PabloHNieto** [comment]
is a MetricData object, retrieved by the model.load method

**Comment by stefdoerr** [comment]
Yeha that's pretty old. Add a line before the type checks where you do

filename = filename.__dict__

So that it gets recognized as a dict. That should work. Then save it with
the new version and undo the code change so that it doesn't mess up your
new files.

**Comment by stefdoerr** [comment]
Did it work? If you have the old files can you send me one? I can then add a fix to read both old and new files

**Comment by PabloHNieto** [comment]
I'm sending you a link with a file
Let me know if you can reproduce the bug

**Comment by stefdoerr** [comment]
Fixed: https://github.com/Acellera/htmd/commit/b8a648dfac448547dc29eb189637f2456da47db5
