### ISSUE TITLE
model.plotFES griddata import error

### ISSUE THREAD

**Issue by PabloHNieto** [Acellera/htmd#936]
Hi,

There is a problem when plotting the free energy surface 

```
model.plotFES(0, 1, temperature=310)
    773         from matplotlib import pylab as plt
--> 774         from matplotlib.mlab import griddata
    775 
    776         if cmap is None:

ImportError: cannot import name 'griddata'
```
Apparently griddata has been deprecated from matplotib
and [`from scipy.interpolate import griddata`](https://scipy-cookbook.readthedocs.io/items/Matplotlib_Gridding_irregularly_spaced_data.html)
can be used to replace it.

**Comment by stefdoerr** [comment]
oh interesting! thanks for catching that :) I will fix it soon

**Comment by stefdoerr** [comment]
https://github.com/Acellera/htmd/commit/b8a648dfac448547dc29eb189637f2456da47db5
Fixed :)
