### ISSUE TITLE
Registration issue on HTMD==1.17

### ISSUE THREAD

**Issue by aclyde11** [Acellera/htmd#937]
htmd_register is resulting a failure on two different Ubuntu systems, installed through conda.
```bash
(/local/conda_envs/htmd) aclyde@chicken:/local$ htmd_register

 Welcome to HTMD. We'd like to know who you are so that we can keep in touch!
 Please enter your name, affiliation and institutional email address.

 Please provide valid information so that it might be verified.

 Institutional Email : ****@uchicago.edu
 Full name   : Austin Clyde
 Institution : University of Chicago
 City        : Chicago
 Country     : USA

Could not register!
```

Then on import it always asks for redoing this step.

**Comment by stefdoerr** [comment]
I can confirm this. It's probably an error with the registration server. I will look into it tomorrow, I apologize for this

**Comment by stefdoerr** [comment]
I temporarily disabled registration checking until we fix this. For the moment you can do the following
```
mkdir ~/.htmd/.registered-htmd
echo "{\"ret\": \"xxx\"}" > ~/.htmd/.registered-htmd/registration
```

This will disable registrations for now. At some point when we fix the server you will be asked to register one last time. Again, sorry for the inconvenience

**Comment by stefdoerr** [comment]
Okay this is fixed now. Many thanks for reporting and sorry for the trouble!
