### ISSUE TITLE
Add parameters for special residues

### ISSUE THREAD

**Issue by smar966** [Acellera/htmd#938]
Hello,

My system is a cytochrome and I have parameter files for the HEME (HEM.mol2), cystein binding the iron (CYP.mol2) and a ligand (DodAmine_gauss-min.mol2); I also have frcmod parameters for the HEM+CYP (IC6.frcmod).

How can I add these parameters to my system in HTMD? I have tried the following and it didn't work:

```python
topos  = amber.defaultTopo() + ['DodAmine_gauss-min.mol2'] + ['ff_parameters_Shahrokh/HEM.mol2'] + ['ff_parameters_Shahrokh/CYP.mol2']
params = amber.defaultParam() + ['frcmod_lig'] + ['ff_parameters_Shahrokh/IC6.frcmod']

molbuilt = amber.build(smol, outdir='./build/', saltconc=0.1, param=params, topo=topos)
molbuilt.view()
```

---------------------------------------------
In tLeap, I could setup the CYP and HEM by specifying the parameters and bonds as follows:

# Loading the system parameters
HEM = loadmol2 ff_parameters_Shahrokh/HEM.mol2
CYP = loadmol2 ff_parameters_Shahrokh/CYP.mol2
loadamberparams ff_parameters_Shahrokh/IC6.frcmod

LIG = loadmol2 DodAmine_gauss-min.mol2

# Loading the system
prot1 = loadpdb WT_prot_corr_comb.pdb
lig1 =  loadpdb WT_DodAmine_aminetoheme_ren.pdb
mol2 = combine {prot1 lig1}

bond mol2.475.FE mol2.422.SG       #BOND CYS-S to HEM-FE

# Define connectivity for CYP residue 
set mol2.422 connect0 mol2.422.N
set mol2.422 connect1 mol2.422.C

bond mol2.421.C mol2.422.N        # BOND CYS to the protein (new CYP residue)
bond mol2.422.C mol2.423.N        # As above

Thank you in advance!
Sergio

**Comment by stefdoerr** [comment]
Sorry for the delay, somehow I missed the notification of this issue.

mol2 files are topology+coordinates and need to be read into a molecule object. They do not contain parameters (as far as I know?). If I am wrong could you please post here the mol2 files in a zip? I would be curious to see them. 

I will try to reply soon on the other matter of defining connectivity

**Comment by smar966** [comment]
The mol2 files are taken from literature, so they replace the traditional prepi files (but cannot be imported in the same way, I've tried).
I'm sending here the files with the modified tleap script that worked for me, after running the first steps with the htmd notebook (also included).

[prep_final.zip](https://github.com/Acellera/htmd/files/3813327/prep_final.zip)

**Comment by stefdoerr** [comment]
Sorry for the delayed response, I was traveling for work.

I see right, they just define the topology in the mol2 files.
AFAIK antechamber can convert mol2 to prepi http://ambermd.org/antechamber/ac.html
Have you given that a try?

**Comment by smar966** [comment]
That was the first thing I tried to do, since before I always used prepi
files to setup the parameters for ligands.
However this would't work, I always obtained errors that would not allow me
to move on. That's when I found about the more recent way of using the mol2
files in tleap, instead of the prepi files, and it worked.

**Comment by stefdoerr** [comment]
I found a workaround. Read the mol2 file with VMD and write out a pdb. The convert the pdb to prepi with antechamber:
`antechamber -fi pdb -i ./CYP.pdb  -fo prepi -o ./CYP.prepi`

**Comment by smar966** [comment]
Hi Stefan,

Thanks for trying. But when you convert mol2 to pdb you lose the
information on the partial charges, which is the whole point of these files
anyway.
Moreover, if I use amber tools (tleap) I already know how to setup my
system using these mol2 files.
My original question was meant to learn how to do the same implementation
using the htmd only. But if there is no current solution don't worry about
me, because for this system I already solved it using tLeap.

**Comment by stefdoerr** [comment]
No, currently not. Would not take me more than 10 minutes to implement, I
just didn't know about this feature of reading just the topology from mol2
files. I will keep the issue open so that I maybe add the feature in in the
future.
