### ISSUE TITLE
Parameterize "Called Process Error"

### ISSUE THREAD

**Issue by GasparPinto** [Acellera/htmd#939]
I was trying to parameterize a ligand to run an MD and I got this error:

CalledProcessError: Command 'b'parameterize test.mol2 --charge 1 --charge-type Gasteiger --min-type None --no-dihed --outdir testing\n'' returned non-zero exit status 1.

I obviously thought that I was doing something wrong so I went to the website to re-do the tutorial of the parameterize example that you have there and I got the exact same error. 
I still think that I did something wrong, I just don't know what and thought that maybe you can help me.

Could this be a difference between version 2 and version 3 protocols?

**Comment by raimis** [comment]
@GasparPinto 

Thank for reporting the issue.

**Comment by GasparPinto** [comment]
@raimis 

Sorry for taking so long with the answer. 
Do you mean run directly on a terminal on my desktop?

This happens:
**Traceback (most recent call last):
  File "/home/gaspar/miniconda3/bin/parameterize", line 11, in <module>
    sys.exit(main_parameterize())
  File "/home/gaspar/miniconda3/lib/python3.6/site-packages/htmd/parameterization/cli.py", line 597, in main_parameterize
    mol = _prepare_molecule(args)
  File "/home/gaspar/miniconda3/lib/python3.6/site-packages/htmd/parameterization/cli.py", line 179, in _prepare_molecule
    chiral_centers = detectChiralCenters(mol)
  File "/home/gaspar/miniconda3/lib/python3.6/site-packages/htmd/parameterization/util.py", line 402, in detectChiralCenters
    from moleculekit.rdkitintegration import _convertMoleculeToRDKitMol
  File "/home/gaspar/miniconda3/lib/python3.6/site-packages/moleculekit/rdkitintegration.py", line 6, in <module>
    from rdkit import Chem
  File "/home/gaspar/miniconda3/lib/python3.6/site-packages/rdkit/Chem/__init__.py", line 18, in <module>
    from rdkit import DataStructs
  File "/home/gaspar/miniconda3/lib/python3.6/site-packages/rdkit/DataStructs/__init__.py", line 13, in <module>
    from rdkit.DataStructs import cDataStructs
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /home/gaspar/miniconda3/lib/python3.6/site-packages/rdkit/DataStructs/../../../../libRDKitDataStructs.so.1)**

If you mean on a jupyter-notebook it gives me a syntax error:
![Parameterize](https://user-images.githubusercontent.com/23507187/68577135-cae35b00-046f-11ea-801c-6598a5ae1839.png)

Thanks

**Comment by raimis** [comment]
Yes, I mean  to run in the terminal.

It seems, you haven't activate the conda environment for HTMD. Try to run `conda activate` and check if `htmd` package is present with `conda list`.

**Comment by GasparPinto** [comment]
I have htmd on the conda list.

htmd                      1.17                     py36_0    acellera

I went to a colleagues computer and it worked, so it's definitely me. he has version 1.13 though.

**Comment by raimis** [comment]
Could you check the version of `rdkit` version and try if a direct import works:
```
python -c 'from rdkit import Chem'
```

**Comment by GasparPinto** [comment]
I think you found the problem:

  File "<string>", line 1, in <module>
  File "/home/gaspar/miniconda3/lib/python3.6/site-packages/rdkit/Chem/__init__.py", line 18, in <module>
    from rdkit import DataStructs
  File "/home/gaspar/miniconda3/lib/python3.6/site-packages/rdkit/DataStructs/__init__.py", line 13, in <module>
    from rdkit.DataStructs import cDataStructs
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /home/gaspar/miniconda3/lib/python3.6/site-packages/rdkit/DataStructs/../../../../libRDKitDataStructs.so.1)

**Comment by raimis** [comment]
Do you have the same version of `rdkit`?

```

**Comment by GasparPinto** [comment]
I do... :/

conda list | grep rdkit
rdkit                     2019.03.4.0      py36hc20afe1_1    acellera

**Comment by raimis** [comment]
Does `rdkit` use correct libraries?
```
$ ldd $CONDA_PREFIX/lib/libRDKitDataStructs.so.1
	linux-vdso.so.1 =>  (0x00007ffda0108000)
	libRDKitRDGeneral.so.1 => /shared/raimis/opt/miniconda/envs/htmd/lib/./libRDKitRDGeneral.so.1 (0x00007faf7b90c000)
	libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007faf7b5f9000)
	libstdc++.so.6 => /shared/raimis/opt/miniconda/envs/htmd/lib/./libstdc++.so.6 (0x00007faf7b485000)
	libm.so.6 => /usr/lib64/libm.so.6 (0x00007faf7b183000)
	libgcc_s.so.1 => /shared/raimis/opt/miniconda/envs/htmd/lib/./libgcc_s.so.1 (0x00007faf7b8d8000)
	libc.so.6 => /usr/lib64/libc.so.6 (0x00007faf7adb5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007faf7b815000)
```

**Comment by GasparPinto** [comment]
I get this:

ldd: /lib/libRDKitDataStructs.so.1: No such file or directory


By the way, thank you so much for your patience!

**Comment by raimis** [comment]
It seems conda environment is not activated:
```

**Comment by raimis** [comment]
Try `conda activate`

**Comment by GasparPinto** [comment]
After conda activate I rerun this:
**$ ldd $CONDA_PREFIX/lib/libRDKitDataStructs.so.1**

/home/gaspar/miniconda3/lib/libRDKitDataStructs.so.1: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /home/gaspar/miniconda3/lib/libRDKitDataStructs.so.1)
/home/gaspar/miniconda3/lib/libRDKitDataStructs.so.1: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/gaspar/miniconda3/lib/libRDKitDataStructs.so.1)
	linux-vdso.so.1 =>  (0x00007fff7565d000)
	libRDKitRDGeneral.so.1 => /home/gaspar/miniconda3/lib/./libRDKitRDGeneral.so.1 (0x00001458cbc96000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00001458cb97e000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00001458cb5fc000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00001458cb2f3000)
	libgcc_s.so.1 => /home/gaspar/miniconda3/lib/./libgcc_s.so.1 (0x00001458cbc5b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00001458caf29000)
	/lib64/ld-linux-x86-64.so.2 (0x00001458cbb9b000)

**Comment by raimis** [comment]
Do you have the C++ STD library in your environment?
```
$ conda list | grep libstdcxx
libstdcxx-ng              9.1.0                hdf63c60_0
```

**Comment by GasparPinto** [comment]
Different version:
libstdcxx-ng              8.2.0                hdf63c60_1

**Comment by raimis** [comment]
Does your library provides correct C++ ABI:
```

**Comment by GasparPinto** [comment]
no such file  is the answer i get

**Comment by raimis** [comment]
Your installation is corrupted! I would recommend to reinstall the conda environment from scratch.

**Comment by GasparPinto** [comment]
Will do it! 

Thank you very much for your patience and help. 
I'll close the ticket with this! 
Cheers
