### ISSUE TITLE
Acemd3 - wrap

### ISSUE THREAD

**Issue by maicol93** [Acellera/htmd#946]
Dear Acellera team,
is it possible to implement in a future acemd3 update the possibility to wrap MD trajectories during their production, as it was implemented on acemd2.
Thanks
Maicol

**Comment by raimis** [comment]
Hi @maicol93 

Trajectory post-processing (including wrapping) should be done with HTMD. We try to avoid the duplication of functionality and keep ACEMD as fast as possible.

**Comment by dizhou-wu** [comment]
Dear Acellera team,

I have a similar problem with acemd3. When I set the barostat on, acemd3 will wrap MD trajectories automatically. Is there any way to turn the wrapping off?

Thanks
Dizhou

**Comment by stefdoerr** [comment]
Not in ACEMD. But you can re-wrap your trajectory around any molecule you want with HTMD.

```python
from htmd.ui import *
mol = Molecule("structure.prmtop")
mol.read("output.xtc")
mol.wrap("protein") # or "protein and resid X to Y" if you want to wrap around specific protein residues
mol.write("output.rewrapped.xtc")
```
This will wrap your simulation around any molecule you want

**Comment by stefdoerr** [comment]
We created a wrapping tutorial now https://software.acellera.com/docs/latest/htmd/tutorials/WrappingTutorial.html

**Comment by anicoli** [comment]
Dear @stefdoerr,

The tutorial for wrapping the trajectory is really helpful, thanks. I would like to ask you if it is possible to find also the documentation relative to the specific module (link not working: https://software.acellera.com/docs/stable/moleculekit/moleculekit.wrap.html) since we are encountering a problem in wrapping a _large_ (12500 frames x 111000 atoms) trajectory. The following error is:

```
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 15.7 GiB for an array with shape (112446, 3, 12500) and data type float32
```

Best,
Alessandro

**Comment by stefdoerr** [comment]
https://software.acellera.com/moleculekit/moleculekit.molecule.html#moleculekit.molecule.Molecule.wrap

For the error unfortunately you will have to find a computer with more RAM to wrap it or find other software which maybe uses less memory for the operation.
