### ISSUE TITLE
catch error of ill-defined fstep and raise it with more meaning

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#95]
Hi all,

I am using version 1.0.26. I am trying to plot the implied timescales for a system but keep getting the following error -using Tica, without, or changing the metrics-:

```
> 
> /path/to/acellera/current/python/lib/python3.5/site-packages/matplotlib/ticker.py in __call__(self)
>    1536         'Return the locations of the ticks'
>    1537         vmin, vmax = self.axis.get_view_interval()
> -> 1538         return self.tick_values(vmin, vmax)
>    1539 
>    1540     def tick_values(self, vmin, vmax):
> 
> /path/to/acellera/current/python/lib/python3.5/site-packages/matplotlib/ticker.py in tick_values(self, vmin, vmax)
>    1554             if vmin <= 0.0 or not np.isfinite(vmin):
>    1555                 raise ValueError(
> -> 1556                     "Data has no positive values, and therefore can not be "
>    1557                     "log-scaled.")
>    1558 
> 
> ValueError: Data has no positive values, and therefore can not be log-scaled.
```

I can forward the whole error it was too big to fit it here.
I would use a newer version but It's broken here -see issue #94-

Any help is appreciated,
Thanks,
Noelia

**Comment by stefdoerr** [comment]
This is typically a problem when you don't set the fstep correctly as it's set to something like 1E-10 and zeroes everything

**Comment by j3mdamas** [comment]
Hi Noelia,

Was this something that was working before and stopped working or is it something new you're trying and it's failing?

**Comment by noeliaferruz** [comment]
Thanks, @stefdoerr  was right. I might have accidentally removed the fstep line.
Sorry for this.

**Comment by stefdoerr** [comment]
Maybe we should catch this kind of error and report a better error

**Comment by stefdoerr** [comment]
Done: https://github.com/multiscalelab/htmd/commit/eef7202eb9ac23ae1265c3246db61d6cff79ebe3
