### ISSUE TITLE
Support deprotonated cysteine in CHARMM build

### ISSUE THREAD

**Issue by tonigi** [Acellera/htmd#950]
Should be simple by adding the pair  `'CYM': 'CYSD'` here https://github.com/Acellera/htmd/blob/56ffd6d6ac8a6a479f31602ee33c74725425865b/htmd/builder/charmm.py#L608  and `pdbalias residue CYM CYS` here
https://github.com/Acellera/htmd/blob/56ffd6d6ac8a6a479f31602ee33c74725425865b/htmd/builder/charmm.py#L471 .

Should be supported since charmm36 ff. Not sure if it will interfere with S-S detection though.

**Comment by stefdoerr** [comment]
Did you test this locally? If yes I will just include it

**Comment by tonigi** [comment]
I tested on a CYM-containing protein, but haven't run the full regtests or other stuff.

**Comment by stefdoerr** [comment]
https://github.com/Acellera/htmd/commit/84e25edf7f4f4d1866a218a2e411c1fb6e7a079b

**Comment by tonigi** [comment]
Minor consideration: CYM also appears in metallic centers. Supporting it should not give the impression that metals are "solved" that way.
