### ISSUE TITLE
Problem with HTMD update

### ISSUE THREAD

**Issue by MASaeed44** [Acellera/htmd#951]
Hello,
After updating HTMD, the program is not running anymore. As I write "from htmd.ui import *" in jupyter, the message I am getting is 

" AttributeError: module 'numpy' has no attribute 'block' "

Later I installed fresh  HTMD and i am getting the same message.

**Comment by stefdoerr** [comment]
Hi, sorry for this. We are uploading now the new installation instructions because we had to upgrade to numpy1.17
Install HTMD in a new conda environment
```
conda create -n my_environment_name
conda activate my_environment_name
conda install htmd=1.19 -c acellera -c psi4 -c conda-forge
```

**Comment by MASaeed44** [comment]
Hi,
HTMD problem is solved. Even I updated to htmd1.21.0. But the problem is Equilibration() is not running properly. The message I am getting:

2020-02-02 00:13:26,851 - jobqueues.localqueue - INFO - Trying to determine all GPU devices
2020-02-02 00:13:26,904 - jobqueues.localqueue - INFO - Using GPU devices 0
2020-02-02 00:13:26,906 - jobqueues.localqueue - INFO - Trying to determine all GPU devices
2020-02-02 00:13:26,943 - jobqueues.localqueue - INFO - Queueing /home/saeed/equil
2020-02-02 00:13:26,945 - jobqueues.localqueue - INFO - Running /home/saeed/equil on device 0
2020-02-02 00:13:27,631 - jobqueues.localqueue - ERROR - Error in simulation /home/saeed/equil. Command '/home/saeed/equil/job.sh' returned non-zero exit status 1.

Can you please help me out. Thanks

**Comment by stefdoerr** [comment]
Try running `/home/saeed/equil/run.sh` from a command line and see what error it gives you. Also in the folder `/home/saeed/equil/` there should already be a file called `log.txt` which will say what error there was.

**Comment by MASaeed44** [comment]
After changing the GPU driver equilibrium is running. But later production is not running. It is saying "acemd: command not found" 
Later I run the run.sh file with ACEMD3. and got the message 
"ERROR: /home/user/conda/conda-bld/acemd3_1573499276231/work/src/mdsim/input.cpp line 192: Unknown input keyword "acemd" "

I have edited the run.sh file from "acemd" to "acemd3" then i got 
"ERROR: /home/user/conda/conda-bld/acemd3_1573499276231/work/src/mdsim/input.cpp line 192: Unknown input keyword "acemd3" "

**Comment by stefdoerr** [comment]
can you show me your "input" file? there seems to be some wrong command in
there
. ACEMD should not be reading the run.sh file.

**Comment by MASaeed44** [comment]
The problem is solved now. I was using "htmd.protocols.production_v4".
"htmd.protocols.production_v6" solved everything. Thank you.

**Comment by stefdoerr** [comment]
Great :)
