### ISSUE TITLE
TypeError: tuple indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by franck-allou** [Acellera/htmd#953]
hello I would like you to help and solve my problem. I'm using python 3.7 including tensorflow 2.0. 
I'm following a GitHub at that step when I run python I get error. Can  anyone help to understand and fix it.

class WarpedSiameseRNN(SiameseRNN):
    # constructor
    def __init__(self, config):
        SiameseRNN.__init__(self, config)
        self.name = 'WarpedSiameseRNN'
        self.is_first_dist_pair_call = True

    # redefine the distance between a pair of instances
    def dist_pair(self, pair_ixd):

        with tf.compat.v1.variable_scope("WarpedSiameseRNNDistPair") as scope:

            # unless it is the first call, then reuse the variables of the scope
            if self.is_first_dist_pair_call:
                self.is_first_dist_pair_call = False
            else:
                scope.reuse_variables()

            # T x K tensors, for T the latent time indices and K the number of RNN cells (encoder length)
            A = self.h[:, 2*pair_ixd, :]
            B = self.h[:, 2*pair_ixd+1, :]

here is the error I meet:
 A = self.h[:, 2*pair_ixd, :]
TypeError: tuple indices must be integers or slices, not tuple

**Comment by stefdoerr** [comment]
Sorry, how is this related to HTMD?
