### ISSUE TITLE
HTMD Installation

### ISSUE THREAD

**Issue by musabbirsaeed** [Acellera/htmd#959]
I am having an issue with installation. I am getting the following message at the time of installation.
"""
(base) saeed@saeed:~$ conda install htmd
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

(base) saeed@saeed:~$
"""
Please help me out.
Thanks.

**Comment by stefdoerr** [comment]
Read the installation instructions on the webpage specifically the installation command (you are missing the channels)

**Comment by musabbirsaeed** [comment]
I already added channels before. Please look at the following message
"""
(base) saeed@saeed:~$ conda config --add channels acellera
Warning: 'acellera' already in 'channels' list, moving to the top
(base) saeed@saeed:~$ conda config --add channels psi4
Warning: 'psi4' already in 'channels' list, moving to the top
(base) saeed@saeed:~$ conda install htmd
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

(base) saeed@saeed:~$
"""

**Comment by stefdoerr** [comment]
You are still missing the conda-forge channel and the acellera channel. Also they need to be added in the correct order so best don't use `--add channels`. Just do
`conda install htmd -c acellera -c psi4 -c conda-forge`

**Comment by musabbirsaeed** [comment]
miniconda with "conda install htmd -c acellera -c psi4 -c conda-forge"  is working properly. Thanks.
