### ISSUE TITLE
Do not clobber the "glob" function

### ISSUE THREAD

**Issue by tonigi** [Acellera/htmd#961]
https://github.com/Acellera/htmd/blob/d8b7b249a839c38570b6275fde934e48f7d569a3/htmd/ui.py#L71

This exports "glob" as a function in the user namespace, which is unexpected. E.g.

```py
import glob
from htmd.ui import *

glob.glob(..) # <- this fails
```

**Comment by stefdoerr** [comment]
we always use just the glob function of the glob module. Do you use any other?

**Comment by tonigi** [comment]
Internally I agree. But that alters the behaviour in user code. E.g., as a user

```py
import glob

#my code uses glob.glob and works
```

then

```py
import glob
from htmd.ui import *

#my code is unchanged and does not work any more
```

and then

```py
from htmd.ui import *
import glob

#my code is unchanged and now works again
```

**Comment by stefdoerr** [comment]
Unfortunately all the tutorials of HTMD use glob as a function so we would need to change those as well. I would say that at the point where you have your own code with glob.glob you should not `import *` anymore anyway and import individual modules of HTMD

**Comment by stefdoerr** [comment]
I will close this issue since we are not planning on changing this behaviour. Same thing would happen if the user was doing `from glob import glob` and we did `import glob` so it's a decision we will have to live with.
