### ISSUE TITLE
acemd=2019.01.24

### ISSUE THREAD

**Issue by shozebhaider** [Acellera/htmd#962]
Hi

I have upgraded to acemd3 using the latest HTMD build via conda. I have some old trajectories that were run using acemd=2019.01.24 and I need to extend them. So I installed acemd=2019.01.24. However, when I run it, it says the version is expired and I need to contact acellera? Can you please advise how to overcome this?

**Comment by raimis** [comment]
Hello @shozebhaider, we will respond to you via our technical support.
