### ISSUE TITLE
Incompatible with  CUDA driver  

### ISSUE THREAD

**Issue by bhwl12** [Acellera/htmd#964]
INSTALL ERROR:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.1=0
  - feature:|@/linux-64::__cuda==10.1=0

Your installed CUDA driver is: 10.1

**Comment by stefdoerr** [comment]
Does your conda environment already have installed packages? What command did you use to get this error? Did you try in a clean conda environment?

**Comment by bhwl12** [comment]
I got this error when using the following command：

conda create -n MD_ENV python=3.6
conda activate MD_ENV
conda config --add channels acellera
conda config --add channels psi4
conda install htmd -y

**Comment by stefdoerr** [comment]
you are missing conda-forge channel
The official instructions state:
conda install htmd -c acellera -c psi4 -c conda-forge
Best also, don't add the channels to your config but only include them in
the command otherwise you might get their order wrong

**Comment by bhwl12** [comment]
It workes when I following the official instructions. Thanks!
