### ISSUE TITLE
Error about mol.view('not water')

### ISSUE THREAD

**Issue by bhwl12** [Acellera/htmd#965]
When I run the tutorial mu-opioid-receptor-gpcr-equilibration, the following the following error occurs.

In cell: 
# Visualize the flat bottom potential box
mol.view('not water')
b = VMDBox([-39, 10, -29, 21, 40, 50])

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-7-a60a30da8106> in <module>
      1 # Visualize the flat bottom potential box
----> 2 mol.view('not water')
      3 b = VMDBox([-39, 10, -29, 21, 40, 50])

~/anaconda3/envs/MD_ENV/lib/python3.6/site-packages/moleculekit/molecule.py in view(self, sel, style, color, guessBonds, viewer, hold, name, viewerhandle, gui)
   1893         if viewer.lower() == "vmd":
   1894             pdb = tempname(suffix=".pdb")
-> 1895             self.write(pdb, writebonds=False)
   1896             self._viewVMD(psf, pdb, xtc, viewerhandle, name, guessBonds)
   1897         elif viewer.lower() == "ngl" or viewer.lower() == "webgl":

~/anaconda3/envs/MD_ENV/lib/python3.6/site-packages/moleculekit/molecule.py in write(self, filename, sel, type, **kwargs)
   1318             ext = type
   1319         if ext in _WRITERS:
-> 1320             _WRITERS[ext](src, filename, **kwargs)
   1321         else:
   1322             raise IOError(

~/anaconda3/envs/MD_ENV/lib/python3.6/site-packages/moleculekit/writers.py in PDBwrite(mol, filename, frames, writebonds, mode)
    151         coords = np.atleast_3d(mol.coords[:, :, frames])
    152         if hasattr(mol, 'box'):
--> 153             box = mol.box[:, frames[0]]
    154     else:  # If Molecule only contains topology, PDB requires some coordinates so give it zeros
    155         coords = np.zeros((mol.numAtoms, 3, 1), dtype=np.float32)

IndexError: index 0 is out of bounds for axis 1 with size 0

**Comment by stefdoerr** [comment]
Hi @bhwl12 I made a fix in `moleculekit` version 0.3.2 which fixes this issue.
I also created a new HTMD version 1.22.4 which includes a new equilibration protocol.
In addition I updated the tutorial for the Mu Opioid receptor.

It should all be available in max 24 hours to finish the builds and publish the new tutorial. Tell me if it doesn't show the new one tomorrow. It should use `htmd.protocols.equilibration_v3` instead of `v2`.
