### ISSUE TITLE
Structure and parmfile are reversed

### ISSUE THREAD

**Issue by tonigi** [Acellera/htmd#967]
https://github.com/Acellera/htmd/blob/8277231c7f70ce990971fcdce1fcd28b0cf8b941/htmd/protocols/production_v6.py#L210

This is more of a cosmetic  issue.  Using protocols with Amber FF creates something like this:

```
parmfile             	parameters
structure            	structure.prmtop
```

It would seem more logical to switch the file names: since `parmfile` is the Amber keyword which enables the FF one would expect the .prmtop, while `structure` is ignored.

**Comment by stefdoerr** [comment]
wasn't this some limitation of GPUGRID? that the parameters had to be called liked that?

**Comment by tonigi** [comment]
No: the files had to exist, but the use in input was irrelevant.

**Comment by tonigi** [comment]
To be clear: for consistency, for amber builds I'm proposing to

1.  swap the two arguments - this  should have no consequence. 
2. If possible, the "structure" statement can also be dropped, but this may need checking.

**Comment by stefdoerr** [comment]
I'll close this since it's more of an ACEMD3 issue and I don't believe we are willing to change the logic of this.
