### ISSUE TITLE
install HTMD failed with CUDA driver 10.2

### ISSUE THREAD

**Issue by huanyusb** [Acellera/htmd#969]
I tried to install htmd on kubuntu 20.04 with the command:
`conda install -c acellera -c psi4 htmd`
and my conda version is 4.8.2 , I tried python version 3.7.7 and 3.6.10 while both returns:

```
UnsatisfiableError: The following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.2=0


Your installed CUDA driver is: 10.2
```
Could anyone give me some advice? Thanks.

**Comment by stefdoerr** [comment]
You are missing -c conda-forge in the channels which was added some months ago. Check the installation instructions of HTMD. Best
