### ISSUE TITLE
AttributeError: module 'propka.lib' has no attribute 'logger'

### ISSUE THREAD

**Issue by shozebhaider** [Acellera/htmd#970]
Hi , I have just updated my htmd to 1.22.7. When I set up proteinprepare I get a persistent error message 

--------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-af0b1ca82aea> in <module>
      1 mol = Molecule("5PEP")
----> 2 mol_op = proteinPrepare(mol)

~/miniconda3/lib/python3.7/site-packages/moleculekit/tools/preparation.py in proteinPrepare(mol_in, pH, verbose, returnDetails, hydrophobicThickness, holdSelection, _loggerLevel)
    377 
    378     # An ugly hack to silence non-prefixed logging messages
--> 379     for h in propka.lib.logger.handlers:
    380         if h.formatter._fmt == '%(message)s':
    381             propka.lib.logger.removeHandler(h)

AttributeError: module 'propka.lib' has no attribute 'logger'

**Comment by stefdoerr** [comment]
Try a fresh conda environment. Conda update frequently messes up the
packages.

**Comment by shozebhaider** [comment]
works now. Thanks.
