### ISSUE TITLE
Simlist without simid

### ISSUE THREAD

**Issue by shozebhaider** [Acellera/htmd#971]
Hi,

I have a set of 200 xtc trajectories that I need to process using HTMD. Since I have not used ACEMD, I do not have a simid associated with it. So when I try to create a simlist using fsims = simlist(glob('./DATA/'), './protein.pdb'), they are all clubbed into simid =0. 
Is there a way I can associate a simid to them and get it processed  without putting them in individual directories?

Many thanks.

**Comment by stefdoerr** [comment]
Each trajectory needs to be in a separate folder and then you should do `glob("./DATA/*/")`. This should work

**Comment by shozebhaider** [comment]
having them in a directory is essential ?

**Comment by stefdoerr** [comment]
Yes, it's built into HTMD to assume that each independent trajectory is in a different folder. If you don't want to move the files just make directories with symlinks in them.

**Comment by shozebhaider** [comment]
Got it. Perfect.. many thanks Stefan.
