### ISSUE TITLE
Building system with multiple ligand molecules in the solvent

### ISSUE THREAD

**Issue by smar966** [Acellera/htmd#972]
Dear support team, 
I need to build a system with several molecules of a ligand placed randomly in the solvent. 
The tutorial [https://software.acellera.com/docs/latest/htmd/tutorials/system-building-protein-ligand.html] explains how to do that for 1 ligand. How can I proceed to implement the same for several ligand molecules? I'm talking about hundreds.
Thank you in advance!

**Comment by smar966** [comment]
I'm using the script below and it's not working. I end up with the ligands largely separated through a huge box with a lot of empty space in between, and because of that the solvation of the system will always crash (too many water molecules).
I've tried to modify it in different ways but always fail to improve it. 
Also, I'm not great with scripting in python.

The ultimate goal is to have a ratio of 1000:1 molec ligand / molec protein, which is larger than in my  trials so far. 
Any suggestionson how  to add the multiple ligand molecules in a more clever way, so that I don't end up with a several hundred-angstrom-sized box? 

Thank you in advance!
---------------
## Create the system
prot = Molecule('ab.01.pdb')
#prot.remove('not protein and not water')
prot = autoSegment(prot, sel='protein')
prot.set('segid', 'W', sel='water')
prot = proteinPrepare(prot, pH=7.5)
prot.center()

ligand = Molecule('ff_parameters/tmp_gauss-min.mol2')
ligand.set('segid','L')
ligand.set('resname','MOL')
ligand.center()

## Add multiple ligand molecules
from htmd.molecule.util import uniformRandomRotation
import random
import math

from htmd.molecule.util import maxDistance

D = maxDistance(prot, 'all')
print(D)

Nlig = 100  # number of ligands molecules to add

mol = Molecule(name='combo')
mol.append(prot)

for i in range(Nlig):
    print(i)
    D = maxDistance(prot, 'protein')
    D += 2  # minimal distance between ligand and protein
    print(D)
    
    x = 0
    y = 0
    z = 0
    while math.sqrt(x**2 + y**2 + z**2) > D + 1 or math.sqrt(x**2 + y**2 + z**2) < D - 1:
        x = random.uniform(0, D)
        y = random.uniform(0, D)
        z = random.uniform(0, D)
    print(math.sqrt(x**2 + y**2 + z**2))
        
    ligand.moveBy([x, y, z]) 
    ligand.rotateBy(uniformRandomRotation())

    mol.append(ligand)

mol.reps.add(sel='protein', style='NewCartoon', color='Secondary Structure')
mol.reps.add(sel='resname MOL', style='Licorice')
mol.view()

**Comment by stefdoerr** [comment]
Oh, you want to add multiple ligand copies in the same system. I see now.

First, there is no reason to recalculate D in every loop iteration. It won't change since your protein doesn't change.

Next issue is that you are moving the ligand around without making copies. You should make a copy of the original ligand at each loop iteration otherwise you are moving it around everywhere.

Next issue is
```python
    x = 0
    y = 0
    z = 0
    while math.sqrt(x**2 + y**2 + z**2) > D + 1 or math.sqrt(x**2 + y**2 + z**2) < D - 1:
        x = random.uniform(0, D)
        y = random.uniform(0, D)
        z = random.uniform(0, D)
    print(math.sqrt(x**2 + y**2 + z**2))
        
    ligand.moveBy([x, y, z]) 
```
This is not necessary, just move your ligands to [0, 0, D] and then rotate them
```python
ligand.center()
ligand.rotateBy(uniformRandomRotation()) # Rotate the ligand around itself
ligand.moveBy([0, 0, D])
ligand.rotateBy(uniformRandomRotation()) # This will now rotate the ligand in a sphere of radius D since the rotation is always around point [0, 0, 0]
```

Lastly you will have to take care your ligands are not clashing with each other
```python
ligand.set("resname", "XXX")
mol_copy = mol.copy()
mol_copy.append(ligand)
if np.any(mol_copy.atomselect("resname XXX and within 3 of resname MOL")):
     # Try again
```

So in total you need something like this:

```python
from htmd.molecule.util import uniformRandomRotation
import random
import math
from htmd.molecule.util import maxDistance

## Create the system
prot = Molecule('ab.01.pdb')
#prot.remove('not protein and not water')
prot = autoSegment(prot, sel='protein')
prot.set('segid', 'W', sel='water')
prot = proteinPrepare(prot, pH=7.5)
prot.center()

ligand = Molecule('ff_parameters/tmp_gauss-min.mol2')
ligand.set('segid','L')
ligand.set('resname','MOL')
ligand.center()

D = maxDistance(prot, 'protein') + 8 # add the ligands at least 8 A away from the protein
print(D)

Nlig = 100  # number of ligands molecules to add

mol = Molecule(name='combo')
mol.append(prot)

ligands_added = 0
while ligands_added < Nlig:
    curr_lig = ligand.copy()
    curr_lig.rotateBy(uniformRandomRotation()) # Rotate the ligand around itself
    curr_lig.moveBy([0, 0, D])
    curr_lig.rotateBy(uniformRandomRotation()) # This will now rotate the ligand in a sphere of radius D since the rotation is always around point [0, 0, 0]

    curr_lig.set("resname", "XXX")
    mol_copy = mol.copy()
    mol_copy.append(ligand)
    if np.any(mol_copy.atomselect("resname XXX and within 3 of resname MOL")):
        continue  # Try again...
    curr_lig.set("resname", "MOL")
    mol.append(curr_lig)
    ligands_added += 1
```

This is untested code but should work more or less.

Best,
Stefan

**Comment by stefdoerr** [comment]
Generally though I need to point out that it's not a very good idea to saturate your system with ligands depending on what you plan to calculate. If you want to calculate binding/unbinding kinetics you will have big issues since the ligands will be competing against each other for binding and might even self-aggregate.

**Comment by smar966** [comment]
Dear Stefan,
Thank you so much for your input and comments.
The script seems to be working nicely for a medium-sized number of ligands (e.g. 10-100), creating a sphere with of ligands placed equidistantly from the protein.
However, for a large number (e.g. 1000), the ligands are crammed and some atoms form different molecules are overlaying on top of each other. This, of course, made the equilibration MD crash immediately.
I found a workaround, which is to use tLeap from AmberTools to add the ligands to a box of solvent. It's not ideal but it is working...

**Comment by stefdoerr** [comment]
Theoretically it should not have overlapping ligands. We are checking for that in the code. If there are you can take a look at debugging it to see how it can add ligands on top of each other even though we check for overlaps.
Glad to hear it works though.

**Comment by smar966** [comment]
Hello,
I have a new problem related to this issue. 
I have managed to add multiple ligands and build the topology with the amber.build module, and those simulations are running. However, now I need to do the same with CHARMM force field, but I'm finding some problems. I have the parameters for the ligands and that seems ok. However, while building the system, all the ligand molecules are removed from the system except for the last one. I checked the build folder, and the segmentL still contains all the ligands. What can I do to keep all the ligands in place in the final structure .pdb?

Thanks in advance!

The lines to build the CHARMM topology are below. Link to the hydrated complex just before building the topology, smol.pdb: 
https://drive.google.com/file/d/17cXimarzLA2fYsLK6OEfMgXa6-7TN6p5/view?usp=sharing

smol = Molecule('smol.pdb')
topos_charmm  = charmm.defaultTopo() + ['ff_parameters/tmp_gauss-min_charmm.rtf']
params_charmm = charmm.defaultParam() + ['ff_parameters/tmp_gauss-min_charmm.str']

molbuilt = charmm.build(smol, outdir='./build/', saltconc=0.1, param=params_charmm, topo=topos_charmm)
molbuilt.view()

**Comment by smar966** [comment]
Problem solved!!
I found that if I defined a different residue number for each molecule, the system was fine after building the topology. For some reason, the amber.build did not need this. 
I did that by adding an extra line in the previous routine: "curr_lig.set("resid", ligands_added) "
