### ISSUE TITLE
Adaptive MetricDihedral

### ISSUE THREAD

**Issue by shozebhaider** [Acellera/htmd#974]
Hi,

I am running an adaptive simulation, where I am trying to sample the conformations of a loop (resid 210-224). I can use ad.projection = MetricSelfDistance('(resid 210 to 224) and (backbone)') just fine. However when I try to use MetricDihedral on  I run into issues.
ad.projection = [MetricDihedral()] works, however, when I just want to project on the loop residues using
ad.projection = [MetricDihedral('(resid 210 to 224) and (backbone)')]
I get the error message: 
RuntimeError: Manually passing dihedrals to MetricDihedral requires use of the Dihedral class. Check the example in the documentation

So the question is: Is there a way I can parse the backbone dihedral angles for this loop directly, or do I have to specify atoms explicitly that make up these dihedral angles and then parse that? 

Here is what I am doing 

queue = LocalGPUQueue()
queue.datadir = './data'
queue.devices = [0,1,2,3]

ad = AdaptiveMD()
ad.app = queue
ad.nmin=3  # minimum number of running sims
ad.nmax=4  # maximum number of running sims
ad.nepochs = 11 
ad.generatorspath = './generators/s3'
ad.ticadim = 3 # number of TICA dimensions
ad.projection = [MetricDihedral('(resid 210 to 224) and (backbone)')]
ad.updateperiod = 7200
ad.run()

Many thanks.

**Comment by stefdoerr** [comment]
https://software.acellera.com/docs/latest/moleculekit/moleculekit.projections.metricdihedral.html#moleculekit.projections.metricdihedral.Dihedral.proteinDihedrals

```
prodih = Dihedral.proteinDihedrals(mol, sel="(resid 210 to 224) and (backbone)", dih=["phi", "psi"])
ad.projection = [MetricDihedral(prodih)]
```
This should work I believe?

**Comment by shozebhaider** [comment]
RuntimeError: Expected one atom from atomselection {'name': 'N', 'resid': 210, 'insertion': '', 'chain': '', 'segid': ''}. Got 0 instead.

**Comment by stefdoerr** [comment]
What does this print?
`mol.get('name', sel='resid 210 and backbone')`
Seems like you are missing the N atom from the backbone on that residue?

**Comment by stefdoerr** [comment]
Oh you know what, you probably have other stuff in the molecule with resid 210. Do `protein and resid 210 and backbone`. That might work?

**Comment by shozebhaider** [comment]
Not quite. Because 
mol.get('name', sel='resid 210 and backbone') 
gives me 
array(['N', 'CA', 'C', 'O'], dtype=object)
and I get the same error message when I do  protein and (resid 210 to 224) and backbone
RuntimeError: Expected one atom from atomselection {'name': 'N', 'resid': 210, 'insertion': '', 'chain': '', 'segid': ''}. Got 0 instead.
I double checked and all backbone atoms are present.

**Comment by stefdoerr** [comment]
Hm, could you share the protein?
It works fine for me on a test protein

```python
from htmd.ui import *

In [2]: mol = Molecule('3ptb')                                                                                                                                                                
2020-10-19 14:28:52,483 - moleculekit.readers - INFO - Using local copy for 3ptb: /home/sdoerr/Work/moleculekit/moleculekit/test-data/pdb/3ptb.pdb

In [3]: prodih = Dihedral.proteinDihedrals(mol, sel="(resid 210 to 224) and (backbone)", dih=["phi", "psi"])                                                                                  

In [4]: print(prodih)                                                                                                                                                                         
["psi" dihedral angle including atoms:
name	resid	insertion	chain	segid
N	210			A	0
CA	210			A	0
C	210			A	0
N	211			A	0
, [...]
```

**Comment by shozebhaider** [comment]
Yes ofcourse. I shall email you my notebook as well where you can see that while it registers and prints prodih similar to your output but does not like it when I parse it as a MetricDihedral projection in an adaptive run.
I dont seem to have your email and here it wont let me send the files. 
Many thanks Stefan.

**Comment by shozebhaider** [comment]
It works now. Thank you Stefan for this:

It's a quite involved bug in HTMD related to AMBER builds. AMBER prmtop files don't contain information on segments or chains and tleap drops all such information when writing prmtop and pdb files.
Since prmtop is a very very ugly format to write we opted for writing the filtered topology as PSF instead (filtered/filtered.psf). The PSF writer by default assigns segments to the proteins.
The Dihedral class works by keeping tabs on each atom related to a dihedral by saving it's name/resid/chain/segid/insertion_code and then trying to find this exact combination in the filtered trajectory it tries to project. But the filtered PSF has a segid defined while the PRMTOP doesn't so it's unable to find the atoms because the atom information does not match exactly.

The hacky workaround I can currently suggest is to do this:
mol = Molecule("generators/s2/structure.prmtop")
mol.read("generators/s2/structure.pdb")
mol.set("segid", "0", sel="protein")
prodih=Dihedral.proteinDihedrals(mol,sel="protein and (resid 210 to 224) and (backbone)", dih=["phi","psi"])
