### ISSUE TITLE
Ligand parameters with CHARMM

### ISSUE THREAD

**Issue by smar966** [Acellera/htmd#975]
Hello!
I'm having problems setting up the ligand parameters with a charmm force field.
I normally use AMBER and add the ligand by defining the MOL2, PREPI and frcmod_lig for the ligand, and everything was working well with amber.build. Is there an easy way to convert these files into charmm compatible parameter files?
On top of this, I am using the modified charmm36m, for which I have parameters that are working for the protein alone. Just to show you, I tried to build my topology as:
 
 topos  = ['top/top_all36_prot.rtf', 'top/top_water_ions.rtf', 'ff_parameters/tmp.prepi'] 
 params = ['ff_parameters/par_all36m_prot.prm', 'par/par_water_ions.prm', 'ff_parameters/frcmod_lig']
 
 molbuilt = charmm.build(smol, outdir='./build1/', saltconc=0.1, param=params_charmm, topo=topos_charmm)
 molbuilt.view()

Thank you in advance!

**Comment by stefdoerr** [comment]
Yes you will  have to do the conversion from ligand AMBER parameters yourself. Proteins are ok. Some tools that do conversions are [parmed](https://parmed.github.io/ParmEd/html/index.html) and (acpype)[http://bio2byte.com/acpype/]. Possibly there are more which I don't know of.

**Comment by smar966** [comment]
OK. I was hoping that there would be come conversion tool in HTMD, but it's alright. 
Thanks anyway! ;)
