### ISSUE TITLE
Passing `validateElements=False` to the adaptive sampling... 

### ISSUE THREAD

**Issue by piia600** [Acellera/htmd#976]
Hi,

Is it possible to pass this into some variable of the adaptive sampling? There are some odd atom names (electron pairs in waters..) in my pdb, which lead to error

`Element E was read in file input/e1s1_0/structure.pdb but was not found in the periodictable. To disable this check, pass `validateElements=False` to the Molecule constructor or read method.`

I can get the HTMD to read the pdb without issues when reading the Molecule object manually, but there does not seem to be a place where I could put the flag in the adaptive sampling class.

**Comment by stefdoerr** [comment]
The correct solution is to fix the elements. It's not too tricky.
Can you take a look at the filtered/filtered.pdb and filtered.psf file if it has in the element column (last column in the PDB file) the letter E?
The issue is that if your original files (generators) are missing the element column Moleculekit will try to guess them from the atom names. So the solution is to fix the generators to have correct element columns and then start adaptive sampling.

**Comment by piia600** [comment]
The pdb-file has the element E in the last column. What could I change it to, as the "atom" is the dummy one for the electron pair in the 4-point water model?

**Comment by stefdoerr** [comment]
Considering adaptive sampling doesn't really care about elements, just change it to some existing but uncommon element? Like Tungsten "W" maybe.
By the way are you simulating the system with ACEMD3? I'm not sure we support 4-point water models. If yes, I should check in with @raimis

**Comment by stefdoerr** [comment]
Also one way to change it fast with moleculekit is:

```python
from moleculekit.molecule import Molecule 
mol = Molecule("badfile.pdb")
mol.element[mol.element == "E"] = "W"
mol.write("fixedfile.pdb")
```

**Comment by piia600** [comment]
Thanks, this seems to work. 

I simulated the system with Amber (due to the waters), I am just trying to see if I could still get new starting structures with adaptive sampling as it would make my life easier.

**Comment by stefdoerr** [comment]
Yes, it should work in practice with any MD engine. If you hit any other
issues feel free to let us know.
