### ISSUE TITLE
module 'propka.lib' has no attribute 'logger' 

### ISSUE THREAD

**Issue by shozebhaider** [Acellera/htmd#977]
This post is linked to Issue No.970. 
Propka.lib is being a serious issue while updating htmd. I usually create a separate environment for HTMD and then install all packages within the environment (as recommended in your post). When I update it, I usually remove the environment and do a reinstall. Propka.lib is messed up on fresh installation. This usually works if I do a fresh conda install. However, this is not always possible as I do not wish to delete other working envs. So is there a workaround to this issue?

**Comment by stefdoerr** [comment]
Did you install htmd with `conda install htmd -c acellera -c psi4 -c conda-forge`? Just to make sure you included conda forge in the installation.
Can you also do `conda list propka` to see the version?

**Comment by shozebhaider** [comment]
Doing exactly that. 
# packages in environment at /home/shozeb/miniconda3/envs/htmd:
#
# Name                    Version                   Build  Channel
propka                    3.3.0            py37h43977f1_0    conda-forge

**Comment by stefdoerr** [comment]
Hmmm. Seems like it picked the conda-forge propka over our propka which
causes the issue. Can you do conda uninstall propka and conda install
propka -c acellera ?
I am afraid that either you passed the channels in the wrong order in the
installation or you have configured permanent channels in your conda
installation.

**Comment by shozebhaider** [comment]
I think it was a case of channel being passed in the wrong order. I got it to work. 
Many thanks Stefan.
