### ISSUE TITLE
adaptive bandit projection issue

### ISSUE THREAD

**Issue by shozebhaider** [Acellera/htmd#984]
I am trying to run Adaptive bandit tutorial (replacing Villin HP with my protein).

While the simulation runs fine for the first epoch, the simulations are unable to project to begin the next epoch.
The run ends with the error message:

**NameError: No trajectories were projected. Check if the simlist is empty or for projection errors**

I check my simlist using  simlist(glob('./filtered/*/'), glob('./filtered/*.pdb'))
and its not empty. So I am not sure what is happening here.

I am using htmd 1.23.7

Any suggestions would be appreciated. 

My input commands are:
```python
queue = LocalGPUQueue()
queue.datadir = './data'
queue.devices = [0,1,2,3]

ab = AdaptiveBandit()
ab.app = queue

ab.generatorspath = './generators/s1'

ab.nmin=5  # minimum number of running sims
ab.nmax=10  # maximum number of running sims
ab.nframes = 1000000

ab.clustmethod = MiniBatchKMeans
ab.projection = MetricSelfDistance('protein and name CA')
ab.exploration = 0.01
ab.updateperiod = 180

ref = Molecule('./protein.pdb')

def contactGoal(mol, crystal):
    crystalCO = MetricSelfDistance('protein and name CA', pbc=False,
                                   metric='contacts',
                                   threshold=10).project(crystal)
    proj = MetricSelfDistance('protein and name CA',
                              metric='contacts',
                              threshold=10).project(mol)
    # How many crystal contacts are seen?
    co_score = np.sum(proj[:, crystalCO] == 1, axis=1)
    co_score /= np.sum(crystalCO)
    return co_score

ab.goalfunction = (contactGoal, (ref,))
ab.goal_init = 0.3

ab.run()
```

**Comment by stefdoerr** [comment]
The easiest way to debug this is usually to check if the projections work on your ref molecule. So before starting the adaptive you would do: 
```python
ref = Molecule('./protein.pdb')
contactGoal(ref, ref)
```
Next thing to check is the simulations themselves.
Try finding the filtered.psf file in the filtered folder plus some filtered trajectory and loading it with:
```
mol = Molecule("filtered/filtered.psf")
mol.read("filtered/e1s1_1/filtered.xtc")
MetricSelfDistance('protein and name CA').project(mol)
```

**Comment by stefdoerr** [comment]
I'd suggest updating though to the latest HTMD if possible if the above doesn't work because there were some bug fixes which might help

**Comment by shozebhaider** [comment]
Thanks @stefdoerr. I updated my HTMD to the latest version.

After the first set of commands, the error has changed to 

_<ipython-input-13-916c6d78f787> in contactGoal(mol, crystal)
     37                               threshold=10).project(mol)
     38     # How many crystal contacts are seen?
---> 39     co_score = np.sum(proj[:, crystalCO] == 1, axis=1)
     40     co_score /= np.sum(crystalCO)
     41     return co_score

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed_


However, the checking the simulations on the filtered trajectories worked fine.

**Comment by stefdoerr** [comment]
can you check the dimensions of the crystalCO array? I assume it's 2D while
it should be 1D the way you are using it?

**Comment by shozebhaider** [comment]
I ran the example (from the adaptive bandit tutorial). The first set of simulations run (like in mycase) and then upon projection I get the same error where crystalCO or proj is not being defined. Separately, I am able to project the simulations on any projection metric.

**Comment by stefdoerr** [comment]
Hi Shozeb. I fixed the tutorial now. It was out of date

```python
def contactGoal(mol, crystal):
    crystalCO = MetricSelfDistance('protein and name CA', periodic=None,
                                   metric='contacts',
                                   threshold=10).project(crystal).squeeze()
    proj = MetricSelfDistance('protein and name CA',
                              metric='contacts',
                              threshold=10).project(mol)
    # How many crystal contacts are seen?
    co_score = np.sum(proj[:, crystalCO] == 1, axis=1).astype(float)
    co_score /= np.sum(crystalCO)
    return co_score
``` 

This is how to get the goal function to work. As I mentioned the best way to debug it is to do:
```python
mol = Molecule("./input/e1s1_villin_100ns_0/structure.psf")
mol.read("./data/e1s1_villin_100ns_0/output.xtc")
contactGoal(mol, crystal)
```

That way you get all the crashed on the projection directly and it's easier to debug them.
The first issue was that the crystal contacts were 2D and needed to be 1D so I squeezed the array to remove the empty dimension. The second issue was that the co_score was integer and numpy didn't want to do integer/integer division with `/=` so I just cast it to float and it works now.

I'll update the online tutorial as well soon

**Comment by shozebhaider** [comment]
Thanks @stefdoerr I shall test this out and then close the post.
While we are at this, one quick question - will the ab.nepochs override ab.nframes? why was nframes introduced in AB over nepochs?

**Comment by stefdoerr** [comment]
I don't remember now the exact details, Adria worked on Bandit, but the
algorithm needs an estimate of the total number of frames you will have
over the whole run to normalize some scores. This is not the case for other
Adaptive sampling algorithms.
Personally I estimate it like this:
adapt.nframes = traj_frames * numepochs * nmax
So: number of frames produced by a simulation (runtime/sampling_rate) times
number of epochs times the maximum number of simulations per epoch. It's a
rough estimate

**Comment by shozebhaider** [comment]
thanks..All working now.
