### ISSUE TITLE
opm not found

### ISSUE THREAD

**Issue by phisanti** [Acellera/htmd#987]
I am trying to run the example available on the web

```python
from htmd.util import opm
prot, thickness = opm('4dkl', keep=False)
thickness
```
However, I encountered the following error:
```python
ImportError                               Traceback (most recent call last)
<ipython-input-1-c8c769caa82d> in <module>
----> 1 from htmd.util import opm
      2 prot, thickness = opm('4dkl', keep=False)
      3 thickness

ImportError: cannot import name 'opm' from 'htmd.util' (/home/coder/miniconda3/envs/htmd_env/lib/python3.7/site-packages/htmd/util.py)
```

I installed htmd with the following script:

```shell
#!/bin/bash

conda create -n htmd_env python=3.7
conda activate htmd_env
conda config --set always_yes yes
conda install htmd=1.24.2 -c acellera -c psi4 -c conda-forge
python -m ipykernel install --user --name=htmd_env
```

I also tried downloading the proteins manually from opm, protonate and then embed into the membrane. Still, it seems the pdb loses the orientation at some point?
Any suggestion on how to quickly embed a protonated structure into a membrane easily?

**Comment by stefdoerr** [comment]
Hi, where is this code snippet from? If it's from a tutorial we need to update it.

The import is now:
`from moleculekit.util import opm`

**Comment by phisanti** [comment]
I took if from here:

https://software.acellera.com/docs/latest/htmd/tutorials/system-building-protein-in-membrane.html

The second block of code in the "Prepare protein" section.

**Comment by stefdoerr** [comment]
Thanks! I'll update the tutorial. Does the above code work for you?

**Comment by phisanti** [comment]
Yes, now it works!
