### ISSUE TITLE
Problem with res names

### ISSUE THREAD

**Issue by phisanti** [Acellera/htmd#988]
I have build a membrane following the membrane builder and then I have combined with a protein using the opm() function. However, when I go to the charmm.build(...), it tells me that cannot find the name of some of the lipid resiudes:

```python
BuildError: UnknownResidueError("Unknown residue(s) ['POP'] found in the input structure. You are either missing a topology definition for the residue or you need to rename it to the correct residue name")
Check /notebooks/final-build/log.txt for further information on errors in building.
```
Thus, I was wondering if there is a quick way to change the name of the residues from 'pop' to POPE so that the charmm files can recognise it. Or if I am doing something wrong, would be good to know.

**Comment by stefdoerr** [comment]
Yes sure. With moleculekit you can easily rename residues as such:
```python
from moleculekit.molecule import Molecule
mol = Molecule("myfile.pdb")
mol.set("resname", "POPE", sel="resname POP")
```
Hope this helps
