### ISSUE TITLE
Molecule.view() does not work after Amber building

### ISSUE THREAD

**Issue by AdriaPerezCulubret** [Acellera/htmd#99]
After building the molecule with amber, when you try to visualize it with vmd, it only opens the .prmtop file, without the .pdb file, so it can't be visualized.

Here's the code

``
molbuilt = amber.build(solvmol,ff=ffs, param=params, topo=preps, saltconc= 0.1 ,outdir = './build_3/')
``
``
molbuilt.view()
``

I think the pdb file is not loaded in the new molecule object (In this case, molbuilt).

**Comment by stefdoerr** [comment]
I think this is an issue with the old amber build. Should be fixed on the new amber branch I think.

**Comment by j3mdamas** [comment]
@stefdoerr what amber branch? mine?

**Comment by stefdoerr** [comment]
Hm can't remember. Will have to look at it from close. Remind me tomorrow @AdriaPerezCulubret

**Comment by stefdoerr** [comment]
Fixed
