### ISSUE TITLE
Get water box size

### ISSUE THREAD

**Issue by phisanti** [Acellera/htmd#991]
I have  built a water box following the example. When I plot the image, I see all the molecules, so it seems to work fine. However, I would like to print the output of the full solvated box, but the output I got is an array [0, 0, 0]. Therefore, I was wondering how to properly calculate the box size containing the system. Here is a snippet of my code:

```python  
# ... load molecule and stuff....

# Generate water box:
coo = mol.get('coords','noh and (lipids or protein)')
m = np.min(coo, axis=0) + [0, 0, -10]
M = np.max(coo, axis=0) + [0, 0, 10]
smol = solvate(peri_ph, minmax=np.vstack((m,M)))
box_size = "box dimensions, x: {x}, y: {y}, z: {z}".format(x = str(smol.box[0][0]),y= str(smol.box[1][0]),z = str(smol.box[2][0]))

```
Output:
`box dimensions, x: 0.0, y: 0.0, z: 0.0`

**Comment by stefdoerr** [comment]
Hi, the box size is only read from xtc or dcd files, meaning from simulations. Solvating does not set the box size. What would you like to do with it?

**Comment by stefdoerr** [comment]
Ah sorry, to calculate the box size you could just do:
`mol.coords.max(axis=0) - mol.coords.min(axis=0)` 
that should give you the total size of the box

**Comment by phisanti** [comment]
That was what I need. Thanks!
